"""
capital_guardian/signals.py — Phase 2 Audit History instrumentation.

`pre_save` snapshots a tracked model's prior DB row (if any); `post_save`
diffs the saved instance's tracked fields against that snapshot and writes
one AuditLogEntry per real changed field via services/audit_log.py. A brand
new row logs a single "(created)" entry rather than one per field.

This is connected from CapitalGuardianConfig.ready() to models in OTHER
apps (gold_intelligence.MineTimelineMilestone/EquipmentSpec/CapitalBudgetLine/
GoldProject, evidence_memory.EvidenceMemory) as well as capital_guardian's
own ProjectGovernance/RedFlag — a normal Django cross-app signal pattern that
requires no changes to those apps' own files beyond the additive model
fields already made. `changed_by` is populated only when a call site (an
admin's save_model, or a service) has explicitly set `instance._cg_changed_by`
— every other write (seed commands, the red-flag engine, shell) is honestly
logged with changed_by=None rather than guessing a user.

Idempotent-seed-safe: re-running an update_or_create with identical values
produces zero diffs (old == new for every tracked field), so no audit noise
is generated by a no-op re-seed.
"""
from django.db.models.signals import post_save, pre_save

_PRIOR_ATTR = '_cg_audit_prior_values'


def _snapshot(model_cls, tracked_fields):
    def handler(sender, instance, **kwargs):
        if not instance.pk:
            setattr(instance, _PRIOR_ATTR, None)
            return
        prior = model_cls.objects.filter(pk=instance.pk).values(*tracked_fields).first()
        setattr(instance, _PRIOR_ATTR, prior)
    return handler


def _log(tracked_fields, event_type, project_getter, description_getter, source_reference_getter, field_labels=None):
    def handler(sender, instance, created, **kwargs):
        from capital_guardian.services import audit_log

        project = project_getter(instance)
        if project is None:
            return
        source_reference = source_reference_getter(instance)
        description = description_getter(instance)
        changed_by = getattr(instance, '_cg_changed_by', None)
        prior = getattr(instance, _PRIOR_ATTR, None)

        if prior is None:
            audit_log.record_creation(project, event_type, description, source_reference, changed_by)
            return
        for field in tracked_fields:
            old_value = prior.get(field)
            new_value = getattr(instance, field)
            if old_value != new_value:
                audit_log.record_change(
                    project, event_type, description, (field_labels or {}).get(field, field),
                    old_value, new_value, changed_by=changed_by, source_reference=source_reference,
                )
    return handler


GOVERNANCE_FIELDS = [
    'founder_holdco_pct', 'investor_spv_pct', 'founder_board_seats', 'investor_board_seats',
    'independent_chair_seats', 'reserved_matters_active', 'escrow_account_active',
    'investor_first_waterfall_active', 'quarterly_audit_active', 'independent_technical_adviser_active',
    'insurance_monitoring_active', 'milestone_based_capital_release_active',
]
MILESTONE_FIELDS = [
    'status', 'planned_start', 'planned_end', 'actual_start', 'actual_end', 'completion_pct_override',
    'capital_required_usd', 'capital_released_usd', 'verification_status', 'delay_risk',
]
EQUIPMENT_FIELDS = [
    'manufacturing_status', 'fat_status', 'shipping_status', 'delivery_status', 'installation_status',
    'commissioning_status', 'warranty_status', 'performance_guarantee_status', 'insurance_status',
    'maintenance_status', 'inspection_status',
]
BUDGET_LINE_FIELDS = ['planned_usd', 'committed_usd', 'spent_usd']
GOLDPROJECT_FIELDS = ['total_committed_capital_usd', 'insurance_coverage_usd', 'insurance_expiry_date']
REDFLAG_FIELDS = ['resolution_status']
EVIDENCE_FIELDS = ['verification_status']
# Phase 3 — CapitalTraceEntry's real workflow-state transitions, feeding the
# Capital Protection page's per-payment "Audit Trail".
CAPITAL_TRACE_ENTRY_FIELDS = [
    'approval_status', 'investor_approval_status', 'verification_status', 'insurance_status', 'payment_status',
]


def _resolve_verified_outcome_project(pk):
    """Vertical-slice PR 7 — a VerifiedCapitalOutcome has no direct GoldProject
    FK (CapitalAllocationDecision.project is a plain-text name, see PR5's
    capital_guardian_handoff.py docstring); resolved via the same public,
    exact-match find_matching_gold_project() rather than a second lookup."""
    from waste_to_value_capital_allocation_engine.models import VerifiedCapitalOutcome
    from waste_to_value_capital_allocation_engine.services.capital_guardian_handoff import (
        AmbiguousProjectMatchError, find_matching_gold_project,
    )

    outcome = VerifiedCapitalOutcome.objects.filter(pk=pk).select_related('decision').first()
    if outcome is None:
        return None
    try:
        return find_matching_gold_project(outcome.decision)
    except AmbiguousProjectMatchError:
        return None


def _resolve_project_from_source_reference(source_reference):
    """Best-effort project lookup for an EvidenceMemory row's soft pointer —
    returns None (never guesses) for anything outside Capital Guardian's
    scope (company reports, country reports, agent output, etc.)."""
    if not source_reference or ':' not in source_reference:
        return None
    key, _, pk = source_reference.rpartition(':')

    from capital_guardian.models import CapitalTraceEntry, OperationalSnapshot, ProjectGovernance, RedFlag
    from gold_intelligence.models import EquipmentSpec, GoldProject, MineTimelineMilestone

    resolvers = {
        'gold_intelligence.GoldProject': lambda: GoldProject.objects.filter(pk=pk).first(),
        'capital_guardian.CapitalTraceEntry': lambda: getattr(CapitalTraceEntry.objects.filter(pk=pk).first(), 'project', None),
        'gold_intelligence.EquipmentSpec': lambda: getattr(EquipmentSpec.objects.filter(pk=pk).first(), 'project', None),
        'gold_intelligence.MineTimelineMilestone': lambda: getattr(MineTimelineMilestone.objects.filter(pk=pk).first(), 'project', None),
        'capital_guardian.RedFlag': lambda: getattr(RedFlag.objects.filter(pk=pk).first(), 'project', None),
        'capital_guardian.OperationalSnapshot': lambda: getattr(OperationalSnapshot.objects.filter(pk=pk).first(), 'project', None),
        'capital_guardian.ProjectGovernance': lambda: getattr(ProjectGovernance.objects.filter(pk=pk).first(), 'project', None),
        'waste_to_value_capital_allocation_engine.VerifiedCapitalOutcome': lambda: _resolve_verified_outcome_project(pk),
    }
    resolver = resolvers.get(key)
    if resolver is None:
        return None
    try:
        return resolver()
    except (ValueError, TypeError):
        return None


def connect():
    from capital_guardian.models import CapitalTraceEntry, ProjectGovernance, RedFlag
    from evidence_memory.models import EvidenceMemory
    from gold_intelligence.models import CapitalBudgetLine, EquipmentSpec, GoldProject, MineTimelineMilestone

    pre_save.connect(_snapshot(ProjectGovernance, GOVERNANCE_FIELDS), sender=ProjectGovernance, dispatch_uid='cg_audit_pre_governance')
    post_save.connect(
        _log(GOVERNANCE_FIELDS, 'governance', lambda i: i.project, lambda i: 'Governance', lambda i: f'capital_guardian.ProjectGovernance:{i.pk}'),
        sender=ProjectGovernance, dispatch_uid='cg_audit_post_governance',
    )

    pre_save.connect(_snapshot(MineTimelineMilestone, MILESTONE_FIELDS), sender=MineTimelineMilestone, dispatch_uid='cg_audit_pre_milestone')
    post_save.connect(
        _log(MILESTONE_FIELDS, 'milestone', lambda i: i.project, lambda i: f'Milestone: {i.get_phase_display()}', lambda i: f'gold_intelligence.MineTimelineMilestone:{i.pk}'),
        sender=MineTimelineMilestone, dispatch_uid='cg_audit_post_milestone',
    )

    pre_save.connect(_snapshot(EquipmentSpec, EQUIPMENT_FIELDS), sender=EquipmentSpec, dispatch_uid='cg_audit_pre_equipment')
    post_save.connect(
        _log(EQUIPMENT_FIELDS, 'equipment', lambda i: i.project, lambda i: f'Equipment: {i}', lambda i: f'gold_intelligence.EquipmentSpec:{i.pk}'),
        sender=EquipmentSpec, dispatch_uid='cg_audit_post_equipment',
    )

    pre_save.connect(_snapshot(CapitalBudgetLine, BUDGET_LINE_FIELDS), sender=CapitalBudgetLine, dispatch_uid='cg_audit_pre_budget')
    post_save.connect(
        _log(BUDGET_LINE_FIELDS, 'capex', lambda i: i.project, lambda i: f'CAPEX Budget: {i.label}', lambda i: f'gold_intelligence.CapitalBudgetLine:{i.pk}'),
        sender=CapitalBudgetLine, dispatch_uid='cg_audit_post_budget',
    )

    pre_save.connect(_snapshot(GoldProject, GOLDPROJECT_FIELDS), sender=GoldProject, dispatch_uid='cg_audit_pre_goldproject')
    post_save.connect(
        _log(GOLDPROJECT_FIELDS, 'capital', lambda i: i, lambda i: f'Project: {i.name}', lambda i: f'gold_intelligence.GoldProject:{i.pk}'),
        sender=GoldProject, dispatch_uid='cg_audit_post_goldproject',
    )

    pre_save.connect(_snapshot(RedFlag, REDFLAG_FIELDS), sender=RedFlag, dispatch_uid='cg_audit_pre_redflag')
    post_save.connect(
        _log(
            REDFLAG_FIELDS, 'red_flag', lambda i: i.project, lambda i: f'Red Flag: {i.category}',
            lambda i: f'capital_guardian.RedFlag:{i.pk}', field_labels={'resolution_status': 'Resolution Status'},
        ),
        sender=RedFlag, dispatch_uid='cg_audit_post_redflag',
    )

    pre_save.connect(_snapshot(EvidenceMemory, EVIDENCE_FIELDS), sender=EvidenceMemory, dispatch_uid='cg_audit_pre_evidence')
    post_save.connect(
        _log(
            EVIDENCE_FIELDS, 'evidence', lambda i: _resolve_project_from_source_reference(i.source_reference),
            lambda i: f'Evidence: {i.text_chunk[:60]}', lambda i: f'evidence_memory.EvidenceMemory:{i.pk}',
            field_labels={'verification_status': 'Verification Status'},
        ),
        sender=EvidenceMemory, dispatch_uid='cg_audit_post_evidence',
    )

    pre_save.connect(_snapshot(CapitalTraceEntry, CAPITAL_TRACE_ENTRY_FIELDS), sender=CapitalTraceEntry, dispatch_uid='cg_audit_pre_trace')
    post_save.connect(
        _log(
            CAPITAL_TRACE_ENTRY_FIELDS, 'capital_trace', lambda i: i.project, lambda i: f'{i.purpose} ({i.trace_id})',
            lambda i: f'capital_guardian.CapitalTraceEntry:{i.pk}',
            field_labels={
                'approval_status': 'Approval Status', 'investor_approval_status': 'Investor Approval Status',
                'verification_status': 'Verification Status', 'insurance_status': 'Insurance Status',
                'payment_status': 'Payment Status',
            },
        ),
        sender=CapitalTraceEntry, dispatch_uid='cg_audit_post_trace',
    )
