# Generated by Django 5.2.14 on 2026-05-25 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='User-supplied name to look up', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('searching', 'Searching'), ('downloading', 'Downloading'), ('extracting', 'Extracting'), ('scoring', 'Scoring'), ('saving', 'Saving'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress_pct', models.PositiveSmallIntegerField(default=0, help_text='0-100')),
                ('progress_message', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('search_result', models.JSONField(blank=True, default=dict, help_text='AI web search structured output')),
                ('extraction_result', models.JSONField(blank=True, default=dict, help_text='AI extraction structured output')),
                ('score_result', models.JSONField(blank=True, default=dict, help_text='Computed pillar scores + reasoning')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_company', models.ForeignKey(blank=True, help_text='Created/updated company record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_jobs', to='league.company')),
            ],
            options={
                'verbose_name': 'Ingestion Job',
                'verbose_name_plural': 'Ingestion Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IngestionSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('source_type', models.CharField(choices=[('web', 'Web Page'), ('pdf', 'PDF Document'), ('annual_report', 'Annual Report'), ('esg_report', 'ESG / Sustainability Report'), ('government', 'Government / Regulator'), ('news', 'News Article'), ('other', 'Other')], default='other', max_length=20)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('snippet', models.TextField(blank=True, help_text='Short excerpt from the source')),
                ('downloaded', models.BooleanField(default=False, help_text='Content was fetched and used')),
                ('content_chars', models.PositiveIntegerField(default=0, help_text='Characters extracted')),
                ('used_in_analysis', models.BooleanField(default=False, help_text='Passed to Claude for extraction')),
                ('confidence', models.FloatField(default=0.0, help_text='0-1 relevance confidence assigned by AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='ingestion.ingestionjob')),
            ],
            options={
                'verbose_name': 'Ingestion Source',
                'verbose_name_plural': 'Ingestion Sources',
                'ordering': ['-confidence', 'source_type'],
            },
        ),
    ]
