# Generated by Django 5.2.14 on 2026-07-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global_research', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchsource',
            name='content_safety_flagged',
            field=models.BooleanField(default=False, help_text="True when this source's text matched a prompt-injection-attempt pattern. Flagging never changes how the content is treated (still inert evidence) — it only surfaces the attempt for review."),
        ),
        migrations.AddField(
            model_name='researchsource',
            name='content_safety_notes',
            field=models.TextField(blank=True),
        ),
    ]
