# Generated by Django 5.2.14 on 2026-07-25 14:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capability_graph', '0002_organisationcapability_declared_by_and_more'),
        ('good_agents', '0007_availableresource_declared_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotCandidateAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionability_class', models.CharField(blank=True, choices=[('informational_event', 'Informational event'), ('public_need', 'Public need'), ('service_gap', 'Service gap'), ('resource_available', 'Resource available'), ('funding_available', 'Funding available'), ('public_consultation', 'Public consultation'), ('data_request_opportunity', 'Data request opportunity'), ('policy_implementation_gap', 'Policy implementation gap'), ('local_environmental_issue', 'Local environmental issue'), ('infrastructure_maintenance_need', 'Infrastructure maintenance need'), ('community_support_need', 'Community support need'), ('regulatory_or_compliance_notice', 'Regulatory or compliance notice')], max_length=40)),
                ('actionability_state', models.CharField(choices=[('informational_only', 'Informational only'), ('potentially_actionable', 'Potentially actionable'), ('actionable_needs_review', 'Actionable — needs review'), ('actionable', 'Actionable'), ('wrong_recipient', 'Wrong recipient'), ('no_responsible_body_identified', 'No responsible body identified'), ('no_clear_action', 'No clear action'), ('insufficient_evidence', 'Insufficient evidence'), ('sensitive_review_required', 'Sensitive — review required')], default='informational_only', max_length=40)),
                ('assessment_notes', models.TextField(blank=True)),
                ('discovery_qualified', models.BooleanField(default=False)),
                ('actionability_qualified', models.BooleanField(default=False)),
                ('outreach_suitable', models.BooleanField(default=False)),
                ('jurisdiction', models.CharField(blank=True, max_length=150)),
                ('jurisdiction_resolved', models.BooleanField(default=False)),
                ('jurisdiction_resolution_notes', models.TextField(blank=True)),
                ('evidence_sufficiency', models.JSONField(blank=True, default=dict)),
                ('capital_required_now', models.CharField(choices=[('no', 'No'), ('yes', 'Yes'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('sensitivity_categories', models.JSONField(blank=True, default=list)),
                ('sensitivity_notes', models.TextField(blank=True)),
                ('evidence_valid_but_outreach_inappropriate', models.BooleanField(default=False)),
                ('suggested_action_type', models.CharField(blank=True, choices=[('submit_evidence_to_consultation', 'Submit evidence to an open consultation'), ('ask_for_referral_route', 'Ask for the correct referral route'), ('clarify_programme_eligibility', 'Clarify programme eligibility'), ('surface_matching_grant', 'Surface a matching public grant'), ('request_missing_dataset', 'Request a missing public dataset'), ('notify_data_inconsistency', 'Notify an authority of a clearly evidenced data inconsistency'), ('refer_to_existing_programme', 'Refer a public need to an existing official programme'), ('connect_resource_to_need', 'Connect an available resource to a published need'), ('other', 'Other (specify)')], max_length=40)),
                ('suggested_action_description', models.TextField(blank=True)),
                ('use_official_process', models.BooleanField(default=False, help_text='True when the correct action is an existing official process, not EcoIQ outreach.')),
                ('official_process_type', models.CharField(blank=True, choices=[('general_contact', 'General contact'), ('official_application', 'Official application'), ('consultation_submission', 'Consultation submission'), ('incident_report', 'Incident report'), ('referral_form', 'Referral form'), ('grant_application', 'Grant application'), ('data_request', 'Data request'), ('procurement_portal', 'Procurement portal'), ('public_feedback', 'Public feedback')], max_length=32)),
                ('official_process_route_reference', models.CharField(blank=True, help_text='URL or soft pointer (e.g. capability_graph.PublicRoute:12) to the real official process.', max_length=500)),
                ('why_real_need', models.TextField(blank=True)),
                ('why_action_useful', models.TextField(blank=True)),
                ('what_ecoiq_does_not_know', models.TextField(blank=True)),
                ('assessed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pilot_candidate_assessment', to='good_agents.goodopportunity')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateOrganisationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('evidence_publisher', 'Evidence publisher'), ('jurisdiction_authority', 'Jurisdiction authority'), ('responsible_authority', 'Responsible authority'), ('potential_implementer', 'Potential implementer'), ('funder', 'Funder'), ('resource_provider', 'Resource provider'), ('referral_body', 'Referral body')], max_length=32)),
                ('evidence_reference', models.CharField(blank=True, help_text="Soft pointer, e.g. capability_graph.OrganisationCapability:12 — never inferred from the org's name alone.", max_length=300)),
                ('rationale', models.TextField(blank=True)),
                ('confirmed', models.BooleanField(default=False, help_text='True once a human has checked this claim, not merely suggested it.')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='capability_graph.organisation')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_roles', to='public_need_discovery.pilotcandidateassessment')),
            ],
            options={
                'ordering': ['role'],
                'unique_together': {('candidate', 'organisation', 'role')},
            },
        ),
        migrations.CreateModel(
            name='ProviderRunMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('records_fetched', models.PositiveIntegerField(default=0)),
                ('duplicates', models.PositiveIntegerField(default=0)),
                ('informational_only', models.PositiveIntegerField(default=0)),
                ('potentially_actionable', models.PositiveIntegerField(default=0)),
                ('actionability_qualified', models.PositiveIntegerField(default=0)),
                ('rejected', models.PositiveIntegerField(default=0)),
                ('missing_jurisdiction', models.PositiveIntegerField(default=0)),
                ('missing_responsible_body', models.PositiveIntegerField(default=0)),
                ('official_routes_found', models.PositiveIntegerField(default=0)),
                ('errors', models.PositiveIntegerField(default=0)),
                ('error_detail', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_metrics', to='good_agents.signalprovider')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_metrics', to='good_agents.gooddiscoveryrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('provider', 'run')},
            },
        ),
    ]
