# Generated by Django 5.2.14 on 2026-05-24 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('work_email', models.EmailField(db_index=True, max_length=254)),
                ('industry', models.CharField(choices=[('oil_gas', 'Oil & Gas / Refining'), ('manufacturing', 'Manufacturing (General)'), ('automotive', 'Automotive'), ('chemicals', 'Chemicals & Petrochemicals'), ('pharma', 'Pharmaceuticals'), ('food_beverage', 'Food & Beverage'), ('utilities', 'Utilities / Energy'), ('logistics', 'Logistics & Warehousing'), ('metals_mining', 'Metals & Mining'), ('other', 'Other Heavy Industry')], max_length=30)),
                ('facility_type', models.CharField(help_text='e.g. Continuous process refinery, Cold-chain warehouse', max_length=200)),
                ('company_size', models.CharField(choices=[('1_50', '1–50 employees'), ('51_200', '51–200 employees'), ('201_1000', '201–1,000 employees'), ('1001_5000', '1,001–5,000 employees'), ('5001_plus', '5,001+ employees')], max_length=20)),
                ('challenge', models.TextField(help_text='Main operational challenge — minimum 30 characters')),
                ('message', models.TextField(blank=True, help_text='Optional additional context')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('demo_scheduled', 'Demo Scheduled'), ('pilot_active', 'Pilot Active'), ('declined', 'Declined')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes — not visible to the submitter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Access Request',
                'verbose_name_plural': 'Access Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
