# Generated by Django 5.2.14 on 2026-05-29 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(db_index=True, editable=False, help_text='Auto-generated claim reference (CLM-YYYYMMDD-XXXX)', max_length=20, unique=True)),
                ('company_slug', models.CharField(blank=True, db_index=True, help_text='Slug of the EcoIQ company profile being claimed', max_length=200)),
                ('company_name_reported', models.CharField(blank=True, help_text='Company name as entered by the claimant', max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('work_email', models.EmailField(db_index=True, max_length=254)),
                ('job_title', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('message', models.TextField(blank=True, help_text='Why the claimant is entitled to manage this profile')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes — not visible to the claimant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profile Claim',
                'verbose_name_plural': 'Profile Claims',
                'ordering': ['-created_at'],
            },
        ),
    ]
