# Generated by Django 5.2.14 on 2026-05-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_profileclaim'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsletterSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('interest', models.CharField(choices=[('investor', 'Investor'), ('company', 'Company'), ('government', 'Government'), ('researcher', 'Researcher'), ('other', 'Other')], default='other', max_length=50)),
                ('signed_up_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to unsubscribe without deleting the record.')),
                ('source', models.CharField(blank=True, help_text='Where the signup originated — popup, /newsletter/, API, etc.', max_length=100)),
            ],
            options={
                'verbose_name': 'Newsletter Signup',
                'verbose_name_plural': 'Newsletter Signups',
                'ordering': ['-signed_up_at'],
            },
        ),
    ]
