# Generated by Django 5.2.14 on 2026-06-06 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_reviewrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='country',
            field=models.CharField(blank=True, help_text='Country of operation (optional)', max_length=100),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='role',
            field=models.CharField(blank=True, choices=[('investor', 'Investor'), ('company', 'Company'), ('government', 'Government'), ('consultant', 'Consultant'), ('analyst', 'Analyst'), ('other', 'Other')], help_text='How the requester identifies themselves (optional)', max_length=30),
        ),
    ]
