# Generated by Django 5.2.14 on 2026-06-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0005_accessrequest_country_accessrequest_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='product_interest',
            field=models.CharField(blank=True, choices=[('free_scan', 'Free Scan'), ('readiness_report', 'Investor Readiness Report'), ('institutional_pilot', 'Institutional Pilot')], help_text='Which EcoIQ product the requester is interested in', max_length=30),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='sector',
            field=models.CharField(blank=True, help_text='Sector of the company/project (optional)', max_length=120),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='target_entity',
            field=models.CharField(blank=True, help_text='Company or project the requester wants assessed', max_length=300),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='challenge',
            field=models.TextField(blank=True, help_text='Main operational challenge (optional)'),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='company_size',
            field=models.CharField(blank=True, choices=[('1_50', '1–50 employees'), ('51_200', '51–200 employees'), ('201_1000', '201–1,000 employees'), ('1001_5000', '1,001–5,000 employees'), ('5001_plus', '5,001+ employees')], max_length=20),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='facility_type',
            field=models.CharField(blank=True, help_text='e.g. Continuous process refinery, Cold-chain warehouse', max_length=200),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='industry',
            field=models.CharField(blank=True, choices=[('oil_gas', 'Oil & Gas / Refining'), ('manufacturing', 'Manufacturing (General)'), ('automotive', 'Automotive'), ('chemicals', 'Chemicals & Petrochemicals'), ('pharma', 'Pharmaceuticals'), ('food_beverage', 'Food & Beverage'), ('utilities', 'Utilities / Energy'), ('logistics', 'Logistics & Warehousing'), ('metals_mining', 'Metals & Mining'), ('other', 'Other Heavy Industry')], max_length=30),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewed', 'Reviewed'), ('sample_sent', 'Sample Sent'), ('call_booked', 'Call Booked'), ('proposal_sent', 'Proposal Sent'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
