# Generated by Django 5.2.14 on 2026-06-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0006_accessrequest_product_interest_accessrequest_sector_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrequest',
            name='draft_recommendations',
            field=models.TextField(blank=True, help_text='Draft investor-readiness recommendations'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='draft_risk_summary',
            field=models.TextField(blank=True, help_text='Draft climate, governance & transition risk summary'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='draft_roadmap',
            field=models.TextField(blank=True, help_text='Draft 90-day roadmap (30 / 60 / 90-day windows)'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='draft_score_summary',
            field=models.TextField(blank=True, help_text='Draft EcoIQ / Maqasid score summary'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Internal analyst notes for report preparation'),
        ),
        migrations.AddField(
            model_name='accessrequest',
            name='report_status',
            field=models.CharField(blank=True, choices=[('not_started', 'Not Started'), ('draft_needed', 'Draft Needed'), ('draft_ready', 'Draft Prepared'), ('sent', 'Sent to Client'), ('paid_request', 'Paid Report Requested'), ('closed', 'Closed')], default='not_started', help_text='Internal draft-report preparation stage', max_length=20),
        ),
    ]
