# Generated by Django 5.2.14 on 2026-08-01 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_accessrequest_draft_recommendations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('organisation', models.CharField(max_length=200)),
                ('work_email', models.EmailField(db_index=True, max_length=254)),
                ('country', models.CharField(max_length=100)),
                ('organisation_type', models.CharField(choices=[('bank', 'Bank'), ('family_office', 'Family Office'), ('investment_fund', 'Investment Fund'), ('sovereign_wealth_fund', 'Sovereign Wealth Fund'), ('ministry', 'Ministry'), ('municipality', 'Municipality'), ('government_entity', 'Government-Related Entity'), ('energy_infrastructure', 'Energy / Infrastructure Company'), ('industrial_group', 'Industrial Group'), ('other', 'Other')], max_length=30)),
                ('preferred_engagement', models.CharField(choices=[('enterprise_diagnostic', 'Enterprise Diagnostic'), ('pilot_90day', '90-Day Pilot'), ('enterprise_deployment', 'Enterprise Deployment'), ('annual_licence', 'Annual Platform Licence'), ('government_sovereign', 'Government or Sovereign Programme'), ('founding_partner', 'Founding Partner Programme')], max_length=30)),
                ('estimated_assets', models.CharField(blank=True, help_text='Estimated number of assets, companies or portfolio entities (free text, optional)', max_length=100)),
                ('use_case', models.CharField(blank=True, help_text='Main use case — e.g. portfolio screening, national ESG programme', max_length=300)),
                ('message', models.TextField(blank=True, help_text='Optional additional context')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Under Review'), ('scoping_call', 'Scoping Call Booked'), ('proposal_sent', 'Proposal Sent'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes — not visible to the submitter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Enterprise Enquiry',
                'verbose_name_plural': 'Enterprise Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
