# Generated by Django 5.2.14 on 2026-08-02 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_enterpriseenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('organisation', models.CharField(max_length=200)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('work_email', models.EmailField(db_index=True, max_length=254)),
                ('phone_whatsapp', models.CharField(blank=True, help_text='Optional phone or WhatsApp number', max_length=40)),
                ('country', models.CharField(max_length=100)),
                ('organisation_type', models.CharField(choices=[('vc_fund', 'Venture Capital Fund'), ('family_office', 'Family Office'), ('bank_financial_inst', 'Bank or Financial Institution'), ('corporate_vc', 'Corporate Venture Capital'), ('strategic_corporate', 'Strategic Corporate Investor'), ('institutional_investor', 'Institutional Investor'), ('government_related', 'Government-Related Organisation'), ('accelerator', 'Accelerator or Innovation Programme'), ('research_institution', 'Research Institution'), ('other', 'Other')], max_length=30)),
                ('type_of_interest', models.CharField(choices=[('strategic_investment', 'Strategic Investment'), ('enterprise_pilot', 'Enterprise Pilot'), ('annual_licence', 'Annual Platform Licence'), ('government_programme', 'Government Programme'), ('technology_partnership', 'Technology Partnership'), ('data_partnership', 'Data Partnership'), ('distribution_partnership', 'Distribution Partnership'), ('founding_partner', 'GCC Founding Partner Programme'), ('confidential_materials', 'Request Confidential Investor Materials')], max_length=30)),
                ('engagement_range', models.CharField(blank=True, choices=[('under_50k', 'Under £50,000'), ('50k_150k', '£50,000 – £150,000'), ('150k_500k', '£150,000 – £500,000'), ('500k_2m', '£500,000 – £2,000,000'), ('over_2m', '£2,000,000+'), ('not_sure', 'Not sure yet — prefer to discuss')], help_text='Indicative only — not a quote or commitment', max_length=20)),
                ('main_area_of_interest', models.CharField(blank=True, help_text='e.g. GCC market entry, Islamic finance intelligence, sovereign portfolio screening', max_length=300)),
                ('message', models.TextField(blank=True, help_text='Optional additional context')),
                ('consent', models.BooleanField(default=False, help_text='Confirms the submitter has read the investor-notice disclaimer')),
                ('source_page', models.CharField(blank=True, max_length=300)),
                ('source_country', models.CharField(blank=True, choices=[('hub', 'GCC Hub'), ('qatar', 'Qatar'), ('saudi_arabia', 'Saudi Arabia'), ('kuwait', 'Kuwait')], max_length=20)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('utm_content', models.CharField(blank=True, max_length=100)),
                ('utm_term', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('reviewing', 'Under Review'), ('scoping_call', 'Scoping Call Booked'), ('proposal_sent', 'Proposal Sent'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes — not visible to the submitter')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Investor Enquiry',
                'verbose_name_plural': 'Investor Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
