# Generated by Django 5.2.14 on 2026-08-25 10:37

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0009_investorenquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrequest',
            name='sustainability_report',
            field=models.FileField(blank=True, help_text='PDF only · max 10 MB', null=True, upload_to=core.storage.upload_to_sustainability_report),
        ),
    ]
