# Generated by Django 5.2.14 on 2026-08-26 09:31

import core.storage
import core.upload_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0010_alter_reviewrequest_sustainability_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrequest',
            name='sustainability_report',
            field=models.FileField(blank=True, help_text='PDF only · max 10 MB', null=True, upload_to=core.storage.upload_to_sustainability_report, validators=[core.upload_validation.UploadValidator(allowed_extensions={'.pdf'}, max_bytes=10485760)]),
        ),
    ]
