"""
_target_market_data.py — Additional company data for EcoIQ's 4 target markets.

Top-up counts (to reach ~100 public profiles per market):
  United Kingdom  +37   (63 existing → 100)
  Kazakhstan      +57   (43 existing → 100)
  Saudi Arabia    +59   (41 existing → 100)
  Türkiye         +40   (60 existing → 100)
  Total:          193 new companies

Format: (name, sector, country, target_ecoiq_score, harm_level)
  sector:     oil_gas | mining | energy | chemical | metallurgy | transport | agriculture | other
  harm_level: Severe | High | Medium | Low

No duplicates with add_400_companies.py, focus_target_markets.py, or seed_global_companies.py.
"""

ADDITIONAL_COMPANIES = [

    # ── United Kingdom (+37) ──────────────────────────────────────────────────
    ("Polymetal International",         "mining",     "United Kingdom", 36, "High"),
    ("ITM Power",                        "energy",     "United Kingdom", 68, "Low"),
    ("Ceres Power Holdings",             "energy",     "United Kingdom", 66, "Low"),
    ("Zenobe Energy",                    "energy",     "United Kingdom", 68, "Low"),
    ("Lightsource bp",                   "energy",     "United Kingdom", 70, "Low"),
    ("Low Carbon Ltd",                   "energy",     "United Kingdom", 70, "Low"),
    ("Dogger Bank Wind Farm",            "energy",     "United Kingdom", 70, "Low"),
    ("Greencoat UK Wind",                "energy",     "United Kingdom", 70, "Low"),
    ("John Wood Group",                  "oil_gas",    "United Kingdom", 42, "High"),
    ("TechnipFMC UK",                    "oil_gas",    "United Kingdom", 44, "High"),
    ("Hunting plc",                      "oil_gas",    "United Kingdom", 40, "High"),
    ("Storengy UK",                      "energy",     "United Kingdom", 48, "Medium"),
    ("Good Energy Group",                "energy",     "United Kingdom", 70, "Low"),
    ("Ecotricity",                       "energy",     "United Kingdom", 72, "Low"),
    ("GlaxoSmithKline GSK",              "other",      "United Kingdom", 64, "Low"),
    ("AstraZeneca",                      "other",      "United Kingdom", 66, "Low"),
    ("BT Group",                         "other",      "United Kingdom", 54, "Low"),
    ("Vodafone UK",                      "other",      "United Kingdom", 56, "Low"),
    ("Sky UK",                           "other",      "United Kingdom", 58, "Low"),
    ("WPP plc",                          "other",      "United Kingdom", 54, "Low"),
    ("Compass Group UK",                 "other",      "United Kingdom", 58, "Low"),
    ("Sage Group",                       "other",      "United Kingdom", 64, "Low"),
    ("Experian UK",                      "other",      "United Kingdom", 62, "Low"),
    ("London Stock Exchange Group LSEG", "other",      "United Kingdom", 64, "Low"),
    ("InterContinental Hotels Group IHG","other",      "United Kingdom", 60, "Low"),
    ("Whitbread",                        "other",      "United Kingdom", 56, "Low"),
    ("Taylor Wimpey",                    "other",      "United Kingdom", 52, "Medium"),
    ("Persimmon Homes",                  "other",      "United Kingdom", 50, "Medium"),
    ("Berkeley Group Holdings",          "other",      "United Kingdom", 56, "Medium"),
    ("Serco Group",                      "other",      "United Kingdom", 52, "Medium"),
    ("Capita plc",                       "other",      "United Kingdom", 46, "Medium"),
    ("DCC plc",                          "other",      "United Kingdom", 54, "Low"),
    ("Haleon plc",                       "other",      "United Kingdom", 60, "Low"),
    ("Reckitt Benckiser",                "other",      "United Kingdom", 58, "Low"),
    ("Diageo",                           "other",      "United Kingdom", 62, "Low"),
    ("Cobham Group",                     "other",      "United Kingdom", 52, "Medium"),
    ("Howden Group Holdings",            "other",      "United Kingdom", 58, "Low"),

    # ── Kazakhstan (+57) ──────────────────────────────────────────────────────
    ("Kazatomprom",                        "mining",     "Kazakhstan", 44, "Medium"),
    ("KMG EP",                             "oil_gas",    "Kazakhstan", 30, "High"),
    ("Atyrau Refinery",                    "oil_gas",    "Kazakhstan", 34, "High"),
    ("Pavlodar Petrochemical Refinery",    "oil_gas",    "Kazakhstan", 32, "High"),
    ("Shymkent Oil Refinery",              "oil_gas",    "Kazakhstan", 33, "High"),
    ("Aktobe Chromium Compounds Plant",    "chemical",   "Kazakhstan", 30, "High"),
    ("Ust-Kamenogorsk Titanium Plant",     "metallurgy", "Kazakhstan", 34, "High"),
    ("Shalkiya Zinc",                      "mining",     "Kazakhstan", 28, "High"),
    ("Polymetal Kazakhstan",               "mining",     "Kazakhstan", 42, "High"),
    ("Stepnogorsk Mining Chemical Combine","mining",     "Kazakhstan", 26, "Severe"),
    ("Zhayremsky GOK",                     "mining",     "Kazakhstan", 30, "High"),
    ("KazPhosphate",                       "chemical",   "Kazakhstan", 28, "High"),
    ("PetroKazakhstan",                    "oil_gas",    "Kazakhstan", 36, "High"),
    ("Mangistau Investments",              "oil_gas",    "Kazakhstan", 32, "High"),
    ("Qazaq Gaz",                          "oil_gas",    "Kazakhstan", 42, "Medium"),
    ("KazTransCom",                        "other",      "Kazakhstan", 48, "Low"),
    ("KazPost",                            "transport",  "Kazakhstan", 44, "Low"),
    ("Almaty International Airport",       "transport",  "Kazakhstan", 48, "Medium"),
    ("Astana International Airport",       "transport",  "Kazakhstan", 50, "Low"),
    ("QazExpressway",                      "transport",  "Kazakhstan", 46, "Medium"),
    ("Jusan Bank",                         "other",      "Kazakhstan", 54, "Low"),
    ("Forte Bank",                         "other",      "Kazakhstan", 50, "Low"),
    ("Nurbank",                            "other",      "Kazakhstan", 44, "Low"),
    ("Bank RBK",                           "other",      "Kazakhstan", 46, "Low"),
    ("ATF Bank",                           "other",      "Kazakhstan", 46, "Low"),
    ("Altyn Bank",                         "other",      "Kazakhstan", 48, "Low"),
    ("Kolesa Group",                       "other",      "Kazakhstan", 58, "Low"),
    ("Chocofamily Holding",                "other",      "Kazakhstan", 56, "Low"),
    ("BTS Digital",                        "other",      "Kazakhstan", 52, "Low"),
    ("Tengri Lab",                         "other",      "Kazakhstan", 54, "Low"),
    ("Sary-Arka Airport Karaganda",        "transport",  "Kazakhstan", 44, "Medium"),
    ("Aktau International Airport",        "transport",  "Kazakhstan", 42, "Medium"),
    ("Kazakhstan Petrochemical Industries","chemical",   "Kazakhstan", 38, "High"),
    ("Verny Capital",                      "other",      "Kazakhstan", 52, "Low"),
    ("Bayterek Development",               "other",      "Kazakhstan", 48, "Low"),
    ("QazIndustry",                        "other",      "Kazakhstan", 42, "Medium"),
    ("Transtelecom Kazakhstan",            "other",      "Kazakhstan", 44, "Low"),
    ("Food Contract Corporation FCC",      "agriculture","Kazakhstan", 46, "Low"),
    ("Prodcorp Kazakhstan",                "agriculture","Kazakhstan", 42, "Medium"),
    ("KazMedTech",                         "other",      "Kazakhstan", 48, "Low"),
    ("Aktobe Plant of Ferroalloys",        "metallurgy", "Kazakhstan", 28, "Severe"),
    ("Shelek Wind Power",                  "energy",     "Kazakhstan", 62, "Low"),
    ("Kapchagay Hydropower Plant",         "energy",     "Kazakhstan", 60, "Low"),
    ("Bukhtarma Hydropower",               "energy",     "Kazakhstan", 58, "Low"),
    ("Samruk Green Energy",                "energy",     "Kazakhstan", 62, "Low"),
    ("Almaty Power Consolidated",          "energy",     "Kazakhstan", 26, "Severe"),
    ("Karaganda GRES-2",                   "energy",     "Kazakhstan", 22, "Severe"),
    ("KAZAKH INVEST National Company",     "other",      "Kazakhstan", 46, "Low"),
    ("Halyk Finance",                      "other",      "Kazakhstan", 54, "Low"),
    ("KMG Refining and Marketing",         "oil_gas",    "Kazakhstan", 32, "High"),
    ("Kostanay Minerals",                  "mining",     "Kazakhstan", 34, "High"),
    ("AIFC Authority Kazakhstan",          "other",      "Kazakhstan", 58, "Low"),
    ("Kaznex Invest",                      "other",      "Kazakhstan", 44, "Low"),
    ("WindPower Kazakhstan",               "energy",     "Kazakhstan", 64, "Low"),
    ("Frontier Mining Kazakhstan",         "mining",     "Kazakhstan", 28, "High"),
    ("KazMinerals Gold",                   "mining",     "Kazakhstan", 38, "High"),
    ("Balkhash Copper Smelter",            "metallurgy", "Kazakhstan", 24, "Severe"),

    # ── Saudi Arabia (+59) ────────────────────────────────────────────────────
    ("Saudi Telecom Company STC",          "other",      "Saudi Arabia", 58, "Low"),
    ("Mobily Etihad Etisalat",             "other",      "Saudi Arabia", 54, "Low"),
    ("Zain Saudi Arabia",                  "other",      "Saudi Arabia", 52, "Low"),
    ("Saudi Fransi Bank",                  "other",      "Saudi Arabia", 54, "Low"),
    ("Arab National Bank ANB",             "other",      "Saudi Arabia", 52, "Low"),
    ("Bank Albilad",                       "other",      "Saudi Arabia", 50, "Low"),
    ("Bank AlJazira",                      "other",      "Saudi Arabia", 48, "Low"),
    ("Saudi Investment Bank SAIB",         "other",      "Saudi Arabia", 50, "Low"),
    ("Gulf International Bank GIB",        "other",      "Saudi Arabia", 52, "Low"),
    ("Riyad Capital",                      "other",      "Saudi Arabia", 52, "Low"),
    ("Saudi Aramco Total Refining SATORP", "oil_gas",    "Saudi Arabia", 34, "High"),
    ("Saudi Aramco Mobil Refinery SAMREF", "oil_gas",    "Saudi Arabia", 32, "High"),
    ("Yanpet Petrochemical",               "chemical",   "Saudi Arabia", 36, "High"),
    ("Ibn Rushd Petrochemical",            "chemical",   "Saudi Arabia", 34, "High"),
    ("Al Jubail Fertilizer SAMAD",         "chemical",   "Saudi Arabia", 38, "Medium"),
    ("Saudi Arabian Fertilizer SAFCO",     "chemical",   "Saudi Arabia", 40, "Medium"),
    ("Maaden Phosphate Company",           "mining",     "Saudi Arabia", 40, "Medium"),
    ("Maaden Aluminium Company",           "metallurgy", "Saudi Arabia", 40, "High"),
    ("Yanbu Cement Company",               "other",      "Saudi Arabia", 38, "High"),
    ("Hail Cement Company",                "other",      "Saudi Arabia", 36, "High"),
    ("Eastern Province Cement",            "other",      "Saudi Arabia", 38, "High"),
    ("Southern Province Cement",           "other",      "Saudi Arabia", 36, "High"),
    ("City Cement Company",                "other",      "Saudi Arabia", 36, "High"),
    ("Northern Region Cement",             "other",      "Saudi Arabia", 34, "High"),
    ("Saudi Readymix Concrete",            "other",      "Saudi Arabia", 40, "Medium"),
    ("Tabuk Pharmaceuticals",              "other",      "Saudi Arabia", 52, "Low"),
    ("Gulf Drug Company GDC",              "other",      "Saudi Arabia", 50, "Low"),
    ("SPIMACO Saudi Pharmaceutical",       "other",      "Saudi Arabia", 52, "Low"),
    ("Saudi Cable Company",                "other",      "Saudi Arabia", 44, "Medium"),
    ("Arabian Pipes Company",              "other",      "Saudi Arabia", 42, "Medium"),
    ("Saudi Steel Pipe SSP",               "metallurgy", "Saudi Arabia", 40, "High"),
    ("Zamil Steel Buildings",              "metallurgy", "Saudi Arabia", 46, "Medium"),
    ("Astra Industrial Group",             "chemical",   "Saudi Arabia", 48, "Medium"),
    ("Elm Information Security",           "other",      "Saudi Arabia", 56, "Low"),
    ("Advanced Electronics Company AEC",  "other",      "Saudi Arabia", 54, "Low"),
    ("Saudi Ground Services SGS",          "transport",  "Saudi Arabia", 44, "Medium"),
    ("Saudia Cargo",                       "transport",  "Saudi Arabia", 42, "High"),
    ("Seera Group",                        "other",      "Saudi Arabia", 54, "Low"),
    ("Jarir Bookstore",                    "other",      "Saudi Arabia", 56, "Low"),
    ("Extra Electronics",                  "other",      "Saudi Arabia", 52, "Low"),
    ("Abdul Latif Jameel ALJ",             "other",      "Saudi Arabia", 52, "Low"),
    ("Fal Energy",                         "energy",     "Saudi Arabia", 58, "Low"),
    ("Amaala Tourism Development",         "other",      "Saudi Arabia", 58, "Low"),
    ("Saudi Ports Authority",              "transport",  "Saudi Arabia", 48, "Medium"),
    ("King Abdullah Port",                 "transport",  "Saudi Arabia", 50, "Low"),
    ("Jeddah Islamic Port",                "transport",  "Saudi Arabia", 44, "Medium"),
    ("Saudi Agricultural and Livestock SALIC","agriculture","Saudi Arabia", 46, "Low"),
    ("National Aquaculture Group Naqua",   "agriculture","Saudi Arabia", 48, "Low"),
    ("Tabuk Agricultural Development",     "agriculture","Saudi Arabia", 44, "Medium"),
    ("Saudi Crop Protection Company",      "agriculture","Saudi Arabia", 44, "Medium"),
    ("Halliburton Saudi Arabia",           "oil_gas",    "Saudi Arabia", 36, "High"),
    ("Schlumberger Saudi Arabia",          "oil_gas",    "Saudi Arabia", 38, "High"),
    ("Baker Hughes Saudi Arabia",          "oil_gas",    "Saudi Arabia", 40, "High"),
    ("NEOM Tech and Digital Company",      "other",      "Saudi Arabia", 60, "Low"),
    ("Abdullah Al Othaim Markets",         "other",      "Saudi Arabia", 50, "Low"),
    ("Saudi Hotels and Resort Areas",      "other",      "Saudi Arabia", 48, "Low"),
    ("Arabian Shield Cooperative Insurance","other",     "Saudi Arabia", 46, "Low"),
    ("Walaa Cooperative Insurance",        "other",      "Saudi Arabia", 48, "Low"),
    ("Zoujaj National Glass Industries",   "other",      "Saudi Arabia", 40, "Medium"),

    # ── Türkiye additional (+40) ──────────────────────────────────────────────
    ("Ford Otosan",                        "transport",  "Türkiye", 56, "Medium"),
    ("Tofaş Türk Otomobil",               "transport",  "Türkiye", 52, "Medium"),
    ("OYAK Renault",                       "transport",  "Türkiye", 54, "Medium"),
    ("Karsan Otomotiv",                    "transport",  "Türkiye", 50, "Low"),
    ("Temsa",                              "transport",  "Türkiye", 52, "Low"),
    ("İzmir Doğalgaz",                    "oil_gas",    "Türkiye", 40, "Medium"),
    ("Naturelgaz",                         "oil_gas",    "Türkiye", 42, "Medium"),
    ("BİM Birleşik Mağazalar",            "other",      "Türkiye", 54, "Low"),
    ("Migros Ticaret",                     "other",      "Türkiye", 54, "Low"),
    ("Yıldız Holding",                    "other",      "Türkiye", 52, "Low"),
    ("Tekfen Holding",                     "other",      "Türkiye", 52, "Low"),
    ("Alarko Holding",                     "other",      "Türkiye", 50, "Low"),
    ("Enka İnşaat",                       "other",      "Türkiye", 50, "Low"),
    ("Cengiz Holding",                     "other",      "Türkiye", 34, "High"),
    ("Şişecam",                           "other",      "Türkiye", 56, "Medium"),
    ("Eczacıbaşı Holding",               "other",      "Türkiye", 58, "Low"),
    ("Abdi İbrahim Pharmaceuticals",      "other",      "Türkiye", 56, "Low"),
    ("Nobel İlaç",                        "other",      "Türkiye", 52, "Low"),
    ("Anadolu Sigorta",                    "other",      "Türkiye", 50, "Low"),
    ("Allianz Türkiye",                   "other",      "Türkiye", 56, "Low"),
    ("TAV Airports Holding",               "transport",  "Türkiye", 52, "Low"),
    ("Çelebi Havacılık",                  "transport",  "Türkiye", 46, "Low"),
    ("MNG Havacılık",                     "transport",  "Türkiye", 44, "Medium"),
    ("Roketsan",                           "other",      "Türkiye", 50, "Medium"),
    ("STM Savunma Teknolojileri",          "other",      "Türkiye", 52, "Low"),
    ("İnci Holding",                      "other",      "Türkiye", 54, "Low"),
    ("Polat Holding",                      "other",      "Türkiye", 46, "Low"),
    ("Kolin İnşaat",                      "other",      "Türkiye", 40, "Medium"),
    ("Türkiye Halk Sigorta",              "other",      "Türkiye", 48, "Low"),
    ("Siemens Türkiye",                   "other",      "Türkiye", 60, "Low"),
    ("ABB Türkiye",                        "other",      "Türkiye", 58, "Low"),
    ("GE Türkiye",                         "energy",     "Türkiye", 56, "Low"),
    ("Schneider Electric Türkiye",        "other",      "Türkiye", 58, "Low"),
    ("Türk Prysmian Kablo",               "other",      "Türkiye", 52, "Medium"),
    ("Global Yatırım Holding",            "transport",  "Türkiye", 46, "Low"),
    ("Mey İçki",                          "other",      "Türkiye", 50, "Low"),
    ("Hayat Kimya",                        "chemical",   "Türkiye", 52, "Low"),
    ("Eti Gıda",                          "agriculture","Türkiye", 50, "Low"),
    ("Selçuk Ecza Deposu",               "other",      "Türkiye", 50, "Low"),
    ("Türkiye Sigorta",                   "other",      "Türkiye", 48, "Low"),
]
