# Generated by Django 5.2.14 on 2026-07-24 11:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0007_companyprofile_last_refresh_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('org_type', models.CharField(choices=[('local_authority', 'Local authority'), ('government_department', 'Government department'), ('company', 'Company'), ('charity', 'Charity'), ('ngo', 'NGO'), ('community_organisation', 'Community organisation'), ('funder', 'Funder'), ('research_institution', 'Research institution'), ('facility_operator', 'Facility operator'), ('regulator', 'Regulator'), ('internal_ecoiq_team', 'Internal EcoIQ team'), ('other', 'Other')], default='other', max_length=24)),
                ('jurisdiction', models.CharField(blank=True, help_text='Free-text jurisdiction/geography this organisation is known to operate in overall (e.g. "England", "Global", "Kazakhstan") — a specific capability may still be scoped narrower via OrganisationCapability.jurisdiction.', max_length=150)),
                ('website', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('dedupe_key', models.CharField(editable=False, max_length=300, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='companies.companyprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrganisationCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.CharField(choices=[('fund', 'Fund'), ('grant', 'Grant'), ('lend', 'Lend'), ('donate', 'Donate'), ('regulate', 'Regulate'), ('authorise', 'Authorise'), ('permit', 'Permit'), ('procure', 'Procure'), ('install', 'Install'), ('transport', 'Transport'), ('collect', 'Collect'), ('recycle', 'Recycle'), ('reuse', 'Reuse'), ('supply', 'Supply'), ('manufacture', 'Manufacture'), ('provide_technology', 'Provide Technology'), ('provide_expertise', 'Provide Expertise'), ('research', 'Research'), ('verify', 'Verify'), ('audit', 'Audit'), ('measure', 'Measure'), ('host', 'Host'), ('train', 'Train'), ('employ', 'Employ'), ('refer', 'Refer'), ('coordinate', 'Coordinate'), ('respond_to_emergency', 'Respond To Emergency')], max_length=24)),
                ('jurisdiction', models.CharField(blank=True, max_length=150)),
                ('topic_domain', models.CharField(blank=True, help_text='Free-text topic/domain this capability applies to (e.g. "flood risk", "heat pumps", "seismic monitoring") — never inferred from the organisation\'s sector alone.', max_length=150)),
                ('evidence_source', models.CharField(blank=True, max_length=300)),
                ('evidence_url', models.URLField(blank=True)),
                ('verification_state', models.CharField(choices=[('unverified', 'Unverified — not yet checked against any real source'), ('self_reported', 'Self-reported — the organisation itself claims this, unconfirmed'), ('documented', 'Documented — a real public source states this'), ('independently_verified', 'Independently verified — a human confirmed this directly')], default='unverified', max_length=24)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('limitations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='capability_graph.organisation')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organisation__name', 'capability'],
                'unique_together': {('organisation', 'capability', 'jurisdiction', 'topic_domain')},
            },
        ),
        migrations.CreateModel(
            name='PublicRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_type', models.CharField(choices=[('online_application', 'Online application'), ('public_contact_form', 'Public contact form'), ('email', 'Email'), ('phone', 'Phone'), ('referral_required', 'Referral required'), ('in_person', 'In person'), ('other', 'Other')], max_length=24)),
                ('route_value', models.CharField(help_text='The real URL, email, or phone number — never inferred.', max_length=500)),
                ('is_currently_open', models.BooleanField(default=True, help_text='Some routes (e.g. grant application windows) are only open at certain times.')),
                ('notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation_capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_routes', to='capability_graph.organisationcapability')),
            ],
            options={
                'ordering': ['organisation_capability', 'route_type'],
            },
        ),
    ]
