# Generated by Django 5.2.14 on 2026-07-24 12:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capability_graph', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationcapability',
            name='declared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organisationcapability',
            name='last_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisationcapability',
            name='provenance',
            field=models.CharField(choices=[('external_public_evidence', 'External public evidence — EcoIQ found this from a public source (PR7 default)'), ('organisation_declared', 'Organisation declared — the organisation itself submitted this via the partner portal'), ('ecoiq_reviewed', 'EcoIQ reviewed — an EcoIQ staff member entered or reviewed this manually')], default='external_public_evidence', max_length=32),
        ),
        migrations.AddField(
            model_name='organisationcapability',
            name='reconfirmation_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicroute',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicroute',
            name='superseded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisationcapability',
            name='verification_state',
            field=models.CharField(choices=[('unverified', 'Unverified — not yet checked against any real source'), ('self_reported', 'Self-reported / self-declared — the organisation itself claims this, unconfirmed'), ('evidence_supported', 'Evidence supported — the organisation attached real evidence to its own declaration'), ('documented', 'Documented — EcoIQ found a real external public source stating this'), ('human_reviewed', 'Human reviewed — an EcoIQ staff member reviewed the claim (not yet independently verified)'), ('independently_verified', 'Independently verified — a human confirmed this directly'), ('disputed', 'Disputed — conflicts with other evidence; needs resolution'), ('expired', 'Expired — past its reconfirmation date, no longer treated as current')], default='unverified', max_length=24),
        ),
        migrations.CreateModel(
            name='CapabilityConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text='What disagrees, in plain language — never fabricated.')),
                ('resolution', models.CharField(choices=[('unresolved', 'Unresolved — review required'), ('declared_claim_upheld', 'Declared claim upheld'), ('external_evidence_upheld', 'External evidence upheld'), ('both_retained_as_distinct', 'Both retained — genuinely distinct claims (e.g. different jurisdiction)')], default='unresolved', max_length=32)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='capability_graph.organisationcapability')),
                ('conflicting_with', models.ForeignKey(blank=True, help_text='The other OrganisationCapability row this one disagrees with, if it still exists.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='capability_graph.organisationcapability')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicRouteRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_route_value', models.CharField(blank=True, max_length=500)),
                ('new_route_value', models.CharField(blank=True, max_length=500)),
                ('previous_is_currently_open', models.BooleanField(null=True)),
                ('new_is_currently_open', models.BooleanField(null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='capability_graph.publicroute')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
