# Generated by Django 5.2.14 on 2026-05-23 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('processing', 'Processing'), ('complete', 'Complete'), ('error', 'Error')], default='draft', max_length=20)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('extracted_text', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score_environment', models.IntegerField(default=0)),
                ('score_social', models.IntegerField(default=0)),
                ('score_governance', models.IntegerField(default=0)),
                ('score_ethics', models.IntegerField(default=0)),
                ('score_innovation', models.IntegerField(default=0)),
                ('score_overall', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('raw_ai_response', models.TextField(blank=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='finding', to='core.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=100)),
                ('question_text', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.assessment')),
            ],
            options={
                'ordering': ['question_key'],
                'unique_together': {('assessment', 'question_key')},
            },
        ),
    ]
