# Generated by Django 5.2.14 on 2026-05-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='pillar_notes',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
