# Generated by Django 5.2.14 on 2026-08-25 10:37

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_assessment_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=core.storage.upload_to_assessment),
        ),
    ]
