# Generated by Django 5.2.14 on 2026-08-26 09:31

import core.storage
import core.upload_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_assessment_uploaded_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=core.storage.upload_to_assessment, validators=[core.upload_validation.UploadValidator()]),
        ),
    ]
