# Generated by Django 5.2.14 on 2026-07-10 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gold_intelligence', '0002_equipmentspec_commissioning_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalTraceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace_id', models.CharField(blank=True, max_length=40, unique=True)),
                ('date', models.DateField()),
                ('amount_usd', models.FloatField()),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('purpose', models.CharField(max_length=250)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=15)),
                ('investor_approval_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_required', max_length=15)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified')], default='unverified', max_length=15)),
                ('insurance_status', models.CharField(choices=[('not_applicable', 'Not Applicable'), ('insured', 'Insured'), ('uninsured', 'Uninsured')], default='not_applicable', max_length=15)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=15)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trace_entries', to='gold_intelligence.capitalbudgetline')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_trace_entries', to='gold_intelligence.goldproject')),
                ('related_equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_trace_entries', to='gold_intelligence.equipmentspec')),
                ('related_milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_trace_entries', to='gold_intelligence.minetimelinemilestone')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectGovernance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('founder_holdco_pct', models.FloatField(blank=True, null=True)),
                ('investor_spv_pct', models.FloatField(blank=True, null=True)),
                ('founder_board_seats', models.PositiveIntegerField(blank=True, null=True)),
                ('investor_board_seats', models.PositiveIntegerField(blank=True, null=True)),
                ('independent_chair_seats', models.PositiveIntegerField(blank=True, null=True)),
                ('reserved_matters_active', models.BooleanField(default=False)),
                ('escrow_account_active', models.BooleanField(default=False)),
                ('investor_first_waterfall_active', models.BooleanField(default=False)),
                ('quarterly_audit_active', models.BooleanField(default=False)),
                ('independent_technical_adviser_active', models.BooleanField(default=False)),
                ('insurance_monitoring_active', models.BooleanField(default=False)),
                ('milestone_based_capital_release_active', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('is_demo', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='governance', to='gold_intelligence.goldproject')),
            ],
        ),
        migrations.CreateModel(
            name='OperationalSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ore_mined_tonnes', models.FloatField(blank=True, null=True)),
                ('plant_throughput_tph', models.FloatField(blank=True, help_text='Tonnes per hour.', null=True)),
                ('gold_grade_g_per_tonne', models.FloatField(blank=True, null=True)),
                ('recovery_rate_pct', models.FloatField(blank=True, null=True)),
                ('dore_produced_kg', models.FloatField(blank=True, null=True)),
                ('equipment_availability_pct', models.FloatField(blank=True, null=True)),
                ('energy_use_mwh', models.FloatField(blank=True, null=True)),
                ('water_recycled_pct', models.FloatField(blank=True, null=True)),
                ('environmental_status', models.CharField(blank=True, choices=[('green', 'Green'), ('amber', 'Amber'), ('red', 'Red')], max_length=10)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operational_snapshots', to='gold_intelligence.goldproject')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('project', 'date'), name='uniq_project_snapshot_date')],
            },
        ),
        migrations.CreateModel(
            name='RedFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_key', models.CharField(help_text='Which deterministic rule created this row (for idempotent re-detection).', max_length=60)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('category', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('capital_exposure_usd', models.FloatField(blank=True, null=True)),
                ('recommended_action', models.TextField(blank=True)),
                ('responsible_party', models.CharField(blank=True, max_length=200)),
                ('resolution_status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved')], default='open', max_length=15)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('is_demo', models.BooleanField(default=True)),
                ('acknowledged_notes', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_flags', to='gold_intelligence.goldproject')),
                ('related_equipment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='red_flags', to='gold_intelligence.equipmentspec')),
                ('related_milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='red_flags', to='gold_intelligence.minetimelinemilestone')),
                ('related_trace_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='red_flags', to='capital_guardian.capitaltraceentry')),
            ],
            options={
                'ordering': ['-severity', '-detected_at'],
                'constraints': [models.UniqueConstraint(fields=('project', 'rule_key'), name='uniq_project_rule_key')],
            },
        ),
    ]
