# Generated by Django 5.2.14 on 2026-07-10 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital_guardian', '0001_initial'),
        ('gold_intelligence', '0003_goldproject_commodity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operationalsnapshot',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='redflag',
            name='actual_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='redflag',
            name='threshold_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='redflag',
            name='resolution_status',
            field=models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('false_positive', 'False Positive')], default='open', max_length=15),
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('governance', 'Governance'), ('milestone', 'Milestone'), ('capex', 'CAPEX Budget'), ('capital', 'Capital / Insurance'), ('equipment', 'Equipment'), ('red_flag', 'Red Flag Status'), ('evidence', 'Evidence Verification')], max_length=20)),
                ('object_description', models.CharField(help_text='e.g. "Milestone: Construction", "Governance: Escrow Account".', max_length=250)),
                ('field_name', models.CharField(max_length=100)),
                ('previous_value', models.CharField(blank=True, max_length=250)),
                ('new_value', models.CharField(blank=True, max_length=250)),
                ('reason', models.TextField(blank=True)),
                ('approval_status', models.CharField(blank=True, max_length=100)),
                ('source_reference', models.CharField(blank=True, db_index=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log_entries', to='gold_intelligence.goldproject')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RedFlagRuleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_key', models.CharField(choices=[('capex_variance', 'CAPEX Variance'), ('insurance_renewal_due', 'Insurance Expiry'), ('equipment_availability', 'Equipment Availability'), ('recovery_rate', 'Recovery Rate vs. Target'), ('water_recycled', 'Water Recycling')], max_length=40)),
                ('enabled', models.BooleanField(default=True)),
                ('warning_threshold', models.FloatField(blank=True, null=True)),
                ('critical_threshold', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(blank=True, help_text='Leave blank for a platform-wide default applied to every project without its own override.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='red_flag_rule_configs', to='gold_intelligence.goldproject')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['rule_key'],
                'constraints': [models.UniqueConstraint(fields=('project', 'rule_key'), name='uniq_project_rule_config')],
            },
        ),
    ]
