# Generated by Django 5.2.14 on 2026-07-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital_guardian', '0002_operationalsnapshot_confidence_redflag_actual_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('equipment_specialty', models.CharField(blank=True, help_text='e.g. "Crushers, Mills", illustrative.', max_length=200)),
                ('typical_lead_time_weeks', models.PositiveIntegerField(blank=True, null=True)),
                ('typical_warranty_years', models.PositiveIntegerField(blank=True, null=True)),
                ('performance_guarantee_years', models.PositiveIntegerField(blank=True, null=True)),
                ('insurance_backed', models.BooleanField(default=False)),
                ('illustrative_price_index', models.FloatField(blank=True, help_text='Relative price positioning, 0-100 (lower = cheaper). Synthetic.', null=True)),
                ('illustrative_service_rating', models.FloatField(blank=True, null=True)),
                ('illustrative_availability_rating', models.FloatField(blank=True, null=True)),
                ('illustrative_energy_efficiency_rating', models.FloatField(blank=True, null=True)),
                ('illustrative_co2_rating', models.FloatField(blank=True, help_text='Higher = lower relative emissions. Synthetic.', null=True)),
                ('illustrative_risk_rating', models.FloatField(blank=True, help_text='Higher = lower relative risk. Synthetic.', null=True)),
                ('illustrative_financial_rating', models.FloatField(blank=True, null=True)),
                ('illustrative_esg_rating', models.FloatField(blank=True, null=True)),
                ('why_selected_notes', models.TextField(blank=True)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='operationalsnapshot',
            name='dore_inventory_kg',
            field=models.FloatField(blank=True, help_text='Doré held in the gold vault, not yet shipped/refined.', null=True),
        ),
        migrations.AddField(
            model_name='operationalsnapshot',
            name='tailings_stored_tonnes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationalsnapshot',
            name='truck_fleet_utilization_pct',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='operationalsnapshot',
            name='water_stored_m3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectgovernance',
            name='dividend_policy_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='auditlogentry',
            name='event_type',
            field=models.CharField(choices=[('governance', 'Governance'), ('milestone', 'Milestone'), ('capex', 'CAPEX Budget'), ('capital', 'Capital / Insurance'), ('equipment', 'Equipment'), ('red_flag', 'Red Flag Status'), ('evidence', 'Evidence Verification'), ('capital_trace', 'Capital Trace Entry')], max_length=20),
        ),
    ]
