# Generated by Django 5.2.14 on 2026-07-17 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capital_guardian', '0003_supplierprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogentry',
            name='event_type',
            field=models.CharField(choices=[('governance', 'Governance'), ('milestone', 'Milestone'), ('capex', 'CAPEX Budget'), ('capital', 'Capital / Insurance'), ('equipment', 'Equipment'), ('red_flag', 'Red Flag Status'), ('evidence', 'Evidence Verification'), ('capital_trace', 'Capital Trace Entry'), ('capital_decision', 'Capital Allocation Decision')], max_length=20),
        ),
    ]
