# Generated by Django 5.2.14 on 2026-09-20 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_observatory', '0011_pipelinestageexecution_actor_and_more'),
        ('capital_guardian', '0004_alter_auditlogentry_event_type'),
        ('gold_intelligence', '0006_projectmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_key', models.CharField(max_length=60)),
                ('trigger_digest', models.CharField(max_length=64)),
                ('risk_snapshot', models.JSONField()),
                ('state', models.CharField(choices=[('awaiting_document', 'Awaiting document'), ('ready', 'Ready to recalculate'), ('failed', 'Failed, retry available'), ('awaiting_approval', 'Awaiting human approval'), ('approved', 'Review approved'), ('rejected', 'Review rejected')], default='awaiting_document', max_length=24)),
                ('document_request', models.TextField()),
                ('document_revision', models.PositiveIntegerField(default=0)),
                ('citation', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=120)),
                ('score_snapshot', models.JSONField(blank=True, default=dict)),
                ('assessment_digest', models.CharField(blank=True, max_length=64)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_followups', to='gold_intelligence.goldproject')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='risk_followup', to='ai_observatory.analysissession')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('project', 'rule_key', 'trigger_digest'), name='unique_risk_followup_trigger')],
            },
        ),
    ]
