"""
company_intelligence/services/kpi_engine.py — feat/company-halal-
intelligence (PR 9): the EcoIQ 114-KPI stewardship alignment engine.

Reuses core.esg_principles_data.PRINCIPLES (public name: "Capital Ethics
Compendium") verbatim as the ONE canonical 114-item source — verified at
import time to still be exactly 114 entries, ids 1-114, so a future edit
to that module that breaks the count fails loudly here rather than
silently producing a wrong denominator anywhere in this app.

Per docs/governance-principles-surah-map.md's internal-only firewall nothing
in this module or its callers may reference the Quran/Surah origin mapping
of that list. Public language: "EcoIQ 114-KPI stewardship framework" /
"Capital Ethics Compendium principle".

CRITICAL RULE (from the PR9 brief): assessments are never generated by
asking an LLM "does this company support KPI Y" and storing the answer as
fact. Every CompanyKPIAssessment.status here is either (a) already stored
by a human/deterministic ingestion process, or (b) derived in
derive_status_from_evidence() below by a fixed, auditable rule over the
EXPLICIT relationship type (supports/conflicts/context) a human or
ingestion rule already assigned to each linked evidence item — never
inferred by this module from evidence text.
"""
from core.esg_principles_data import PRINCIPLES

assert len(PRINCIPLES) == 114 and sorted(p['id'] for p in PRINCIPLES) == list(range(1, 115)), (
    'core.esg_principles_data.PRINCIPLES is no longer a clean 1-114 list — '
    'company_intelligence.services.kpi_engine refuses to compute a KPI '
    'denominator against a broken canonical source.'
)

PRINCIPLES_BY_ID = {p['id']: p for p in PRINCIPLES}

STRONG_EVIDENCE_TIERS = {'human_reviewed', 'independently_verified'}

STATUS_BUCKET_ORDER = [
    'strong_support', 'support', 'mixed', 'neutral_or_no_material_link',
    'conflict', 'insufficient_evidence', 'not_assessed',
]


def derive_status_from_evidence(evidence_links):
    """
    evidence_links: iterable of CompanyKPIEvidenceLink rows (with
    .evidence prefetched), each carrying an explicit, human/ingestion-set
    `relationship` ('supports'/'conflicts'/'context') — never re-derived
    from evidence free text here.

    feat/company-evidence-ingestion (PR 10): only 'confirmed' links count.
    A deterministic ingestion matcher may PROPOSE a link from newly
    harvested evidence (review_state='proposed') — that link exists in the
    database for a human reviewer to see and act on, but never moves this
    company's KPI status until review confirms it. This is what keeps
    "evidence-driven, never LLM/ingestion-asserted" true even once
    automated candidate matching exists.

    Deterministic rule, in priority order (over confirmed links only):
    - No links at all                                  -> insufficient_evidence
    - Only 'context' links (no supports/conflicts)      -> insufficient_evidence
    - Both supporting AND conflicting links exist        -> mixed
    - Only conflicting links exist                       -> conflict
    - Only supporting links exist, none at a strong tier -> support
    - Only supporting links exist, at least one strong
      (human_reviewed/independently_verified) tier        -> strong_support
    """
    links = [l for l in evidence_links if l.review_state == 'confirmed']
    supports = [l for l in links if l.relationship == 'supports']
    conflicts = [l for l in links if l.relationship == 'conflicts']

    if not supports and not conflicts:
        return 'insufficient_evidence'
    if supports and conflicts:
        return 'mixed'
    if conflicts:
        return 'conflict'
    strong = any(l.evidence.review_tier in STRONG_EVIDENCE_TIERS for l in supports)
    return 'strong_support' if strong else 'support'


def recompute_assessment_status(assessment):
    """Recomputes and persists one CompanyKPIAssessment's status from its
    real, currently-linked evidence — never leaves a stale status after
    evidence is added/removed. Returns the new status string."""
    status = derive_status_from_evidence(assessment.evidence_links.select_related('evidence').all())
    if assessment.status != status:
        assessment.status = status
        assessment.save(update_fields=['status', 'last_assessed_at'])
    return status


def kpi_alignment_profile(company_profile):
    """
    Builds the full 114-row profile for one company: every principle in
    PRINCIPLES, cross-referenced against this company's real
    CompanyKPIAssessment rows (a principle with no row is honestly
    'not_assessed', never silently dropped from the denominator).

    Returns {'total': 114, 'counts': {status: int, ...}, 'coverage_pct',
    'rows': [{'kpi_id','title','category','tagline','status','status_display',
    'assessment' (model instance or None)}, ...]} — rows preserve
    PRINCIPLES' natural id order (1-114).
    """
    from company_intelligence.models import KPI_STATUS_CHOICES

    status_display = dict(KPI_STATUS_CHOICES)
    assessments_by_kpi = {
        a.kpi_id: a for a in company_profile.kpi_assessments.select_related('company').all()
    }

    counts = {key: 0 for key, _ in KPI_STATUS_CHOICES}
    rows = []
    pending_review_total = 0
    for principle in PRINCIPLES:
        assessment = assessments_by_kpi.get(principle['id'])
        status = assessment.status if assessment is not None else 'not_assessed'
        counts[status] = counts.get(status, 0) + 1
        pending_count = 0
        if assessment is not None:
            pending_count = sum(1 for l in assessment.evidence_links.all() if l.review_state == 'proposed')
            pending_review_total += pending_count
        rows.append({
            'kpi_id': principle['id'],
            'title': principle['title'],
            'category': principle['category'],
            'tagline': principle['tagline'],
            'question': principle['question'],
            'status': status,
            'status_display': status_display.get(status, status),
            'assessment': assessment,
            'pending_review_count': pending_count,
        })

    total = len(PRINCIPLES)
    assessed = total - counts.get('not_assessed', 0)
    return {
        'total': total,
        'assessed': assessed,
        'coverage_pct': round((assessed / total) * 100, 1) if total else 0.0,
        'counts': counts,
        'rows': rows,
        'pending_review_total': pending_review_total,
    }


def filter_rows(rows, status_filter=None):
    """Used by the KPI Explorer view — a pure filter over already-computed
    rows, never a second query path. `status_filter` may be a single
    status key or an iterable of them; None returns all rows unfiltered."""
    if not status_filter:
        return rows
    if isinstance(status_filter, str):
        status_filter = {status_filter}
    else:
        status_filter = set(status_filter)
    return [r for r in rows if r['status'] in status_filter]
