# Generated by Django 5.2.14 on 2026-05-25 13:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryIntelligence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text='Lowercase ISO country name used as slug', max_length=3, unique=True)),
                ('country_name', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, help_text='e.g. Central Asia, Eastern Europe', max_length=100)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
                ('national_ecoiq_score', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('company_count', models.PositiveIntegerField(default=0)),
                ('verified_company_count', models.PositiveIntegerField(default=0)),
                ('avg_pollution', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('avg_reduction', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('avg_investment', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('avg_transparency', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('avg_community', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('total_co2_reduction_tonnes', models.BigIntegerField(default=0)),
                ('total_investment_usd', models.BigIntegerField(default=0)),
                ('total_households_helped', models.BigIntegerField(default=0)),
                ('total_projects', models.PositiveIntegerField(default=0)),
                ('sector_distribution', models.JSONField(blank=True, default=dict)),
                ('top_sector', models.CharField(blank=True, max_length=30)),
                ('reporting_pct', models.FloatField(default=0.0, help_text='% of companies with public reports')),
                ('transparency_rank', models.PositiveIntegerField(blank=True, null=True)),
                ('score_6m_ago', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('trend_direction', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('declining', 'Declining')], default='stable', max_length=12)),
                ('trend_delta', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('ai_briefing', models.TextField(blank=True, help_text='AI-generated executive briefing (latest)')),
                ('briefing_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_computed', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country Intelligence',
                'verbose_name_plural': 'Country Intelligence',
                'ordering': ['-national_ecoiq_score', 'country_name'],
            },
        ),
        migrations.CreateModel(
            name='ExecutiveBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('company', 'Company'), ('country', 'Country'), ('sector', 'Sector'), ('global', 'Global')], default='company', max_length=10)),
                ('sector_code', models.CharField(blank=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('headline', models.CharField(blank=True, help_text='One-line AI verdict', max_length=500)),
                ('body', models.TextField(help_text='Full AI-generated briefing (Markdown)')),
                ('key_risks', models.JSONField(blank=True, default=list)),
                ('key_drivers', models.JSONField(blank=True, default=list)),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='briefings', to='league.company')),
                ('country_intel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='briefings', to='intelligence.countryintelligence')),
            ],
            options={
                'verbose_name': 'Executive Briefing',
                'verbose_name_plural': 'Executive Briefings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntelligenceAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('score_drop', 'Score Drop'), ('score_surge', 'Score Surge'), ('greenwashing', 'Greenwashing Detected'), ('transparency_loss', 'Transparency Loss'), ('transparency_gain', 'Transparency Gain'), ('new_report', 'New Report Available'), ('methane_spike', 'Methane Spike'), ('violation', 'Regulatory Violation'), ('new_project', 'New Project Announced'), ('rank_change', 'Rank Change'), ('monitor_change', 'Website Change Detected')], max_length=25)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='medium', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('metric_before', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('metric_after', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('metric_delta', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='league.company')),
                ('country_intel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='intelligence.countryintelligence')),
            ],
            options={
                'verbose_name': 'Intelligence Alert',
                'verbose_name_plural': 'Intelligence Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonitorWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2000)),
                ('check_type', models.CharField(choices=[('website', 'Company Website'), ('pdf_directory', 'PDF/Report Directory'), ('news_feed', 'News Feed'), ('regulator', 'Regulator / Gov Portal')], default='website', max_length=20)),
                ('label', models.CharField(blank=True, help_text='Human-readable label for this watch target', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_content_hash', models.CharField(blank=True, help_text='SHA-256 of fetched content', max_length=64)),
                ('last_content_size', models.PositiveIntegerField(default=0)),
                ('change_detected', models.BooleanField(default=False)),
                ('change_detected_at', models.DateTimeField(blank=True, null=True)),
                ('ingestion_triggered', models.BooleanField(default=False)),
                ('check_interval_hours', models.PositiveIntegerField(default=24)),
                ('consecutive_errors', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='league.company')),
            ],
            options={
                'verbose_name': 'Monitor Watch',
                'verbose_name_plural': 'Monitor Watches',
                'ordering': ['company', 'url'],
            },
        ),
        migrations.CreateModel(
            name='StrategicSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('methane', 'Methane Leakage'), ('coal_transition', 'Coal-to-Gas Transition'), ('water_restoration', 'Water Restoration'), ('flare_reduction', 'Flare Reduction'), ('modernisation', 'Industrial Modernisation'), ('ethical_investment', 'Ethical Investment')], max_length=25)),
                ('polarity', models.CharField(choices=[('risk', 'Risk'), ('positive', 'Positive'), ('neutral', 'Neutral')], default='neutral', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('metric_value', models.FloatField(blank=True, null=True)),
                ('metric_unit', models.CharField(blank=True, max_length=50)),
                ('source_url', models.URLField(blank=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.5, help_text='0-1 AI confidence')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='league.company')),
            ],
            options={
                'verbose_name': 'Strategic Signal',
                'verbose_name_plural': 'Strategic Signals',
                'ordering': ['-detected_at', '-confidence'],
            },
        ),
    ]
