# Generated by Django 5.2.14 on 2026-07-26 09:36
"""
Data migration — seeds the reference registries (AssetType, UnitCategory,
Unit) a Digital Twin needs to exist at all. All idempotent (get_or_create),
safe to re-run. No stewardship/religious content is seeded here — that
ships separately in digital_twin/services/stewardship.py, in explicit
draft/requires-scholarly-review status.
"""
from django.db import migrations

ASSET_TYPES = [
    ('manufacturing_facility', 'Manufacturing Facility', 'A factory or production facility converting inputs into finished goods.'),
    ('mine', 'Mine', 'An active extraction site for ore, minerals or aggregates.'),
    ('mineral_deposit_exploration', 'Mineral Deposit / Exploration Asset', 'A pre-production deposit or exploration licence area.'),
    ('processing_plant', 'Processing Plant', 'A plant that processes, refines or beneficiates a raw material.'),
    ('energy_asset', 'Energy Asset', 'A generation, storage or distribution asset (thermal, renewable, grid, heating).'),
    ('infrastructure_project', 'Infrastructure Project', 'Transport, water, or other public/industrial infrastructure.'),
    ('generic_industrial_asset', 'Generic Industrial Asset', 'An industrial asset that does not fit a more specific category yet.'),
    ('other', 'Other', 'Escape hatch for an asset type not yet catalogued — extend this registry with a new row, not new code.'),
]

UNIT_CATEGORIES = {
    'energy': ('Energy', [
        ('kwh', 'Kilowatt-hour', 'kWh', 1.0, True),
        ('mwh', 'Megawatt-hour', 'MWh', 1000.0, False),
        ('gj', 'Gigajoule', 'GJ', 277.7778, False),
    ]),
    'mass': ('Mass', [
        ('kg', 'Kilogram', 'kg', 1.0, True),
        ('tonne', 'Tonne', 't', 1000.0, False),
    ]),
    'volume': ('Volume', [
        ('m3', 'Cubic Metre', 'm³', 1.0, True),
        ('liter', 'Litre', 'L', 0.001, False),
    ]),
    'time': ('Time', [
        ('hour', 'Hour', 'hr', 1.0, True),
        ('day', 'Day', 'day', 24.0, False),
        ('year', 'Year', 'yr', 8760.0, False),
    ]),
    'percentage': ('Percentage', [
        ('pct', 'Percent', '%', 1.0, True),
    ]),
    'count': ('Count', [
        ('count', 'Count', '', 1.0, True),
    ]),
    'emissions': ('Emissions (CO2-equivalent)', [
        ('kgco2e', 'Kilogram CO2-equivalent', 'kgCO2e', 1.0, True),
        ('tco2e', 'Tonne CO2-equivalent', 'tCO2e', 1000.0, False),
    ]),
}


def seed_reference_data(apps, schema_editor):
    AssetType = apps.get_model('digital_twin', 'AssetType')
    UnitCategory = apps.get_model('digital_twin', 'UnitCategory')
    Unit = apps.get_model('digital_twin', 'Unit')

    for code, display_name, description in ASSET_TYPES:
        AssetType.objects.get_or_create(code=code, defaults={'display_name': display_name, 'description': description})

    for category_code, (category_name, units) in UNIT_CATEGORIES.items():
        category, _ = UnitCategory.objects.get_or_create(code=category_code, defaults={'name': category_name})
        for unit_code, unit_name, symbol, multiplier, is_base in units:
            Unit.objects.get_or_create(
                code=unit_code,
                defaults={
                    'category': category, 'name': unit_name, 'symbol': symbol,
                    'to_base_multiplier': multiplier, 'is_base_unit': is_base,
                },
            )


def noop_reverse(apps, schema_editor):
    """Reference data is safe to leave in place on rollback — nothing else
    depends on this migration being reversible destructively."""


class Migration(migrations.Migration):

    dependencies = [
        ('digital_twin', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_reference_data, noop_reverse),
    ]
