# Generated by Django 5.2.14 on 2026-07-26 09:41
"""
Data migration — seeds the initial 10 StewardshipPrinciple rows, one
SacredSourceReference placeholder each, and one StewardshipKPI per
principle (matching the slugs `services/stewardship.py::KPI_SCORERS`
knows how to compute).

CRITICAL: no verse text, translation, or scholarly interpretation is
authored here. Every SacredSourceReference ships with
review_status='source_needed' and an empty `approved_translation`; every
StewardshipPrinciple ships with review_status='draft_reflection' and
is_approved_for_use=False; every StewardshipKPI ships with
approval_status='requires_scholarly_review'. The formulas can exist and be
tested; nothing here is presented as an approved religious judgement.
"""
from django.db import migrations
from django.utils.text import slugify

REQUIRES_REVIEW_NOTE = 'Requires scholarly review before use in any principle or KPI.'

# (principle_name, domain, description, operational_meaning, kpi_slug, kpi_name, kpi_description, formula_definition)
PRINCIPLES = [
    (
        'Prevention of Waste', 'environmental',
        "Avoid the wasteful destruction or squandering of useful resources.",
        'Reduce preventable loss of useful resources (material, energy, water) across the process.',
        'prevention-of-waste-reduction', 'Preventable Waste Reduction',
        'Whether a scenario reduces recorded material/waste loss relative to baseline.',
        'score = 100 if scenario.waste_impact < 0 (reduction); 0 if increased; 50 if unchanged; '
        'null if waste_impact was never recorded. See services/stewardship.py::_score_prevention_of_waste.',
    ),
    (
        'Protection from Harm', 'safety',
        'Do not cause harm to people through action or negligence.',
        'Screen worker- and community-impact narratives for harm indicators before any promotion.',
        'worker-community-harm-screen', 'Worker & Community Harm Screen',
        'Deterministic keyword scan of worker_impact/community_impact text for harm language.',
        'blocking=True if harm keywords (injury, fatality, displacement, exposure, harm, unsafe) are found in '
        'worker_impact or community_impact; else score=100 if both fields documented, else a warning. See '
        'services/stewardship.py::_score_protection_from_harm.',
    ),
    (
        'Honesty and Accurate Measurement', 'governance',
        'Give full measure and do not deal fraudulently in weighing or reporting.',
        'A stated confidence value is only meaningful when backed by real evidence references.',
        'evidence-backed-confidence', 'Evidence-Backed Confidence',
        'Whether the scenario confidence is backed by at least one evidence reference.',
        'score = scenario.confidence; warning if evidence_references is empty. See '
        'services/stewardship.py::_score_honesty_accurate_measurement.',
    ),
    (
        'Stewardship of Natural Resources', 'environmental',
        'Humanity holds the earth in trust and must not corrupt or deplete it heedlessly.',
        'Favour scenarios that reduce energy, water and emissions impact together, not just one axis.',
        'net-natural-resource-footprint', 'Net Natural-Resource Footprint',
        'Proportion of recorded energy/water/emissions impacts that are reductions.',
        'score = (count of negative values among {energy_impact, water_impact, emissions_impact}) / '
        '(count of non-null values) * 100. See services/stewardship.py::_score_stewardship_of_natural_resources.',
    ),
    (
        'Balance', 'financial',
        "Maintain due proportion — do not transgress the balance ('mizan').",
        'A modernisation scenario should be proportionate: cost and benefit should stay in a reasonable balance.',
        'capex-benefit-balance', 'CAPEX/Benefit Balance',
        'A simple decreasing function of estimated payback period.',
        'score = max(0, 100 - min(100, payback_months / 120 * 100)). See services/stewardship.py::_score_balance.',
    ),
    (
        'Accountability', 'governance',
        'Every person is accountable for what they are entrusted with.',
        'A scenario should carry a documented evidence, risk, dependency and regulatory trail.',
        'decision-trail-accountability', 'Decision-Trail Accountability',
        'Proportion of governance-trail fields (evidence, risks, dependencies, regulatory requirements) populated.',
        'score = (count of populated fields among {evidence_references, technical_risks, dependencies, '
        'regulatory_requirements}) / 4 * 100. See services/stewardship.py::_score_accountability.',
    ),
    (
        'Fair Dealing', 'governance',
        'Deal fairly and transparently, without favouring a hidden party.',
        'A technical specification should be supplier-neutral and reviewable, not a hidden endorsement.',
        'supplier-neutral-specification-check', 'Supplier-Neutral Specification Check',
        'Whether a reviewable technical specification has been recorded.',
        'score = 100 if technical_specification is non-empty, else null with a warning. See '
        'services/stewardship.py::_score_fair_dealing.',
    ),
    (
        'Protection of Vulnerable People', 'social',
        'Special care is due to those most exposed to harm from a decision.',
        'Community-impact narratives should be screened for vulnerable-group effects.',
        'community-vulnerability-screen', 'Community Vulnerability Screen',
        'Deterministic keyword scan of community_impact text for vulnerability language.',
        'A neutral score of 50 (never auto-approved) and a mandatory warning when vulnerability keywords '
        '(vulnerable, indigenous, resettlement, children, displaced) are found. See '
        'services/stewardship.py::_score_protection_of_vulnerable_people.',
    ),
    (
        'Benefit to Future Generations', 'environmental',
        'Consider the long-term legacy left for those who come after.',
        'Favour scenarios with a long-term reduction in emissions, not just short-term savings.',
        'long-term-emissions-legacy', 'Long-Term Emissions Legacy',
        'Whether the scenario reduces recorded emissions impact.',
        'score = 100 if emissions_impact < 0, 0 if increased, 50 if unchanged, null if unset. See '
        'services/stewardship.py::_score_benefit_to_future_generations.',
    ),
    (
        'Justice', 'social',
        'Stand firm for justice, even against your own interest.',
        'Costs and benefits to workers and the community should be documented, not left invisible.',
        'equitable-impact-disclosure', 'Equitable Impact Disclosure',
        'Whether both worker_impact and community_impact have been documented for this scenario.',
        'This is an operational documentation-completeness indicator, not a religious/moral judgement. '
        'score = (count of {worker_impact, community_impact} documented) / 2 * 100. See '
        'services/stewardship.py::_score_justice.',
    ),
]


def seed_stewardship_kpis(apps, schema_editor):
    SacredSourceReference = apps.get_model('digital_twin', 'SacredSourceReference')
    StewardshipPrinciple = apps.get_model('digital_twin', 'StewardshipPrinciple')
    StewardshipKPI = apps.get_model('digital_twin', 'StewardshipKPI')

    for (principle_name, domain, description, operational_meaning, kpi_slug, kpi_name,
         kpi_description, formula_definition) in PRINCIPLES:
        source, _ = SacredSourceReference.objects.get_or_create(
            canonical_reference=f"Qur'anic source for '{principle_name}' — to be confirmed by qualified scholar.",
            defaults={
                'source_tradition': 'quran',
                'review_status': 'source_needed',
                'notes': REQUIRES_REVIEW_NOTE,
            },
        )
        principle, _ = StewardshipPrinciple.objects.get_or_create(
            slug=slugify(principle_name),
            defaults={
                'name': principle_name,
                'description': description,
                'operational_meaning': operational_meaning,
                'domain': domain,
                'review_status': 'draft_reflection',
                'is_approved_for_use': False,
            },
        )
        principle.source_references.add(source)

        StewardshipKPI.objects.get_or_create(
            slug=kpi_slug,
            defaults={
                'principle': principle,
                'name': kpi_name,
                'description': kpi_description,
                'formula_definition': formula_definition,
                'formula_version': '1.0.0',
                'scoring_direction': 'higher_is_better',
                'approval_status': 'requires_scholarly_review',
                'is_active': True,
            },
        )


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('digital_twin', '0002_seed_reference_data'),
    ]

    operations = [
        migrations.RunPython(seed_stewardship_kpis, noop_reverse),
    ]
