# Generated by Django 5.2.14 on 2026-07-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_agents', '0002_goodmission_signalcluster_signalprovider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldsignal',
            name='source_excerpt',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='signalcluster',
            name='signal_type',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='worldsignal',
            name='signal_type',
            field=models.CharField(choices=[('need', 'Need'), ('harm', 'Harm'), ('waste', 'Waste'), ('risk', 'Risk'), ('resource', 'Resource'), ('funding', 'Funding'), ('policy_change', 'Policy change'), ('technology_change', 'Technology change'), ('price_change', 'Price change'), ('opportunity', 'Opportunity'), ('emergency', 'Emergency'), ('public_need', 'Public need'), ('environmental_risk', 'Environmental risk'), ('resource_available', 'Resource available'), ('funding_available', 'Funding available'), ('infrastructure_opportunity', 'Infrastructure opportunity'), ('waste_or_unused_resource', 'Waste or unused resource'), ('community_need', 'Community need'), ('unknown', 'Unknown / needs review')], max_length=30),
        ),
    ]
