# Generated by Django 5.2.14 on 2026-07-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('good_agents', '0003_worldsignal_source_excerpt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humanreviewdecision',
            name='decision',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('deferred', 'Deferred'), ('needs_more_evidence', 'Needs more evidence'), ('useful', 'Useful'), ('not_useful', 'Not useful'), ('false_positive', 'False positive'), ('duplicate', 'Duplicate'), ('high_priority', 'High priority'), ('not_actionable', 'Not actionable')], max_length=24),
        ),
    ]
