# Generated by Django 5.2.14 on 2026-07-23 18:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_companyprofile_last_refresh_at_and_more'),
        ('gold_intelligence', '0005_goldproject_organisation'),
        ('good_agents', '0004_alter_humanreviewdecision_decision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_role', models.CharField(blank=True, max_length=150)),
                ('public_contact_channel', models.CharField(blank=True, max_length=255)),
                ('source_of_contact_info', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('verified', 'Verified'), ('stale', 'Stale'), ('invalid', 'Invalid')], default='identified', max_length=10)),
                ('last_verified', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ActionGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_state', models.CharField(choices=[('discovered', 'Discovered'), ('needs_review', 'Needs review'), ('approved_for_contact', 'Approved for contact'), ('approved_for_research', 'Approved for research'), ('approved_for_project_creation', 'Approved for project creation'), ('rejected', 'Rejected'), ('needs_more_evidence', 'Needs more evidence'), ('duplicate', 'Duplicate'), ('not_actionable', 'Not actionable')], default='discovered', max_length=32)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action_gate', to='good_agents.goodopportunity')),
            ],
        ),
        migrations.CreateModel(
            name='ActionGateTransition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_state', models.CharField(blank=True, max_length=32)),
                ('new_state', models.CharField(max_length=32)),
                ('reason', models.TextField(blank=True)),
                ('evidence_reviewed', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='good_agents.actiongate')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathway_type', models.CharField(choices=[('information_request', 'Information request'), ('introduction', 'Introduction'), ('resource_connection', 'Resource connection'), ('funding_referral', 'Funding referral'), ('authority_alert', 'Authority alert'), ('project_candidate', 'Project candidate'), ('expert_review', 'Expert review'), ('data_request', 'Data request'), ('zero_capital_action', 'Zero-capital action'), ('other', 'Other')], max_length=24)),
                ('rationale', models.TextField(blank=True)),
                ('capital_required', models.CharField(choices=[('yes', 'Yes'), ('no', 'No'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('zero_capital_path', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('blocked', 'Blocked'), ('completed', 'Completed')], default='open', max_length=12)),
                ('next_step', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('blocked_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_pathways', to='good_agents.goodopportunity')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_action_pathways', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActionTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('discovered', 'Opportunity discovered'), ('human_reviewed', 'Human reviewed'), ('action_approved', 'Action approved'), ('owner_assigned', 'Owner assigned'), ('outreach_drafted', 'Outreach drafted'), ('outreach_approved', 'Outreach approved'), ('sent', 'Sent'), ('reply_received', 'Reply received'), ('connection_made', 'Connection made'), ('project_created', 'Project created'), ('execution_started', 'Execution started'), ('outcome_measured', 'Outcome measured'), ('outcome_verified', 'Outcome verified'), ('evidence_memory_updated', 'Evidence Memory updated')], max_length=32)),
                ('source_object_reference', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='good_agents.goodopportunity')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConnectionCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('candidate_match', 'Candidate match'), ('approved_for_introduction', 'Approved for introduction'), ('introduced', 'Introduced'), ('interest_confirmed', 'Interest confirmed'), ('not_suitable', 'Not suitable'), ('declined', 'Declined'), ('expired', 'Expired')], default='candidate_match', max_length=26)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_pathway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection_candidates', to='good_agents.actionpathway')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('resource_match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='connection_candidate', to='good_agents.resourcematch')),
            ],
        ),
        migrations.CreateModel(
            name='FundingAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('match_found', 'Match found'), ('eligibility_review', 'Eligibility review'), ('application_candidate', 'Application candidate'), ('application_started', 'Application started'), ('submitted', 'Submitted'), ('awarded', 'Awarded'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('unknown', 'Unknown')], default='match_found', max_length=24)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_pathway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_actions', to='good_agents.actionpathway')),
                ('funding_match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funding_action', to='good_agents.fundingmatch')),
            ],
        ),
        migrations.CreateModel(
            name='OutreachDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_type', models.CharField(choices=[('email', 'Email'), ('briefing_note', 'Briefing note'), ('introduction_request', 'Introduction request'), ('evidence_summary', 'Evidence summary'), ('project_invitation', 'Project invitation'), ('data_request', 'Data request'), ('grant_referral_note', 'Grant referral note')], default='email', max_length=24)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('associated_evidence', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready_for_review', 'Ready for review'), ('approved', 'Approved'), ('sent', 'Sent'), ('replied', 'Replied'), ('no_response', 'No response'), ('declined', 'Declined'), ('follow_up_required', 'Follow-up required')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_channel', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outreach_drafts', to='good_agents.actionpathway')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outreach_drafts', to='good_agents.actioncontact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rationale', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('created', 'Created')], default='proposed', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_pathway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_candidates', to='good_agents.actionpathway')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gold_intelligence.goldproject')),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_candidate', to='good_agents.goodopportunity')),
            ],
        ),
        migrations.CreateModel(
            name='ResponsibleParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('party_type', models.CharField(choices=[('local_authority', 'Local authority'), ('government_department', 'Government department'), ('company', 'Company'), ('charity', 'Charity'), ('ngo', 'NGO'), ('community_organisation', 'Community organisation'), ('funder', 'Funder'), ('research_institution', 'Research institution'), ('facility_operator', 'Facility operator'), ('regulator', 'Regulator'), ('internal_ecoiq_team', 'Internal EcoIQ team'), ('other', 'Other')], default='other', max_length=24)),
                ('resolution_status', models.CharField(choices=[('known_organisation', 'Known organisation'), ('possible_organisation', 'Possible organisation'), ('unresolved', 'Unresolved')], default='unresolved', max_length=24)),
                ('evidence_ref', models.CharField(blank=True, max_length=200)),
                ('confidence', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_pathway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_parties', to='good_agents.actionpathway')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('linked_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='companies.companyprofile')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible_parties', to='good_agents.goodopportunity')),
            ],
            options={
                'verbose_name_plural': 'Responsible parties',
                'ordering': ['-confidence'],
            },
        ),
        migrations.AddField(
            model_name='actioncontact',
            name='responsible_party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='good_agents.responsibleparty'),
        ),
    ]
