# Generated by Django 5.2.14 on 2026-07-24 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capability_graph', '0001_initial'),
        ('good_agents', '0005_actioncontact_actiongate_actiongatetransition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingmatch',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funding_match_mentions', to='capability_graph.organisation'),
        ),
        migrations.AddField(
            model_name='responsibleparty',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_party_mentions', to='capability_graph.organisation'),
        ),
    ]
