# Generated by Django 5.2.14 on 2026-07-24 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capability_graph', '0002_organisationcapability_declared_by_and_more'),
        ('good_agents', '0006_fundingmatch_organisation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='availableresource',
            name='declared_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='availableresource',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declared_resources', to='capability_graph.organisation'),
        ),
        migrations.AlterField(
            model_name='availableresource',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('limited', 'Limited'), ('reserved', 'Reserved'), ('unavailable', 'Unavailable'), ('expired', 'Expired'), ('unknown', 'Unknown')], default='unknown', max_length=11),
        ),
    ]
