# Generated by Django 5.2.14 on 2026-05-29 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ethics', '0002_formula_registry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='analystnote',
            name='formula_score',
            field=models.ForeignKey(blank=True, help_text='Optional: link note to a specific formula score', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyst_notes', to='ethics.formulascore'),
        ),
        migrations.AlterField(
            model_name='analystnote',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Show this note on the public company page'),
        ),
        migrations.AlterField(
            model_name='companyethicsprofile',
            name='analyst_notes_text',
            field=models.TextField(blank=True, help_text='Quick analyst notes (full notes in AnalystNote records)'),
        ),
        migrations.AlterField(
            model_name='companyethicsprofile',
            name='analyst_reviewer',
            field=models.ForeignKey(blank=True, help_text='Staff member who last reviewed this profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyethicsprofile',
            name='data_confidence',
            field=models.FloatField(default=0.5, help_text='0-1: data completeness and analysis reliability'),
        ),
        migrations.AlterField(
            model_name='companyethicsprofile',
            name='expected_score_improvement',
            field=models.FloatField(blank=True, help_text='Expected EcoIQ point gain if top 3 actions implemented', null=True),
        ),
        migrations.AlterField(
            model_name='companyethicsprofile',
            name='key_benefits',
            field=models.JSONField(blank=True, default=list, help_text='List of {label, detail, strength, maqasid}'),
        ),
        migrations.AlterField(
            model_name='companyethicsprofile',
            name='key_harms',
            field=models.JSONField(blank=True, default=list, help_text='List of {label, detail, severity, maqasid}'),
        ),
        migrations.AlterField(
            model_name='companyethicsprofile',
            name='net_ethical_impact',
            field=models.FloatField(default=0.0, help_text='NEI: benefit minus harm balance (0-100)'),
        ),
        migrations.AlterField(
            model_name='companyethicsprofile',
            name='next_best_actions',
            field=models.JSONField(blank=True, default=list, help_text='Top 3 recommended action titles'),
        ),
        migrations.AlterField(
            model_name='companyethicsprofile',
            name='regenerative_value',
            field=models.FloatField(default=0.0, help_text='RVI: long-term societal value creation (0-100)'),
        ),
        migrations.AlterField(
            model_name='companyethicsprofile',
            name='total_benefit_score',
            field=models.FloatField(default=0.0, help_text='Average of all benefit pillars (0-100)'),
        ),
        migrations.AlterField(
            model_name='companyethicsprofile',
            name='total_harm_score',
            field=models.FloatField(default=0.0, help_text='Weighted harm composite (0-100)'),
        ),
        migrations.AlterField(
            model_name='companyethicsprofile',
            name='transition_stewardship',
            field=models.FloatField(default=0.0, help_text='TSS: active harm-reduction trajectory (0-100)'),
        ),
        migrations.AlterField(
            model_name='formuladefinition',
            name='input_fields',
            field=models.JSONField(blank=True, default=list, help_text='List of {field, source, description} dicts'),
        ),
        migrations.AlterField(
            model_name='formuladefinition',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Show on public methodology page'),
        ),
        migrations.AlterField(
            model_name='formuladefinition',
            name='maqasid_notes',
            field=models.TextField(blank=True, help_text='Internal mapping notes — do not expose in public UI'),
        ),
        migrations.AlterField(
            model_name='formuladefinition',
            name='master_formula',
            field=models.CharField(choices=[('NEI', 'Net Ethical Impact'), ('TSS', 'Transition Stewardship Score'), ('RVI', 'Regenerative Value Index'), ('ALL', 'Cross-cutting / All Formulas')], default='ALL', help_text='Which master formula this sub-formula feeds into', max_length=5),
        ),
        migrations.AlterField(
            model_name='formuladefinition',
            name='methodology_notes',
            field=models.TextField(blank=True, help_text='Technical implementation notes (internal)'),
        ),
        migrations.AlterField(
            model_name='formuladefinition',
            name='weight',
            field=models.FloatField(default=1.0, help_text='Relative weight within master formula (0-1)'),
        ),
        migrations.AlterField(
            model_name='formulascore',
            name='analyst_override',
            field=models.FloatField(blank=True, help_text='Analyst-adjusted score (0-100); overrides computed value', null=True),
        ),
        migrations.AlterField(
            model_name='formulascore',
            name='analyst_reason',
            field=models.TextField(blank=True, help_text='Rationale for analyst adjustment'),
        ),
        migrations.AlterField(
            model_name='formulascore',
            name='confidence',
            field=models.FloatField(default=0.5, help_text='0-1 data confidence for this formula'),
        ),
        migrations.AlterField(
            model_name='formulascore',
            name='evidence_verified',
            field=models.BooleanField(default=False, help_text='Evidence has been independently verified'),
        ),
        migrations.AlterField(
            model_name='formulascore',
            name='normalized_score',
            field=models.FloatField(help_text='0-100 normalized score'),
        ),
        migrations.AlterField(
            model_name='formulascore',
            name='raw_value',
            field=models.FloatField(help_text='Raw computed value before normalization'),
        ),
        migrations.AlterField(
            model_name='formulascore',
            name='source_urls',
            field=models.JSONField(blank=True, default=list, help_text='URLs supporting this score'),
        ),
        migrations.AlterField(
            model_name='improvementmilestone',
            name='expected_score_gain',
            field=models.FloatField(default=0.0, help_text='Expected EcoIQ total score improvement (points)'),
        ),
        migrations.AlterField(
            model_name='improvementmilestone',
            name='kpi_metric',
            field=models.CharField(blank=True, help_text='Measurable KPI to track progress', max_length=255),
        ),
        migrations.AlterField(
            model_name='improvementmilestone',
            name='pillar',
            field=models.CharField(blank=True, help_text='EcoIQ pillar this improvement targets', max_length=50),
        ),
        migrations.AlterField(
            model_name='improvementmilestone',
            name='priority',
            field=models.PositiveSmallIntegerField(default=5, help_text='1=highest, 10=lowest priority'),
        ),
    ]
