# Generated by Django 5.2.14 on 2026-07-24 12:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capability_graph', '0002_organisationcapability_declared_by_and_more'),
        ('good_agents', '0007_availableresource_declared_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingProgrammeDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programme_name', models.CharField(max_length=255)),
                ('funder_type', models.CharField(choices=[('government_programme', 'Government Programme'), ('grant', 'Grant'), ('development_finance', 'Development Finance'), ('impact_investor', 'Impact Investor'), ('family_office', 'Family Office'), ('philanthropy', 'Philanthropy'), ('waqf', 'Waqf'), ('islamic_finance', 'Islamic Finance'), ('green_finance', 'Green Finance'), ('corporate', 'Corporate')], max_length=24)),
                ('official_source_url', models.URLField(blank=True)),
                ('amount_min_usd', models.FloatField(blank=True, null=True)),
                ('amount_max_usd', models.FloatField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('geography', models.CharField(blank=True, max_length=150)),
                ('eligibility', models.TextField(blank=True)),
                ('application_route_url', models.URLField(blank=True)),
                ('requires_sharia_review', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('self_declared', 'Self-declared'), ('human_reviewed', 'Human reviewed'), ('independently_verified', 'Independently verified'), ('expired', 'Expired')], default='self_declared', max_length=24)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('declared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_programmes', to='capability_graph.organisation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(choices=[('energy', 'Energy'), ('water', 'Water'), ('food', 'Food'), ('housing', 'Housing'), ('health', 'Health'), ('education', 'Education'), ('employment', 'Employment'), ('poverty', 'Poverty'), ('justice', 'Justice'), ('environment', 'Environment'), ('biodiversity', 'Biodiversity'), ('waste', 'Waste'), ('circular_economy', 'Circular Economy'), ('climate_adaptation', 'Climate Adaptation'), ('infrastructure', 'Infrastructure'), ('government_efficiency', 'Government Efficiency'), ('financial_inclusion', 'Financial Inclusion'), ('digital_access', 'Digital Access'), ('community_resilience', 'Community Resilience')], max_length=32)),
                ('acceptance_mode', models.CharField(choices=[('open_to_relevant_opportunities', 'Open to relevant opportunities'), ('limited', 'Limited — some conditions apply'), ('invitation_only', 'Invitation only'), ('application_required', 'Application required'), ('not_accepting', 'Not accepting'), ('paused', 'Paused')], default='limited', max_length=32)),
                ('min_evidence_quality', models.CharField(choices=[('any', 'Any evidence quality'), ('documented_or_better', 'Documented or better'), ('independently_verified_only', 'Independently verified only')], default='any', max_length=32)),
                ('eligible_beneficiary_type', models.TextField(blank=True)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('min_project_size_usd', models.FloatField(blank=True, null=True)),
                ('max_project_size_usd', models.FloatField(blank=True, null=True)),
                ('requires_sharia_review', models.BooleanField(default=False)),
                ('regulatory_prerequisites', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_preferences', to='capability_graph.organisation')),
                ('set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organisation__name', 'theme'],
                'unique_together': {('organisation', 'theme')},
            },
        ),
        migrations.CreateModel(
            name='OrganisationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', "Admin — full control of this organisation's participation data"), ('editor', 'Editor — can create/edit declarations, cannot manage members'), ('routing_manager', 'Routing manager — can respond to routing candidates'), ('reviewer', 'Reviewer — read + comment, cannot edit declarations'), ('viewer', 'Viewer — read-only')], default='viewer', max_length=20)),
                ('status', models.CharField(choices=[('claim_requested', 'Claim requested — awaiting EcoIQ review'), ('under_review', 'Under review'), ('verified_member', 'Verified member'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='claim_requested', max_length=20)),
                ('justification', models.TextField(blank=True, help_text='Why the claimant says they represent this organisation.')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='capability_graph.organisation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organisation_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('organisation', 'user')},
            },
        ),
        migrations.CreateModel(
            name='RoutingCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('routing_candidate', 'Routing candidate'), ('ready_for_ecoiq_review', 'Ready for EcoIQ review'), ('approved_to_share', 'Approved to share'), ('shared', 'Shared'), ('viewed', 'Viewed'), ('interested', 'Interested'), ('not_interested', 'Not interested'), ('needs_more_information', 'Needs more information'), ('accepted_for_next_step', 'Accepted for next step')], default='routing_candidate', max_length=32)),
                ('confidence_label', models.CharField(choices=[('strong_verified_match', 'Strong verified match'), ('verified_capability_match', 'Verified capability match'), ('participation_match', 'Participation match'), ('possible_responsible_party', 'Possible responsible party'), ('needs_review', 'Needs review'), ('no_verified_route', 'No verified route')], default='needs_review', max_length=32)),
                ('match_reasons', models.JSONField(blank=True, default=list)),
                ('shared_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_candidates', to='good_agents.goodopportunity')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_candidates', to='capability_graph.organisation')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('shared_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('organisation', 'opportunity')},
            },
        ),
    ]
