# Generated by Django 5.2.14 on 2026-07-24 19:03

import django.db.models.deletion
import django.utils.timezone
import partner_participation.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capability_graph', '0002_organisationcapability_declared_by_and_more'),
        ('partner_participation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='routingcandidate',
            name='status',
            field=models.CharField(choices=[('routing_candidate', 'Routing candidate'), ('ready_for_ecoiq_review', 'Ready for EcoIQ review'), ('approved_to_share', 'Approved to share'), ('not_approved', 'Not approved to share'), ('shared', 'Shared'), ('no_response', 'Shared — no response yet'), ('viewed', 'Viewed'), ('interested', 'Interested'), ('not_interested', 'Not interested'), ('needs_more_information', 'Needs more information'), ('accepted_for_next_step', 'Accepted for next step')], default='routing_candidate', max_length=32),
        ),
        migrations.CreateModel(
            name='NetworkActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('invitation_sent', 'Invitation sent'), ('invitation_accepted', 'Invitation accepted'), ('membership_verified', 'Membership verified'), ('consent_recorded', 'Participation consent recorded'), ('consent_withdrawn', 'Participation consent withdrawn'), ('capability_declared', 'Capability declared'), ('routing_ready', 'Became routing ready'), ('opportunity_matched', 'Opportunity matched'), ('approved_to_share', 'Approved to share'), ('not_approved_to_share', 'Not approved to share'), ('shared', 'Shared'), ('responded', 'Partner responded'), ('interested', 'Partner expressed interest'), ('declined', 'Partner declined'), ('next_action_created', 'Next-step action created'), ('project_candidate_created', 'Project candidate created')], max_length=32)),
                ('source_object_reference', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='network_events', to='capability_graph.organisation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='NextStepAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('connection_action', 'Connection action'), ('data_exchange_request', 'Data exchange request'), ('meeting_request', 'Meeting / call request'), ('project_candidate', 'Project candidate'), ('resource_match_followup', 'Resource match follow-up'), ('funding_eligibility_review', 'Funding eligibility review')], max_length=32)),
                ('linked_object_reference', models.CharField(blank=True, help_text='Soft pointer to the real underlying object, e.g. "good_agents.ProjectCandidate:12" — same convention as evidence_memory.EvidenceMemory.source_reference.', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('in_progress', 'In progress'), ('completed', 'Completed')], default='proposed', max_length=12)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_steps', to='partner_participation.routingcandidate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParticipationConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terms_version', models.CharField(default='v1', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('withdrawn', 'Withdrawn')], default='active', max_length=12)),
                ('consented_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to='partner_participation.organisationmembership')),
            ],
            options={
                'ordering': ['-consented_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_email', models.EmailField(max_length=254)),
                ('intended_role', models.CharField(choices=[('admin', "Admin — full control of this organisation's participation data"), ('editor', 'Editor — can create/edit declarations, cannot manage members'), ('routing_manager', 'Routing manager — can respond to routing candidates'), ('reviewer', 'Reviewer — read + comment, cannot edit declarations'), ('viewer', 'Viewer — read-only')], default='viewer', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('token', models.CharField(default=partner_participation.models._generate_invitation_token, editable=False, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft — not yet sent'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='draft', max_length=12)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('send_status', models.CharField(choices=[('not_sent', 'Not sent'), ('sent_real_email', 'Sent via real email delivery'), ('manual_delivery_required', 'Manual delivery required — no real send infrastructure configured'), ('failed', 'Send failed')], default='not_sent', max_length=32)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='capability_graph.organisation')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShareDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.CharField(help_text='The real route value (email/contact) used.', max_length=300)),
                ('subject', models.CharField(blank=True, max_length=300)),
                ('body', models.TextField(help_text='The exact share package content sent/recorded — a real snapshot, not regenerated later.')),
                ('delivery_method', models.CharField(choices=[('real_email', 'Real email send'), ('manual_recorded', 'Manual delivery, recorded by staff')], max_length=20)),
                ('message_id', models.CharField(blank=True, help_text='Left blank when the send infrastructure does not expose one — never fabricated.', max_length=200)),
                ('send_status', models.CharField(choices=[('sent', 'Sent'), ('manual_pending', 'Manual delivery pending confirmation'), ('failed', 'Failed')], default='manual_pending', max_length=20)),
                ('manual_evidence', models.TextField(blank=True, help_text='e.g. "confirmed by phone call on 2026-08-01" — only for manual_recorded deliveries.')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='partner_participation.routingcandidate')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
