# Generated by Django 5.2.14 on 2026-07-04 06:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_agent_council', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentRegistryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.SlugField(max_length=80, unique=True)),
                ('agent_name', models.CharField(max_length=100)),
                ('training_pack_path', models.CharField(blank=True, max_length=255)),
                ('training_pack_version', models.CharField(default='v1', help_text='No real version file exists in ai_agents/ yet — honest static placeholder.', max_length=20)),
                ('content_hash', models.CharField(blank=True, help_text="Real SHA-256 over the training pack's required files, computed at sync time.", max_length=64)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('supported_task_types', models.JSONField(blank=True, default=list)),
                ('allowed_input_types', models.JSONField(blank=True, default=list)),
                ('expected_output_schema', models.JSONField(blank=True, default=dict)),
                ('required_reviewer_types', models.JSONField(blank=True, default=list)),
                ('maturity_stage', models.PositiveSmallIntegerField(default=0)),
                ('last_evaluation_score', models.FloatField(blank=True, help_text='Stays null until a real evaluation-scoring run exists — never fabricated.', null=True)),
                ('enabled', models.BooleanField(default=True)),
                ('is_next_stage', models.BooleanField(default=False, help_text='True for the 4 agents with no operational training pack — never marked enabled.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent Registry Entry',
                'verbose_name_plural': 'Agent Registry Entries',
                'ordering': ['agent_name'],
            },
        ),
        migrations.CreateModel(
            name='AgentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(max_length=80)),
                ('execution_mode_requested', models.CharField(choices=[('live', 'Live'), ('deterministic_test', 'Deterministic Test'), ('simulated_demo', 'Simulated Demo')], max_length=20)),
                ('execution_mode_used', models.CharField(blank=True, choices=[('live', 'Live'), ('deterministic_test', 'Deterministic Test'), ('simulated_demo', 'Simulated Demo')], max_length=20)),
                ('model_provider', models.CharField(blank=True, max_length=40)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('routing_reason', models.TextField(blank=True)),
                ('sensitivity_level', models.CharField(default='standard', max_length=20)),
                ('required_capability', models.CharField(blank=True, max_length=40)),
                ('cost_class', models.CharField(blank=True, max_length=20)),
                ('rejected_routes', models.JSONField(blank=True, default=list)),
                ('fallback_route', models.CharField(blank=True, max_length=80)),
                ('fallback_reason', models.TextField(blank=True)),
                ('fallback_chain', models.JSONField(blank=True, default=list)),
                ('training_pack_path', models.CharField(blank=True, max_length=255)),
                ('training_pack_version', models.CharField(blank=True, max_length=20)),
                ('prompt_version', models.CharField(blank=True, max_length=20)),
                ('schema_version', models.CharField(blank=True, max_length=20)),
                ('safety_rules_version', models.CharField(blank=True, max_length=20)),
                ('golden_test_version', models.CharField(blank=True, max_length=20)),
                ('training_pack_content_hash', models.CharField(blank=True, max_length=64)),
                ('input_summary', models.TextField(blank=True)),
                ('raw_output', models.TextField(blank=True)),
                ('parsed_output', models.JSONField(blank=True, default=dict)),
                ('schema_valid', models.BooleanField(blank=True, null=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('evidence_used', models.JSONField(blank=True, default=list, help_text='Simple string tags, same shape ai_agent_council.AgentTask expects.')),
                ('evidence_provenance', models.JSONField(blank=True, default=list, help_text='Rich per-evidence records: {evidence_id, source_document, source_ref, quality, missing_data_warning, visibility}.')),
                ('missing_data', models.JSONField(blank=True, default=list)),
                ('raw_confidence', models.FloatField(blank=True, null=True)),
                ('calibrated_confidence', models.FloatField(blank=True, null=True)),
                ('confidence_calibration_explanation', models.JSONField(blank=True, default=list)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('safety_findings', models.JSONField(blank=True, default=list)),
                ('safety_status', models.CharField(choices=[('pass', 'Pass'), ('warning', 'Warning'), ('needs_review', 'Needs Review'), ('blocking', 'Blocking')], default='pass', max_length=20)),
                ('human_approval_required', models.BooleanField(default=True)),
                ('human_approved', models.BooleanField(blank=True, null=True)),
                ('estimated_input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_cost_usd', models.FloatField(blank=True, null=True)),
                ('actual_usage', models.JSONField(blank=True, default=dict)),
                ('budget_exceeded', models.BooleanField(default=False)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('rerun_reason', models.TextField(blank=True)),
                ('failure_reason', models.CharField(blank=True, choices=[('', '—'), ('missing_credentials', 'Missing Credentials'), ('timeout', 'Timeout'), ('rate_limit', 'Rate Limit'), ('invalid_json', 'Invalid JSON'), ('schema_failure', 'Schema Failure'), ('empty_response', 'Empty Response'), ('unsupported_capability', 'Unsupported Capability'), ('safety_violation', 'Safety Violation')], default='', max_length=40)),
                ('audit_trail', models.JSONField(blank=True, default=list, help_text='[{ts, event, detail}, ...]')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('blocked', 'Blocked'), ('needs_human_review', 'Needs Human Review')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='agent_runtime_model_router.agentregistryentry')),
                ('council_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_runs', to='ai_agent_council.councilrun')),
                ('council_position', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_run', to='ai_agent_council.agenttask')),
                ('rerun_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reruns', to='agent_runtime_model_router.agentrun')),
            ],
            options={
                'verbose_name': 'Agent Run',
                'verbose_name_plural': 'Agent Runs',
                'ordering': ['-created_at'],
            },
        ),
    ]
