# Generated by Django 5.2.14 on 2026-09-20 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent_runtime_model_router', '0002_agentrun_project'),
        ('ai_observatory', '0011_pipelinestageexecution_actor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentrun',
            name='observatory_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='agent_runs', to='ai_observatory.analysissession'),
        ),
    ]
