# Generated by Django 5.2.14 on 2026-05-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyfinancingprofile',
            name='ai_financing_narrative',
            field=models.TextField(blank=True, help_text='Plain-language financing pathway description'),
        ),
        migrations.AlterField(
            model_name='companyfinancingprofile',
            name='ai_gap_analysis',
            field=models.TextField(blank=True, help_text='Gaps preventing optimal financing readiness'),
        ),
        migrations.AlterField(
            model_name='companyfinancingprofile',
            name='climate_readiness',
            field=models.FloatField(default=0.0, help_text='Climate transition progress and environmental commitment 0–100'),
        ),
        migrations.AlterField(
            model_name='companyfinancingprofile',
            name='confidence',
            field=models.FloatField(default=0.5, help_text='0–1 confidence in readiness assessment'),
        ),
        migrations.AlterField(
            model_name='companyfinancingprofile',
            name='estimated_annual_impact_usd',
            field=models.BigIntegerField(blank=True, help_text='Estimated annual economic/environmental impact at full implementation (USD)', null=True),
        ),
        migrations.AlterField(
            model_name='companyfinancingprofile',
            name='estimated_capex_high_usd',
            field=models.BigIntegerField(blank=True, help_text='High-end capex estimate (USD)', null=True),
        ),
        migrations.AlterField(
            model_name='companyfinancingprofile',
            name='estimated_capex_low_usd',
            field=models.BigIntegerField(blank=True, help_text='Low-end capex estimate for priority modernization projects (USD)', null=True),
        ),
        migrations.AlterField(
            model_name='companyfinancingprofile',
            name='evidence_completeness',
            field=models.FloatField(default=0.0, help_text='Data completeness and source quality 0–100'),
        ),
        migrations.AlterField(
            model_name='companyfinancingprofile',
            name='financing_readiness',
            field=models.FloatField(default=0.0, help_text='Overall financing readiness 0–100'),
        ),
        migrations.AlterField(
            model_name='companyfinancingprofile',
            name='governance_readiness',
            field=models.FloatField(default=0.0, help_text='Governance and anti-corruption standards 0–100'),
        ),
        migrations.AlterField(
            model_name='companyfinancingprofile',
            name='missing_requirements',
            field=models.JSONField(blank=True, default=list, help_text='List of {label, detail, priority, impact} dicts blocking financing'),
        ),
        migrations.AlterField(
            model_name='companyfinancingprofile',
            name='modernization_readiness',
            field=models.FloatField(default=0.0, help_text='Industrial modernization preparedness 0–100'),
        ),
        migrations.AlterField(
            model_name='companyfinancingprofile',
            name='next_actions',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of recommended next steps'),
        ),
        migrations.AlterField(
            model_name='companyfinancingprofile',
            name='transparency_readiness',
            field=models.FloatField(default=0.0, help_text='Disclosure and reporting quality for DFI compliance 0–100'),
        ),
        migrations.AlterField(
            model_name='directfinancingmatch',
            name='match_score',
            field=models.FloatField(default=0.0, help_text='0–100 match quality'),
        ),
        migrations.AlterField(
            model_name='directfinancingmatch',
            name='missing_requirements',
            field=models.JSONField(blank=True, default=list, help_text='Items blocking full eligibility for this instrument'),
        ),
    ]
