# Generated by Django 5.2.14 on 2026-05-30 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Descriptive label (client name / purpose)', max_length=200)),
                ('key_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('prefix', models.CharField(editable=False, help_text='First 8 chars of raw key — for identification in logs', max_length=8)),
                ('tier', models.CharField(choices=[('explorer', 'Explorer    (100 req/day)'), ('professional', 'Professional (2,000 req/day)'), ('enterprise', 'Enterprise  (50,000 req/day)')], default='explorer', max_length=20)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null = never expires', null=True)),
                ('total_requests', models.PositiveIntegerField(default=0)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
