# Generated by Django 5.2.14 on 2026-07-31 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial_apikey'),
        ('ecoiq_commerce', '0002_plan_requires_legal_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='apikey',
            name='environment',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=10),
        ),
        migrations.AddField(
            model_name='apikey',
            name='owner_organisation',
            field=models.ForeignKey(blank=True, help_text='Organisation this key bills/entitles against, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='ecoiq_commerce.organisation'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='plan',
            field=models.ForeignKey(blank=True, help_text="Commercial plan governing this key's entitlements", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='api_keys', to='ecoiq_commerce.plan'),
        ),
        migrations.AddField(
            model_name='apikey',
            name='revoked_at',
            field=models.DateTimeField(blank=True, help_text='Explicit revocation timestamp — distinct from is_active so the audit trail shows WHEN a key stopped working, not just that it did', null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='rotated_from',
            field=models.ForeignKey(blank=True, help_text='The key this one replaced, if rotated', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotated_to', to='api.apikey'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='organisation',
            field=models.CharField(blank=True, help_text='Free-text label — see owner_organisation for the real FK link', max_length=200),
        ),
        migrations.AddField(
            model_name='apikey',
            name='scopes',
            field=models.ManyToManyField(blank=True, related_name='keys', to='api.apiscope'),
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to='api.apikey')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['key', 'created_at'], name='api_apirequ_key_id_372852_idx')],
            },
        ),
    ]
