# Generated by Django 5.2.14 on 2026-07-01 11:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('organisation', models.CharField(blank=True, max_length=200)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'LegacySafe Project',
                'verbose_name_plural': 'LegacySafe Projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='e.g. ask, permission_demo, revoke', max_length=30)),
                ('question', models.TextField(blank=True)),
                ('decision', models.CharField(blank=True, help_text='e.g. allowed, blocked, partial, revoked', max_length=20)),
                ('allowed_sources', models.JSONField(blank=True, default=list)),
                ('blocked_sources', models.JSONField(blank=True, default=list)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_safe_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DerivedMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('engineering', 'Engineering'), ('finance', 'Finance'), ('executive', 'Executive')], default='executive', max_length=12)),
                ('lineage', models.JSONField(blank=True, default=list, help_text='List of {"source_document_id", "source_document_title"}')),
                ('is_revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derived_memories', to='legacy_safe.legacyproject')),
            ],
            options={
                'verbose_name': 'Derived Memory',
                'verbose_name_plural': 'Derived Memories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChangeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('affected_systems', models.JSONField(blank=True, default=list)),
                ('risks', models.JSONField(blank=True, default=list)),
                ('recommended_actions', models.JSONField(blank=True, default=list)),
                ('required_roles', models.JSONField(blank=True, default=list)),
                ('evidence', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_proposals', to='legacy_safe.legacyproject')),
            ],
            options={
                'verbose_name': 'Change Proposal',
                'verbose_name_plural': 'Change Proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document_type', models.CharField(choices=[('esg_report', 'ESG Report'), ('maintenance_notes', 'Maintenance Notes'), ('budget', 'Investment Budget'), ('strategy_memo', 'Strategy Memo'), ('other', 'Other')], default='other', max_length=20)),
                ('text_content', models.TextField()),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('engineering', 'Engineering'), ('finance', 'Finance'), ('executive', 'Executive')], default='public', max_length=12)),
                ('is_revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_documents', to='legacy_safe.legacyproject')),
            ],
            options={
                'verbose_name': 'Source Document',
                'verbose_name_plural': 'Source Documents',
                'ordering': ['project', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoryChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('chunk_index', models.PositiveIntegerField(default=0)),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('engineering', 'Engineering'), ('finance', 'Finance'), ('executive', 'Executive')], default='public', max_length=12)),
                ('lineage', models.JSONField(blank=True, default=list, help_text='List of {"source_document_id", "source_document_title"}')),
                ('is_revoked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='legacy_safe.sourcedocument')),
            ],
            options={
                'verbose_name': 'Memory Chunk',
                'verbose_name_plural': 'Memory Chunks',
                'ordering': ['source_document', 'chunk_index'],
                'unique_together': {('source_document', 'chunk_index')},
            },
        ),
    ]
