# Generated by Django 5.2.14 on 2026-07-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy_safe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcedocument',
            name='document_type',
            field=models.CharField(choices=[('esg_report', 'ESG Report'), ('solar_battery', 'Solar & Battery Feasibility'), ('heat_pump_boiler', 'Heat Pump & Boiler Replacement'), ('insulation', 'Insulation & Heat Loss Reduction'), ('smart_meters_iot', 'Smart Meters & IoT Sensors'), ('grid_optimisation', 'Grid & Load Optimisation'), ('budget', 'Investment Budget'), ('procurement', 'Equipment Procurement'), ('capex_opex', 'CAPEX/OPEX & ROI'), ('strategy_memo', 'Strategy Memo'), ('worker_community', 'Worker & Community Transition'), ('justice_maqasid', 'Justice & Maqasid Review'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
