# Generated by Django 5.2.14 on 2026-07-17 20:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gold_intelligence', '0005_goldproject_organisation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('project_analysis', 'Project Analysis (Mizan + Resource Purpose + Retrieval)'), ('better_way_comparison', 'The Better Way Comparison'), ('capital_decision', 'Capital Decision Preparation'), ('outcome_recording', 'Outcome Recording / Expected-vs-Actual'), ('evidence_memory_sync', 'Evidence Memory Sync'), ('other', 'Other Instrumented Pipeline')], default='other', max_length=30)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=12)),
                ('evidence_retrieved_count', models.PositiveIntegerField(blank=True, null=True)),
                ('evidence_reused_count', models.PositiveIntegerField(blank=True, null=True)),
                ('human_review_required', models.BooleanField(default=True)),
                ('human_review_completed', models.BooleanField(default=False)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('blocked_recommendation_count', models.PositiveIntegerField(default=0)),
                ('final_recommendation_status', models.CharField(choices=[('not_applicable', 'Not Applicable (no recommendation produced by this pipeline)'), ('produced', 'Recommendation Produced — Awaiting Human Review'), ('blocked', 'Blocked on Safety/Eligibility Grounds'), ('human_review_required', 'Human Review Explicitly Required'), ('recorded', 'Result Recorded')], default='not_applicable', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observatory_sessions', to='gold_intelligence.goldproject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observatory_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Analysis Session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelInvocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('model_version', models.CharField(blank=True, max_length=80)),
                ('prompt_version', models.CharField(blank=True, max_length=20)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cached_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('streaming', models.BooleanField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('agent_run_reference', models.CharField(blank=True, db_index=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_invocations', to='ai_observatory.analysissession')),
            ],
            options={
                'verbose_name': 'Model Invocation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PipelineStageExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_key', models.CharField(max_length=60)),
                ('label', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('deterministic', 'Deterministic Engine'), ('retrieval', 'Evidence Retrieval'), ('governance', 'Governance / Safety Check'), ('llm', 'Model-Backed Step')], default='deterministic', max_length=15)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('items_processed', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='ai_observatory.analysissession')),
            ],
            options={
                'verbose_name': 'Pipeline Stage Execution',
                'ordering': ['started_at', 'pk'],
            },
        ),
    ]
