# Generated by Django 5.2.14 on 2026-07-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_observatory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelinvocation',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelinvocation',
            name='succeeded',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
