# Generated by Django 5.2.14 on 2026-07-19 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_observatory', '0002_modelinvocation_duration_ms_and_more'),
        ('companies', '0006_companyscoresnapshot_climate_risk_score_and_more'),
        ('gold_intelligence', '0005_goldproject_organisation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analysissession',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observatory_sessions', to='companies.companyprofile'),
        ),
        migrations.AlterField(
            model_name='analysissession',
            name='kind',
            field=models.CharField(choices=[('project_analysis', 'Project Analysis (Mizan + Resource Purpose + Retrieval)'), ('better_way_comparison', 'The Better Way Comparison'), ('capital_decision', 'Capital Decision Preparation'), ('outcome_recording', 'Outcome Recording / Expected-vs-Actual'), ('evidence_memory_sync', 'Evidence Memory Sync'), ('company_intelligence', 'Company Intelligence Analysis (Shariah Screen / 114-KPI Mapping)'), ('other', 'Other Instrumented Pipeline')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='analysissession',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observatory_sessions', to='gold_intelligence.goldproject'),
        ),
        migrations.AddConstraint(
            model_name='analysissession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('company__isnull', True), ('project__isnull', False)), models.Q(('company__isnull', False), ('project__isnull', True)), _connector='OR'), name='observatory_session_exactly_one_anchor'),
        ),
    ]
