# Generated by Django 5.2.14 on 2026-07-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_observatory', '0003_analysissession_company_alter_analysissession_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysissession',
            name='kind',
            field=models.CharField(choices=[('project_analysis', 'Project Analysis (Mizan + Resource Purpose + Retrieval)'), ('better_way_comparison', 'The Better Way Comparison'), ('capital_decision', 'Capital Decision Preparation'), ('outcome_recording', 'Outcome Recording / Expected-vs-Actual'), ('evidence_memory_sync', 'Evidence Memory Sync'), ('company_intelligence', 'Company Intelligence Analysis (Shariah Screen / 114-KPI Mapping)'), ('company_evidence_ingestion', 'Company Evidence Ingestion (Source Fetch / Extraction / KPI Candidate Matching)'), ('other', 'Other Instrumented Pipeline')], default='other', max_length=30),
        ),
    ]
