# Generated by Django 5.2.14 on 2026-07-23 17:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_observatory', '0007_alter_analysissession_kind'),
        ('companies', '0007_companyprofile_last_refresh_at_and_more'),
        ('gold_intelligence', '0005_goldproject_organisation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='analysissession',
            name='observatory_session_exactly_one_anchor',
        ),
        migrations.AlterField(
            model_name='analysissession',
            name='kind',
            field=models.CharField(choices=[('project_analysis', 'Project Analysis (Mizan + Resource Purpose + Retrieval)'), ('better_way_comparison', 'The Better Way Comparison'), ('capital_decision', 'Capital Decision Preparation'), ('outcome_recording', 'Outcome Recording / Expected-vs-Actual'), ('evidence_memory_sync', 'Evidence Memory Sync'), ('company_intelligence', 'Company Intelligence Analysis (Shariah Screen / 114-KPI Mapping)'), ('company_evidence_ingestion', 'Company Evidence Ingestion (Source Fetch / Extraction / KPI Candidate Matching)'), ('company_discovery', 'Company Discovery / Ranking (Filtering, Comparison, Explain Match)'), ('evidence_review_workbench', 'Evidence Review Workbench (Queue, Decision, Dispute, Re-Review)'), ('stewardship_refresh', 'Stewardship Universe Refresh (Source Discovery / Fetch / KPI Candidates)'), ('good_agents_discovery', 'Good Agents Global Discovery Run (Signal Ingestion / 114-Principle Activation)'), ('other', 'Other Instrumented Pipeline')], default='other', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='analysissession',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('company__isnull', True), ('project__isnull', False)), models.Q(('company__isnull', False), ('project__isnull', True)), models.Q(('company__isnull', True), ('kind__in', ('company_discovery', 'evidence_review_workbench', 'good_agents_discovery')), ('project__isnull', True)), _connector='OR'), name='observatory_session_exactly_one_anchor'),
        ),
    ]
