# Generated by Django 5.2.14 on 2026-09-20 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_observatory', '0010_remove_analysissession_observatory_session_exactly_one_anchor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pipelinestageexecution',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pipelinestageexecution',
            name='event_key',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddConstraint(
            model_name='pipelinestageexecution',
            constraint=models.UniqueConstraint(fields=('session', 'event_key'), name='unique_session_event_key'),
        ),
    ]
