"""
Evidence coverage and score eligibility — measurement only.

This module answers one question about a CompanyProfile: how much of the score
is actually supported by evidence? It reads; it never writes, never changes a
score, and is not yet wired into any public page. See
docs/product/EVIDENCE_INTEGRITY_PLAN.md.

Why measurement comes before schema
-----------------------------------
The obvious first step is to make the `default=50.0` score fields nullable so
unknown stops masquerading as average. That is unsafe today. `companies.scoring`
reduces every value through

    def _clamp(v, lo=0.0, hi=100.0) -> float:
        return max(lo, min(hi, float(v or 0)))

so a NULL would arrive at the pillar calculations as **0** — the worst possible
score, published — rather than as unknown. Nullability has to wait for the
calculation semantics to change (plan step D2). Until then the honest move is to
measure the gap and report it.

What counts as evidence
-----------------------
A material input counts toward coverage only when its provenance is real. Today
no `CompanyProfile` score field carries per-field provenance at all, and the
values were produced by seeding commands that generate them with a seeded RNG
around an editorial target (see the plan, §0). `PROVENANCE_UNKNOWN` is therefore
the correct answer for existing data, and coverage is correspondingly low. That
is the finding, not a bug in this module.

The weights are not invented here. They are the weights `companies.scoring`
already applies when it builds the composite, so coverage is expressed in the
same currency as the score it qualifies.
"""
from __future__ import annotations

from dataclasses import dataclass, field

# ── Provenance ────────────────────────────────────────────────────────────────
# Deliberately reuses decision_studio's vocabulary rather than inventing a third
# one; SEEDED and LEGACY_UNKNOWN_PROVENANCE are the two cases that repository
# needs and decision_studio does not express.
PROVENANCE_MEASURED = 'MEASURED'
PROVENANCE_ESTIMATED = 'ESTIMATED'
PROVENANCE_MODELLED = 'MODELLED'
PROVENANCE_INFERRED = 'INFERRED'
PROVENANCE_SEEDED = 'SEEDED'
PROVENANCE_UNKNOWN = 'LEGACY_UNKNOWN_PROVENANCE'

# D3A adds the one state the D1 vocabulary was missing.
#
# LEGACY_UNKNOWN_PROVENANCE and NO_VALUE are NOT synonyms, and collapsing them
# would undo the D2 programme:
#
#   LEGACY_UNKNOWN_PROVENANCE  there IS a number; we cannot say where it came
#                              from. Unpublishable, but real, and traceable later.
#   NO_VALUE                   there is NO number. This is the state #242, #243
#                              and #244 spent three PRs making representable in
#                              the calculation layer.
#
# Named NO_VALUE rather than UNKNOWN because PROVENANCE_UNKNOWN is already taken
# by LEGACY_UNKNOWN_PROVENANCE above, and two constants a letter apart meaning
# opposite things is how the original `or 50` confusion started.
PROVENANCE_NO_VALUE = 'UNKNOWN'

#: The canonical set. The brief's SYNTHETIC is this repository's SEEDED — same
#: meaning, and the repository named it first; a second near-identical term is
#: exactly the duplicate vocabulary D3 exists to avoid.
PROVENANCE_CHOICES = [
    (PROVENANCE_MEASURED,  'Measured — directly observed from defensible source data'),
    (PROVENANCE_ESTIMATED, 'Estimated — calculated on disclosed assumptions'),
    (PROVENANCE_MODELLED,  'Modelled — output of an explicit model or simulation'),
    (PROVENANCE_INFERRED,  'Inferred — derived indirectly from other evidence'),
    (PROVENANCE_SEEDED,    'Seeded — synthetic development or demonstration data'),
    (PROVENANCE_UNKNOWN,   'Legacy — a value exists but its lineage cannot be reconstructed'),
    (PROVENANCE_NO_VALUE,  'Unknown — no defensible value exists'),
]

#: Only these count toward evidence coverage. SEEDED and
#: LEGACY_UNKNOWN_PROVENANCE deliberately do not: a value generated by a seeding
#: command is not evidence, and neither is one whose origin nobody can establish.
EVIDENCED_PROVENANCE = frozenset({
    PROVENANCE_MEASURED, PROVENANCE_ESTIMATED,
    PROVENANCE_MODELLED, PROVENANCE_INFERRED,
})

#: The inverse, stated explicitly so a caller can ask the question either way
#: without re-deriving the set — and so adding a state forces a decision about
#: which side it falls on rather than defaulting to publishable.
UNEVIDENCED_PROVENANCE = frozenset({
    PROVENANCE_SEEDED, PROVENANCE_UNKNOWN, PROVENANCE_NO_VALUE,
})

# ── Availability / confidence labels ──────────────────────────────────────────
# Same strings as decision_studio.DecisionSession, so the two layers can be read
# together without a translation table.
AVAILABILITY_AVAILABLE = 'AVAILABLE'
AVAILABILITY_PARTIAL = 'PARTIAL'
AVAILABILITY_INSUFFICIENT = 'INSUFFICIENT'

ELIGIBILITY_ELIGIBLE = 'ELIGIBLE'
ELIGIBILITY_PROVISIONAL = 'PROVISIONAL'
ELIGIBILITY_UNAVAILABLE = 'UNAVAILABLE'


# ── Material inputs ───────────────────────────────────────────────────────────
# Pillar weights are companies.scoring's own composite weights. Within a pillar
# each sub-input carries an equal share unless scoring itself weights them —
# transparency does (0.40 / 0.35 / 0.25), so that is mirrored rather than
# averaged.
@dataclass(frozen=True)
class MaterialInput:
    field_name: str
    pillar: str
    weight: float           # share of the whole composite, sums to 1.0


def _pillar(pillar: str, weight: float, fields: list[str],
            shares: list[float] | None = None) -> list[MaterialInput]:
    shares = shares or [1.0 / len(fields)] * len(fields)
    return [MaterialInput(f, pillar, weight * s) for f, s in zip(fields, shares)]


MATERIAL_INPUTS: tuple[MaterialInput, ...] = tuple(
    _pillar('public_benefit', 0.25, [
        'jobs_created_score', 'regional_development_score',
        'infrastructure_contribution_score', 'national_value_score',
    ])
    + _pillar('environmental', 0.25, [
        'waste_management_score', 'water_impact_score', 'biodiversity_impact_score',
    ])
    + _pillar('modernization', 0.20, [
        'energy_transition_score', 'digitalization_score',
        'infrastructure_upgrade_score', 'future_readiness_score',
    ])
    + _pillar('transparency', 0.15, [
        'transparency_score_detail', 'audit_quality_score',
        'procurement_transparency_score',
    ], shares=[0.40, 0.35, 0.25])
    + _pillar('anti_corruption', 0.10, ['anti_corruption_score'])
    + _pillar('ethical_alignment', 0.05, ['controversy_risk_score', 'national_value_score'])
)


#: Origins that count as evidence FOR A MATERIAL INPUT.
#:
#: MODELLED is deliberately absent, and the omission is the substantive
#: decision in this module. A material input is supposed to be something
#: somebody observed, estimated, or derived from a source. If one carries
#: MODELLED it is a model output wearing an input's clothes, and counting it as
#: evidence would let a model corroborate itself.
#:
#: MODELLED remains correct for DERIVED metrics, whose defensibility comes
#: transitively from their own inputs (see provenance._row_is_defensible).
EVIDENCED_MATERIAL_ORIGINS = frozenset({
    PROVENANCE_MEASURED, PROVENANCE_INFERRED, PROVENANCE_ESTIMATED,
})


def _weight_by_field() -> dict:
    """
    Material field -> its share of the composite, counted ONCE.

    national_value_score feeds two pillars, so it appears twice in
    MATERIAL_INPUTS. Its weight is legitimately the sum of both contributions,
    but the DENOMINATOR must count the field once -- otherwise a company is
    asked for 17 pieces of evidence when there are 16 to give, and 100%
    coverage becomes unreachable.
    """
    weights = {}
    for item in MATERIAL_INPUTS:
        weights[item.field_name] = weights.get(item.field_name, 0.0) + item.weight
    return weights


@dataclass
class CoverageReport:
    """
    What is actually known about one profile's score.

    Answers one question: HOW MUCH of the information this assessment requires
    is defensibly supported?

    Weighted by the scoring engine's own composite weights rather than by a
    count, so a company missing the 25%-weighted public-benefit pillar does not
    read the same as one missing the 5%-weighted ethical-alignment one.

    Both the ratio and its two halves are exposed, so a surface can say
    "78% -- 11 of 14 material inputs supported" rather than a contextless
    percentage.
    """
    covered_weight: float = 0.0
    total_weight: float = 0.0
    covered_inputs: int = 0
    total_inputs: int = 0
    missing: list = field(default_factory=list)
    #: Inputs that HAVE a value and a provenance row, but an unevidenced one --
    #: SEEDED or LEGACY. Reported separately from `missing`, because "we hold a
    #: number we cannot stand behind" is a different problem from "we hold
    #: nothing", and they need different work to fix.
    unevidenced: list = field(default_factory=list)

    @property
    def coverage(self) -> float:
        """0.0-1.0. Weighted share of material inputs with real provenance."""
        return self.covered_weight / self.total_weight if self.total_weight else 0.0

    @property
    def coverage_percent(self) -> int:
        """
        Whole percent only. The denominator is 16 inputs, so a figure like
        '82.4%' would imply a precision the underlying data cannot support.
        """
        return round(self.coverage * 100)

    @property
    def numerator(self) -> int:
        """Inputs supported by defensible provenance."""
        return self.covered_inputs

    @property
    def denominator(self) -> int:
        """Inputs this assessment requires."""
        return self.total_inputs

    @property
    def availability(self) -> str:
        if self.coverage >= 0.999:
            return AVAILABILITY_AVAILABLE
        if self.coverage > 0.0:
            return AVAILABILITY_PARTIAL
        return AVAILABILITY_INSUFFICIENT

    def __str__(self) -> str:
        return (f'Evidence coverage {self.coverage_percent}% - '
                f'{self.numerator} of {self.denominator} material inputs')


def field_provenance(profile, field_name: str) -> str:
    """
    Recorded provenance of one field on one profile.

    D5. This used to GUESS: it compared the stored value against the model
    default and called a match SEEDED. That was a stand-in for a store which
    did not exist yet, and D4C removed the defaults it compared against,
    leaving it inert.

    It now reads the store D3 built. No inference, no comparison against a
    magic number -- either a writer recorded where this value came from or
    nobody did, and LEGACY_UNKNOWN_PROVENANCE is the honest answer to the
    second case.

    Returns PROVENANCE_NO_VALUE when the field itself is unknown: there is no
    origin for a number that does not exist.
    """
    if getattr(profile, field_name, None) is None:
        return PROVENANCE_NO_VALUE

    from companies import provenance as prov

    row = prov.current(profile, field_name)
    return row.origin if row is not None else PROVENANCE_UNKNOWN


def _model_default(profile, field_name: str):
    """
    Retained for callers that still ask, and for the record.

    D4C removed every neutral default, so this returns None for the score
    fields now. Nothing in coverage depends on it any more.
    """
    try:
        f = profile._meta.get_field(field_name)
    except Exception:
        return None
    default = getattr(f, 'default', None)
    return default if isinstance(default, (int, float)) else None


def _has_linked_evidence(profile) -> bool:
    """
    True when anything in the repository links evidence to this profile.

    No longer consulted by coverage -- provenance rows carry their own evidence
    FK -- but still a useful question for analyst surfaces.
    """
    if getattr(profile, 'public_sources', None):
        return True
    try:
        return profile.kpi_assessments.filter(evidence_links__isnull=False).exists()
    except Exception:
        return False


def coverage_for(profile) -> CoverageReport:
    """Evidence coverage for one CompanyProfile. Reads only."""
    report = CoverageReport()
    if profile is None:
        return report

    from companies import provenance as prov

    current = prov.current_map(profile)
    for field_name, weight in _weight_by_field().items():
        report.total_weight += weight
        report.total_inputs += 1

        row = current.get(field_name)
        if getattr(profile, field_name, None) is None or row is None:
            report.missing.append(field_name)
        elif row.origin in EVIDENCED_MATERIAL_ORIGINS:
            report.covered_weight += weight
            report.covered_inputs += 1
        else:
            # SEEDED or LEGACY: a number we hold but cannot stand behind.
            report.unevidenced.append(field_name)
    return report


def derived_coverage_for(profile, metric_key: str) -> CoverageReport:
    """
    Coverage for a DERIVED metric, from the graph it actually consumed.

    Not the same question as `coverage_for`. The composite reads all sixteen
    material inputs; Mizan reads seventeen things, most of them pillars; the
    financing metric reads four. Reporting whole-estate coverage against any of
    them would describe a different calculation from the one that produced the
    number.

    The traversal walks the recorded lineage down to its MATERIAL ancestors and
    counts each DISTINCT one once. Diamonds are common here -- several pillars
    share material inputs -- and counting a shared ancestor once per path would
    inflate coverage for exactly the metrics whose evidence is most
    concentrated.

    A metric with no recorded lineage returns an empty report: coverage 0.0,
    availability INSUFFICIENT. Correct rather than pessimistic -- a derived
    value whose lineage was never recorded cannot be shown to rest on anything.
    """
    from companies import provenance as prov

    report = CoverageReport()
    row = prov.current(profile, metric_key)
    if row is None:
        return report

    weights = _weight_by_field()
    ancestors = {}

    def walk(node, seen):
        if node.pk in seen:
            return
        seen.add(node.pk)
        inputs = list(node.inputs.all())
        if not inputs:
            if node.metric_key in weights:
                ancestors[node.metric_key] = (
                    node.origin in EVIDENCED_MATERIAL_ORIGINS
                    and node.value is not None
                )
            return
        for item in inputs:
            walk(item, seen)

    walk(row, set())

    for field_name, evidenced in ancestors.items():
        weight = weights[field_name]
        report.total_weight += weight
        report.total_inputs += 1
        if evidenced:
            report.covered_weight += weight
            report.covered_inputs += 1
        else:
            report.unevidenced.append(field_name)
    return report


def eligibility(coverage: float, minimum: float, full: float) -> str:
    """
    Map a coverage ratio onto the three public states.

    Thresholds are arguments, not constants: the plan (§8) records that they are
    a product decision to be taken against the real distribution, and hard-coding
    a guess here would quietly make that decision instead.

    Zero coverage is checked first and unconditionally. Thresholds are caller
    input, and a caller passing full=0.0 would otherwise satisfy `coverage >=
    full` at zero coverage and publish a score for a company with no evidence at
    all — the precise failure this module exists to prevent. No threshold may
    override the invariant.
    """
    if coverage <= 0.0:
        return ELIGIBILITY_UNAVAILABLE
    if coverage >= full:
        return ELIGIBILITY_ELIGIBLE
    if coverage >= minimum:
        return ELIGIBILITY_PROVISIONAL
    return ELIGIBILITY_UNAVAILABLE


# ── Public presentation gate (D1.5 containment) ───────────────────────────────
#
# The floor below is deliberately NOT one of the candidate thresholds in the
# plan's §8. Choosing 20% / 40% / 60% is a product decision that needs the real
# distribution behind it. This is a different, weaker statement that needs no
# such decision:
#
#     a score may be published only if at least ONE material input has real
#     evidence provenance.
#
# A company for which nothing at all is evidenced cannot have a defensible
# public assessment under any threshold anyone might later choose, so gating on
# it now pre-empts no decision. Real thresholds arrive with D5.

STATUS_PUBLISHED = 'PUBLISHED'
STATUS_INSUFFICIENT_EVIDENCE = 'INSUFFICIENT_EVIDENCE'

#: Wording is fixed here rather than in templates so every surface says the same
#: thing, and so it can be asserted once in tests. It states what EcoIQ lacks,
#: never anything about the organisation.
PENDING_HEADLINE = 'Evidence assessment pending'
PENDING_DETAIL = (
    'EcoIQ does not currently have sufficient verified evidence to publish a '
    'defensible assessment for this organisation.'
)


@dataclass(frozen=True)
class PublicScoreState:
    """Whether a company score may be shown publicly, and what to show instead."""
    available: bool
    score: float | None
    status: str
    coverage_percent: int
    headline: str = ''
    detail: str = ''

    def __bool__(self) -> bool:          # `{% if state %}` reads naturally
        return self.available


def _state_from(profile, raw_score) -> PublicScoreState:
    if profile is None:
        return PublicScoreState(
            False, None, STATUS_INSUFFICIENT_EVIDENCE, 0,
            PENDING_HEADLINE, PENDING_DETAIL)

    report = coverage_for(profile)

    # D5. The floor was `covered_inputs > 0` while coverage was inert and
    # nothing could ever pass it. Now that coverage reads the provenance store
    # that floor would publish a company with ONE evidenced input out of
    # sixteen, so it is replaced with the most conservative rule available:
    # every material input the score claims to weigh must be evidenced.
    #
    # Deliberately stricter than any threshold D5's eligibility step is likely
    # to choose, and chosen for that reason -- a threshold picked against the
    # real distribution is a product decision, and this must not pre-empt it in
    # the permissive direction. Tightening later is a policy change; publishing
    # something that should not have been published is not recoverable.
    if raw_score is None or report.availability != AVAILABILITY_AVAILABLE:
        return PublicScoreState(
            False, None, STATUS_INSUFFICIENT_EVIDENCE, report.coverage_percent,
            PENDING_HEADLINE, PENDING_DETAIL)
    return PublicScoreState(
        True, float(raw_score), STATUS_PUBLISHED, report.coverage_percent)


def public_score_state(profile) -> PublicScoreState:
    """Public presentation state for a CompanyProfile's composite score."""
    return _state_from(profile, getattr(profile, 'ecoiq_total_score', None))


def public_score_state_for_company(company) -> PublicScoreState:
    """
    Same gate for a league.Company.

    The league table renders `Company.ecoiq_score`, a separate field from
    `CompanyProfile.ecoiq_total_score`, but it is derived from the same
    unevidenced inputs — so it is gated on the linked profile's coverage. A
    company with no profile at all has no evidence by definition.
    """
    profile = getattr(company, 'profile', None)
    return _state_from(profile, getattr(company, 'ecoiq_score', None))
