"""
Evidence coverage and score eligibility — measurement only.

This module answers one question about a CompanyProfile: how much of the score
is actually supported by evidence? It reads; it never writes, never changes a
score, and is not yet wired into any public page. See
docs/product/EVIDENCE_INTEGRITY_PLAN.md.

Why measurement comes before schema
-----------------------------------
The obvious first step is to make the `default=50.0` score fields nullable so
unknown stops masquerading as average. That is unsafe today. `companies.scoring`
reduces every value through

    def _clamp(v, lo=0.0, hi=100.0) -> float:
        return max(lo, min(hi, float(v or 0)))

so a NULL would arrive at the pillar calculations as **0** — the worst possible
score, published — rather than as unknown. Nullability has to wait for the
calculation semantics to change (plan step D2). Until then the honest move is to
measure the gap and report it.

What counts as evidence
-----------------------
A material input counts toward coverage only when its provenance is real. Today
no `CompanyProfile` score field carries per-field provenance at all, and the
values were produced by seeding commands that generate them with a seeded RNG
around an editorial target (see the plan, §0). `PROVENANCE_UNKNOWN` is therefore
the correct answer for existing data, and coverage is correspondingly low. That
is the finding, not a bug in this module.

The weights are not invented here. They are the weights `companies.scoring`
already applies when it builds the composite, so coverage is expressed in the
same currency as the score it qualifies.
"""
from __future__ import annotations

from dataclasses import dataclass, field

# ── Provenance ────────────────────────────────────────────────────────────────
# Deliberately reuses decision_studio's vocabulary rather than inventing a third
# one; SEEDED and LEGACY_UNKNOWN_PROVENANCE are the two cases that repository
# needs and decision_studio does not express.
PROVENANCE_MEASURED = 'MEASURED'
PROVENANCE_ESTIMATED = 'ESTIMATED'
PROVENANCE_MODELLED = 'MODELLED'
PROVENANCE_INFERRED = 'INFERRED'
PROVENANCE_SEEDED = 'SEEDED'
PROVENANCE_UNKNOWN = 'LEGACY_UNKNOWN_PROVENANCE'

#: Only these count toward evidence coverage. SEEDED and
#: LEGACY_UNKNOWN_PROVENANCE deliberately do not: a value generated by a seeding
#: command is not evidence, and neither is one whose origin nobody can establish.
EVIDENCED_PROVENANCE = frozenset({
    PROVENANCE_MEASURED, PROVENANCE_ESTIMATED,
    PROVENANCE_MODELLED, PROVENANCE_INFERRED,
})

# ── Availability / confidence labels ──────────────────────────────────────────
# Same strings as decision_studio.DecisionSession, so the two layers can be read
# together without a translation table.
AVAILABILITY_AVAILABLE = 'AVAILABLE'
AVAILABILITY_PARTIAL = 'PARTIAL'
AVAILABILITY_INSUFFICIENT = 'INSUFFICIENT'

ELIGIBILITY_ELIGIBLE = 'ELIGIBLE'
ELIGIBILITY_PROVISIONAL = 'PROVISIONAL'
ELIGIBILITY_UNAVAILABLE = 'UNAVAILABLE'


# ── Material inputs ───────────────────────────────────────────────────────────
# Pillar weights are companies.scoring's own composite weights. Within a pillar
# each sub-input carries an equal share unless scoring itself weights them —
# transparency does (0.40 / 0.35 / 0.25), so that is mirrored rather than
# averaged.
@dataclass(frozen=True)
class MaterialInput:
    field_name: str
    pillar: str
    weight: float           # share of the whole composite, sums to 1.0


def _pillar(pillar: str, weight: float, fields: list[str],
            shares: list[float] | None = None) -> list[MaterialInput]:
    shares = shares or [1.0 / len(fields)] * len(fields)
    return [MaterialInput(f, pillar, weight * s) for f, s in zip(fields, shares)]


MATERIAL_INPUTS: tuple[MaterialInput, ...] = tuple(
    _pillar('public_benefit', 0.25, [
        'jobs_created_score', 'regional_development_score',
        'infrastructure_contribution_score', 'national_value_score',
    ])
    + _pillar('environmental', 0.25, [
        'waste_management_score', 'water_impact_score', 'biodiversity_impact_score',
    ])
    + _pillar('modernization', 0.20, [
        'energy_transition_score', 'digitalization_score',
        'infrastructure_upgrade_score', 'future_readiness_score',
    ])
    + _pillar('transparency', 0.15, [
        'transparency_score_detail', 'audit_quality_score',
        'procurement_transparency_score',
    ], shares=[0.40, 0.35, 0.25])
    + _pillar('anti_corruption', 0.10, ['anti_corruption_score'])
    + _pillar('ethical_alignment', 0.05, ['controversy_risk_score', 'national_value_score'])
)


@dataclass
class CoverageReport:
    """What is actually known about one profile's score."""
    covered_weight: float = 0.0
    total_weight: float = 0.0
    covered_inputs: int = 0
    total_inputs: int = 0
    missing: list[str] = field(default_factory=list)

    @property
    def coverage(self) -> float:
        """0.0–1.0. Weighted share of material inputs with real provenance."""
        return self.covered_weight / self.total_weight if self.total_weight else 0.0

    @property
    def coverage_percent(self) -> int:
        """
        Whole percent only. The denominator is ~16 inputs, so a figure like
        '82.4%' would imply a precision the underlying data cannot support.
        """
        return round(self.coverage * 100)

    @property
    def availability(self) -> str:
        if self.coverage >= 0.999:
            return AVAILABILITY_AVAILABLE
        if self.coverage > 0.0:
            return AVAILABILITY_PARTIAL
        return AVAILABILITY_INSUFFICIENT

    def __str__(self) -> str:
        return (f'Evidence coverage {self.coverage_percent}% · '
                f'{self.covered_inputs} of {self.total_inputs} material inputs')


def field_provenance(profile, field_name: str) -> str:
    """
    Provenance of one field on one profile.

    There is no per-field provenance store yet, so this reports what can be
    established rather than guessing. It returns SEEDED only for the one case
    that is deterministic — a value still exactly equal to the model default on
    a profile with no linked evidence — and LEGACY_UNKNOWN_PROVENANCE for
    everything else. It never returns MEASURED: nothing in the current schema
    can justify that claim.
    """
    value = getattr(profile, field_name, None)
    if value is None:
        return PROVENANCE_UNKNOWN

    default = _model_default(profile, field_name)
    if default is not None and abs(float(value) - float(default)) < 1e-9:
        if not _has_linked_evidence(profile):
            return PROVENANCE_SEEDED
    return PROVENANCE_UNKNOWN


def _model_default(profile, field_name: str):
    try:
        f = profile._meta.get_field(field_name)
    except Exception:
        return None
    default = getattr(f, 'default', None)
    # Django uses a sentinel class for "no default"; it is not callable-safe here.
    return default if isinstance(default, (int, float)) else None


def _has_linked_evidence(profile) -> bool:
    """
    True when anything in the repository links evidence to this profile.

    Checked rather than assumed: company_intelligence.CompanyKPIEvidenceLink is
    the only real per-assessment evidence linkage that exists today, and
    public_sources is a profile-level JSON list.
    """
    if getattr(profile, 'public_sources', None):
        return True
    try:
        return profile.kpi_assessments.filter(evidence_links__isnull=False).exists()
    except Exception:
        return False


def coverage_for(profile) -> CoverageReport:
    """Evidence coverage for one CompanyProfile. Reads only."""
    report = CoverageReport()
    for item in MATERIAL_INPUTS:
        report.total_weight += item.weight
        report.total_inputs += 1
        if field_provenance(profile, item.field_name) in EVIDENCED_PROVENANCE:
            report.covered_weight += item.weight
            report.covered_inputs += 1
        else:
            report.missing.append(item.field_name)
    return report


def eligibility(coverage: float, minimum: float, full: float) -> str:
    """
    Map a coverage ratio onto the three public states.

    Thresholds are arguments, not constants: the plan (§8) records that they are
    a product decision to be taken against the real distribution, and hard-coding
    a guess here would quietly make that decision instead.

    Zero coverage is checked first and unconditionally. Thresholds are caller
    input, and a caller passing full=0.0 would otherwise satisfy `coverage >=
    full` at zero coverage and publish a score for a company with no evidence at
    all — the precise failure this module exists to prevent. No threshold may
    override the invariant.
    """
    if coverage <= 0.0:
        return ELIGIBILITY_UNAVAILABLE
    if coverage >= full:
        return ELIGIBILITY_ELIGIBLE
    if coverage >= minimum:
        return ELIGIBILITY_PROVISIONAL
    return ELIGIBILITY_UNAVAILABLE
