# Generated by Django 5.2.14 on 2026-10-07 16:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgePassage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('sajda', 'Sajda'), ('azan_kz', 'Azan.kz')], max_length=20)),
                ('external_id', models.CharField(max_length=160)),
                ('source_url', models.URLField(max_length=1000)),
                ('kind', models.CharField(choices=[('quran_text', 'quran_text'), ('translation', 'translation'), ('tafsir', 'tafsir'), ('hadith', 'hadith'), ('scholarly_position', 'scholarly_position'), ('ecoiq_operationalisation', 'ecoiq_operationalisation'), ('ai_inference', 'ai_inference')], max_length=40)),
                ('work', models.CharField(max_length=240)),
                ('edition', models.CharField(max_length=160)),
                ('source_version', models.CharField(max_length=160)),
                ('language', models.CharField(max_length=20)),
                ('attribution', models.CharField(max_length=240)),
                ('passage', models.TextField()),
                ('surah', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ayah_start', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ayah_end', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('name_key', models.CharField(blank=True, max_length=80)),
                ('enumeration', models.CharField(blank=True, max_length=160)),
                ('rights', models.CharField(choices=[('owned', 'owned'), ('licensed', 'licensed'), ('public_domain', 'public_domain'), ('permission_pending', 'permission_pending')], default='permission_pending', max_length=30)),
                ('rights_evidence', models.TextField(blank=True)),
                ('digest', models.CharField(editable=False, max_length=64)),
                ('reviewed_digest', models.CharField(blank=True, editable=False, max_length=64)),
                ('reviewed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('embedding', models.JSONField(blank=True, default=list, editable=False)),
                ('embedding_model', models.CharField(blank=True, editable=False, max_length=240)),
                ('embedding_digest', models.CharField(blank=True, editable=False, max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('provider', 'external_id'),
                'indexes': [models.Index(fields=['provider', 'language'], name='islamic_provider_lang_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_id'), name='islamic_provider_external_unique')],
            },
        ),
    ]
