# Generated by Django 5.2.14 on 2026-05-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('iso_code', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 code (e.g. GB, US, DE)', max_length=3)),
                ('flag_emoji', models.CharField(blank=True, max_length=10)),
                ('region', models.CharField(choices=[('western_europe', 'Western Europe'), ('eastern_europe', 'Eastern Europe'), ('north_america', 'North America'), ('latin_america', 'Latin America'), ('middle_east', 'Middle East'), ('central_asia', 'Central Asia'), ('east_asia', 'East Asia'), ('south_asia', 'South Asia'), ('southeast_asia', 'Southeast Asia'), ('africa', 'Africa'), ('oceania', 'Oceania')], default='western_europe', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False, help_text='Show on homepage / featured countries section')),
                ('national_ecoiq_index', models.FloatField(default=0.0, help_text='Weighted avg EcoIQ score of tracked companies')),
                ('transition_readiness_score', models.FloatField(default=0.0, help_text='0-100: Readiness for industrial transition')),
                ('policy_environment_score', models.FloatField(default=0.0, help_text='0-100: Quality and ambition of industrial/climate policy')),
                ('investment_climate_score', models.FloatField(default=0.0, help_text='0-100: Attractiveness for ethical investment')),
                ('transparency_score', models.FloatField(default=0.0, help_text='0-100: National transparency baseline')),
                ('industrial_modernization_score', models.FloatField(default=0.0, help_text='0-100: How modernized is the industrial base')),
                ('transition_readiness_label', models.CharField(choices=[('leading', 'Transition Leader'), ('advancing', 'Advancing'), ('developing', 'Developing'), ('lagging', 'Lagging'), ('critical', 'Critical — Urgent Need')], default='developing', max_length=20)),
                ('gdp_usd', models.BigIntegerField(blank=True, help_text='GDP in USD (latest year)', null=True)),
                ('industrial_gdp_share', models.FloatField(blank=True, help_text='% of GDP from industrial/extractive sectors', null=True)),
                ('co2_megatonnes', models.FloatField(blank=True, help_text='Annual CO₂ in megatonnes', null=True)),
                ('renewable_energy_share', models.FloatField(blank=True, help_text='% of electricity from renewables', null=True)),
                ('fossil_fuel_dependency', models.FloatField(blank=True, help_text='% of energy from fossil fuels', null=True)),
                ('companies_tracked', models.PositiveIntegerField(default=0)),
                ('estimated_transition_gap_usd', models.BigIntegerField(blank=True, help_text='Annual financing gap for transition (USD)', null=True)),
                ('green_finance_available_usd', models.BigIntegerField(blank=True, help_text='Available green finance (USD)', null=True)),
                ('ai_overview', models.TextField(blank=True, help_text='2-3 paragraph country intelligence overview')),
                ('ai_transition_narrative', models.TextField(blank=True, help_text='Transition story and opportunities')),
                ('ai_risk_summary', models.TextField(blank=True, help_text='Transition risks and barriers')),
                ('ai_investment_thesis', models.TextField(blank=True, help_text='Investment thesis for this country')),
                ('industrial_sectors', models.JSONField(blank=True, default=list, help_text='[{name, ecoiq_score, pollution_level, transition_status}]')),
                ('pollution_hotspots', models.JSONField(blank=True, default=list, help_text='[{name, description, severity}]')),
                ('financing_gaps', models.JSONField(blank=True, default=list, help_text='[{sector, gap_usd, opportunity}]')),
                ('policy_highlights', models.JSONField(blank=True, default=list, help_text='[{title, description, year, status}]')),
                ('upcoming_deadlines', models.JSONField(blank=True, default=list, help_text='[{event, date, relevance}]')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Country Profile',
                'verbose_name_plural': 'Country Profiles',
                'ordering': ['-national_ecoiq_index', 'name'],
            },
        ),
    ]
