# Generated by Django 5.2.14 on 2026-06-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countryprofile',
            name='data_last_updated',
            field=models.DateField(blank=True, help_text='Date macro/climate data was last reviewed and updated', null=True),
        ),
        migrations.AddField(
            model_name='countryprofile',
            name='data_sources',
            field=models.TextField(blank=True, help_text='Citation string e.g. "GDP: IMF WEO Apr 2026; CO2: EDGAR 2024"'),
        ),
        migrations.AddField(
            model_name='countryprofile',
            name='gdp_growth_pct',
            field=models.FloatField(blank=True, help_text='Real GDP growth rate % (IMF WEO estimate for current year)', null=True),
        ),
        migrations.AddField(
            model_name='countryprofile',
            name='inflation_pct',
            field=models.FloatField(blank=True, help_text='Inflation rate % (IMF WEO estimate for current year)', null=True),
        ),
        migrations.AddField(
            model_name='countryprofile',
            name='population_millions',
            field=models.FloatField(blank=True, help_text='Population in millions (IMF WEO estimate)', null=True),
        ),
        migrations.AlterField(
            model_name='countryprofile',
            name='companies_tracked',
            field=models.PositiveIntegerField(default=0, help_text='Legacy stored count — prefer live_company_count property'),
        ),
    ]
