# Generated by Django 5.2.14 on 2026-07-08 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrchestrationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_request', models.TextField(blank=True)),
                ('target_type', models.CharField(choices=[('company', 'Company'), ('country', 'Country'), ('location', 'Location'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('target_repr', models.CharField(blank=True, help_text='Human-readable label, e.g. a company name.', max_length=255)),
                ('target_reference', models.CharField(blank=True, db_index=True, max_length=200)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('needs_human_review', 'Needs Human Review'), ('failed', 'Failed')], db_index=True, default='running', max_length=20)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('human_review_required', models.BooleanField(default=False)),
                ('nodes_executed', models.JSONField(blank=True, default=list)),
                ('failed_node', models.CharField(blank=True, max_length=100)),
                ('error_summary', models.TextField(blank=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=155)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
