# Generated by Django 5.2.14 on 2026-06-22 22:05

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_dataingestionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Stable key: niyyah, halal, adl, …', max_length=20, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('arabic_term', models.CharField(max_length=40)),
                ('title_en', models.CharField(max_length=60)),
                ('core_question', models.CharField(max_length=200)),
                ('weight', models.FloatField(default=1.0, help_text='Relative weight in the Decision Integrity Score')),
                ('definition', models.TextField()),
                ('plain_english', models.TextField()),
                ('evidence_required', models.JSONField(blank=True, default=list)),
                ('red_flags', models.JSONField(blank=True, default=list)),
                ('scoring_rubric', models.JSONField(blank=True, default=dict, help_text='Band → description, e.g. {"0-2": "…"}')),
                ('ai_prompt', models.TextField(blank=True, help_text='Prompt used by the AI reasoning engine')),
                ('low_score_actions', models.JSONField(blank=True, default=list)),
                ('example_company', models.TextField(blank=True)),
                ('example_policy', models.TextField(blank=True)),
                ('example_investment', models.TextField(blank=True)),
                ('is_red_line', models.BooleanField(default=False, help_text='Severe failure caps the overall score (justice not traded off)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Decision Question',
                'verbose_name_plural': 'Decision Questions (the 10)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DecisionAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('company', 'Company'), ('investment', 'Investment Decision'), ('policy', 'Government Policy'), ('infrastructure', 'Infrastructure Project'), ('government', 'Government Decision')], default='company', max_length=20)),
                ('subject_name', models.CharField(help_text='e.g. "Carbon Tax Bill 2026", "Series A — SolarCo"', max_length=200)),
                ('subject_ref', models.CharField(blank=True, help_text='Optional slug / id / URL for the subject', max_length=300)),
                ('decision_integrity_score', models.FloatField(default=0.0, help_text='0–100 weighted Decision Integrity Score')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('elevated', 'Elevated'), ('high', 'High'), ('severe', 'Severe')], default='moderate', max_length=10)),
                ('verdict', models.CharField(choices=[('proceed', 'Proceed'), ('proceed_conditions', 'Proceed with Conditions'), ('revise', 'Revise Before Proceeding'), ('do_not_proceed', 'Do Not Proceed')], default='revise', max_length=20)),
                ('evidence_status', models.CharField(choices=[('verified', 'Verified'), ('partial', 'Partial'), ('insufficient', 'Insufficient'), ('unverified', 'Unverified')], default='unverified', max_length=12)),
                ('confidence', models.FloatField(default=0.5, help_text='0–1 confidence')),
                ('rizq_without_zulm_summary', models.TextField(blank=True, help_text='One-line "Create Rizq Without Zulm" verdict')),
                ('ai_narrative', models.TextField(blank=True)),
                ('red_line_breached', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('auto', 'Auto-computed from EcoIQ profile'), ('analyst', 'Analyst-authored')], default='auto', max_length=10)),
                ('analyst_reviewed', models.BooleanField(default=False)),
                ('analyst_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_computed', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qdf_assessments', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qdf_assessments', to='companies.companyprofile')),
            ],
            options={
                'verbose_name': 'Decision Assessment',
                'verbose_name_plural': 'Decision Assessments',
                'ordering': ['-last_computed'],
            },
        ),
        migrations.CreateModel(
            name='QuestionScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0, help_text='0–10')),
                ('rationale', models.TextField(blank=True)),
                ('evidence_status', models.CharField(choices=[('verified', 'Verified'), ('partial', 'Partial'), ('insufficient', 'Insufficient'), ('missing', 'Missing')], default='insufficient', max_length=12)),
                ('red_flags_triggered', models.JSONField(blank=True, default=list)),
                ('recommended_actions', models.JSONField(blank=True, default=list)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_scores', to='qdf.decisionassessment')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='qdf.decisionquestion')),
            ],
            options={
                'verbose_name': 'Question Score',
                'verbose_name_plural': 'Question Scores',
                'ordering': ['question__order'],
            },
        ),
        migrations.AddConstraint(
            model_name='decisionassessment',
            constraint=models.UniqueConstraint(condition=models.Q(('source', 'auto')), fields=('profile', 'source'), name='uniq_auto_assessment_per_profile'),
        ),
        migrations.AlterUniqueTogether(
            name='questionscore',
            unique_together={('assessment', 'question')},
        ),
    ]
