# Generated by Django 5.2.14 on 2026-05-24 16:46

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('sector', models.CharField(choices=[('oil_gas', 'Oil & Gas'), ('mining', 'Mining'), ('energy', 'Energy / Power'), ('chemical', 'Chemical'), ('metallurgy', 'Metallurgy'), ('transport', 'Transport'), ('agriculture', 'Agriculture'), ('other', 'Other')], default='other', max_length=30)),
                ('country', models.CharField(default='Kazakhstan', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('logo_url', models.URLField(blank=True, help_text='Public URL to company logo (SVG/PNG)')),
                ('employee_count', models.PositiveIntegerField(blank=True, help_text='Approximate headcount', null=True)),
                ('annual_revenue_usd', models.BigIntegerField(blank=True, help_text='Annual revenue in USD', null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Publicly listed company')),
                ('verified', models.BooleanField(default=False, help_text='Data independently verified')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on landing page')),
                ('score_pollution_footprint', models.IntegerField(default=0, help_text='Lower emissions/waste = higher score (0-100)')),
                ('score_reduction_progress', models.IntegerField(default=0, help_text='Year-on-year pollution reduction trend (0-100)')),
                ('score_investment', models.IntegerField(default=0, help_text='Environmental investment relative to revenue (0-100)')),
                ('score_transparency', models.IntegerField(default=0, help_text='Reporting quality, public disclosures (0-100)')),
                ('score_community_impact', models.IntegerField(default=0, help_text='Measurable benefit to people & ecosystem (0-100)')),
                ('ecoiq_score', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=5)),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['-ecoiq_score', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EnvironmentalProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('project_type', models.CharField(choices=[('coal_stove', 'Coal Stove Replacement'), ('gasification', 'Gasification'), ('power_modern', 'Power Plant Modernisation'), ('renewable', 'Renewable Energy'), ('water_cleanup', 'Water Clean-up'), ('waste', 'Waste Reduction'), ('tree_planting', 'Tree Planting'), ('filters', 'Industrial Filters'), ('methane', 'Methane Leak Reduction'), ('other', 'Other')], default='other', max_length=30)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('investment_usd', models.BigIntegerField(blank=True, help_text='Total investment in USD', null=True)),
                ('co2_reduction_tonnes', models.IntegerField(blank=True, help_text='Annual CO₂ reduction in tonnes', null=True)),
                ('pm25_reduction_kg', models.IntegerField(blank=True, help_text='Annual PM2.5 reduction in kg', null=True)),
                ('households_helped', models.IntegerField(blank=True, help_text='Households directly benefiting', null=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='league.company')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('audit_report', 'Audit Report'), ('government_report', 'Government Report'), ('photo', 'Photo / Video'), ('satellite', 'Satellite Evidence'), ('invoice', 'Invoice / Contract'), ('permit', 'Environmental Permit'), ('engineering_audit', 'Engineering Audit'), ('press_release', 'Press Release'), ('other', 'Other')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, null=True, upload_to='league/evidence/')),
                ('url', models.URLField(blank=True)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('issuer', models.CharField(blank=True, max_length=255)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='league.company')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='league.environmentalproject')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Документы',
                'ordering': ['-date_issued', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ecoiq_score', models.DecimalField(decimal_places=1, max_digits=5)),
                ('score_pollution_footprint', models.IntegerField()),
                ('score_reduction_progress', models.IntegerField()),
                ('score_investment', models.IntegerField()),
                ('score_transparency', models.IntegerField()),
                ('score_community_impact', models.IntegerField()),
                ('rank', models.PositiveIntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='league.company')),
            ],
            options={
                'verbose_name': 'История рейтинга',
                'verbose_name_plural': 'История рейтингов',
                'ordering': ['date'],
                'unique_together': {('company', 'date')},
            },
        ),
    ]
