# Generated by Django 5.2.14 on 2026-05-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='anomaly_score',
            field=models.FloatField(blank=True, help_text='Isolation Forest anomaly score; negative = more anomalous', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='is_anomaly',
            field=models.BooleanField(default=False, help_text='True if Isolation Forest flags this company as anomalous'),
        ),
        migrations.AddField(
            model_name='company',
            name='ml_cluster',
            field=models.IntegerField(blank=True, help_text='K-Means cluster index', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ml_cluster_label',
            field=models.CharField(blank=True, help_text='Human-readable cluster name', max_length=80),
        ),
        migrations.AddField(
            model_name='company',
            name='ml_last_run',
            field=models.DateTimeField(blank=True, help_text='When the ML pipeline last ran for this company', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ml_predicted_score_12m',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='12-month forward-projected score', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ml_score',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='GBR model-predicted EcoIQ score', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ml_score_confidence',
            field=models.FloatField(blank=True, help_text='Model confidence (0–1); higher = more training data neighbours', null=True),
        ),
    ]
