# Generated by Django 5.2.14 on 2026-05-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_add_ml_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='search_text',
            field=models.TextField(blank=True, help_text='Pre-built rich text for keyword / semantic search (built by build_embeddings)'),
        ),
    ]
