# Generated by Django 5.2.14 on 2026-07-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_add_search_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='market_cap_usd',
            field=models.BigIntegerField(blank=True, help_text='Market capitalisation in USD', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='stock_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Latest share price, in stock_price_currency', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='stock_price_currency',
            field=models.CharField(blank=True, default='USD', max_length=8),
        ),
        migrations.AddField(
            model_name='company',
            name='stock_price_updated_at',
            field=models.DateTimeField(blank=True, help_text='When stock_price / market_cap_usd were last refreshed', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='ticker',
            field=models.CharField(blank=True, help_text='Exchange ticker symbol, Yahoo Finance format (e.g. AAPL, SHEL.L, 2222.SR)', max_length=20),
        ),
    ]
