# Generated by Django 5.2.14 on 2026-07-30 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0005_company_market_cap_usd_company_stock_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='day_change_pct',
            field=models.FloatField(blank=True, help_text='Daily % price movement vs. previous close', null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='day_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='day_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='exchange',
            field=models.CharField(blank=True, help_text='Explicit exchange code for chart links (e.g. NASDAQ, LSE, TADAWUL). Preferred over guessing from the ticker suffix — set this whenever known.', max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='market_status',
            field=models.CharField(blank=True, help_text='Exchange session state when last fetched, e.g. REGULAR, CLOSED, PRE, POST', max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='previous_close',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='week52_high',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='week52_low',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='stock_price_updated_at',
            field=models.DateTimeField(blank=True, help_text='When stock_price / market_cap_usd were last refreshed — this is the last SUCCESSFUL fetch, never cleared just because a later fetch failed, so it always reflects the true age of the displayed price.', null=True),
        ),
    ]
