# Generated by Django 5.2.14 on 2026-08-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_company_day_change_pct_company_day_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='ecoiq_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='score_community_impact',
            field=models.IntegerField(blank=True, help_text='Measurable benefit to people & ecosystem (0-100). NULL when unassessed — a 0 default made an unassessed company the worst possible one.', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='score_investment',
            field=models.IntegerField(blank=True, help_text='Environmental investment relative to revenue (0-100). NULL when unassessed — a 0 default made an unassessed company the worst possible one.', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='score_pollution_footprint',
            field=models.IntegerField(blank=True, help_text='Lower emissions/waste = higher score (0-100). NULL when unassessed — a 0 default made an unassessed company the worst possible one.', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='score_reduction_progress',
            field=models.IntegerField(blank=True, help_text='Year-on-year pollution reduction trend (0-100). NULL when unassessed — a 0 default made an unassessed company the worst possible one.', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='score_transparency',
            field=models.IntegerField(blank=True, help_text='Reporting quality, public disclosures (0-100). NULL when unassessed — a 0 default made an unassessed company the worst possible one.', null=True),
        ),
    ]
