# Generated by Django 5.2.14 on 2026-08-25 10:37

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_nullable_company_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.storage.upload_to_evidence),
        ),
    ]
