# Generated by Django 5.2.14 on 2026-08-26 09:31

import core.storage
import core.upload_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_alter_evidence_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=core.storage.upload_to_evidence, validators=[core.upload_validation.UploadValidator()]),
        ),
    ]
