# Generated by Django 5.2.14 on 2026-07-31 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0006_company_day_change_pct_company_day_high_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('base_currency', models.CharField(default='USD', help_text='Display/reporting currency for this portfolio', max_length=8)),
                ('description', models.TextField(blank=True)),
                ('cash_balance', models.DecimalField(blank=True, decimal_places=2, help_text='Optional uninvested cash, in base_currency', max_digits=16, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
                'ordering': ['-updated_at'],
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('methodology_version', models.CharField(default='v1', max_length=20)),
                ('total_market_value', models.DecimalField(blank=True, decimal_places=2, help_text='Null when fx_incomplete — see currency_subtotals instead', max_digits=18, null=True)),
                ('total_value_currency', models.CharField(blank=True, max_length=8)),
                ('fx_incomplete', models.BooleanField(default=False, help_text='True when holdings span >1 currency and no FX conversion was applied')),
                ('currency_subtotals', models.JSONField(blank=True, default=dict, help_text='{currency: subtotal} — authoritative when fx_incomplete')),
                ('exposure_score', models.FloatField(blank=True, help_text='0-100 weighted exposure score across analytics-included holdings', null=True)),
                ('known_exposure_pct', models.FloatField(blank=True, help_text='% of analytics-included value with a published classification', null=True)),
                ('unknown_exposure_pct', models.FloatField(blank=True, help_text='% of analytics-included value with NO published classification — never folded into "low risk"', null=True)),
                ('evidence_coverage_pct', models.FloatField(blank=True, help_text='% of analytics-included value backed by verified or company-reported evidence (vs. AI-interpretation only)', null=True)),
                ('stale_analysis_pct', models.FloatField(blank=True, help_text='% of analytics-included value whose report is >90 days old', null=True)),
                ('distribution', models.JSONField(blank=True, default=dict, help_text='{lower_exposure/moderate_exposure/elevated_exposure/high_exposure/insufficient_evidence: pct}')),
                ('concentration', models.JSONField(blank=True, default=dict, help_text='sector/country/exchange/classification concentration breakdowns')),
                ('holding_snapshots', models.JSONField(blank=True, default=list, help_text='Per-holding computed data: weight_pct, market_value, classification, confidence, report_version, report_date, stale flag, exposure_contribution')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='investor_portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Portfolio Snapshot',
                'verbose_name_plural': 'Portfolio Snapshots',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, help_text='Private by default')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watchlist',
                'verbose_name_plural': 'Watchlists',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Manual ordering within the watchlist')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='league.company')),
                ('watchlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='investor_portfolio.watchlist')),
            ],
            options={
                'verbose_name': 'Watchlist Item',
                'verbose_name_plural': 'Watchlist Items',
                'ordering': ['order', 'added_at'],
                'unique_together': {('watchlist', 'company')},
            },
        ),
        migrations.AddField(
            model_name='watchlist',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='watchlisted_by', through='investor_portfolio.WatchlistItem', to='league.company'),
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares', models.DecimalField(decimal_places=4, max_digits=18)),
                ('avg_acquisition_price', models.DecimalField(blank=True, decimal_places=4, help_text='Average price paid per share, in acquisition_currency', max_digits=14, null=True)),
                ('acquisition_currency', models.CharField(blank=True, default='USD', max_length=8)),
                ('acquisition_date', models.DateField(blank=True, null=True)),
                ('manual_current_value', models.DecimalField(blank=True, decimal_places=2, help_text='Manually entered total holding value — used only when the company has no live EcoIQ market price', max_digits=16, null=True)),
                ('notes', models.TextField(blank=True)),
                ('include_in_analytics', models.BooleanField(default=True, help_text='Uncheck to exclude this holding from portfolio-level EcoIQ analytics')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='league.company')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='investor_portfolio.portfolio')),
            ],
            options={
                'verbose_name': 'Holding',
                'verbose_name_plural': 'Holdings',
                'ordering': ['-updated_at'],
                'unique_together': {('portfolio', 'company')},
            },
        ),
        migrations.CreateModel(
            name='PortfolioBriefing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('published', 'Published')], default='draft', max_length=10)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('model_provider', models.CharField(blank=True, max_length=30)),
                ('routing_reason', models.TextField(blank=True)),
                ('prompt_version', models.CharField(default='v1', max_length=20)),
                ('methodology_version', models.CharField(default='v1', max_length=20)),
                ('prohibited_language_flags', models.JSONField(blank=True, default=list)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefings', to='investor_portfolio.portfolio')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='briefings', to='investor_portfolio.portfoliosnapshot')),
            ],
            options={
                'verbose_name': 'Portfolio Briefing',
                'verbose_name_plural': 'Portfolio Briefings',
                'ordering': ['-version'],
                'unique_together': {('portfolio', 'version')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('owner', 'name')},
        ),
    ]
