# Generated by Django 5.2.14 on 2026-07-25 20:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capability_graph', '0002_organisationcapability_declared_by_and_more'),
        ('good_agents', '0007_availableresource_declared_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionTypeDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(blank=True, choices=[('use_official_public_process', 'Use official public process'), ('submit_consultation_response', 'Submit consultation response'), ('request_programme_clarification', 'Request programme clarification'), ('refer_to_existing_service', 'Refer to existing service'), ('request_public_data', 'Request public data'), ('surface_funding_route', 'Surface funding route'), ('propose_zero_capital_connection', 'Propose zero-capital connection'), ('prepare_outreach', 'Prepare outreach (via outreach_readiness)'), ('no_action', 'No action')], max_length=40)),
                ('rationale', models.TextField(blank=True)),
                ('has_real_beneficiary', models.BooleanField(default=False)),
                ('beneficiary_basis_notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action_type_decision', to='good_agents.goodopportunity')),
            ],
        ),
        migrations.CreateModel(
            name='ActionContentDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('content_type', models.CharField(choices=[('consultation_response', 'Consultation response'), ('referral_brief', 'Referral brief'), ('clarification_question', 'Clarification question'), ('data_request', 'Data request'), ('connection_proposal', 'Connection proposal'), ('other', 'Other')], max_length=24)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('fact_points', models.JSONField(blank=True, default=list)),
                ('inference_points', models.JSONField(blank=True, default=list)),
                ('specific_recommendation', models.TextField(blank=True)),
                ('limitations', models.TextField(blank=True)),
                ('source_links', models.JSONField(blank=True, default=list)),
                ('body_text', models.TextField(blank=True, help_text='The actual rendered content that would be submitted/sent.')),
                ('required_fields_missing', models.JSONField(blank=True, default=list, help_text='Fields a referral/form needs that are not yet known — never silently omitted.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('change_summary', models.TextField(blank=True)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('founder_approved', 'Founder approved'), ('invalidated', 'Invalidated')], default='draft', max_length=16)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('founder_approved_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_reason', models.TextField(blank=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('founder_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_drafts', to='public_action_preparation.actiontypedecision')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('decision', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='EthicsReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vulnerability_considered', models.BooleanField(default=False)),
                ('health_or_financial_hardship_considered', models.BooleanField(default=False)),
                ('personal_data_risk_checked', models.BooleanField(default=False)),
                ('representation_risk_checked', models.BooleanField(default=False)),
                ('consent_addressed', models.BooleanField(default=False)),
                ('misrouting_risk_checked', models.BooleanField(default=False)),
                ('wasted_public_resources_risk_checked', models.BooleanField(default=False)),
                ('implied_authority_risk_checked', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ethics_review', to='good_agents.goodopportunity')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FounderActionDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(blank=True, choices=[('proceed', 'Proceed'), ('revise', 'Revise'), ('do_not_proceed', 'Do not proceed')], max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('rationale', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_draft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='public_action_preparation.actioncontentdraft')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='founder_action_decision', to='good_agents.goodopportunity')),
            ],
        ),
        migrations.CreateModel(
            name='VerifiedOfficialProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_name', models.CharField(blank=True, max_length=255)),
                ('official_url', models.URLField(blank=True)),
                ('route_type', models.CharField(blank=True, help_text='capability_graph.ROUTE_TYPE_CHOICES value.', max_length=24)),
                ('opening_date', models.DateField(blank=True, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('eligibility', models.TextField(blank=True)),
                ('required_information', models.TextField(blank=True)),
                ('submission_format', models.CharField(blank=True, max_length=255)),
                ('evidence_allowed', models.TextField(blank=True)),
                ('acknowledgement_semantics', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('unknown', 'Unknown — not yet checked'), ('open', 'Open'), ('expired', 'Expired / closed'), ('not_applicable', 'Not applicable')], default='unknown', max_length=16)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('checked_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verified_official_process', to='good_agents.goodopportunity')),
                ('owning_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='capability_graph.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='ActionReviewRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('researcher', 'Researcher'), ('reviewer', 'Reviewer'), ('founder_approver', 'Founder approver')], max_length=20)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_review_roles', to='good_agents.goodopportunity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('opportunity', 'user', 'role')},
            },
        ),
    ]
