"""
EcoIQ — Capital Ethics Compendium
114 Governance Principle data objects for the /governance-principles/ page.

Public language: professional English only. Zero religious terminology.
Internal origin mapping: docs/governance-principles-surah-map.md  (INTERNAL ONLY — not for public distribution)

PRINCIPLES_JSON and CATEGORIES_JSON are pre-serialised at module load time so
that the governance_principles() view never calls json.dumps() on a request
thread — the ~60 KB JSON string is produced exactly once per worker.
"""
import json as _json

# ---------------------------------------------------------------------------
# 10 Categories (id → display label)
# ---------------------------------------------------------------------------
PRINCIPLE_CATEGORIES = [
    ('governance',  'Governance & Leadership'),
    ('economy',     'Wealth, Trade & Fair Economy'),
    ('social',      'Social Protection & Human Dignity'),
    ('earth',       'Stewardship of Earth & Resources'),
    ('justice',     'Justice & Accountability'),
    ('risk',        'Risk, Warning & Consequences'),
    ('knowledge',   'Knowledge, Evidence & Truth'),
    ('human',       'Mercy & Human Development'),
    ('community',   'Community & Collective Action'),
    ('longterm',    'Long-Term Accountability'),
]

# ---------------------------------------------------------------------------
# 114 Principles
# Each dict:
#   id          — int 1–114
#   title       — English governance principle name
#   category    — one of the 10 category ids above
#   tagline     — one-line summary
#   question    — the governance question this principle asks
#   metrics     — list[str] of measurable indicators
#   signal      — brief assessment guidance for analysts
# ---------------------------------------------------------------------------

PRINCIPLES = [
    {
        'id': 1,
        'title': 'Guidance & Purpose',
        'category': 'governance',
        'tagline': 'Does this organisation know where it is going — and why?',
        'question': 'Is there a clear, accountable purpose statement that guides decisions at every level?',
        'metrics': ['mission alignment score', 'purpose-to-action consistency', 'board strategy reviews per year', 'purpose-linked executive KPIs'],
        'signal': 'Organisations without an anchored purpose drift toward short-term extraction. Score poorly where purpose is marketing language, not operational reality.',
    },
    {
        'id': 2,
        'title': 'Economic Ethics & Contract Integrity',
        'category': 'economy',
        'tagline': 'Are contracts fair, transparent and honoured?',
        'question': 'Do economic arrangements respect all parties equally and avoid hidden exploitation?',
        'metrics': ['contract transparency index', 'supplier payment terms', 'penalty clause fairness', 'dispute resolution access', 'interest rate disclosure'],
        'signal': 'Assess whether standard contracts shift risk disproportionately to weaker parties — workers, SME suppliers, or end consumers.',
    },
    {
        'id': 3,
        'title': 'Community Solidarity & Institutional Resilience',
        'category': 'community',
        'tagline': 'Does the organisation strengthen the communities it depends on?',
        'question': 'Is there active investment in community resilience, not only extraction of community resources?',
        'metrics': ['community investment ratio', 'local supplier spend %', 'employee volunteerism hours', 'community satisfaction score', 'local hire rate'],
        'signal': 'Flag where operational footprint exceeds community investment by a wide margin — a leading indicator of social licence risk.',
    },
    {
        'id': 4,
        'title': 'Protection of Vulnerable Groups',
        'category': 'social',
        'tagline': 'Are children, workers, elderly and marginalised people safeguarded?',
        'question': 'What systems exist to prevent harm to people with lower power or legal standing?',
        'metrics': ['child labour screening depth', 'modern slavery audit pass rate', 'accessible product/service offering', 'safeguarding incident response time', 'living wage compliance %'],
        'signal': 'Zero tolerance for supply-chain child labour and forced labour. Any confirmed instance triggers an immediate red-flag on the EcoIQ score.',
    },
    {
        'id': 5,
        'title': 'Inheritance & Intergenerational Equity',
        'category': 'longterm',
        'tagline': 'What are we leaving behind — asset or liability?',
        'question': 'Are decisions today creating long-term value or transferring costs to future generations?',
        'metrics': ['deferred liability disclosure', 'pension fund adequacy', 'environmental remediation provision', 'long-term asset-liability ratio', 'intergenerational equity index'],
        'signal': 'Capital structures that privatise today\'s profits while socialising tomorrow\'s costs score poorly on intergenerational equity.',
    },
    {
        'id': 6,
        'title': 'Rational Discourse & Evidence Standards',
        'category': 'knowledge',
        'tagline': 'Are claims backed by evidence, not narrative?',
        'question': 'What standards govern the quality of information used in decision-making?',
        'metrics': ['data source quality rating', 'third-party audit coverage', 'greenwashing flag rate', 'claim substantiation %', 'methodology transparency score'],
        'signal': 'Reject unsubstantiated ESG claims. Require verifiable evidence chains. Flag narrative-heavy, data-light disclosures.',
    },
    {
        'id': 7,
        'title': 'Moral Courage & Reform',
        'category': 'governance',
        'tagline': 'Does leadership act on what it knows, even when costly?',
        'question': 'Is the organisation willing to take positions and make changes that challenge short-term interests?',
        'metrics': ['whistleblower protection strength', 'self-initiated compliance upgrades', 'public position consistency', 'governance reform frequency', 'conflict-of-interest disclosure rate'],
        'signal': 'Organisations that only reform under regulatory pressure score lower than those with proactive improvement culture.',
    },
    {
        'id': 8,
        'title': 'War, Conflict & Harm Exclusion',
        'category': 'justice',
        'tagline': 'Is capital kept away from conflict, weapons and direct harm?',
        'question': 'Are there explicit, verified exclusions for conflict-enabling activities and weapons systems?',
        'metrics': ['weapons revenue exposure %', 'conflict-zone operations disclosure', 'exclusion list coverage', 'arms-trade screening depth', 'cluster munitions prohibition compliance'],
        'signal': 'Any direct revenue from banned weapons, cluster munitions, or landmines is an automatic disqualifier.',
    },
    {
        'id': 9,
        'title': 'Ecological Stewardship & Land Ethics',
        'category': 'earth',
        'tagline': 'How does the organisation relate to the land and ecosystems it uses?',
        'question': 'Are land use decisions made with full accountability for ecological cost?',
        'metrics': ['land-use change reporting', 'biodiversity net gain/loss score', 'soil health monitoring', 'deforestation exposure', 'indigenous land rights compliance'],
        'signal': 'Operations that degrade land quality or displace indigenous communities must carry heavy discounts in the EcoIQ property-sector scores.',
    },
    {
        'id': 10,
        'title': 'Repentance & Remediation Culture',
        'category': 'justice',
        'tagline': 'Does the organisation acknowledge failures and genuinely repair them?',
        'question': 'Is there a credible track record of owning mistakes and delivering concrete remediation?',
        'metrics': ['remediation delivery rate', 'apology-to-action gap', 'recurrence rate after incidents', 'compensation timeliness', 'third-party remediation verification'],
        'signal': 'Organisations that acknowledge ESG failures quickly and remediate fully are more predictive of long-term resilience than those with clean public records but hidden exposure.',
    },
    {
        'id': 11,
        'title': 'Gratitude & Value Recognition',
        'category': 'human',
        'tagline': 'Does the organisation recognise and reward value created by all contributors?',
        'question': 'Are workers, communities and nature credited for the value they generate?',
        'metrics': ['worker recognition programmes', 'fair value attribution in supply chains', 'community acknowledgement disclosures', 'natural capital accounting', 'living wage premium rate'],
        'signal': 'Value recognition includes natural capital — flag where resource extraction is priced below ecological cost.',
    },
    {
        'id': 12,
        'title': 'Architectural & Urban Justice',
        'category': 'social',
        'tagline': 'Does built-environment investment serve communities equitably?',
        'question': 'Do infrastructure and real estate decisions increase or decrease community inequality?',
        'metrics': ['affordable housing units %', 'community access rate', 'displacement incidents', 'gentrification pressure index', 'public space provision', 'accessibility compliance'],
        'signal': 'Real estate and infrastructure investments that accelerate displacement or reduce affordable access should be scored for social harm.',
    },
    {
        'id': 13,
        'title': 'Thunder & Systemic Warning Signals',
        'category': 'risk',
        'tagline': 'Are emerging systemic risks acknowledged early — not dismissed?',
        'question': 'Does the governance process treat early warning signals seriously, before they become crises?',
        'metrics': ['early warning system sophistication', 'scenario planning depth', 'board risk culture score', 'whistleblower signal response rate', 'stress-test frequency'],
        'signal': 'Organisations that ignore repeated early warnings — regulatory signals, community complaints, environmental indicators — carry elevated transition risk.',
    },
    {
        'id': 14,
        'title': 'Prosperity & Equitable Distribution',
        'category': 'economy',
        'tagline': 'Is wealth creation shared broadly or concentrated narrowly?',
        'question': 'What mechanisms ensure value creation flows to workers, communities and wider stakeholders, not just capital owners?',
        'metrics': ['CEO-to-median-worker pay ratio', 'profit-sharing participation rate', 'shareholder vs stakeholder return ratio', 'wage growth vs profit growth delta', 'regional economic multiplier'],
        'signal': 'Extreme pay ratios and zero profit-sharing are governance red flags even when headline financials are strong.',
    },
    {
        'id': 15,
        'title': 'Stone & Immovable Standards',
        'category': 'governance',
        'tagline': 'Are core ethical standards treated as non-negotiable?',
        'question': 'Which principles are beyond commercial compromise — and is that enforced in practice?',
        'metrics': ['policy waiver frequency', 'ethical override incidents', 'code of conduct enforcement rate', 'non-negotiable threshold list', 'board ethics committee independence'],
        'signal': 'An organisation whose stated non-negotiables have documented exceptions scores poorly on governance integrity.',
    },
    {
        'id': 16,
        'title': 'Bees & Sustainable Production Systems',
        'category': 'earth',
        'tagline': 'Does the production model regenerate or deplete?',
        'question': 'Is the production system modelled on circularity and regeneration — or on linear extraction?',
        'metrics': ['circularity rate %', 'waste-to-landfill reduction', 'regenerative sourcing %', 'pollinator-positive land management', 'renewable energy in production %'],
        'signal': 'Production systems with no circularity pathway carry escalating stranded-asset risk as regulatory pressure rises.',
    },
    {
        'id': 17,
        'title': 'Night, Cycles & Temporal Accountability',
        'category': 'longterm',
        'tagline': 'Is the organisation prepared for cycles — downturns, disruptions and endings?',
        'question': 'Are reserves, transition plans and worst-case scenarios fully accounted for?',
        'metrics': ['contingency reserve adequacy', 'business continuity plan quality', 'scenario range (pessimistic to optimistic)', 'decommissioning provision', 'end-of-life product plans'],
        'signal': 'Organisations without credible cycle and exit planning transfer tail risks to taxpayers, communities and future investors.',
    },
    {
        'id': 18,
        'title': 'Stewardship of Trust & Sacred Duty',
        'category': 'governance',
        'tagline': 'Is custodianship of assets and relationships treated as a genuine duty?',
        'question': 'Do fiduciaries act as true stewards — or primarily as extractors?',
        'metrics': ['fiduciary duty compliance', 'conflict-of-interest rate', 'stewardship code adherence', 'long-term vs short-term orientation ratio', 'related-party transaction transparency'],
        'signal': 'Fiduciaries who consistently prioritise short-term return over long-term stewardship create systemic fragility.',
    },
    {
        'id': 19,
        'title': 'Visible Consequences & Accountability Culture',
        'category': 'justice',
        'tagline': 'Are those who cause harm held accountable — visibly and proportionately?',
        'question': 'Is there a credible chain of accountability when harm occurs?',
        'metrics': ['enforcement action completion rate', 'penalty proportionality ratio', 'accountability gap index', 'named responsible officer rate', 'board consequence delivery'],
        'signal': 'Accountability that stops at the company boundary and never reaches individuals driving decisions is structurally insufficient.',
    },
    {
        'id': 20,
        'title': 'Prophetic Leadership & Transformational Vision',
        'category': 'governance',
        'tagline': 'Does leadership set the direction — not just manage the present?',
        'question': 'Is the organisation led by forward-looking vision, or reactive management?',
        'metrics': ['10-year strategic horizon exists', 'transition plan completeness', 'innovation investment as % revenue', 'leadership transformation track record', 'future-state scenario quality'],
        'signal': 'Organisations without a clear 10-year transition vision face compounding governance and financial risk in a disrupting economy.',
    },
    {
        'id': 21,
        'title': 'Social Proof & Peer Accountability',
        'category': 'community',
        'tagline': 'Do industry peers and civil society validate this organisation\'s claims?',
        'question': 'Is independent social and peer-based validation sought and published?',
        'metrics': ['peer review participation', 'civil society engagement quality', 'industry benchmark position', 'external assurance coverage', 'NGO relationship quality'],
        'signal': 'Third-party validation without independence is insufficient — flag related-party assurance providers.',
    },
    {
        'id': 22,
        'title': 'Travel, Migration & Human Mobility Rights',
        'category': 'social',
        'tagline': 'Does the organisation respect and protect freedom of movement for all workers?',
        'question': 'Are migrant workers, remote workers and travelling staff treated with full legal and ethical standing?',
        'metrics': ['migrant worker rights policy completeness', 'passport retention incidents (zero tolerance)', 'mobility freedom compliance', 'repatriation support rate', 'cross-border worker benefits parity'],
        'signal': 'Passport confiscation or debt bondage for migrant workers is an automatic EcoIQ disqualifier.',
    },
    {
        'id': 23,
        'title': 'Faith in Process & Procedural Integrity',
        'category': 'governance',
        'tagline': 'Are internal processes followed with discipline — not just when convenient?',
        'question': 'Is there consistent respect for governance processes, even when outcomes are uncertain?',
        'metrics': ['governance process adherence rate', 'protocol override frequency', 'procedural compliance audit score', 'board quorum consistency', 'decision documentation completeness'],
        'signal': 'Organisations that routinely bypass their own processes create operational and legal fragility.',
    },
    {
        'id': 24,
        'title': 'Light, Vision & Clarity of Purpose',
        'category': 'knowledge',
        'tagline': 'Is strategic direction communicated with clarity to all stakeholders?',
        'question': 'Can every material stakeholder understand what this organisation is doing and why?',
        'metrics': ['stakeholder comprehension survey', 'plain-language disclosure %', 'strategy communication frequency', 'investor clarity rating', 'employee understanding score'],
        'signal': 'Deliberate opacity in strategic communication — especially on ESG — is a governance red flag.',
    },
    {
        'id': 25,
        'title': 'Criterion & Differentiating Standards',
        'category': 'knowledge',
        'tagline': 'Are standards clearly applied to distinguish compliant from non-compliant behaviour?',
        'question': 'Is there a clear, accessible standard against which performance is measured and communicated?',
        'metrics': ['framework alignment count (GRI, TCFD, CSRD)', 'standard application consistency', 'exemption rate', 'materiality assessment quality', 'threshold clarity score'],
        'signal': 'Where no clear standard exists, organisations set their own — often in their own favour. Require external framework alignment.',
    },
    {
        'id': 26,
        'title': 'Poets & Narrative Responsibility',
        'category': 'knowledge',
        'tagline': 'Is the organisation\'s public narrative honest — or strategically misleading?',
        'question': 'Does the organisation\'s communication reflect its actual ESG performance?',
        'metrics': ['greenwashing flag rate', 'claim-vs-performance delta', 'narrative consistency with data', 'investor communication accuracy', 'ad claim withdrawal rate'],
        'signal': 'Organisations whose narrative is consistently better than their data carry a discount for communication risk.',
    },
    {
        'id': 27,
        'title': 'Ants & Collective Intelligence Systems',
        'category': 'community',
        'tagline': 'Does the organisation harness distributed intelligence — or centralise it?',
        'question': 'Are employees, suppliers and communities invited to contribute knowledge and flag problems?',
        'metrics': ['employee suggestion uptake rate', 'supply-chain intelligence sharing', 'community consultation depth', 'distributed risk signal systems', 'open innovation participation'],
        'signal': 'Highly centralised intelligence with no distributed input misses the most important early warnings.',
    },
    {
        'id': 28,
        'title': 'Storytelling & Truthful Disclosure',
        'category': 'knowledge',
        'tagline': 'Does the organisation tell stories that are true — not just compelling?',
        'question': 'Are disclosures, case studies and impact reports accurate and independently verified?',
        'metrics': ['impact story verification rate', 'third-party assurance on narrative', 'retraction/correction history', 'data-to-story alignment', 'case study audit coverage'],
        'signal': 'Impact stories that cannot be verified independently carry significant reputational and investor risk.',
    },
    {
        'id': 29,
        'title': 'Spider\'s Web & Systemic Fragility Mapping',
        'category': 'risk',
        'tagline': 'Are fragile dependencies identified — before they collapse?',
        'question': 'Has the organisation mapped and stress-tested its most fragile dependencies?',
        'metrics': ['supply-chain concentration risk', 'single-point-of-failure count', 'interdependency map completeness', 'resilience scenario testing frequency', 'critical supplier redundancy ratio'],
        'signal': 'Organisations built on fragile, unmapped dependencies are vulnerable to cascading failures.',
    },
    {
        'id': 30,
        'title': 'Romans & Civilisational Resilience',
        'category': 'risk',
        'tagline': 'Can this organisation absorb major external shocks?',
        'question': 'Is the balance sheet and governance structure capable of surviving a macro disruption?',
        'metrics': ['Altman Z-score', 'liquidity buffer months', 'geopolitical exposure rating', 'regulatory shock resilience', 'climate-scenario stress-test result'],
        'signal': 'High leverage plus high ESG exposure without transition planning is a compounding fragility signal.',
    },
    {
        'id': 31,
        'title': 'Luqman & Parental Wisdom',
        'category': 'human',
        'tagline': 'Does the organisation mentor, develop and protect the next generation of contributors?',
        'question': 'Are there genuine programmes for developing, mentoring and retaining talent — especially younger workers?',
        'metrics': ['graduate programme quality', 'mentorship participation rate', 'youth employment %', 'intergenerational skills transfer score', 'L&D spend per employee'],
        'signal': 'Organisations with poor succession, learning and youth development face compounding human capital risk.',
    },
    {
        'id': 32,
        'title': 'Sacred Respect & Dignity at Work',
        'category': 'social',
        'tagline': 'Is workplace dignity protected as a non-negotiable standard?',
        'question': 'Are all workers — regardless of level, location or contract type — treated with full dignity?',
        'metrics': ['dignity-at-work policy comprehensiveness', 'harassment incident rate', 'dignity breach resolution time', 'third-party worker coverage', 'gig worker protection score'],
        'signal': 'Dignity violations in the supply chain are often invisible — require third-party auditing down to tier 3.',
    },
    {
        'id': 33,
        'title': 'Confederates & Coalition Risk',
        'category': 'risk',
        'tagline': 'Are coalitions and partnerships exposing the organisation to hidden risk?',
        'question': 'Are the ESG credentials of partners, coalitions and industry groups consistent with stated values?',
        'metrics': ['partner ESG alignment score', 'industry group membership alignment', 'coalition accountability disclosures', 'joint-venture ESG due diligence depth', 'anti-competitive behaviour risk'],
        'signal': 'Membership in industry lobbying groups that oppose climate regulation contradicts stated climate commitments.',
    },
    {
        'id': 34,
        'title': 'Illumination & Energy Transition',
        'category': 'earth',
        'tagline': 'Is the organisation moving toward clean energy with credible pace?',
        'question': 'Is the organisation\'s energy transition plan credible, funded and on track?',
        'metrics': ['renewable energy % current', 'energy transition CapEx', 'Scope 1+2 reduction trajectory', 'energy intensity ratio', 'green tariff coverage', 'SBTi validation status'],
        'signal': 'Energy transition claims without funded CapEx plans and SBTi validation carry significant greenwash risk.',
    },
    {
        'id': 35,
        'title': 'Fatir & Origination of Value',
        'category': 'economy',
        'tagline': 'Is value created from genuine activity — not financial engineering?',
        'question': 'Does financial performance reflect real-economy value creation, not accounting manipulation?',
        'metrics': ['cash flow vs reported earnings alignment', 'non-recurring item frequency', 'accounting restatement history', 'financial engineering flag count', 'audit qualification history'],
        'signal': 'Persistent gaps between cash flow and reported earnings signal accounting quality issues.',
    },
    {
        'id': 36,
        'title': 'Ya-Sin & Core Commitment',
        'category': 'governance',
        'tagline': 'What is the organisation\'s irreducible core commitment — and is it honoured?',
        'question': 'Is there an explicit, binding commitment that drives governance above and beyond compliance?',
        'metrics': ['core commitment clarity score', 'board-level binding resolution count', 'mission-critical policy adherence', 'above-compliance programme count', 'voluntary standard adoption rate'],
        'signal': 'Organisations whose only commitments are legal minimums lack the governance depth needed for long-term resilience.',
    },
    {
        'id': 37,
        'title': 'The Rows & Structured Systems Thinking',
        'category': 'governance',
        'tagline': 'Are governance systems structured, ordered and consistently applied?',
        'question': 'Is there a coherent governance architecture — not a patchwork of ad-hoc policies?',
        'metrics': ['governance framework integration score', 'policy coherence rating', 'governance architecture review frequency', 'system redundancy rate', 'cross-function governance alignment'],
        'signal': 'Fragmented governance — multiple conflicting policies, unclear escalation paths — is a major operational risk.',
    },
    {
        'id': 38,
        'title': 'Sad & Adversarial Testing',
        'category': 'risk',
        'tagline': 'Has governance been tested under real pressure — not just in calm conditions?',
        'question': 'Are governance systems stress-tested against realistic adversarial scenarios?',
        'metrics': ['crisis simulation frequency', 'adversarial audit depth', 'red-team exercise results', 'governance failure scenario coverage', 'post-crisis review quality'],
        'signal': 'Governance systems that have never been tested under pressure will fail when it matters most.',
    },
    {
        'id': 39,
        'title': 'Groups & Collective Moral Responsibility',
        'category': 'community',
        'tagline': 'Does the organisation accept collective moral responsibility for sector-wide impacts?',
        'question': 'Does the organisation engage in sector-level reform, or only manage its own compliance?',
        'metrics': ['sector reform participation', 'industry standard-setting contribution', 'collective action fund contribution', 'systemic risk acknowledgement', 'pre-competitive collaboration rate'],
        'signal': 'Organisations that benefit from systemic harm without engaging in systemic reform are co-responsible for that harm.',
    },
    {
        'id': 40,
        'title': 'Forgiveness & Restorative Governance',
        'category': 'justice',
        'tagline': 'Are restorative mechanisms built into governance — not just punitive ones?',
        'question': 'When harm occurs, is the priority restoration and learning — not just punishment and liability management?',
        'metrics': ['restorative justice programme existence', 'community repair fund activity', 'learning-from-failure rate', 'remediation quality score', 'victim acknowledgement rate'],
        'signal': 'Governance dominated by liability avoidance — rather than genuine repair — produces poor long-term outcomes.',
    },
    {
        'id': 41,
        'title': 'Detailed Explanation & Full Disclosure',
        'category': 'knowledge',
        'tagline': 'Are material risks and impacts disclosed in full — not buried?',
        'question': 'Is every material ESG risk and impact explained in accessible, complete language?',
        'metrics': ['materiality coverage score', 'buried disclosure frequency', 'plain-language score', 'forward-looking statement accuracy', 'disclosure completeness vs TCFD'],
        'signal': 'Material risks disclosed only in footnotes or technical annexes without accessible summary are functionally hidden.',
    },
    {
        'id': 42,
        'title': 'Consultation & Multi-Stakeholder Governance',
        'category': 'community',
        'tagline': 'Are major decisions informed by those most affected?',
        'question': 'Is there a structured, genuine consultation process for affected communities before major decisions?',
        'metrics': ['community consultation rate', 'FPIC process compliance', 'stakeholder response uptake rate', 'consultation outcome influence %', 'post-consultation action report'],
        'signal': 'Consultations that gather input but demonstrably change nothing are performance, not governance.',
    },
    {
        'id': 43,
        'title': 'Luxury, Excess & Consumption Ethics',
        'category': 'economy',
        'tagline': 'Does the organisation profit from — or challenge — unsustainable consumption?',
        'question': 'Is the business model dependent on excessive consumption, or does it incentivise sustainable behaviour?',
        'metrics': ['consumption reduction incentive %', 'planned obsolescence score', 'repairability index', 'end-of-life take-back rate', 'sustainability-linked revenue %'],
        'signal': 'Revenue models relying on planned obsolescence or designed waste face growing regulatory and reputational risk.',
    },
    {
        'id': 44,
        'title': 'Smoke & Transition Uncertainty',
        'category': 'risk',
        'tagline': 'Are transition risks — including regulatory and market shifts — fully acknowledged?',
        'question': 'Does the organisation have a credible response to known transition uncertainties?',
        'metrics': ['regulatory scenario coverage', 'carbon-price sensitivity analysis', 'market disruption scenario depth', 'technology transition plan quality', 'political risk exposure'],
        'signal': 'Organisations that treat transition risk as remote or manageable without evidence are underpricing known exposure.',
    },
    {
        'id': 45,
        'title': 'Kneeling & Equitable Access',
        'category': 'social',
        'tagline': 'Are products and services accessible to all — not only the privileged?',
        'question': 'Is the organisation working to close access gaps across income, geography and ability?',
        'metrics': ['low-income market access %', 'geographic service coverage', 'accessibility compliance rate', 'price elasticity for essential services', 'social tariff availability'],
        'signal': 'Businesses providing essential services at unaffordable prices to low-income groups carry significant social licence risk.',
    },
    {
        'id': 46,
        'title': 'Dunes & Patient, Long-Horizon Investment',
        'category': 'longterm',
        'tagline': 'Is the organisation structured for endurance — not just quarterly performance?',
        'question': 'Are capital allocation and incentive structures aligned with long-term value creation?',
        'metrics': ['long-term incentive plan % of total comp', 'holding period for major investments', 'multi-year average ROIC', 'capital recycling patience', 'board long-term orientation score'],
        'signal': 'Incentive structures that reward only short-term metrics produce consistently short-sighted governance.',
    },
    {
        'id': 47,
        'title': 'Victory & Just Outcomes',
        'category': 'justice',
        'tagline': 'When the organisation succeeds, who shares in that success?',
        'question': 'Are the benefits of success distributed fairly — or captured by a narrow group?',
        'metrics': ['stakeholder benefit participation rate', 'profit-sharing coverage %', 'community benefit agreement presence', 'worker ownership rate', 'impact beneficiary count'],
        'signal': 'Concentrated value capture — even from ESG-positive activities — undermines the governance legitimacy of the organisation.',
    },
    {
        'id': 48,
        'title': 'Conquest & Resource Extraction Ethics',
        'category': 'earth',
        'tagline': 'Does resource extraction leave communities better — or worse — off?',
        'question': 'Are the terms of resource extraction fair to host communities and ecosystems?',
        'metrics': ['community benefit agreement value', 'ecosystem restoration commitment', 'revenue transparency (EITI)', 'host community net benefit score', 'land rehabilitation provision'],
        'signal': 'Resource extraction that enriches distant shareholders while impoverishing host communities is ethically and practically unsustainable.',
    },
    {
        'id': 49,
        'title': 'Rooms & Private Accountability',
        'category': 'governance',
        'tagline': 'Are private decisions — not just public ones — held to the same ethical standard?',
        'question': 'Is governance applied consistently in private and informal settings — not only in public disclosures?',
        'metrics': ['board meeting governance quality', 'off-record decision documentation', 'private commitment follow-through rate', 'informal governance audit score', 'shadow governance risk assessment'],
        'signal': 'The gap between public governance commitments and private decision-making is often where real governance risk lies.',
    },
    {
        'id': 50,
        'title': 'Qaf & Limits',
        'category': 'risk',
        'tagline': 'Are there explicit limits — and are they respected?',
        'question': 'Has the organisation defined clear upper bounds on risk, harm and resource use — and enforced them?',
        'metrics': ['risk appetite statement completeness', 'limit breach frequency', 'ecological limit alignment', 'planetary boundary exposure', 'hard stop policy count'],
        'signal': 'Organisations without hard limits on harm, resource use or risk exposure will exceed those limits under competitive pressure.',
    },
    {
        'id': 51,
        'title': 'Scattering Winds & Distributed Impact',
        'category': 'earth',
        'tagline': 'Are wide, diffuse environmental impacts tracked — not just direct, visible ones?',
        'question': 'Does ESG monitoring extend to distant, indirect and distributed environmental effects?',
        'metrics': ['Scope 3 emissions coverage', 'downstream impact tracking', 'value-chain monitoring depth', 'biodiversity footprint scope', 'water-use indirect accounting'],
        'signal': 'Organisations that account only for Scope 1 emissions are managing a fraction of their actual environmental risk.',
    },
    {
        'id': 52,
        'title': 'Mountain & Foundational Stability',
        'category': 'governance',
        'tagline': 'Does governance provide bedrock stability — or shift under pressure?',
        'question': 'Is the governance architecture stable enough to hold under financial, regulatory and reputational stress?',
        'metrics': ['governance framework stability score', 'policy reversal rate', 'board continuity metric', 'institutional resilience index', 'crisis governance quality rating'],
        'signal': 'Governance that pivots under commercial pressure is not genuine governance — it is compliance theatre.',
    },
    {
        'id': 53,
        'title': 'Star & Navigation Ethics',
        'category': 'governance',
        'tagline': 'Are guiding principles stable and used for actual navigation — not just display?',
        'question': 'Do stated values shape actual decisions — or are they decorative?',
        'metrics': ['values-to-decision alignment rate', 'ethics committee decision influence', 'values integration in strategy', 'leadership values modelling score', 'culture audit result'],
        'signal': 'When stated values and operating decisions diverge consistently, the values are misleading.',
    },
    {
        'id': 54,
        'title': 'Moon & Cyclical Measurement',
        'category': 'knowledge',
        'tagline': 'Is ESG performance measured consistently over time — enabling real trend analysis?',
        'question': 'Are measurement standards stable enough to allow meaningful year-on-year comparison?',
        'metrics': ['methodology change frequency', 'baseline consistency', 'year-on-year comparability', 'data series length', 'restatement rate'],
        'signal': 'Frequent methodology changes — without restating prior years — make trend analysis unreliable and should be flagged.',
    },
    {
        'id': 55,
        'title': 'Ecological Balance & Systemic Sustainability',
        'category': 'earth',
        'tagline': 'Does the organisation\'s operating model respect the carrying capacity of natural systems?',
        'question': 'Are operational boundaries consistent with ecological limits — not just regulatory minimums?',
        'metrics': ['planetary boundary alignment', 'ecological overshoot score', 'water-stress alignment', 'land-use sustainability rating', 'net biodiversity impact'],
        'signal': 'Legal compliance is insufficient. Score organisations against ecological carrying capacity, not just current regulations.',
    },
    {
        'id': 56,
        'title': 'The Inevitable & Material Consequence Planning',
        'category': 'risk',
        'tagline': 'Are inevitable consequences — transition costs, obsolescence, end of life — planned for?',
        'question': 'Has the organisation planned explicitly for consequences that are known and unavoidable?',
        'metrics': ['stranded-asset provision adequacy', 'phase-out timeline completeness', 'inevitable cost disclosure quality', 'end-of-life provision', 'disruption scenario readiness'],
        'signal': 'Treating known inevitable consequences as contingent liabilities is a misrepresentation of financial position.',
    },
    {
        'id': 57,
        'title': 'Iron & Infrastructure Responsibility',
        'category': 'earth',
        'tagline': 'Is physical infrastructure managed with a full account of its social and environmental impact?',
        'question': 'Does infrastructure investment account for full lifecycle environmental and community impact?',
        'metrics': ['lifecycle carbon accounting', 'infrastructure community impact assessment', 'end-of-life decommissioning plan', 'construction worker safety rate', 'infrastructure resilience score'],
        'signal': 'Infrastructure projects without full lifecycle environmental and community impact accounting carry hidden long-term liabilities.',
    },
    {
        'id': 58,
        'title': 'Dispute Resolution & Grievance Mechanisms',
        'category': 'justice',
        'tagline': 'Are disputes resolved fairly — with accessible mechanisms for all parties?',
        'question': 'Do workers, communities and suppliers have genuine access to dispute resolution?',
        'metrics': ['grievance mechanism accessibility score', 'resolution time', 'outcome satisfaction rate', 'third-party escalation availability', 'case closure without resolution %'],
        'signal': 'Dispute mechanisms that are nominally available but practically inaccessible to workers or communities are governance failures.',
    },
    {
        'id': 59,
        'title': 'Mobilisation & Urgent Action Culture',
        'category': 'governance',
        'tagline': 'Can the organisation act quickly when urgent situations demand it?',
        'question': 'Are there fast-response governance mechanisms for crisis, emergency or urgent ethical situations?',
        'metrics': ['emergency response time', 'rapid-escalation protocol quality', 'crisis decision authority clarity', 'emergency budget access', 'rapid stakeholder communication score'],
        'signal': 'Governance that requires months of process to address urgent harm is structurally inadequate.',
    },
    {
        'id': 60,
        'title': 'Testing & Proof of Commitment',
        'category': 'governance',
        'tagline': 'Has the organisation\'s governance been tested — and demonstrated — under real pressure?',
        'question': 'Is there a track record of maintaining commitments when they become commercially inconvenient?',
        'metrics': ['commitment maintenance under pressure rate', 'policy reversal during downturns', 'ethics-over-profit decision instances', 'board governance crisis track record', 'external governance rating'],
        'signal': 'Commitments maintained only in favourable conditions are not governance commitments — they are preferences.',
    },
    {
        'id': 61,
        'title': 'Ranks & Ordered Accountability Structures',
        'category': 'governance',
        'tagline': 'Is there clear, ordered accountability — with no gaps or ambiguities?',
        'question': 'Is every material governance function clearly assigned to a named person or body?',
        'metrics': ['accountability map completeness', 'RACI coverage', 'governance gap count', 'escalation path clarity', 'named responsible officer rate'],
        'signal': 'Governance gaps — functions with no clear owner — are where most failures originate.',
    },
    {
        'id': 62,
        'title': 'Friday & Collective Commitment Rhythms',
        'category': 'community',
        'tagline': 'Are there regular collective moments of accountability and renewal?',
        'question': 'Does governance include structured, recurring reviews of community commitments and collective performance?',
        'metrics': ['stakeholder review frequency', 'community reporting cadence', 'collective governance meeting regularity', 'board accountability session count', 'public reporting schedule adherence'],
        'signal': 'Governance without regular collective accountability sessions allows drift from stated commitments.',
    },
    {
        'id': 63,
        'title': 'Hypocrites & Integrity Testing',
        'category': 'governance',
        'tagline': 'Does behaviour match stated values — consistently, under scrutiny and without audience?',
        'question': 'Is there a credible integrity testing process — not just formal compliance?',
        'metrics': ['stated-vs-actual behaviour gap score', 'integrity audit results', 'whistleblower disclosure rate', 'greenwash complaint rate', 'supplier integrity audit depth'],
        'signal': 'The most dangerous governance failure is when stated values and actual behaviour consistently diverge — undetected.',
    },
    {
        'id': 64,
        'title': 'Mutual Exchange & Fair Trade',
        'category': 'economy',
        'tagline': 'Are commercial exchanges genuinely mutual — or systematically unequal?',
        'question': 'Do trading relationships leave both parties better off — or does one side consistently extract value from the other?',
        'metrics': ['supplier benefit ratio', 'fair trade certification coverage', 'buyer-supplier value split', 'renegotiation protection mechanisms', 'SME supplier share %'],
        'signal': 'Supply chains built on monopsony power that systematically disadvantages SME suppliers carry growing regulatory and reputational risk.',
    },
    {
        'id': 65,
        'title': 'Divorce & Clean Separation Protocols',
        'category': 'governance',
        'tagline': 'Are exits, divestments and separations handled equitably?',
        'question': 'When ending relationships — with suppliers, employees, communities or assets — are obligations met in full?',
        'metrics': ['exit obligation fulfilment rate', 'community exit impact assessment', 'employee redundancy fairness score', 'divestment due diligence quality', 'post-exit liability management'],
        'signal': 'Asset disposals that transfer environmental or social liabilities to less-equipped parties are a form of harm externalisation.',
    },
    {
        'id': 66,
        'title': 'Prohibition & Harm Exclusion Lists',
        'category': 'justice',
        'tagline': 'Are harm-generating activities genuinely excluded — not just disclosed?',
        'question': 'Is the exclusion list actively enforced — with clear triggers and independent verification?',
        'metrics': ['exclusion list breadth', 'enforcement verification rate', 'exclusion trigger clarity', 'exclusion list update frequency', 'third-party exclusion audit'],
        'signal': 'Exclusion lists that are not independently enforced are marketing documents, not governance controls.',
    },
    {
        'id': 67,
        'title': 'Dominion & Responsible Power Use',
        'category': 'governance',
        'tagline': 'Is institutional power exercised in service of stakeholders — not in service of itself?',
        'question': 'Are mechanisms in place to prevent the abuse of market, regulatory or institutional power?',
        'metrics': ['power concentration index', 'abuse-of-dominance incidents', 'market conduct compliance', 'regulatory capture risk score', 'institutional power oversight quality'],
        'signal': 'Organisations with high market power and low external accountability carry systemic risk for markets and communities.',
    },
    {
        'id': 68,
        'title': 'Pen & Documentation Standards',
        'category': 'knowledge',
        'tagline': 'Is governance documented comprehensively — not selectively?',
        'question': 'Are all material governance decisions, policies and outcomes documented in an accessible, persistent record?',
        'metrics': ['governance decision documentation rate', 'policy version control quality', 'audit trail completeness', 'document retention compliance', 'board minute quality score'],
        'signal': 'Undocumented decisions cannot be audited, challenged or learned from — they are invisible governance failures.',
    },
    {
        'id': 69,
        'title': 'Inevitable Reality & Absolute Materiality',
        'category': 'risk',
        'tagline': 'Are the most important risks treated as real — not manageable away?',
        'question': 'Is there a clear list of risks treated as genuinely material — not just technically disclosed?',
        'metrics': ['materiality matrix quality', 'top-10 risk treatment depth', 'risk treatment vs disclosure gap', 'board time on material risk', 'insurance vs mitigation balance'],
        'signal': 'Risks that are technically disclosed but receive no board time or mitigation budget are not managed — they are acknowledged and ignored.',
    },
    {
        'id': 70,
        'title': 'Ascending Pathways & Improvement Trajectories',
        'category': 'longterm',
        'tagline': 'Is ESG performance genuinely improving — with evidence?',
        'question': 'Are improvement trajectories credible, funded and independently verified?',
        'metrics': ['year-on-year ESG score delta', 'target attainment rate', 'improvement programme funding', 'external verification coverage', 'regression rate (going backwards)'],
        'signal': 'Improvement plans without funded implementation programmes and independent tracking are aspirational, not operational.',
    },
    {
        'id': 71,
        'title': "Noah's Patience & Long-Term Persistence",
        'category': 'longterm',
        'tagline': 'Does the organisation have the structural patience to see long-term change through?',
        'question': 'Are governance and incentive structures built for a long transformation horizon — not just the next cycle?',
        'metrics': ['CEO tenure vs transformation timeline', 'long-term incentive plan structure', 'multi-decade asset planning quality', 'generational knowledge transfer', 'patient capital access'],
        'signal': 'Transformation commitments that extend beyond the current executive\'s tenure need institutional — not personal — governance backing.',
    },
    {
        'id': 72,
        'title': 'Hidden Knowledge & Latent Risk Detection',
        'category': 'risk',
        'tagline': 'Are the risks that cannot yet be seen actively looked for?',
        'question': 'Is there a systematic process for surfacing unknown, latent or emergent risks?',
        'metrics': ['horizon scanning programme quality', 'unknown-unknown protocol existence', 'novel risk detection rate', 'pre-mortem exercise frequency', 'expert network breadth for emerging risk'],
        'signal': 'The risks most likely to cause catastrophic failure are the ones that are not yet on the risk register.',
    },
    {
        'id': 73,
        'title': 'Wrapped & Protected Core Assets',
        'category': 'governance',
        'tagline': 'Are core productive assets — human, natural and physical — protected from short-term exploitation?',
        'question': 'Are mechanisms in place to prevent short-term extraction from assets that underpin long-term value?',
        'metrics': ['core asset impairment rate', 'resource depletion vs replenishment ratio', 'talent retention rate', 'natural capital protection score', 'non-current asset protection policy'],
        'signal': 'Organisations that consume core assets for short-term returns are destroying future capacity — even when current financials look strong.',
    },
    {
        'id': 74,
        'title': 'Cloaked & Hidden Harm Detection',
        'category': 'risk',
        'tagline': 'Are harms being actively concealed — intentionally or by institutional blindness?',
        'question': 'Does the organisation have independent processes to detect harm that may be actively or passively hidden?',
        'metrics': ['independent harm detection programme', 'supplier hidden-harm audit rate', 'supply chain opacity index', 'dark-pattern reporting mechanism', 'conflict-of-interest in audit provider'],
        'signal': 'Self-reported ESG data without independent verification creates systematic blind spots — especially for supply-chain harm.',
    },
    {
        'id': 75,
        'title': 'Resurrection & Transformation Readiness',
        'category': 'longterm',
        'tagline': 'Is the organisation capable of genuine transformation — not just incremental improvement?',
        'question': 'Are there structural capabilities for fundamental business model transformation when needed?',
        'metrics': ['transformation programme investment %', 'business model innovation rate', 'pivot decision-making speed', 'transformation track record', 'structural renewal capability score'],
        'signal': 'Incremental improvement on a fundamentally flawed model is not transformation — it is managed decline.',
    },
    {
        'id': 76,
        'title': 'Human Responsibility & Agency',
        'category': 'human',
        'tagline': 'Are individuals within the organisation held responsible for their personal decisions?',
        'question': 'Do governance structures create individual accountability — or allow diffusion of responsibility?',
        'metrics': ['individual accountability clarity', 'named decision-maker rate', 'personal liability mechanism coverage', 'diffused responsibility risk score', 'executive personal accountability indicators'],
        'signal': 'Governance that allows harm to occur without individual accountability creates moral hazard.',
    },
    {
        'id': 77,
        'title': 'Sent Signs & Leading Indicators',
        'category': 'risk',
        'tagline': 'Are leading ESG indicators tracked — not just lagging ones?',
        'question': 'Does the organisation track forward-looking indicators that predict ESG performance, not just historical outcomes?',
        'metrics': ['leading indicator count', 'early warning system quality', 'predictive ESG model use', 'trend inflection detection speed', 'forward-looking disclosure depth'],
        'signal': 'Organisations that only track lagging indicators cannot prevent harm — only record it.',
    },
    {
        'id': 78,
        'title': 'Great News & Material Positive Impact',
        'category': 'longterm',
        'tagline': 'Is positive impact real, material and verifiable — not performative?',
        'question': 'Can the organisation substantiate genuine positive ESG outcomes with independent evidence?',
        'metrics': ['impact verification coverage', 'positive impact materiality score', 'additionality demonstrated', 'impact per pound invested', 'counterfactual methodology quality'],
        'signal': 'Positive impact claims without additionality testing are systematically overstated — require counterfactual analysis.',
    },
    {
        'id': 79,
        'title': 'Extractors & Responsible Harvest Ethics',
        'category': 'earth',
        'tagline': 'Is natural resource extraction conducted sustainably and equitably?',
        'question': 'Does resource extraction remain within sustainable yield limits and deliver fair returns to source communities?',
        'metrics': ['extraction vs replenishment rate', 'sustainable yield compliance', 'resource rent distribution', 'community royalty transparency', 'environmental impact bond adequacy'],
        'signal': 'Extraction operations exceeding sustainable yield create stranded-asset risk as regulatory responses tighten.',
    },
    {
        'id': 80,
        'title': 'Frowning & Blind Spots in Stakeholder Engagement',
        'category': 'community',
        'tagline': 'Are some stakeholders systematically less heard than others?',
        'question': 'Does the organisation\'s stakeholder engagement process reach all groups — including the least powerful?',
        'metrics': ['marginalised group consultation rate', 'engagement representativeness score', 'silent stakeholder identification', 'low-power voice inclusion', 'engagement outcome equity'],
        'signal': 'Stakeholder engagement processes dominated by the most powerful voices systematically miss the most important risks.',
    },
    {
        'id': 81,
        'title': 'Folding & Adaptive Governance',
        'category': 'governance',
        'tagline': 'Can governance structures adapt when circumstances change — without losing integrity?',
        'question': 'Are governance frameworks designed to be adaptive — without enabling opportunistic revision?',
        'metrics': ['governance revision process quality', 'adaptation speed vs integrity preservation', 'policy evolution tracking', 'change management governance rating', 'adaptive capacity score'],
        'signal': 'Governance that cannot adapt becomes brittle — but adaptation without integrity controls becomes arbitrary.',
    },
    {
        'id': 82,
        'title': 'Cleaving & Separation of Powers',
        'category': 'governance',
        'tagline': 'Are checks and balances genuinely independent — not structurally compromised?',
        'question': 'Is there genuine independence between audit, oversight, executive and board functions?',
        'metrics': ['audit independence score', 'board independence %', 'remuneration committee independence', 'oversight function separation quality', 'combined role frequency'],
        'signal': 'Governance in which one person or body controls multiple independent functions is structurally compromised.',
    },
    {
        'id': 83,
        'title': 'Fair Measurement & Weighing Standards',
        'category': 'justice',
        'tagline': 'Are ESG metrics measured consistently, honestly and without manipulation?',
        'question': 'Are measurement standards applied with integrity — or adjusted to produce favourable outcomes?',
        'metrics': ['measurement methodology consistency', 'independent metric verification %', 'data manipulation risk flag', 'metric selection bias audit', 'cherry-picking indicator score'],
        'signal': 'ESG metrics that are selectively reported — showing best-performing indicators while hiding weak ones — are misleading by design.',
    },
    {
        'id': 84,
        'title': 'Rending & Irreversible Decision Protocols',
        'category': 'risk',
        'tagline': 'Are irreversible decisions subject to higher scrutiny and sign-off?',
        'question': 'Is there a distinct governance track for decisions that cannot be undone?',
        'metrics': ['irreversibility classification process', 'enhanced scrutiny rate for irreversible decisions', 'board sign-off requirement for irreversible actions', 'reversibility assessment coverage', 'irreversible harm trigger list'],
        'signal': 'Irreversible decisions — deforestation, closure of communities, permanent asset disposals — must carry a higher governance burden.',
    },
    {
        'id': 85,
        'title': 'The Constellations & System Mapping',
        'category': 'knowledge',
        'tagline': 'Does the organisation understand the full system it operates within?',
        'question': 'Is there a complete map of the systems, dependencies and actors that shape and are shaped by this organisation?',
        'metrics': ['value chain mapping completeness', 'system dependency documentation', 'stakeholder ecosystem map quality', 'interdependency risk coverage', 'sector influence diagram'],
        'signal': 'Organisations that do not understand their systemic position cannot manage their systemic risk.',
    },
    {
        'id': 86,
        'title': 'The Night Visitor & Deep Due Diligence',
        'category': 'knowledge',
        'tagline': 'Does due diligence go deep enough — below surface presentations?',
        'question': 'Is there a rigorous, independent process for verifying what is claimed — not just receiving what is presented?',
        'metrics': ['due diligence depth score', 'independent verification rate', 'site visit frequency', 'anonymous source inclusion', 'adversarial due diligence use'],
        'signal': 'Due diligence that relies only on management-prepared materials misses the most important information.',
    },
    {
        'id': 87,
        'title': 'The Most High & Aspirational Standards',
        'category': 'governance',
        'tagline': 'Is the organisation benchmarked against the best — not just the compliant?',
        'question': 'Does the organisation aim to lead on ESG — or simply to avoid falling below the minimum?',
        'metrics': ['voluntary standard adoption count', 'above-peer ESG performance rate', 'leadership commitment signal quality', 'best-in-class benchmark position', 'frontier standard participation'],
        'signal': 'Compliance with minimum standards is baseline, not leadership. Score for ambition, not just compliance.',
    },
    {
        'id': 88,
        'title': 'The Overwhelming & Systemic Pressure Points',
        'category': 'risk',
        'tagline': 'Are there systemic pressures that could overwhelm the organisation\'s governance?',
        'question': 'Has the organisation identified conditions under which its governance could be overwhelmed — and built defences?',
        'metrics': ['systemic pressure resilience score', 'governance breaking-point analysis', 'extreme scenario coverage', 'cascade failure prevention measures', 'systemic risk buffer adequacy'],
        'signal': 'Governance that holds under normal conditions but fails under pressure is not real governance.',
    },
    {
        'id': 89,
        'title': 'Dawn & New Beginning Frameworks',
        'category': 'longterm',
        'tagline': 'Is the organisation prepared to lead in the next era — not just excel in the current one?',
        'question': 'Does strategic planning account for the possibility of fundamental sector transformation?',
        'metrics': ['next-generation strategy investment', 'emerging sector participation', 'innovation horizon (years)', 'disruption readiness score', 'leadership of new frameworks rate'],
        'signal': 'Organisations optimised for current conditions and not investing in next-era capability will be disrupted.',
    },
    {
        'id': 90,
        'title': 'The City & Urban System Responsibility',
        'category': 'community',
        'tagline': 'Does the organisation take responsibility for its contribution to urban systems?',
        'question': 'Is the organisation\'s urban and physical footprint managed with full accountability for community and infrastructure impacts?',
        'metrics': ['urban sustainability contribution', 'city resilience partnership activity', 'infrastructure burden vs contribution', 'urban heat / green space impact', 'transit access contribution'],
        'signal': 'Organisations with large urban footprints and no urban sustainability contribution are externalising infrastructure costs.',
    },
    {
        'id': 91,
        'title': 'The Sun & Energy as Shared Resource',
        'category': 'earth',
        'tagline': 'Is energy treated as a shared resource — not a private extraction opportunity?',
        'question': 'Does energy strategy account for community access, affordability and the rights of future users?',
        'metrics': ['energy access contribution', 'community energy scheme participation', 'renewable surplus sharing', 'energy poverty mitigation programme', 'energy transition equity score'],
        'signal': 'Energy strategies that maximise extraction from natural resources without contributing to equitable access are ethically and politically fragile.',
    },
    {
        'id': 92,
        'title': 'The Night & Rest, Recovery & Renewal',
        'category': 'human',
        'tagline': 'Are workers given adequate time for rest, recovery and personal renewal?',
        'question': 'Are working hours, rest periods and mental health of workers protected — not exploited?',
        'metrics': ['average working hours vs ILO standards', 'rest period compliance rate', 'mental health programme access', 'burnout indicator tracking', 'annual leave utilisation rate'],
        'signal': 'Organisations whose productivity model depends on excessive working hours are externalising health costs onto workers.',
    },
    {
        'id': 93,
        'title': 'The Morning Brightness & Positive Future Signal',
        'category': 'longterm',
        'tagline': 'Does the organisation communicate a credible, positive long-term vision?',
        'question': 'Is the future orientation of the organisation specific, funded and independently credible?',
        'metrics': ['long-term vision specificity score', 'funding alignment with stated vision', 'third-party credibility rating', 'vision-to-action timeline', 'stakeholder confidence in future direction'],
        'signal': 'Vague, unfunded long-term visions are not governance commitments — they are investor relations communications.',
    },
    {
        'id': 94,
        'title': 'The Opening Up & Systemic Expansion of Opportunity',
        'category': 'social',
        'tagline': 'Does the organisation actively work to expand opportunity beyond its immediate stakeholders?',
        'question': 'Are there deliberate programmes to expand access, opportunity and benefit to those currently excluded?',
        'metrics': ['opportunity expansion programme count', 'beneficiary reach beyond core customers', 'systemic access improvement investment', 'new entrant support %', 'inclusive hiring initiative scope'],
        'signal': 'Organisations that benefit from existing advantage without contributing to broader opportunity expansion are consuming social licence without replenishing it.',
    },
    {
        'id': 95,
        'title': 'The Fig & Nutritive Value Creation',
        'category': 'economy',
        'tagline': 'Does the organisation create products and services that genuinely nourish — not harm — those who use them?',
        'question': 'Is value creation assessed not just by financial return but by genuine benefit to end users and society?',
        'metrics': ['product harm index', 'user benefit assessment', 'dark pattern flag count', 'addictive design risk score', 'health and wellbeing product impact'],
        'signal': 'Products and services that generate revenue by exploiting psychological vulnerabilities or creating dependency carry long-term regulatory and reputational risk.',
    },
    {
        'id': 96,
        'title': 'The Clot & Origin of Value',
        'category': 'economy',
        'tagline': 'Does the organisation understand the true source of its value — and honour those who create it?',
        'question': 'Is there full recognition and fair compensation for the people and systems at the source of value creation?',
        'metrics': ['worker value attribution clarity', 'source-community benefit rate', 'knowledge worker recognition score', 'natural capital accounting presence', 'value origin transparency'],
        'signal': 'Organisations that obscure or undercompensate the original sources of value — labour, community, nature — are operating on hidden subsidy.',
    },
    {
        'id': 97,
        'title': 'Power & Legitimate Authority',
        'category': 'governance',
        'tagline': 'Is power exercised with legitimate authority and transparent mandate?',
        'question': 'Is the basis of governance authority clear, legitimate and accountable?',
        'metrics': ['governance authority legitimacy score', 'mandate clarity rating', 'delegated authority documentation', 'authority overreach incident rate', 'governance legitimacy challenge count'],
        'signal': 'Authority without clear mandate creates governance vacuum — and enables abuse.',
    },
    {
        'id': 98,
        'title': 'The Proof & Evidence-Based Governance',
        'category': 'knowledge',
        'tagline': 'Are governance decisions grounded in rigorous, objective evidence?',
        'question': 'What is the standard of evidence required before material governance decisions are made?',
        'metrics': ['evidence standard for major decisions', 'data quality in board packs', 'expert independence rate', 'decision documentation quality', 'evidence-to-outcome audit trail'],
        'signal': 'Governance decisions made on anecdote, consensus or commercial pressure rather than evidence carry systematic risk.',
    },
    {
        'id': 99,
        'title': 'The Earthquake & Magnitude of Impact',
        'category': 'risk',
        'tagline': 'Has the organisation assessed the magnitude of its potential negative impacts — at full scale?',
        'question': 'Are worst-case scenario impacts estimated and disclosed with full transparency?',
        'metrics': ['worst-case impact estimate quality', 'maximum harm scenario modelling', 'full-scale negative impact disclosure', 'catastrophic event preparedness', 'systemic risk contribution score'],
        'signal': 'Most ESG disclosures focus on average-case impacts. Require worst-case scenario modelling for all material risks.',
    },
    {
        'id': 100,
        'title': 'Charging Horses & Competitive Ethics',
        'category': 'economy',
        'tagline': 'Does competitive behaviour remain within ethical bounds — even when advantage could be gained by crossing them?',
        'question': 'Are there clear limits on competitive methods — and are they observed even when unobserved?',
        'metrics': ['anti-competitive behaviour incidents', 'market manipulation risk score', 'competitive intelligence ethics policy', 'competition law compliance rate', 'fair play commitment evidence'],
        'signal': 'Competitive environments create pressure to compromise ethical standards. Governance must hold the line even when enforcement is absent.',
    },
    {
        'id': 101,
        'title': 'The Calamity & Catastrophic Risk Planning',
        'category': 'risk',
        'tagline': 'Are catastrophic risk scenarios genuinely planned for — not just listed?',
        'question': 'Are there funded, tested response plans for the worst realistic scenarios?',
        'metrics': ['catastrophic scenario plan completeness', 'plan testing frequency', 'recovery time objective realism', 'catastrophe fund adequacy', 'regulatory notification protocol quality'],
        'signal': 'Risk registers that include catastrophic scenarios without funded response plans are compliance theatre.',
    },
    {
        'id': 102,
        'title': 'The Race to Good & Competitive Sustainability',
        'category': 'longterm',
        'tagline': 'Is the organisation trying to lead — not just comply — on sustainability?',
        'question': 'Does competitive strategy include a component of racing to the top on ESG — not the bottom?',
        'metrics': ['voluntary ESG standard leadership count', 'industry-first ESG commitment rate', 'sustainability leadership award recognition', 'above-industry-average ESG investment', 'proactive regulatory engagement quality'],
        'signal': 'Organisations that wait for regulatory mandates to improve ESG performance consistently lag their sectors.',
    },
    {
        'id': 103,
        'title': 'Time Risk & Transition Urgency',
        'category': 'risk',
        'tagline': 'Is the organisation acting with urgency proportionate to the transition timeline?',
        'question': 'Does the pace of ESG improvement match the speed required by transition science and regulation?',
        'metrics': ['emissions reduction pace vs 1.5°C pathway', 'transition plan implementation speed', 'policy change response time', 'IPCC deadline alignment', 'regulatory pre-emption score'],
        'signal': 'Organisations improving at a pace far slower than required by physical or regulatory transition timetables carry growing stranded-asset risk.',
    },
    {
        'id': 104,
        'title': 'The Backbiter & Reputational Integrity',
        'category': 'governance',
        'tagline': 'Does the organisation build genuine reputation — not manage appearances?',
        'question': 'Is public reputation grounded in genuine performance — or in communications management?',
        'metrics': ['reputation-vs-performance alignment score', 'PR correction rate', 'greenwash complaint rate', 'investigative media scrutiny resilience', 'anonymous stakeholder rating delta'],
        'signal': 'Organisations whose reputation is significantly better than their independently-assessed performance carry high reputational correction risk.',
    },
    {
        'id': 105,
        'title': 'The Elephant & Scale of Systemic Impact',
        'category': 'risk',
        'tagline': 'Does the organisation\'s scale create unique responsibilities and risks?',
        'question': 'Are the governance demands of operating at large scale recognised and met?',
        'metrics': ['scale-adjusted governance score', 'systemic importance classification', 'too-big-to-fail risk assessment', 'scale-specific risk register quality', 'oversight intensity vs scale'],
        'signal': 'Governance frameworks appropriate for SMEs are inadequate for systemically important organisations — scale creates additional obligations.',
    },
    {
        'id': 106,
        'title': "Quraysh & Anchor Community Obligations",
        'category': 'community',
        'tagline': 'Does the organisation honour its obligations to the communities that enabled its growth?',
        'question': 'Is there a deliberate programme to maintain and invest in the communities from which value was originally drawn?',
        'metrics': ['origin-community investment rate', 'historical community benefit acknowledgement', 'founding location investment', 'anchor institution programme quality', 'legacy obligation fulfilment rate'],
        'signal': 'Organisations that extract from founding communities and redeploy capital entirely to global markets erode social legitimacy over time.',
    },
    {
        'id': 107,
        'title': 'Small Kindnesses & Everyday Ethics',
        'category': 'human',
        'tagline': 'Are everyday ethical standards — not just headline policies — maintained throughout the organisation?',
        'question': 'Are small ethical failures — the everyday incivilities, minor deceptions and small injustices — taken seriously?',
        'metrics': ['daily ethics monitoring system', 'small misconduct reporting rate', 'micro-aggression policy coverage', 'everyday fairness survey result', 'routine ethics checkpoint quality'],
        'signal': 'Large-scale ethics failures are almost always preceded by tolerated small-scale failures. Track the small ones.',
    },
    {
        'id': 108,
        'title': 'Abundance & Sufficiency Ethics',
        'category': 'economy',
        'tagline': 'Does the organisation operate from a model of sufficiency — or endless accumulation?',
        'question': 'Is there a defined notion of enough — a sufficiency ceiling above which resources are redistributed or reinvested socially?',
        'metrics': ['executive pay cap existence', 'profit reinvestment vs distribution ratio', 'sufficiency commitment disclosure', 'excess profit redistribution policy', 'maximum return cap mechanism'],
        'signal': 'Organisations without any concept of sufficiency will always find ways to externalise the costs of accumulation onto others.',
    },
    {
        'id': 109,
        'title': 'The Disbelievers & Value Pluralism',
        'category': 'governance',
        'tagline': 'Does the organisation respect genuine diversity of values among stakeholders?',
        'question': 'Are decision-making processes designed to accommodate and integrate diverse stakeholder values — not suppress them?',
        'metrics': ['value diversity policy depth', 'minority stakeholder voice protection', 'pluralism in governance structure', 'cultural competence score', 'dissenting view incorporation rate'],
        'signal': 'Governance monocultures — where one worldview dominates all decisions — systematically miss important risks and perspectives.',
    },
    {
        'id': 110,
        'title': 'The Help & Collective Recovery Mechanisms',
        'category': 'community',
        'tagline': 'When others in the sector struggle, does this organisation contribute to collective recovery?',
        'question': 'Are there mechanisms to contribute to sector-wide or community-wide recovery when disruption occurs?',
        'metrics': ['sectoral mutual-aid contribution', 'crisis solidarity fund participation', 'community recovery programme activity', 'peer support during downturns', 'collective recovery investment'],
        'signal': 'Organisations that benefit from shared infrastructure and norms should contribute to their maintenance and restoration.',
    },
    {
        'id': 111,
        'title': 'Palm Fibre & Consequences of Harm',
        'category': 'justice',
        'tagline': 'Are harmful actors held accountable — not shielded by structural complexity?',
        'question': 'Does the governance system allow harm to be traced back to individuals and entities — not diffused into systems?',
        'metrics': ['harm traceability score', 'individual accountability rate', 'complex structure accountability gap', 'liability diffusion risk', 'named harm-actor disclosure rate'],
        'signal': 'Corporate structures that diffuse accountability for harm across jurisdictions, vehicles and individuals are governance failures.',
    },
    {
        'id': 112,
        'title': 'Sincere Action & Undivided Commitment',
        'category': 'governance',
        'tagline': 'Is governance commitment genuine and undivided — or hedged and conditional?',
        'question': 'Are ESG commitments made without strategic escape clauses or commercial override conditions?',
        'metrics': ['commitment conditionality rate', 'commitment firmness score', 'no-escape clause percentage', 'strategic override frequency', 'commitment delivery track record'],
        'signal': 'ESG commitments with embedded commercial override conditions are not commitments — they are conditional preferences.',
    },
    {
        'id': 113,
        'title': 'Dawn Breaking & Crisis Preparedness',
        'category': 'risk',
        'tagline': 'Is the organisation genuinely ready for the moment of transition — not just theoretically prepared?',
        'question': 'Has crisis and transition preparedness been tested — with evidence that it would actually work?',
        'metrics': ['crisis exercise completion rate', 'crisis plan last-tested date', 'transition readiness live-fire test', 'response effectiveness in past crises', 'crisis team competence certification'],
        'signal': 'Untested crisis plans have unknown reliability. Require evidence of realistic testing, not just plan documentation.',
    },
    {
        'id': 114,
        'title': 'Consumer Protection & Anti-Manipulation',
        'category': 'social',
        'tagline': 'Are customers and communities protected from manipulation, deception and exploitation?',
        'question': 'Does the organisation actively protect users from manipulation — even where legally permitted?',
        'metrics': ['dark-pattern prohibition policy', 'consumer complaint rate', 'deceptive design audit score', 'vulnerable-user protection mechanism', 'regulatory action history'],
        'signal': 'Legal permissibility is an insufficient standard. Score against genuine consumer protection — not just regulatory compliance.',
    },
]

# ---------------------------------------------------------------------------
# Pre-serialised JSON strings — computed once at import time.
# The governance_principles() view passes these directly to the template
# instead of calling json.dumps() on every request.
# ---------------------------------------------------------------------------
PRINCIPLES_JSON: str   = _json.dumps(PRINCIPLES,          separators=(',', ':'))
CATEGORIES_JSON: str   = _json.dumps(PRINCIPLE_CATEGORIES, separators=(',', ':'))
