# Generated by Django 5.2.14 on 2026-06-07 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySponsorshipLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('package', models.CharField(blank=True, choices=[('sponsor_10', 'Sponsor 10 Homes'), ('clean_street', 'Clean Street Pilot (25–50 homes)'), ('coal_free', 'Coal-Free Village Pilot (100 homes)'), ('esg_partner', 'ESG Heat Partnership')], max_length=30)),
                ('budget_band', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('proposal', 'Proposal Sent'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Sponsorship Lead',
                'verbose_name_plural': 'Company Sponsorship Leads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeatingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('tier', models.PositiveSmallIntegerField(default=1, help_text='Tier order, 1 = cheapest')),
                ('target_customer', models.CharField(blank=True, max_length=200)),
                ('included', models.TextField(blank=True, help_text='What is included')),
                ('not_included', models.TextField(blank=True, help_text='What is not included')),
                ('price_min_kzt', models.PositiveIntegerField(default=0)),
                ('price_max_kzt', models.PositiveIntegerField(default=0)),
                ('install_responsibility', models.CharField(choices=[('customer', 'Customer'), ('shared', 'Shared (customer master + EcoIQ supervision)'), ('ecoiq', 'EcoIQ / contracted crew')], default='customer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Heating Package',
                'verbose_name_plural': 'Heating Packages',
                'ordering': ['sort_order', 'tier', 'price_min_kzt'],
            },
        ),
        migrations.CreateModel(
            name='PilotProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('scale', models.CharField(choices=[('A', 'Pilot A — 1 home'), ('B', 'Pilot B — 10 homes'), ('C', 'Pilot C — 100 homes')], default='A', max_length=1)),
                ('status', models.CharField(choices=[('concept', 'Concept'), ('scoping', 'Scoping'), ('active', 'Active'), ('complete', 'Complete')], default='concept', max_length=20)),
                ('homes_target', models.PositiveIntegerField(default=0)),
                ('homes_done', models.PositiveIntegerField(default=0)),
                ('budget_kzt', models.PositiveBigIntegerField(blank=True, null=True)),
                ('objective', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pilot Project',
                'verbose_name_plural': 'Pilot Projects',
                'ordering': ['scale', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeatingApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('organisation', models.CharField(blank=True, help_text='For company / akimat leads', max_length=200)),
                ('location', models.CharField(blank=True, help_text='City / village / district', max_length=200)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('install_type', models.CharField(blank=True, choices=[('diy', 'DIY'), ('assisted', 'Assisted'), ('full', 'Full Install')], max_length=20)),
                ('lead_type', models.CharField(choices=[('household', 'Household'), ('company', 'Company'), ('akimat', 'Akimat / Government')], default='household', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('assessed', 'Assessed'), ('quoted', 'Quoted'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20)),
                ('starter_report', models.TextField(blank=True, help_text='Internal starter report (generated by admin action)')),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='heating.heatingpackage')),
            ],
            options={
                'verbose_name': 'Heating Application',
                'verbose_name_plural': 'Heating Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_m2', models.PositiveIntegerField(default=0)),
                ('insulation', models.CharField(choices=[('poor', 'Poor'), ('medium', 'Medium'), ('good', 'Good')], default='medium', max_length=10)),
                ('rooms', models.PositiveSmallIntegerField(default=0)),
                ('has_radiators', models.BooleanField(default=True)),
                ('electricity', models.CharField(choices=[('220', '220V (single-phase)'), ('380', '380V (three-phase)')], default='220', max_length=3)),
                ('available_kw', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('selected_package', models.CharField(blank=True, max_length=60)),
                ('install_type', models.CharField(blank=True, choices=[('diy', 'DIY'), ('assisted', 'Assisted'), ('full', 'Full Install')], max_length=20)),
                ('recommended_kw', models.PositiveSmallIntegerField(default=0)),
                ('estimated_cost_min', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_cost_max', models.PositiveIntegerField(blank=True, null=True)),
                ('hp_ready_recommended', models.BooleanField(default=False)),
                ('warnings', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='heating.heatingapplication')),
            ],
            options={
                'verbose_name': 'Home Assessment',
                'verbose_name_plural': 'Home Assessments',
                'ordering': ['-created_at'],
            },
        ),
    ]
