# Generated by Django 5.2.14 on 2026-06-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heating', '0002_seed_packages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companysponsorshiplead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('scheduled', 'Scheduled'), ('closed', 'Closed'), ('spam', 'Spam')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='heatingapplication',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('scheduled', 'Scheduled'), ('closed', 'Closed'), ('spam', 'Spam')], default='new', max_length=20),
        ),
    ]
