# Generated by Django 5.2.14 on 2026-07-08 13:24

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0005_alter_companyscoresnapshot_trigger'),
        ('countries', '0003_update_focus_country_data'),
    ]

    operations = [
        # Safe no-op on non-Postgres backends (VectorExtension subclasses
        # Django's own CreateExtension, which checks connection.vendor and
        # returns immediately if it isn't 'postgresql' — confirmed by reading
        # django.contrib.postgres.operations.CreateExtension.database_forwards).
        VectorExtension(),
        migrations.CreateModel(
            name='EvidenceMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_chunk', models.TextField()),
                ('source_url', models.URLField(blank=True, max_length=2000)),
                ('source_type', models.CharField(choices=[('harvester_evidence', 'Evidence Harvester Record'), ('agent_output', 'AI Agent Output'), ('company_report', 'Company Report / Document'), ('country_report', 'Country Report / Document'), ('manual', 'Manual Entry'), ('other', 'Other')], default='other', max_length=30)),
                ('agent_name', models.CharField(blank=True, max_length=150)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('date_collected', models.DateField(blank=True, null=True)),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=256, null=True)),
                ('embedding_status', models.CharField(choices=[('pending', 'Pending'), ('embedded', 'Embedded'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('source_reference', models.CharField(blank=True, db_index=True, max_length=200)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_memories', to='companies.companyprofile')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_memories', to='countries.countryprofile')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['source_type', 'company'], name='evidence_me_source__d36448_idx'), models.Index(fields=['source_type', 'country'], name='evidence_me_source__4500ee_idx')],
            },
        ),
    ]
