# Generated by Django 5.2.14 on 2026-07-10 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_memory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencememory',
            name='document_category',
            field=models.CharField(choices=[('contract', 'Contract'), ('inspection_report', 'Inspection Report'), ('fat_certificate', 'Factory Acceptance Test Certificate'), ('insurance_certificate', 'Insurance Certificate'), ('governance_minute', 'Governance Decision / Minute'), ('payment_confirmation', 'Payment Confirmation'), ('technical_report', 'Technical Report'), ('other', 'Other')], default='other', max_length=25),
        ),
        migrations.AddField(
            model_name='evidencememory',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidencememory',
            name='integrity_reference',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='evidencememory',
            name='review_tier',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('system_checked', 'System Checked'), ('human_reviewed', 'Human Reviewed'), ('independently_verified', 'Independently Verified')], default='uploaded', max_length=25),
        ),
        migrations.AddField(
            model_name='evidencememory',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_evidence_memories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencememory',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired'), ('requires_review', 'Requires Review')], default='pending', max_length=20),
        ),
    ]
