# Generated by Django 5.2.14 on 2026-07-17 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_memory', '0002_evidencememory_document_category_and_more'),
        ('gold_intelligence', '0005_goldproject_organisation'),
        ('waste_to_value_capital_allocation_engine', '0002_alter_capitalallocationdecision_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencememory',
            name='organisation',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='evidencememory',
            name='originating_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_memories', to='waste_to_value_capital_allocation_engine.capitalallocationdecision'),
        ),
        migrations.AddField(
            model_name='evidencememory',
            name='originating_outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_memories', to='waste_to_value_capital_allocation_engine.verifiedcapitaloutcome'),
        ),
        migrations.AddField(
            model_name='evidencememory',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_memories', to='gold_intelligence.goldproject'),
        ),
        migrations.AddField(
            model_name='evidencememory',
            name='visibility',
            field=models.CharField(choices=[('project_private', 'Project Private'), ('organisation_shared', 'Organisation Shared'), ('platform_learning_demo', 'Platform Learning (Demo)'), ('platform_learning_verified', 'Platform Learning (Verified)'), ('restricted_unresolved', 'Restricted — Unresolved Provenance')], default='project_private', max_length=30),
        ),
    ]
