# Generated by Django 5.2.14 on 2026-08-25 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_memory', '0004_backfill_access_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencememory',
            name='legal_status',
            field=models.CharField(blank=True, choices=[('company_policy', 'Company Policy'), ('company_disclosure', 'Company Disclosure'), ('third_party_analysis', 'Third-Party Analysis'), ('preliminary_regulatory_finding', 'Preliminary Regulatory Finding'), ('final_regulatory_finding', 'Final Regulatory Finding'), ('court_finding', 'Court Finding'), ('remediation_record', 'Remediation Record'), ('disputed', 'Disputed'), ('superseded', 'Superseded')], default='', help_text='Evidentiary standing. Blank means unclassified — which is NOT the same as a company policy, and must never be rendered as though it were a finding.', max_length=40),
        ),
        migrations.AddField(
            model_name='evidencememory',
            name='source_authority',
            field=models.CharField(blank=True, default='', help_text='The body that issued it, e.g. "European Commission". Named separately from source_url because authority is what a reader weighs, not a hostname.', max_length=200),
        ),
    ]
