# Generated by Django 5.2.14 on 2026-09-19 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_memory', '0005_evidencememory_legal_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceCitationSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('digest', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citation_snapshots', to='evidence_memory.evidencememory')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('memory', 'digest'), name='unique_memory_citation_snapshot')],
            },
        ),
    ]
