"""
Khalifa Heat — Coal-to-Electric Heating Retrofit models.

Captures the productised household packages, household/company/akimat leads,
home assessments (from the calculator), and pilot projects. All lead/contact
fields are optional where reasonable so the public forms stay low-friction.
"""
from django.db import models


INSTALL_RESPONSIBILITY_CHOICES = [
    ('customer', 'Customer'),
    ('shared',   'Shared (customer master + EcoIQ supervision)'),
    ('ecoiq',    'EcoIQ / contracted crew'),
]

INSTALL_TYPE_CHOICES = [
    ('diy',      'DIY'),
    ('assisted', 'Assisted'),
    ('full',     'Full Install'),
]

LEAD_TYPE_CHOICES = [
    ('household', 'Household'),
    ('company',   'Company'),
    ('akimat',    'Akimat / Government'),
]

APPLICATION_STATUS_CHOICES = [
    ('new',       'New'),
    ('contacted', 'Contacted'),
    ('assessed',  'Assessed'),
    ('quoted',    'Quoted'),
    ('won',       'Won'),
    ('lost',      'Lost'),
]

INSULATION_CHOICES = [
    ('poor',   'Poor'),
    ('medium', 'Medium'),
    ('good',   'Good'),
]

ELECTRICITY_CHOICES = [
    ('220', '220V (single-phase)'),
    ('380', '380V (three-phase)'),
]

COMPANY_PACKAGE_CHOICES = [
    ('sponsor_10',     'Sponsor 10 Homes'),
    ('clean_street',   'Clean Street Pilot (25–50 homes)'),
    ('coal_free',      'Coal-Free Village Pilot (100 homes)'),
    ('esg_partner',    'ESG Heat Partnership'),
]

COMPANY_LEAD_STATUS_CHOICES = [
    ('new',       'New'),
    ('contacted', 'Contacted'),
    ('proposal',  'Proposal Sent'),
    ('won',       'Won'),
    ('lost',      'Lost'),
]

PILOT_SCALE_CHOICES = [
    ('A', 'Pilot A — 1 home'),
    ('B', 'Pilot B — 10 homes'),
    ('C', 'Pilot C — 100 homes'),
]

PILOT_STATUS_CHOICES = [
    ('concept',  'Concept'),
    ('scoping',  'Scoping'),
    ('active',   'Active'),
    ('complete', 'Complete'),
]


class HeatingPackage(models.Model):
    """A productised household retrofit tier (DIY Basic … Heat Pump Ready)."""
    slug                   = models.SlugField(max_length=60, unique=True)
    name                   = models.CharField(max_length=120)
    tier                   = models.PositiveSmallIntegerField(default=1, help_text='Tier order, 1 = cheapest')
    target_customer        = models.CharField(max_length=200, blank=True)
    included               = models.TextField(blank=True, help_text='What is included')
    not_included           = models.TextField(blank=True, help_text='What is not included')
    price_min_kzt          = models.PositiveIntegerField(default=0)
    price_max_kzt          = models.PositiveIntegerField(default=0)
    install_responsibility = models.CharField(max_length=20, choices=INSTALL_RESPONSIBILITY_CHOICES, default='customer')
    is_active              = models.BooleanField(default=True)
    sort_order             = models.PositiveSmallIntegerField(default=0)

    class Meta:
        ordering = ['sort_order', 'tier', 'price_min_kzt']
        verbose_name = 'Heating Package'
        verbose_name_plural = 'Heating Packages'

    def __str__(self):
        return self.name

    @property
    def price_for_10(self):
        return (self.price_min_kzt * 10, self.price_max_kzt * 10)


class HeatingApplication(models.Model):
    """A household / company / akimat lead for a retrofit or partnership."""
    full_name    = models.CharField(max_length=200)
    phone        = models.CharField(max_length=50, blank=True)
    email        = models.EmailField(blank=True)
    organisation = models.CharField(max_length=200, blank=True, help_text='For company / akimat leads')
    location     = models.CharField(max_length=200, blank=True, help_text='City / village / district')
    address      = models.CharField(max_length=300, blank=True)

    package      = models.ForeignKey(HeatingPackage, null=True, blank=True, on_delete=models.SET_NULL, related_name='applications')
    install_type = models.CharField(max_length=20, choices=INSTALL_TYPE_CHOICES, blank=True)
    lead_type    = models.CharField(max_length=20, choices=LEAD_TYPE_CHOICES, default='household')
    message      = models.TextField(blank=True)

    status         = models.CharField(max_length=20, choices=APPLICATION_STATUS_CHOICES, default='new')
    starter_report = models.TextField(blank=True, help_text='Internal starter report (generated by admin action)')
    notes          = models.TextField(blank=True, help_text='Internal notes')

    ip_address = models.GenericIPAddressField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Heating Application'
        verbose_name_plural = 'Heating Applications'

    def __str__(self):
        return f'{self.full_name} — {self.get_lead_type_display()} ({self.get_status_display()})'


class HomeAssessment(models.Model):
    """A calculator result / site survey for one home (no PII required)."""
    application            = models.ForeignKey(HeatingApplication, null=True, blank=True, on_delete=models.SET_NULL, related_name='assessments')
    area_m2                = models.PositiveIntegerField(default=0)
    insulation             = models.CharField(max_length=10, choices=INSULATION_CHOICES, default='medium')
    rooms                  = models.PositiveSmallIntegerField(default=0)
    has_radiators          = models.BooleanField(default=True)
    electricity            = models.CharField(max_length=3, choices=ELECTRICITY_CHOICES, default='220')
    available_kw           = models.DecimalField(max_digits=5, decimal_places=1, default=0)
    selected_package       = models.CharField(max_length=60, blank=True)
    install_type           = models.CharField(max_length=20, choices=INSTALL_TYPE_CHOICES, blank=True)

    recommended_kw         = models.PositiveSmallIntegerField(default=0)
    estimated_cost_min     = models.PositiveIntegerField(null=True, blank=True)
    estimated_cost_max     = models.PositiveIntegerField(null=True, blank=True)
    hp_ready_recommended   = models.BooleanField(default=False)
    warnings               = models.TextField(blank=True)

    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Home Assessment'
        verbose_name_plural = 'Home Assessments'

    def __str__(self):
        return f'{self.area_m2} m² · {self.recommended_kw} kW ({self.get_insulation_display()})'


class CompanySponsorshipLead(models.Model):
    """A corporate / CSR / ESG sponsorship enquiry."""
    company_name = models.CharField(max_length=200)
    contact_name = models.CharField(max_length=200)
    email        = models.EmailField()
    phone        = models.CharField(max_length=50, blank=True)
    package      = models.CharField(max_length=30, choices=COMPANY_PACKAGE_CHOICES, blank=True)
    budget_band  = models.CharField(max_length=120, blank=True)
    message      = models.TextField(blank=True)

    status     = models.CharField(max_length=20, choices=COMPANY_LEAD_STATUS_CHOICES, default='new')
    notes      = models.TextField(blank=True)
    ip_address = models.GenericIPAddressField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = 'Company Sponsorship Lead'
        verbose_name_plural = 'Company Sponsorship Leads'

    def __str__(self):
        return f'{self.company_name} — {self.get_package_display() or "—"} ({self.get_status_display()})'


class PilotProject(models.Model):
    """A heating pilot project (1 / 10 / 100 homes)."""
    name         = models.CharField(max_length=200)
    slug         = models.SlugField(max_length=80, unique=True)
    location     = models.CharField(max_length=200, blank=True)
    scale        = models.CharField(max_length=1, choices=PILOT_SCALE_CHOICES, default='A')
    status       = models.CharField(max_length=20, choices=PILOT_STATUS_CHOICES, default='concept')
    homes_target = models.PositiveIntegerField(default=0)
    homes_done   = models.PositiveIntegerField(default=0)
    budget_kzt   = models.PositiveBigIntegerField(null=True, blank=True)
    objective    = models.TextField(blank=True)
    notes        = models.TextField(blank=True)
    created_at   = models.DateTimeField(auto_now_add=True)
    updated_at   = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['scale', '-created_at']
        verbose_name = 'Pilot Project'
        verbose_name_plural = 'Pilot Projects'

    def __str__(self):
        return f'{self.name} ({self.get_scale_display()})'
