# Generated by Django 5.2.14 on 2026-06-14 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_dataingestionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_slug', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=12)),
                ('triggered_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('sources_discovered', models.IntegerField(default=0)),
                ('documents_downloaded', models.IntegerField(default=0)),
                ('evidence_extracted', models.IntegerField(default=0)),
                ('evidence_verified', models.IntegerField(default=0)),
                ('evidence_normalized', models.IntegerField(default=0)),
                ('evidence_stored', models.IntegerField(default=0)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvest_jobs', to='companies.companyprofile')),
            ],
            options={
                'db_table': 'harvester_harvest_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source_type', models.CharField(choices=[('annual_report', 'Annual Report'), ('sustainability_report', 'Sustainability Report'), ('esg_report', 'ESG Report'), ('tcfd_report', 'TCFD Report'), ('transition_plan', 'Transition Plan'), ('company_website', 'Company Website'), ('investor_relations', 'Investor Relations Page'), ('companies_house', 'Companies House'), ('fca_filing', 'FCA Filing'), ('regulatory_filing', 'Regulatory Filing'), ('ofgem', 'Ofgem'), ('environment_agency', 'Environment Agency'), ('financial_times', 'Financial Times'), ('reuters', 'Reuters'), ('bloomberg', 'Bloomberg (reference)'), ('press_release', 'Press Release'), ('tender_portal', 'Tender Portal'), ('procurement_db', 'Procurement Database'), ('world_bank', 'World Bank'), ('iea', 'IEA'), ('ebrd', 'EBRD'), ('oecd', 'OECD'), ('undp', 'UNDP'), ('cdp', 'CDP'), ('gri', 'GRI'), ('sasb', 'SASB'), ('issb', 'ISSB'), ('sbti', 'SBTi'), ('msci', 'MSCI (future)'), ('sustainalytics', 'Sustainalytics (future)'), ('refinitiv', 'Refinitiv (future)')], max_length=40)),
                ('source_url', models.URLField(blank=True)),
                ('source_owner', models.CharField(blank=True, max_length=200)),
                ('confidence_base', models.FloatField(default=0.5)),
                ('update_frequency', models.CharField(choices=[('realtime', 'Real-time'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual'), ('adhoc', 'Ad hoc')], default='adhoc', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, help_text='Null = global source.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvest_sources', to='companies.companyprofile')),
            ],
            options={
                'db_table': 'harvester_source',
                'ordering': ['source_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_slug', models.CharField(max_length=120)),
                ('title', models.CharField(blank=True, max_length=400)),
                ('url', models.URLField(blank=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
                ('excerpt', models.TextField(blank=True)),
                ('full_text', models.TextField(blank=True)),
                ('document_type', models.CharField(blank=True, max_length=60)),
                ('category', models.CharField(choices=[('financial', 'Financial'), ('governance', 'Governance'), ('board', 'Board'), ('ownership', 'Ownership'), ('executive_compensation', 'Executive Compensation'), ('strategy', 'Strategy'), ('risk', 'Risk'), ('climate', 'Climate'), ('emissions', 'Emissions'), ('energy', 'Energy'), ('water', 'Water'), ('waste', 'Waste'), ('air_pollution', 'Air Pollution'), ('biodiversity', 'Biodiversity'), ('land_use', 'Land Use'), ('supply_chain', 'Supply Chain'), ('human_rights', 'Human Rights'), ('workforce', 'Workforce'), ('health_safety', 'Health & Safety'), ('cybersecurity', 'Cybersecurity'), ('innovation', 'Innovation'), ('capital_projects', 'Capital Projects'), ('regulatory_compliance', 'Regulatory Compliance'), ('future_commitments', 'Future Commitments'), ('contradictions', 'Contradictions')], max_length=40)),
                ('source_quality_score', models.FloatField(default=0.0)),
                ('freshness_score', models.FloatField(default=0.0)),
                ('corroboration_score', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=0.0)),
                ('verification_status', models.CharField(choices=[('VERIFIED', 'Verified — corroborated by an independent source'), ('PARTIAL', 'Partial — single credible source, not yet corroborated'), ('UNVERIFIED', 'Unverified — recorded but not assessed'), ('CONTRADICTED', 'Contradicted — sources disagree'), ('NOT_FOUND', 'Not found — no source located'), ('INSUFFICIENT_EVIDENCE', 'Insufficient evidence — source too weak to assert')], default='UNVERIFIED', max_length=24)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=40)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvested_evidence', to='companies.companyprofile')),
                ('harvest_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='harvester.harvestjob')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence', to='harvester.source')),
            ],
            options={
                'db_table': 'harvester_evidence',
                'ordering': ['-publication_date', '-retrieved_at'],
            },
        ),
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_slug', models.CharField(max_length=120)),
                ('metric', models.CharField(max_length=120)),
                ('value', models.FloatField(blank=True, null=True)),
                ('value_text', models.CharField(blank=True, max_length=400)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('period_year', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('financial', 'Financial'), ('governance', 'Governance'), ('board', 'Board'), ('ownership', 'Ownership'), ('executive_compensation', 'Executive Compensation'), ('strategy', 'Strategy'), ('risk', 'Risk'), ('climate', 'Climate'), ('emissions', 'Emissions'), ('energy', 'Energy'), ('water', 'Water'), ('waste', 'Waste'), ('air_pollution', 'Air Pollution'), ('biodiversity', 'Biodiversity'), ('land_use', 'Land Use'), ('supply_chain', 'Supply Chain'), ('human_rights', 'Human Rights'), ('workforce', 'Workforce'), ('health_safety', 'Health & Safety'), ('cybersecurity', 'Cybersecurity'), ('innovation', 'Innovation'), ('capital_projects', 'Capital Projects'), ('regulatory_compliance', 'Regulatory Compliance'), ('future_commitments', 'Future Commitments'), ('contradictions', 'Contradictions')], max_length=40)),
                ('confidence', models.FloatField(default=0.0)),
                ('extraction_method', models.CharField(blank=True, max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvested_datapoints', to='companies.companyprofile')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datapoints', to='harvester.evidence')),
            ],
            options={
                'db_table': 'harvester_datapoint',
                'ordering': ['company_slug', 'metric', '-period_year'],
                'indexes': [models.Index(fields=['company_slug', 'metric'], name='harvester_d_company_1b1e8a_idx'), models.Index(fields=['category'], name='harvester_d_categor_d26812_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='harvestjob',
            index=models.Index(fields=['company_slug', 'status'], name='harvester_h_company_58281a_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['source_type'], name='harvester_s_source__e17c2e_idx'),
        ),
        migrations.AddIndex(
            model_name='source',
            index=models.Index(fields=['is_active'], name='harvester_s_is_acti_8ffbbb_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['company_slug', 'category'], name='harvester_e_company_f792f2_idx'),
        ),
        migrations.AddIndex(
            model_name='evidence',
            index=models.Index(fields=['verification_status'], name='harvester_e_verific_a565d7_idx'),
        ),
    ]
