# Generated by Django 5.2.14 on 2026-06-14 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='corroboration_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evidence',
            name='dedup_key',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='EvidenceSourceRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(blank=True, max_length=40)),
                ('source_owner', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(blank=True)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('excerpt', models.TextField(blank=True)),
                ('source_quality_score', models.FloatField(default=0.0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('canonical_evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_refs', to='harvester.evidence')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_refs', to='harvester.source')),
            ],
            options={
                'db_table': 'harvester_evidence_source_ref',
                'ordering': ['-source_quality_score', '-publication_date'],
                'constraints': [models.UniqueConstraint(fields=('canonical_evidence', 'source_type', 'url'), name='uniq_canonical_source_url')],
            },
        ),
    ]
