# Generated by Django 5.2.14 on 2026-06-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0002_evidence_corroboration_count_evidence_dedup_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='normalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='period',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='datapoint',
            name='status',
            field=models.CharField(choices=[('NORMALIZED', 'Normalized — clean value extracted'), ('NOT_NORMALIZED', 'Not normalized — metric present, no parseable value')], default='NORMALIZED', max_length=16),
        ),
    ]
