# Generated by Django 5.2.14 on 2026-06-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0003_datapoint_normalized_at_datapoint_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistryCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('ticker', models.CharField(blank=True, max_length=16)),
                ('sector', models.CharField(choices=[('energy', 'Energy'), ('utilities', 'Utilities'), ('water', 'Water'), ('infrastructure', 'Infrastructure'), ('industrials', 'Industrials')], max_length=20)),
                ('subsector', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(default='GB', max_length=2)),
                ('website', models.URLField(blank=True)),
                ('investor_relations_url', models.URLField(blank=True)),
                ('annual_report_url', models.URLField(blank=True)),
                ('sustainability_report_url', models.URLField(blank=True)),
                ('companies_house_number', models.CharField(blank=True, max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'registry companies',
                'db_table': 'harvester_registry_company',
                'ordering': ['priority', 'company_name'],
                'indexes': [models.Index(fields=['sector'], name='harvester_r_sector_2bd2ba_idx'), models.Index(fields=['is_active'], name='harvester_r_is_acti_b3217b_idx')],
            },
        ),
    ]
