# Generated by Django 5.2.14 on 2026-06-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0004_registrycompany'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchHarvestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='running', max_length=12)),
                ('filter_note', models.CharField(blank=True, max_length=120)),
                ('total_companies', models.IntegerField(default=0)),
                ('successful', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('evidence_created', models.IntegerField(default=0)),
                ('datapoints_created', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'harvester_batch_harvest_run',
                'ordering': ['-created_at'],
            },
        ),
    ]
