# Generated by Django 5.2.14 on 2026-07-09 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0005_batchharvestrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='last_failure_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='source',
            name='last_failure_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='source',
            name='last_success_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('annual_report', 'Annual Report'), ('sustainability_report', 'Sustainability Report'), ('esg_report', 'ESG Report'), ('tcfd_report', 'TCFD Report'), ('transition_plan', 'Transition Plan'), ('company_website', 'Company Website'), ('investor_relations', 'Investor Relations Page'), ('companies_house', 'Companies House'), ('csv_dataset', 'CSV Dataset'), ('fca_filing', 'FCA Filing'), ('regulatory_filing', 'Regulatory Filing'), ('ofgem', 'Ofgem'), ('environment_agency', 'Environment Agency'), ('financial_times', 'Financial Times'), ('reuters', 'Reuters'), ('bloomberg', 'Bloomberg (reference)'), ('press_release', 'Press Release'), ('tender_portal', 'Tender Portal'), ('procurement_db', 'Procurement Database'), ('world_bank', 'World Bank'), ('iea', 'IEA'), ('ebrd', 'EBRD'), ('oecd', 'OECD'), ('undp', 'UNDP'), ('cdp', 'CDP'), ('gri', 'GRI'), ('sasb', 'SASB'), ('issb', 'ISSB'), ('sbti', 'SBTi'), ('msci', 'MSCI (future)'), ('sustainalytics', 'Sustainalytics (future)'), ('refinitiv', 'Refinitiv (future)')], max_length=40),
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('updated', 'Updated'), ('unchanged', 'Unchanged'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='skipped', max_length=12)),
                ('triggered_by', models.CharField(blank=True, help_text='e.g. "celery:ingest_source" or "manual"', max_length=80)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('evidence_created_count', models.IntegerField(default=0)),
                ('evidence_updated_count', models.IntegerField(default=0)),
                ('refs_attached_count', models.IntegerField(default=0)),
                ('memory_records_created', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestion_runs', to='harvester.source')),
            ],
            options={
                'db_table': 'harvester_ingestion_run',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='harvester_i_status_ace638_idx'), models.Index(fields=['source'], name='harvester_i_source__a1ccae_idx')],
            },
        ),
    ]
