# Generated by Django 5.2.14 on 2026-07-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvester', '0006_source_last_failure_at_source_last_failure_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=models.CharField(choices=[('annual_report', 'Annual Report'), ('sustainability_report', 'Sustainability Report'), ('esg_report', 'ESG Report'), ('tcfd_report', 'TCFD Report'), ('transition_plan', 'Transition Plan'), ('company_website', 'Company Website'), ('investor_relations', 'Investor Relations Page'), ('companies_house', 'Companies House'), ('sec_edgar', 'SEC EDGAR (XBRL)'), ('csv_dataset', 'CSV Dataset'), ('fca_filing', 'FCA Filing'), ('regulatory_filing', 'Regulatory Filing'), ('ofgem', 'Ofgem'), ('environment_agency', 'Environment Agency'), ('financial_times', 'Financial Times'), ('reuters', 'Reuters'), ('bloomberg', 'Bloomberg (reference)'), ('press_release', 'Press Release'), ('tender_portal', 'Tender Portal'), ('procurement_db', 'Procurement Database'), ('world_bank', 'World Bank'), ('iea', 'IEA'), ('ebrd', 'EBRD'), ('oecd', 'OECD'), ('undp', 'UNDP'), ('cdp', 'CDP'), ('gri', 'GRI'), ('sasb', 'SASB'), ('issb', 'ISSB'), ('sbti', 'SBTi'), ('msci', 'MSCI (future)'), ('sustainalytics', 'Sustainalytics (future)'), ('refinitiv', 'Refinitiv (future)')], max_length=40),
        ),
    ]
