# Generated by Django 5.2.14 on 2026-07-20 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_companyscoresnapshot_climate_risk_score_and_more'),
        ('harvester', '0007_alter_source_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='source_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_slug', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=400)),
                ('document_type', models.CharField(choices=[('annual_report', 'Annual Report'), ('sustainability_report', 'Sustainability Report'), ('esg_report', 'ESG Report'), ('tcfd_report', 'TCFD Report'), ('transition_plan', 'Transition Plan'), ('company_website', 'Company Website'), ('investor_relations', 'Investor Relations Page'), ('companies_house', 'Companies House'), ('sec_edgar', 'SEC EDGAR (XBRL)'), ('csv_dataset', 'CSV Dataset'), ('fca_filing', 'FCA Filing'), ('regulatory_filing', 'Regulatory Filing'), ('ofgem', 'Ofgem'), ('environment_agency', 'Environment Agency'), ('financial_times', 'Financial Times'), ('reuters', 'Reuters'), ('bloomberg', 'Bloomberg (reference)'), ('press_release', 'Press Release'), ('tender_portal', 'Tender Portal'), ('procurement_db', 'Procurement Database'), ('world_bank', 'World Bank'), ('iea', 'IEA'), ('ebrd', 'EBRD'), ('oecd', 'OECD'), ('undp', 'UNDP'), ('cdp', 'CDP'), ('gri', 'GRI'), ('sasb', 'SASB'), ('issb', 'ISSB'), ('sbti', 'SBTi'), ('msci', 'MSCI (future)'), ('sustainalytics', 'Sustainalytics (future)'), ('refinitiv', 'Refinitiv (future)')], max_length=40)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('url', models.URLField(max_length=1000)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('reporting_period', models.CharField(blank=True, max_length=40)),
                ('retrieved_at', models.DateTimeField(auto_now_add=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('source_tier', models.PositiveSmallIntegerField(default=4)),
                ('verification_status', models.CharField(choices=[('VERIFIED', 'Verified — corroborated by an independent source'), ('PARTIAL', 'Partial — single credible source, not yet corroborated'), ('UNVERIFIED', 'Unverified — recorded but not assessed'), ('CONTRADICTED', 'Contradicted — sources disagree'), ('NOT_FOUND', 'Not found — no source located'), ('INSUFFICIENT_EVIDENCE', 'Insufficient evidence — source too weak to assert')], default='UNVERIFIED', max_length=24)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_documents', to='companies.companyprofile')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='harvester.source')),
            ],
            options={
                'verbose_name': 'Source Document',
                'db_table': 'harvester_source_document',
                'ordering': ['-retrieved_at'],
            },
        ),
        migrations.AddField(
            model_name='evidence',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_chunks', to='harvester.sourcedocument'),
        ),
        migrations.AddConstraint(
            model_name='sourcedocument',
            constraint=models.UniqueConstraint(fields=('company_slug', 'url', 'content_hash'), name='uniq_document_company_url_hash'),
        ),
    ]
