# Generated by Django 5.2.14 on 2026-07-09 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('langgraph_orchestration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DecisionQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('intent', models.CharField(choices=[('COMPARE', 'Compare'), ('RANK', 'Rank'), ('ASSESS', 'Assess'), ('INVESTIGATE', 'Investigate'), ('PRIORITISE', 'Prioritise'), ('FIND_RISK', 'Find Risk'), ('FIND_OPPORTUNITY', 'Find Opportunity'), ('EXPLAIN', 'Explain'), ('RECOMMEND', 'Recommend'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('resolved_entities', models.JSONField(blank=True, default=list)),
                ('scope', models.JSONField(blank=True, default=dict)),
                ('capability_plan', models.JSONField(blank=True, default=list)),
                ('data_availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('PARTIAL', 'Partial'), ('INSUFFICIENT', 'Insufficient'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=15)),
                ('confidence_label', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('INSUFFICIENT_EVIDENCE', 'Insufficient Evidence')], default='INSUFFICIENT_EVIDENCE', max_length=25)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orchestration_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='decision_queries', to='langgraph_orchestration.orchestrationrun')),
                ('parent_query', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='decision_studio.decisionquery')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
