# Generated by Django 5.2.14 on 2026-09-17 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('decision_studio', '0001_initial'),
        ('gold_intelligence', '0006_projectmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='decisionquery',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gold_intelligence.goldproject'),
        ),
    ]
