# Generated by Django 5.2.14 on 2026-07-06 12:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agent_runtime_model_router', '0001_initial'),
        ('waste_to_value_capital_allocation_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('accounting_firm', 'Accounting Firm'), ('advisory_firm', 'Advisory Firm'), ('bank', 'Bank'), ('lender', 'Lender'), ('private_equity', 'Private Equity'), ('asset_manager', 'Asset Manager'), ('family_office', 'Family Office'), ('corporate', 'Corporate'), ('development_finance', 'Development Finance Institution'), ('sovereign_institution', 'Sovereign Institution')], max_length=30)),
                ('firm_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('subscription_tier', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('institutional', 'Institutional')], default='starter', max_length=15)),
                ('subscription_price_label', models.CharField(default='Contact / Custom', max_length=60)),
                ('is_demo', models.BooleanField(default=True, help_text='Every account seeded by this build is a labelled demo, never a real customer.')),
                ('relationship_owner', models.CharField(blank=True, max_length=150)),
                ('report_title', models.CharField(blank=True, max_length=200)),
                ('logo_reference', models.CharField(blank=True, help_text='Text/URL reference only — no file upload.', max_length=300)),
                ('approved_brand_accent', models.CharField(blank=True, help_text='e.g. "#00e89a"', max_length=20)),
                ('client_facing_disclaimer', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['firm_name'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('portfolio_type', models.CharField(choices=[('client_book', 'Client Book'), ('investment_portfolio', 'Investment Portfolio'), ('loan_book', 'Loan Book')], max_length=25)),
                ('description', models.TextField(blank=True)),
                ('assets_under_analysis', models.FloatField(default=0.0, help_text='Analysed exposure, not an audited/verified AUM figure.')),
                ('assets_under_analysis_currency', models.CharField(default='GBP', max_length=10)),
                ('entity_count', models.PositiveIntegerField(default=0, help_text='Denormalized, kept in sync by add_portfolio_entity().')),
                ('last_refreshed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institutional_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='financial_intelligence_cloud.institutionalaccount')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioDailyBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief_date', models.DateField(default=django.utils.timezone.now)),
                ('headline_summary', models.TextField(blank=True)),
                ('top_clients_to_call', models.JSONField(blank=True, default=list)),
                ('top_portfolio_risks', models.JSONField(blank=True, default=list)),
                ('top_finance_opportunities', models.JSONField(blank=True, default=list)),
                ('new_signals_count', models.PositiveIntegerField(default=0)),
                ('human_approvals_pending', models.PositiveIntegerField(default=0)),
                ('verified_value_recovered_to_date', models.FloatField(default=0.0)),
                ('currency', models.CharField(default='GBP', max_length=10)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('institutional_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_briefs', to='financial_intelligence_cloud.institutionalaccount')),
            ],
            options={
                'ordering': ['-brief_date'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('entity_type', models.CharField(choices=[('sme_client', 'SME Client'), ('portfolio_company', 'Portfolio Company'), ('borrower', 'Borrower')], max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('relationship_stage', models.CharField(choices=[('active', 'Active'), ('at_risk', 'At Risk'), ('dormant', 'Dormant'), ('prospect', 'Prospect')], default='active', max_length=15)),
                ('is_flagship', models.BooleanField(default=False, help_text='True only for the one entity per demo portfolio that runs through the real Council agent pipeline (e.g. FreshBridge Foods, ABC Engineering).')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='financial_intelligence_cloud.portfolio')),
                ('source_operational_loss', models.ForeignKey(blank=True, help_text='Populated only for the flagship entity — links this entity to the real OperationalLoss row its signal was derived from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='waste_to_value_capital_allocation_engine.operationalloss')),
            ],
            options={
                'verbose_name_plural': 'Portfolio entities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AdvisoryOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_type', models.CharField(choices=[('cost_recovery_advisory', 'Cost Recovery Advisory'), ('finance_readiness_advisory', 'Finance Readiness Advisory'), ('capital_raise_support', 'Capital Raise Support'), ('governance_advisory', 'Governance Advisory')], max_length=30)),
                ('headline', models.CharField(max_length=255)),
                ('rationale', models.TextField(blank=True)),
                ('estimated_capital_at_risk', models.FloatField(blank=True, null=True)),
                ('estimated_recoverable_value', models.FloatField(blank=True, null=True)),
                ('finance_readiness_score', models.FloatField(blank=True, null=True)),
                ('funding_gap', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(default='GBP', max_length=10)),
                ('priority_score', models.FloatField(default=0.0, help_text='Output of rank_clients_to_call_today()/rank_finance_opportunities() — stored, not recomputed per-request.')),
                ('requires_human_review', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('queued', 'Queued'), ('contacted', 'Contacted'), ('declined', 'Declined'), ('converted', 'Converted')], default='identified', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisory_opportunities', to='financial_intelligence_cloud.portfolioentity')),
            ],
            options={
                'ordering': ['-priority_score'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('financial_risk', 'Financial Risk'), ('operational_loss', 'Operational Loss'), ('working_capital', 'Working Capital'), ('margin_erosion', 'Margin Erosion'), ('energy_cost', 'Energy Cost'), ('asset_underperformance', 'Asset Underperformance'), ('finance_opportunity', 'Finance Opportunity'), ('capital_allocation', 'Capital Allocation'), ('evidence_gap', 'Evidence Gap'), ('governance_review', 'Governance Review'), ('MRV_update', 'MRV Update'), ('client_advisory_opportunity', 'Client Advisory Opportunity')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('capital_at_risk', models.FloatField(blank=True, help_text='Projected/estimated exposure. Never the same as verified_recovered_value.', null=True)),
                ('potential_recoverable_value', models.FloatField(blank=True, help_text='Estimated. Never the same as verified_recovered_value.', null=True)),
                ('verified_recovered_value', models.FloatField(blank=True, help_text='Stays null until a real MRV-style verification exists — never fabricated.', null=True)),
                ('currency', models.CharField(default='GBP', max_length=10)),
                ('urgency_score', models.FloatField(default=50.0)),
                ('evidence_quality', models.CharField(choices=[('strong', 'Strong'), ('medium', 'Medium'), ('weak', 'Weak'), ('missing', 'Missing')], default='medium', max_length=10)),
                ('confidence', models.FloatField(default=50.0)),
                ('human_approval_required', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], default='open', max_length=15)),
                ('portfolio_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='financial_intelligence_cloud.portfolioentity')),
                ('source_run', models.ForeignKey(blank=True, help_text='Populated ONLY for the flagship, real-agent-pipeline case. Null for every deterministically generated signal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='agent_runtime_model_router.agentrun')),
            ],
            options={
                'ordering': ['-urgency_score', '-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='OpportunityFeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('new_signal', 'New Signal'), ('new_opportunity', 'New Opportunity'), ('evidence_gap_flagged', 'Evidence Gap Flagged'), ('human_approval_needed', 'Human Approval Needed'), ('status_change', 'Status Change')], max_length=25)),
                ('headline', models.CharField(max_length=255)),
                ('detail', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('institutional_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_items', to='financial_intelligence_cloud.institutionalaccount')),
                ('related_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_items', to='financial_intelligence_cloud.advisoryopportunity')),
                ('portfolio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_items', to='financial_intelligence_cloud.portfolio')),
                ('related_signal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feed_items', to='financial_intelligence_cloud.portfoliosignal')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddField(
            model_name='advisoryopportunity',
            name='linked_signal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to='financial_intelligence_cloud.portfoliosignal'),
        ),
        migrations.AddIndex(
            model_name='portfolio',
            index=models.Index(fields=['institutional_account'], name='financial_i_institu_9e99fd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='portfoliodailybrief',
            unique_together={('institutional_account', 'brief_date')},
        ),
        migrations.AddIndex(
            model_name='portfolioentity',
            index=models.Index(fields=['portfolio', 'relationship_stage'], name='financial_i_portfol_2ddd4c_idx'),
        ),
        migrations.AddIndex(
            model_name='portfoliosignal',
            index=models.Index(fields=['portfolio_entity', 'signal_type', 'status'], name='financial_i_portfol_3a958f_idx'),
        ),
        migrations.AddIndex(
            model_name='opportunityfeeditem',
            index=models.Index(fields=['institutional_account', 'occurred_at'], name='financial_i_institu_d625df_idx'),
        ),
        migrations.AddIndex(
            model_name='advisoryopportunity',
            index=models.Index(fields=['portfolio_entity', 'status'], name='financial_i_portfol_0386ba_idx'),
        ),
    ]
