# Generated by Django 5.2.14 on 2026-07-06 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_intelligence_cloud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisoryopportunity',
            name='human_approved',
            field=models.BooleanField(blank=True, default=None, help_text='Explicit human sign-off, read by services/human_approval_gate.py — never inferred.', null=True),
        ),
    ]
