# Generated by Django 5.2.14 on 2026-09-14 22:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_intelligence_cloud', '0002_advisoryopportunity_human_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('code', models.SlugField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('default_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='GBP', max_length=10)),
                ('frequency', models.CharField(choices=[('one_off', 'One-off'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annual', 'Annual')], default='annual', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institutional_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_services', to='financial_intelligence_cloud.institutionalaccount')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('waiting_client', 'Waiting for client'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=20)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('next_due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('agreed_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='GBP', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_engagements', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_engagements', to='financial_intelligence_cloud.portfolioentity')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_engagements', to='financial_intelligence_cloud.accountingservice')),
            ],
            options={
                'ordering': ['next_due_date', 'client__name'],
            },
        ),
        migrations.CreateModel(
            name='ClientReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('notes', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('snoozed', 'Snoozed'), ('done', 'Done'), ('dismissed', 'Dismissed')], default='open', max_length=12)),
                ('snoozed_until', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_reminders', to='financial_intelligence_cloud.portfolioentity')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_reminders', to=settings.AUTH_USER_MODEL)),
                ('client_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='financial_intelligence_cloud.clientservice')),
            ],
            options={
                'ordering': ['due_at'],
            },
        ),
        migrations.CreateModel(
            name='ClientPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('currency', models.CharField(default='GBP', max_length=10)),
                ('due_date', models.DateField(db_index=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=80)),
                ('reference', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('due', 'Due'), ('part_paid', 'Part paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('waived', 'Waived')], default='due', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='financial_intelligence_cloud.clientservice')),
            ],
            options={
                'ordering': ['due_date', 'client_service__client__name'],
            },
        ),
        migrations.CreateModel(
            name='AccountingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('summary', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_activity', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_activity', to='financial_intelligence_cloud.portfolioentity')),
                ('institutional_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_activity', to='financial_intelligence_cloud.institutionalaccount')),
                ('client_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity', to='financial_intelligence_cloud.clientservice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='accountingservice',
            constraint=models.UniqueConstraint(fields=('institutional_account', 'code'), name='unique_accounting_service_code_per_firm'),
        ),
        migrations.AddIndex(
            model_name='clientservice',
            index=models.Index(fields=['status', 'next_due_date'], name='financial_i_status_5e86af_idx'),
        ),
        migrations.AddIndex(
            model_name='clientservice',
            index=models.Index(fields=['assigned_to', 'status'], name='financial_i_assigne_1b182e_idx'),
        ),
        migrations.AddIndex(
            model_name='clientreminder',
            index=models.Index(fields=['status', 'due_at'], name='financial_i_status_d4eeba_idx'),
        ),
        migrations.AddIndex(
            model_name='clientreminder',
            index=models.Index(fields=['owner', 'status'], name='financial_i_owner_i_01a2fc_idx'),
        ),
        migrations.AddIndex(
            model_name='clientpayment',
            index=models.Index(fields=['status', 'due_date'], name='financial_i_status_f8add2_idx'),
        ),
        migrations.AddIndex(
            model_name='accountingactivity',
            index=models.Index(fields=['institutional_account', 'created_at'], name='financial_i_institu_be950e_idx'),
        ),
    ]
