# Generated by Django 5.2.14 on 2026-09-14 22:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_intelligence_cloud', '0003_accountingservice_clientservice_clientreminder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clientreminder',
            constraint=models.CheckConstraint(condition=models.Q(('client__isnull', False), ('client_service__isnull', False), _connector='OR'), name='accounting_reminder_has_client_or_service'),
        ),
    ]
