# Generated by Django 5.2.14 on 2026-07-08 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0003_update_focus_country_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('city', 'City / Reference Point'), ('company_office', 'Company Office'), ('factory', 'Factory'), ('power_plant', 'Power Plant'), ('cold_store', 'Cold Store'), ('heating_unit', 'Heating Unit'), ('stewardship_site', 'Stewardship Site'), ('other', 'Other')], default='other', max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('city', models.CharField(blank=True, max_length=150)),
                ('region', models.CharField(blank=True, max_length=150)),
                ('sector', models.CharField(blank=True, max_length=150)),
                ('climate_exposure_score', models.FloatField(blank=True, null=True)),
                ('modernisation_priority', models.CharField(choices=[('not_assessed', 'Not Assessed'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='not_assessed', max_length=20)),
                ('source_reference', models.CharField(blank=True, max_length=200)),
                ('workbench_case_slug', models.CharField(blank=True, help_text='ai_agent_workbench demo-case slug this asset can be analysed with, if any.', max_length=100)),
                ('workbench_agent_slug', models.CharField(blank=True, max_length=100)),
                ('is_demo', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_assets', to='countries.countryprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GeoRiskZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('risk_type', models.CharField(choices=[('extreme_heat', 'Extreme Heat'), ('flood', 'Flood'), ('drought', 'Drought'), ('water_stress', 'Water Stress'), ('infrastructure_exposure', 'Infrastructure Exposure')], max_length=30)),
                ('region', models.CharField(blank=True, max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('radius_km', models.FloatField(default=25.0)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, help_text='e.g. "Meteostat historical analysis"', max_length=200)),
                ('is_demo', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_risk_zones', to='countries.countryprofile')),
            ],
            options={
                'ordering': ['-severity', 'name'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentGeoOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('region', models.CharField(blank=True, max_length=150)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('opportunity_type', models.CharField(choices=[('modernisation', 'Modernisation'), ('renewable_energy', 'Renewable Energy'), ('grid_upgrade', 'Grid Upgrade'), ('cold_chain', 'Cold Chain'), ('heating_replacement', 'Heating Replacement'), ('other', 'Other')], default='other', max_length=30)),
                ('estimated_impact', models.CharField(blank=True, max_length=200)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('investment_score', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('recommended_action', models.CharField(blank=True, max_length=200)),
                ('source_reference', models.CharField(blank=True, max_length=200)),
                ('workbench_case_slug', models.CharField(blank=True, max_length=100)),
                ('workbench_agent_slug', models.CharField(blank=True, max_length=100)),
                ('is_demo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='geo_opportunities', to='countries.countryprofile')),
            ],
            options={
                'ordering': ['-investment_score'],
            },
        ),
    ]
