# Generated by Django 5.2.14 on 2026-07-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geoasset',
            name='asset_type',
            field=models.CharField(choices=[('city', 'City / Reference Point'), ('company_office', 'Company Office'), ('factory', 'Factory'), ('power_plant', 'Power Plant'), ('cold_store', 'Cold Store'), ('heating_unit', 'Heating Unit'), ('stewardship_site', 'Stewardship Site'), ('gold_deposit', 'Gold Deposit'), ('active_mine', 'Active Mine'), ('processing_plant', 'Processing Plant'), ('exploration_licence', 'Exploration Licence'), ('transport_hub', 'Transport Hub'), ('rail', 'Rail'), ('road', 'Road'), ('airport', 'Airport'), ('water_source', 'Water Source'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
