# Generated by Django 5.2.14 on 2026-05-23 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=255)),
                ('sector', models.CharField(choices=[('manufacturing', 'Manufacturing (General)'), ('automotive', 'Automotive'), ('food', 'Food & Beverage'), ('chemicals', 'Chemicals & Petrochemicals'), ('metals', 'Metals & Mining'), ('oil_gas', 'Oil & Gas / Refining'), ('utilities', 'Utilities / Energy'), ('pharma', 'Pharmaceuticals'), ('other', 'Other Heavy Industry')], default='manufacturing', max_length=50)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('facility_age', models.PositiveIntegerField(blank=True, help_text='Years since facility was built', null=True)),
                ('headcount', models.PositiveIntegerField(blank=True, null=True)),
                ('annual_revenue', models.BigIntegerField(blank=True, help_text='USD, optional — used to scale ROI estimates', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('processing', 'Processing'), ('complete', 'Complete'), ('error', 'Error')], default='draft', max_length=20)),
                ('uploaded_file', models.FileField(blank=True, null=True, upload_to='audit_uploads/')),
                ('extracted_text', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('overall_efficiency_score', models.IntegerField(default=0)),
                ('modernization_score', models.IntegerField(default=0)),
                ('total_savings_potential', models.BigIntegerField(default=0)),
                ('total_investment_required', models.BigIntegerField(default=0)),
                ('blended_roi_months', models.IntegerField(default=0)),
                ('executive_summary', models.TextField(blank=True)),
                ('current_state_summary', models.TextField(blank=True)),
                ('future_state_summary', models.TextField(blank=True)),
                ('before_after', models.JSONField(default=dict)),
                ('raw_ai_response', models.TextField(blank=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='audit.auditsession')),
            ],
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.PositiveSmallIntegerField()),
                ('label', models.CharField(max_length=100)),
                ('items', models.JSONField(default=list)),
                ('investment', models.BigIntegerField(default=0)),
                ('savings', models.BigIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_phases', to='audit.auditsession')),
            ],
            options={
                'ordering': ['phase'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(choices=[('energy', 'Energy'), ('production', 'Production'), ('maintenance', 'Maintenance'), ('safety', 'Safety'), ('infrastructure', 'Infrastructure'), ('quality', 'Quality'), ('workforce', 'Workforce')], max_length=30)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('loss_usd', models.BigIntegerField(default=0, help_text='Estimated annual loss in USD')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audit.auditsession')),
            ],
            options={
                'ordering': ['-loss_usd'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20)),
                ('category', models.CharField(choices=[('energy', 'Energy'), ('production', 'Production'), ('maintenance', 'Maintenance'), ('safety', 'Safety'), ('infrastructure', 'Infrastructure'), ('quality', 'Quality'), ('workforce', 'Workforce')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('implementation', models.TextField(blank=True, help_text='Step-by-step implementation guidance')),
                ('savings_usd', models.BigIntegerField(default=0, help_text='Estimated annual savings in USD')),
                ('cost_usd', models.BigIntegerField(default=0, help_text='Estimated one-time implementation cost in USD')),
                ('roi_months', models.PositiveIntegerField(default=0, help_text='Payback period in months')),
                ('complexity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('is_quick_win', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='audit.auditsession')),
            ],
            options={
                'ordering': ['order', '-savings_usd'],
            },
        ),
        migrations.CreateModel(
            name='AuditResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=100)),
                ('question_text', models.TextField()),
                ('answer', models.TextField(blank=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='audit.auditsession')),
            ],
            options={
                'ordering': ['question_key'],
                'unique_together': {('session', 'question_key')},
            },
        ),
    ]
