# Generated by Django 5.2.14 on 2026-05-24 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_finding_detail_report_projections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditsession',
            name='sector',
            field=models.CharField(choices=[('manufacturing', 'Manufacturing (General)'), ('automotive', 'Automotive'), ('food', 'Food & Beverage'), ('chemicals', 'Chemicals & Petrochemicals'), ('metals', 'Metals & Mining'), ('oil_gas', 'Oil & Gas / Refining'), ('utilities', 'Utilities / Energy'), ('pharma', 'Pharmaceuticals'), ('logistics', 'Logistics & Warehousing'), ('other', 'Other Heavy Industry')], default='manufacturing', max_length=50),
        ),
        migrations.AlterField(
            model_name='finding',
            name='efficiency_gain_pct',
            field=models.IntegerField(default=0, help_text='Estimated efficiency improvement if addressed (%)'),
        ),
    ]
