# Generated by Django 5.2.14 on 2026-05-24 21:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_add_logistics_sector_helptext'),
        ('league', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysisJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='ai_analysis/%Y/%m/')),
                ('original_filename', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('model_used', models.CharField(blank=True, max_length=100)),
                ('pages_analyzed', models.IntegerField(default=0)),
                ('chars_analyzed', models.IntegerField(default=0)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('detected_company_name', models.CharField(blank=True, max_length=255)),
                ('detected_doc_type', models.CharField(blank=True, max_length=50)),
                ('detected_year', models.IntegerField(blank=True, null=True)),
                ('executive_summary', models.TextField(blank=True)),
                ('data_quality_notes', models.TextField(blank=True)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('analyst_notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(blank=True, help_text='Link to an existing company record (optional — can be set post-analysis)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to='league.company')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Analysis Job',
                'verbose_name_plural': 'AI Analysis Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_type', models.CharField(choices=[('co2_metric', 'CO₂ Metric'), ('methane_metric', 'Methane Metric'), ('pm25_metric', 'PM2.5 Metric'), ('so2_metric', 'SO₂ Metric'), ('nox_metric', 'NOₓ Metric'), ('water_metric', 'Water Metric'), ('waste_metric', 'Waste Metric'), ('pollution_other', 'Pollution — Other'), ('investment', 'Environmental Investment'), ('project', 'Environmental Project'), ('coal_replacement', 'Coal Replacement Initiative'), ('greenwashing', 'Greenwashing Signal'), ('transparency', 'Transparency Indicator'), ('recommendation', 'AI Recommendation'), ('other', 'Other Finding')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('numeric_value', models.FloatField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('source_quote', models.TextField(blank=True, help_text='Exact verbatim text from the document where this was found')),
                ('source_location', models.CharField(blank=True, help_text='Page number or section reference', max_length=200)),
                ('confidence_score', models.FloatField(default=0.5, help_text='AI confidence 0.0 (low) → 1.0 (high)')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('applied', 'Applied to Company')], default='pending', max_length=20)),
                ('analyst_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audit.aianalysisjob')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_ai_findings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Finding',
                'verbose_name_plural': 'AI Findings',
                'ordering': ['-confidence_score', 'finding_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AIScoreEstimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_pollution', models.IntegerField(blank=True, null=True)),
                ('est_reduction', models.IntegerField(blank=True, null=True)),
                ('est_investment', models.IntegerField(blank=True, null=True)),
                ('est_transparency', models.IntegerField(blank=True, null=True)),
                ('est_community', models.IntegerField(blank=True, null=True)),
                ('est_ecoiq', models.FloatField(blank=True, null=True)),
                ('confidence', models.FloatField(default=0.0, help_text='Overall scoring confidence 0.0–1.0')),
                ('reasoning', models.TextField(blank=True, help_text='AI explanation for each pillar score')),
                ('data_gaps', models.JSONField(default=list, help_text='List of missing data points')),
                ('greenwashing_level', models.CharField(blank=True, choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], max_length=20)),
                ('greenwashing_score', models.IntegerField(blank=True, help_text='0=clean, 100=critical greenwashing', null=True)),
                ('greenwashing_signals', models.JSONField(default=list)),
                ('greenwashing_verdict', models.TextField(blank=True)),
                ('approved', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('analyst_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_score_estimates', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score_estimate', to='audit.aianalysisjob')),
            ],
            options={
                'verbose_name': 'AI Score Estimate',
                'verbose_name_plural': 'AI Score Estimates',
            },
        ),
    ]
