# Generated by Django 5.2.14 on 2026-08-03 22:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Adds AuditSession.created_by so audit sessions and the documents uploaded
    to them can be scoped to their owner.

    Additive and reversible: one nullable FK, SET_NULL, no data migration.

    LEGACY ROWS — deliberately NOT backfilled. AuditSession has never stored a
    user reference, and none of its related models (AuditReport, AuditResponse,
    Finding, Recommendation, ActionPlan) carry one either, so the owner of a
    pre-existing row is not recoverable from the data. Backfilling would mean
    inventing ownership. Those rows keep created_by=NULL and are visible to
    staff only (audit.views._audit_sessions_visible_to) — they fail closed for
    regular users and never appear in a non-staff list.
    """

    dependencies = [
        ('audit', '0004_ai_findings_engine'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditsession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
