# Generated by Django 5.2.14 on 2026-08-25 10:37

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_auditsession_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysisjob',
            name='pdf_file',
            field=models.FileField(upload_to=core.storage.upload_to_ai_analysis),
        ),
        migrations.AlterField(
            model_name='auditsession',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=core.storage.upload_to_audit),
        ),
    ]
