# Generated by Django 5.2.14 on 2026-08-26 09:31

import core.storage
import core.upload_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0006_alter_aianalysisjob_pdf_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditsession',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=core.storage.upload_to_audit, validators=[core.upload_validation.UploadValidator()]),
        ),
    ]
