# Generated by Django 5.2.14 on 2026-07-31 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('fixed', 'Fixed Amount')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percent (0-100) or fixed amount', max_digits=8)),
                ('currency', models.CharField(blank=True, help_text='Only used when discount_type=fixed', max_length=8)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, null=True)),
                ('redeemed_count', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('company_data', 'Company Data'), ('portfolio', 'Portfolio Intelligence'), ('screening', 'Ethical / Islamic Screening'), ('api', 'API Access'), ('reports', 'Research & Reports'), ('marketplace', 'Project Marketplace'), ('academy', 'Academy')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('billing_email', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('one_time', 'One-Time'), ('usage', 'Usage-Based'), ('custom', 'Custom / Contact Sales')], default='monthly', max_length=10)),
                ('price_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Null = "Contact Sales" / custom enterprise pricing', max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('trial_days', models.PositiveIntegerField(default=0)),
                ('is_public', models.BooleanField(default=True, help_text='Shown on /products/ and self-serve signup')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('api_tier', models.CharField(blank=True, help_text='Matches api.APIKey TIER_CHOICES (explorer/professional/enterprise)', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['product', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('product_type', models.CharField(choices=[('data_api', 'EcoIQ Data API'), ('lite', 'EcoIQ Lite'), ('professional', 'EcoIQ Professional'), ('marketplace', 'EcoIQ Project Marketplace'), ('academy', 'EcoIQ Academy'), ('research', 'EcoIQ Research')], max_length=20)),
                ('name', models.CharField(max_length=150)),
                ('tagline', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('target_audience', models.TextField(blank=True, help_text='Who this product is for — shown on /products/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('coming_soon', 'Coming Soon'), ('disabled', 'Disabled')], default='coming_soon', max_length=15)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BillingCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('none', 'No Provider (Manual)'), ('stripe', 'Stripe')], default='none', max_length=10)),
                ('external_customer_id', models.CharField(blank=True, max_length=120)),
                ('default_currency', models.CharField(default='USD', max_length=8)),
                ('tax_id', models.CharField(blank=True, help_text='VAT/GST/Tax ID, when applicable', max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_customer', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing_customer', to='ecoiq_commerce.organisation')),
            ],
        ),
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=150)),
                ('extra_quantity', models.PositiveIntegerField(help_text='Additional quantity granted per period on top of the plan limit')),
                ('price_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('one_time', 'One-Time'), ('usage', 'Usage-Based'), ('custom', 'Custom / Contact Sales')], default='monthly', max_length=10)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='ecoiq_commerce.feature')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=250)),
                ('amount_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('paid', 'Paid'), ('void', 'Void'), ('uncollectible', 'Uncollectible')], default='draft', max_length=15)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='ecoiq_commerce.billingcustomer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='ecoiq_commerce.invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Entitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_quantity', models.PositiveIntegerField(blank=True, help_text='Null = unlimited', null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_entitlements', to=settings.AUTH_USER_MODEL)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_entitlements', to='ecoiq_commerce.feature')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_entitlements', to='ecoiq_commerce.organisation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganisationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=10)),
                ('seats', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='ecoiq_commerce.organisation')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organisation_subscriptions', to='ecoiq_commerce.plan')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='organisation_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='ecoiq_commerce.organisationsubscription'),
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], max_length=10)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('failure_reason', models.CharField(blank=True, max_length=250)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_events', to='ecoiq_commerce.invoice')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='ecoiq_commerce.product'),
        ),
        migrations.CreateModel(
            name='LicenceAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_type', models.CharField(choices=[('standard', 'Standard'), ('enterprise', 'Enterprise'), ('white_label', 'White-Label'), ('api_data', 'API Data Licence')], default='standard', max_length=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated')], default='draft', max_length=12)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('geographical_scope', models.JSONField(blank=True, default=list, help_text='List of country codes, or [] = worldwide')),
                ('data_modules', models.JSONField(blank=True, default=list, help_text='Which data modules are licensed')),
                ('white_label_allowed', models.BooleanField(default=False)),
                ('requires_legal_review', models.BooleanField(default=True, help_text='Must be explicitly cleared by a human reviewer before this licence can move to active status if it involves white-labelling, resale, or transaction-related terms.')),
                ('legal_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('signed_by', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licence_agreements', to='ecoiq_commerce.organisation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licence_agreements', to='ecoiq_commerce.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trialing', 'Trialing'), ('active', 'Active'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='ecoiq_commerce.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='ecoiq_commerce.subscription'),
        ),
        migrations.CreateModel(
            name='SubscriptionAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_addons', to='ecoiq_commerce.addon')),
                ('organisation_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='ecoiq_commerce.organisationsubscription')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='ecoiq_commerce.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='UsageLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_value', models.PositiveIntegerField(blank=True, help_text='Null = unlimited', null=True)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('unlimited', 'Unlimited')], default='monthly', max_length=10)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_limit_overrides', to='ecoiq_commerce.feature')),
                ('organisation_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_limit_overrides', to='ecoiq_commerce.organisationsubscription')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_limit_overrides', to='ecoiq_commerce.subscription')),
            ],
            options={
                'ordering': ['feature'],
            },
        ),
        migrations.CreateModel(
            name='OrganisationMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('billing', 'Billing Contact'), ('member', 'Member')], default='member', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='ecoiq_commerce.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['organisation', 'role'],
                'unique_together': {('organisation', 'user')},
            },
        ),
        migrations.CreateModel(
            name='PlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_included', models.BooleanField(default=True)),
                ('quantity_limit', models.PositiveIntegerField(blank=True, help_text='Null = unlimited (when is_included and limit_period=unlimited)', null=True)),
                ('limit_period', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual'), ('unlimited', 'Unlimited')], default='unlimited', max_length=10)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='ecoiq_commerce.feature')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='ecoiq_commerce.plan')),
            ],
            options={
                'ordering': ['plan', 'feature'],
                'unique_together': {('plan', 'feature')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='plan',
            unique_together={('product', 'key')},
        ),
        migrations.CreateModel(
            name='CommercialEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('trial_started', 'Trial Started'), ('subscription_started', 'Subscription Started'), ('subscription_upgraded', 'Subscription Upgraded'), ('subscription_cancelled', 'Subscription Cancelled'), ('report_viewed', 'Report Viewed'), ('report_purchased', 'Report Purchased'), ('course_enrolled', 'Course Enrolled'), ('course_completed', 'Course Completed'), ('api_key_created', 'Api Key Created'), ('api_key_revoked', 'Api Key Revoked'), ('api_limit_reached', 'Api Limit Reached'), ('project_submitted', 'Project Submitted'), ('investor_interest_created', 'Investor Interest Created'), ('introduction_approved', 'Introduction Approved')], max_length=40)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_events', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commercial_events', to='ecoiq_commerce.organisation')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ecoiq_commerce.plan')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='ecoiq_commerce.product')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['event_type', 'occurred_at'], name='ecoiq_comme_event_t_de0721_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('used_quantity', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='ecoiq_commerce.feature')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='ecoiq_commerce.organisation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_start'],
                'indexes': [models.Index(fields=['user', 'feature', 'period_start'], name='ecoiq_comme_user_id_929f9d_idx')],
            },
        ),
    ]
