# Generated by Django 5.2.14 on 2026-07-31 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoiq_commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='requires_legal_review',
            field=models.BooleanField(default=False, help_text='Set True for any plan whose commercial terms involve transaction-based fees (success fees, % introduction fees, etc.) — such a plan must never be sold or activated for real customers until legal/compliance review clears it. See PART 2.'),
        ),
    ]
