"""
Stripe billing integration.

Additive only: new nullable/blank columns on existing tables plus three new
tables. No column is dropped or retyped, so this applies cleanly to a database
carrying existing subscription and invoice rows, and reverses without data
loss.
"""
# Generated by Django 5.2.14 on 2026-08-05 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoiq_commerce', '0002_plan_requires_legal_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='scope',
            field=models.CharField(choices=[('manual', 'Manual / invoiced billing only')], default='manual', help_text='Manual/invoiced billing only. Stripe Checkout uses Stripe promotion codes — create those in the Stripe Dashboard.', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='external_invoice_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='invoice',
            name='hosted_invoice_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='organisationsubscription',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='organisationsubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='plan',
            name='stripe_price_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe Price id (price_…) — public identifier, never a secret', max_length=120),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='billingcustomer',
            name='external_customer_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.CreateModel(
            name='StripeCheckoutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=200, unique=True)),
                ('mode', models.CharField(choices=[('subscription', 'Subscription'), ('payment', 'One-Time Payment')], max_length=12)),
                ('status', models.CharField(choices=[('created', 'Created'), ('completed', 'Completed'), ('expired', 'Expired')], default='created', max_length=10)),
                ('stripe_price_id', models.CharField(blank=True, max_length=120)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=120)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=120)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=120)),
                ('amount_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('access_granted', models.BooleanField(default=False, help_text='Set only by the verified webhook handler — never by the browser success redirect.')),
                ('revocation_reason', models.CharField(blank=True, choices=[('refund', 'Refunded'), ('dispute', 'Disputed')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stripe_checkouts', to='ecoiq_commerce.organisation')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_checkouts', to='ecoiq_commerce.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stripe_checkouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispute_id', models.CharField(max_length=120, unique=True)),
                ('charge_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('payment_intent_id', models.CharField(blank=True, db_index=True, max_length=120)),
                ('status', models.CharField(choices=[('open', 'Open — funds withheld'), ('won', 'Won — funds returned to EcoIQ'), ('lost', 'Lost — funds returned to the cardholder')], default='open', max_length=6)),
                ('reason', models.CharField(blank=True, max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(blank=True, max_length=8)),
                ('previous_subscription_status', models.CharField(blank=True, max_length=10)),
                ('access_suspended', models.BooleanField(default=False)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('checkout_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='ecoiq_commerce.stripecheckoutrecord')),
                ('organisation_subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='ecoiq_commerce.organisationsubscription')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='ecoiq_commerce.subscription')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_event_id', models.CharField(max_length=120, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('api_version', models.CharField(blank=True, max_length=40)),
                ('livemode', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='received', max_length=10)),
                ('payload_summary', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['event_type', 'received_at'], name='ecoiq_comme_event_t_1c79ad_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stripecheckoutrecord',
            index=models.Index(fields=['user', 'created_at'], name='ecoiq_comme_user_id_72e0ad_idx'),
        ),
    ]
