"""
Links a chargeback back to what it suspended.

Invoice.external_payment_intent_id is the trail from a dispute (which carries
only a charge and a payment_intent) to the subscription it paid for.
StripeDispute.suspended_to_status records the state this dispute moved the
subscription into, so restoration can confirm nothing else changed it since.
"""
# Generated by Django 5.2.14 on 2026-08-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoiq_commerce', '0003_stripe_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='external_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='stripedispute',
            name='suspended_to_status',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
