# Generated by Django 5.2.14 on 2026-05-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='harm_penalty',
            field=models.FloatField(default=0.0, help_text='Points deducted for pollution/harm (0-30)'),
        ),
    ]
