# Generated by Django 5.2.14 on 2026-05-30 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_companyscoresnapshot'),
        ('league', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataIngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('companies_house', 'Companies House UK'), ('sec_edgar', 'SEC EDGAR US'), ('cdp', 'CDP Climate Disclosure'), ('yfinance', 'Yahoo Finance / Bloomberg'), ('rss', 'Regulatory RSS Feed'), ('manual', 'Manual Admin Entry')], max_length=30)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('fields_updated', models.JSONField(blank=True, default=list)),
                ('success', models.BooleanField(default=True)),
                ('error_msg', models.TextField(blank=True)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_logs', to='league.company')),
            ],
            options={
                'verbose_name': 'Data Ingestion Log',
                'verbose_name_plural': 'Data Ingestion Logs',
                'ordering': ['-ingested_at'],
            },
        ),
    ]
