# Generated by Django 5.2.14 on 2026-07-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_dataingestionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyscoresnapshot',
            name='trigger',
            field=models.CharField(choices=[('manual', 'Manual (Admin)'), ('annual_review', 'Annual Review'), ('report_update', 'New Report / Evidence'), ('verification', 'Profile Verification'), ('transition', 'Transition Milestone'), ('seed', 'Initial Seed Score'), ('background_refresh', 'Automated Background Refresh')], default='manual', max_length=30),
        ),
    ]
