# Generated by Django 5.2.14 on 2026-07-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_alter_companyscoresnapshot_trigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyscoresnapshot',
            name='climate_risk_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyscoresnapshot',
            name='evidence_quality_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyscoresnapshot',
            name='geo_exposure_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyscoresnapshot',
            name='intelligence_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyscoresnapshot',
            name='intelligence_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyscoresnapshot',
            name='intelligence_score_explanation',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='companyscoresnapshot',
            name='investment_opportunity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='companyscoresnapshot',
            name='modernisation_priority_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
