# Generated by Django 5.2.14 on 2026-07-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_companyscoresnapshot_climate_risk_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='last_refresh_at',
            field=models.DateTimeField(blank=True, help_text='When refresh_company_intelligence() last completed (any status).', null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='last_source_discovery_at',
            field=models.DateTimeField(blank=True, help_text='When discover_sources_for_company() last ran for this company.', null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='next_refresh_due_at',
            field=models.DateTimeField(blank=True, help_text="Computed by services/refresh_policy.py from this company's registered sources' own refresh intervals — null when no source is registered yet (nothing to schedule).", null=True),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='tracking_status',
            field=models.CharField(choices=[('not_tracked', 'Not Tracked'), ('active', 'Active'), ('refresh_in_progress', 'Refresh In Progress'), ('paused', 'Paused'), ('error', 'Error — Last Refresh Failed')], default='not_tracked', help_text='Process-level lifecycle only — see TRACKING_STATUS_CHOICES docstring above for why the richer operational states are computed live, never stored here.', max_length=20),
        ),
    ]
