# Generated by Django 5.2.14 on 2026-07-30 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        # Renumbered 0007 -> 0008 during recovery: main had already shipped its
        # own 0007 (companyprofile_last_refresh_at_and_more) while this work sat
        # unmerged locally. Only the number and this dependency changed — the
        # operations below are byte-identical to the original.
        ('companies', '0007_companyprofile_last_refresh_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentRelevanceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(help_text='1-based, incremented per company on each generation')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('reviewed', 'Reviewed'), ('published', 'Published')], default='draft', max_length=10)),
                ('classification', models.CharField(choices=[('lower_exposure', 'Lower Identified Exposure'), ('moderate_exposure', 'Moderate Identified Exposure'), ('elevated_exposure', 'Elevated Identified Exposure'), ('high_exposure', 'High Identified Exposure'), ('insufficient_evidence', 'Insufficient Evidence')], max_length=25)),
                ('content', models.JSONField(blank=True, default=dict)),
                ('source_snapshot', models.JSONField(blank=True, default=dict, help_text='Copy of the EcoIQ scores/fields the report was generated from, for audit')),
                ('model_name', models.CharField(blank=True, max_length=80)),
                ('model_provider', models.CharField(blank=True, help_text='Provider selected by agent_runtime_model_router for this generation', max_length=30)),
                ('routing_reason', models.TextField(blank=True, help_text='Why the model router selected this provider/model')),
                ('prompt_version', models.CharField(default='v1', max_length=20)),
                ('methodology_version', models.CharField(default='v1', max_length=20)),
                ('prohibited_language_flags', models.JSONField(blank=True, default=list, help_text='Findings from the prohibited-recommendation-language check; must be empty to publish')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_reports', to='companies.companyprofile')),
                ('generated_by', models.ForeignKey(blank=True, help_text='Admin/analyst who triggered generation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investment Relevance Report',
                'verbose_name_plural': 'Investment Relevance Reports',
                'ordering': ['-version'],
                'unique_together': {('company', 'version')},
            },
        ),
    ]
