# Generated by Django 5.2.14 on 2026-08-20 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0008_investmentrelevancereport'),
        ('evidence_memory', '0004_backfill_access_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyMetricProvenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_key', models.CharField(help_text='CompanyProfile field name. Validated against companies.evidence.MATERIAL_INPUTS on save — a typo is rejected rather than becoming a silently orphaned row.', max_length=60)),
                ('origin', models.CharField(help_text='One of companies.evidence.PROVENANCE_CHOICES. No default: a value whose origin nobody stated must not silently become MEASURED, which is the strongest claim in the vocabulary.', max_length=30)),
                ('source_quality', models.CharField(blank=True, help_text='Optional analyst override for cases with no EvidenceMemory row. Where evidence IS linked, its own source_type and review_tier are authoritative and this stays blank.', max_length=20)),
                ('confidence', models.FloatField(blank=True, help_text='0-100. NULL means unknown confidence — never fabricated, and never 50. A genuine 0.0 stays distinguishable from unknown.', null=True)),
                ('methodology', models.TextField(blank=True, help_text='How the value was produced. Expected for ESTIMATED, MODELLED and INFERRED, where the number is only as defensible as the method behind it.')),
                ('calculation_version', models.CharField(blank=True, help_text='Version of the model or formula that produced a MODELLED or ESTIMATED value, so a later change is attributable.', max_length=30)),
                ('observed_at', models.DateTimeField(blank=True, help_text='When the underlying observation was made — distinct from created_at, which is when EcoIQ recorded it.', null=True)),
                ('review_status', models.CharField(default='proposed', help_text="Reuses company_intelligence.CompanyKPIEvidenceLink's review vocabulary rather than inventing a sixth. Independent of origin: MEASURED is not auto-reviewed, and MODELLED is not auto-distrusted.", max_length=25)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_current', models.BooleanField(default=True, help_text='Exactly one current row per company+metric, enforced by a partial unique constraint. Superseded rows stay for audit.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('written_by', models.CharField(blank=True, help_text="Machine writer that created this row (e.g. 'seed_companies', 'ingest_sec_edgar', 'companies.scoring'). Populated by D3C.", max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_provenance', to='companies.companyprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('evidence', models.ForeignKey(blank=True, help_text='SET_NULL rather than CASCADE: losing the evidence record must not erase the fact that this value once had a stated origin. The row survives and says so.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_provenance', to='evidence_memory.evidencememory')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Metric Provenance',
                'verbose_name_plural': 'Company Metric Provenance',
                'ordering': ['metric_key', '-created_at'],
                'indexes': [models.Index(fields=['company', 'metric_key'], name='companies_prov_company_metric')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('company', 'metric_key'), name='companies_unique_current_metric_provenance')],
            },
        ),
    ]
