# Generated by Django 5.2.14 on 2026-08-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_companymetricprovenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymetricprovenance',
            name='inputs',
            field=models.ManyToManyField(blank=True, help_text='The provenance rows this calculation consumed. Empty for material metrics, which have no inputs.', related_name='derived_from', to='companies.companymetricprovenance'),
        ),
        migrations.AddField(
            model_name='companymetricprovenance',
            name='recorded_value',
            field=models.FloatField(blank=True, help_text='The computed value, for ephemeral derived metrics only. Must be NULL for any metric whose value has a persisted home — that value is resolved through the registry instead.', null=True),
        ),
        migrations.AlterField(
            model_name='companymetricprovenance',
            name='metric_key',
            field=models.CharField(help_text='Registered metric key. Validated against companies.metric_registry on save — a typo is rejected rather than becoming a silently orphaned row. Material keys are bare CompanyProfile field names; derived keys are namespaced (ethics.nei, mizan.score).', max_length=60),
        ),
    ]
