# Generated by Django 5.2.14 on 2026-08-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0011_nullable_score_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='anti_corruption_score',
            field=models.FloatField(blank=True, help_text='0-100: anti-corruption practices', null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='audit_quality_score',
            field=models.FloatField(blank=True, help_text='0-100: audit standards and independence', null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='biodiversity_impact_score',
            field=models.FloatField(blank=True, help_text='0-100: impact on biodiversity and ecosystems', null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='controversy_risk_score',
            field=models.FloatField(blank=True, help_text='0-100: higher = more controversy risk', null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='digitalization_score',
            field=models.FloatField(blank=True, help_text='0-100: digital transformation maturity', null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='ecoiq_total_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='energy_transition_score',
            field=models.FloatField(blank=True, help_text='0-100: energy transition progress', null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='environmental_responsibility_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='ethical_alignment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='future_readiness_score',
            field=models.FloatField(blank=True, help_text='0-100: preparedness for future economy', null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='harm_penalty',
            field=models.FloatField(blank=True, help_text='Points deducted for pollution/harm (0-30)', null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='infrastructure_contribution_score',
            field=models.FloatField(blank=True, help_text='0-100: infrastructure contribution', null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='infrastructure_upgrade_score',
            field=models.FloatField(blank=True, help_text='0-100: physical infrastructure modernity', null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='jobs_created_score',
            field=models.FloatField(blank=True, help_text='0-100: quality and quantity of employment', null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='modernization_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='national_value_score',
            field=models.FloatField(blank=True, help_text='0-100: long-term national benefit', null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='procurement_transparency_score',
            field=models.FloatField(blank=True, help_text='0-100: procurement process openness', null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='profit_extraction_risk_score',
            field=models.FloatField(blank=True, help_text='0-100: risk indicator — higher = more concern', null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='profit_extraction_score',
            field=models.FloatField(blank=True, help_text='0-100: how much profit flows back to people vs. owners', null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='public_benefit_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='regional_development_score',
            field=models.FloatField(blank=True, help_text='0-100: contribution to regional economy', null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='transparency_anti_corruption_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='transparency_score_detail',
            field=models.FloatField(blank=True, help_text='0-100: reporting quality and openness', null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='waste_management_score',
            field=models.FloatField(blank=True, help_text='0-100: quality of waste management practices', null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='water_impact_score',
            field=models.FloatField(blank=True, help_text='0-100: water stewardship quality', null=True),
        ),
        migrations.AlterField(
            model_name='companyscoresnapshot',
            name='anti_corruption_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyscoresnapshot',
            name='environmental_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyscoresnapshot',
            name='ethical_alignment_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyscoresnapshot',
            name='governance_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyscoresnapshot',
            name='harm_penalty',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyscoresnapshot',
            name='modernization_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyscoresnapshot',
            name='public_benefit_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
