# Generated by Django 5.2.14 on 2026-08-25 10:37

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0012_remove_neutral_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyguidancevideo',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=core.storage.upload_to_guidance_thumbnail),
        ),
    ]
