# Generated by Django 5.2.14 on 2026-08-28 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0013_alter_companyguidancevideo_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('public', 'Public'), ('public_demo', 'Public — demonstration only'), ('verified', 'Verified'), ('archived', 'Archived')], default='public', max_length=15),
        ),
    ]
