# Generated by Django 5.2.14 on 2026-07-24 20:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('capability_graph', '0002_organisationcapability_declared_by_and_more'),
        ('good_agents', '0007_availableresource_declared_by_and_more'),
        ('partner_participation', '0002_alter_routingcandidate_status_networkactivityevent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('waiting_on_ecoiq', 'Waiting on EcoIQ'), ('waiting_on_partner', 'Waiting on partner'), ('waiting_on_evidence', 'Waiting on evidence'), ('next_step_proposed', 'Next step proposed'), ('next_step_agreed', 'Next step agreed'), ('promoted_to_action', 'Promoted to action'), ('promoted_to_project', 'Promoted to project'), ('closed', 'Closed'), ('archived', 'Archived')], default='open', max_length=24)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('close_reason', models.TextField(blank=True)),
                ('promoted_action_reference', models.CharField(blank=True, max_length=200)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('routing_candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_room', to='partner_participation.routingcandidate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InformationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('document', 'Document'), ('measurement', 'Measurement'), ('eligibility_evidence', 'Eligibility evidence'), ('technical_specification', 'Technical specification'), ('authority_confirmation', 'Authority confirmation'), ('resource_availability', 'Resource availability'), ('funding_terms', 'Funding terms'), ('timeline', 'Timeline'), ('other', 'Other')], default='other', max_length=32)),
                ('question_text', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('answered', 'Answered'), ('partially_answered', 'Partially answered'), ('needs_evidence', 'Needs evidence'), ('closed', 'Closed')], default='open', max_length=20)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('directed_to_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='information_requests_received', to='capability_graph.organisation')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requesting_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='capability_graph.organisation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information_requests', to='collaboration_rooms.collaborationroom')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NextStepProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_type', models.CharField(choices=[('technical_discussion', 'Schedule technical discussion'), ('share_dataset', 'Share missing dataset'), ('introduction', 'Make introduction'), ('verify_resource', 'Verify resource'), ('funding_eligibility_review', 'Review funding eligibility'), ('site_assessment', 'Conduct site assessment'), ('project_candidate', 'Create project candidate'), ('reject_close', 'Reject / close opportunity')], max_length=32)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('proposed', 'Proposed'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('needs_modification', 'Needs modification'), ('completed', 'Completed')], default='draft', max_length=20)),
                ('requires_ecoiq_consent', models.BooleanField(default=True)),
                ('promoted_reference', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_funding_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='good_agents.fundingmatch')),
                ('linked_resource_match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='good_agents.resourcematch')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposing_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='capability_graph.organisation')),
                ('required_organisations', models.ManyToManyField(blank=True, related_name='+', to='capability_graph.organisation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_step_proposals', to='collaboration_rooms.collaborationroom')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('room_created', 'Room created'), ('participant_added', 'Participant added'), ('participant_revoked', 'Participant revoked'), ('evidence_shared', 'Evidence shared'), ('evidence_verified', 'Evidence verified'), ('question_asked', 'Question asked'), ('answer_provided', 'Answer provided'), ('request_status_changed', 'Request status changed'), ('message_sent', 'Message sent'), ('next_step_proposed', 'Next step proposed'), ('consent_given', 'Consent given'), ('consent_rejected', 'Consent rejected'), ('next_step_agreed', 'Next step agreed'), ('action_created', 'Action created'), ('project_candidate_created', 'Project candidate created'), ('room_status_changed', 'Room status changed'), ('room_closed', 'Room closed'), ('stall_detected', 'Stall detected'), ('organisation_withdrew', 'Organisation withdrew'), ('ai_assistance_used', 'AI assistance used')], max_length=32)),
                ('source_object_reference', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='capability_graph.organisation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_events', to='collaboration_rooms.collaborationroom')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='capability_graph.organisation')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='collaboration_rooms.nextstepproposal')),
            ],
            options={
                'ordering': ['organisation_id'],
            },
        ),
        migrations.CreateModel(
            name='RoomEvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('existing_ecoiq_evidence', 'Existing EcoIQ evidence'), ('public_source_link', 'Public source link'), ('document', 'Document reference'), ('measurement', 'Measurement'), ('resource_information', 'Resource information'), ('funding_information', 'Funding information'), ('organisation_provided', 'Organisation-provided information'), ('other', 'Other')], default='other', max_length=32)),
                ('verification_state', models.CharField(choices=[('declared_claim', 'Declared claim — asserted by a participant, not yet verified'), ('linked_evidence', 'Linked evidence — points at a real external or EcoIQ source'), ('ecoiq_verified', 'EcoIQ verified — a real EcoIQ staff member confirmed this directly')], default='declared_claim', max_length=20)),
                ('visibility', models.CharField(choices=[('shared_with_room', 'Shared with all active room participants'), ('ecoiq_internal_only', 'EcoIQ internal only — never shown to any partner'), ('organisation_private', "Private to the sharing organisation's own members")], default='shared_with_room', max_length=24)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('source_url', models.URLField(blank=True, max_length=2000)),
                ('source_reference', models.CharField(blank=True, max_length=200)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='capability_graph.organisation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='collaboration_rooms.collaborationroom')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InformationRequestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='collaboration_rooms.informationrequest')),
                ('responded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('responding_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='capability_graph.organisation')),
                ('evidence_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='information_responses', to='collaboration_rooms.roomevidenceitem')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('visibility', models.CharField(choices=[('shared_with_room', 'Shared with all active room participants'), ('ecoiq_internal_only', 'EcoIQ internal only — never shown to any partner'), ('organisation_private', "Private to the sharing organisation's own members")], default='shared_with_room', max_length=24)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('edit_history', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='capability_graph.organisation')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='collaboration_rooms.collaborationroom')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('coordinator', 'Coordinator (EcoIQ staff)'), ('organisation_representative', 'Organisation representative'), ('expert', 'Approved expert'), ('observer', 'Observer')], default='observer', max_length=32)),
                ('reason', models.CharField(blank=True, help_text='Why this participant has access — never blank for a non-anchor participant.', max_length=255)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, max_length=255)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_participations', to='capability_graph.organisation')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='collaboration_rooms.collaborationroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['added_at'],
                'unique_together': {('room', 'user')},
            },
        ),
    ]
