# Generated by Django 5.2.14 on 2026-07-31 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='Stable client-generated device identifier', max_length=200)),
                ('device_name', models.CharField(blank=True, help_text='e.g. "Ali\'s iPhone 15"', max_length=200)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('windows', 'Windows'), ('other', 'Other')], default='other', max_length=10)),
                ('app_version', models.CharField(blank=True, max_length=30)),
                ('refresh_token_hash', models.CharField(max_length=64, unique=True)),
                ('previous_refresh_token_hash', models.CharField(blank=True, help_text="Prior rotation's hash, kept one generation to detect refresh-token reuse", max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(auto_now_add=True)),
                ('refresh_expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_reason', models.CharField(blank=True, choices=[('', 'Not revoked'), ('user_logout', 'User logged out'), ('logout_all_devices', 'User logged out of all devices'), ('refresh_token_reuse_detected', 'Refresh token reuse detected (possible theft)'), ('admin_revoked', 'Revoked by staff'), ('expired', 'Expired')], default='', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used_at'],
                'indexes': [models.Index(fields=['user', 'device_id'], name='mobile_auth_user_id_13bda3_idx')],
            },
        ),
    ]
