# Generated by Django 5.2.14 on 2026-07-06 17:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0003_update_focus_country_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='StewardshipProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_type', models.CharField(choices=[('coal_heating', 'Coal heating'), ('inefficient_heating', 'Inefficient heating'), ('heat_loss', 'Heat loss'), ('household_air_quality_risk', 'Household air quality risk'), ('energy_cost_burden', 'Energy cost burden'), ('trail_waste', 'Trail waste'), ('trail_erosion', 'Trail erosion'), ('damaged_trails', 'Damaged trails'), ('nature_degradation', 'Nature degradation'), ('water_pollution', 'Water pollution'), ('unsafe_access', 'Unsafe access'), ('unmanaged_tourism_impact', 'Unmanaged tourism impact'), ('food_surplus', 'Food surplus'), ('cold_chain_loss', 'Cold-chain loss'), ('food_waste', 'Meat/food waste'), ('community_need', 'Community need'), ('food_insecurity', 'Food insecurity'), ('underused_land', 'Underused land'), ('habitat_loss', 'Habitat loss'), ('biodiversity_risk', 'Biodiversity risk'), ('animal_welfare_concern', 'Animal welfare concern')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('evidence_quality', models.CharField(choices=[('strong', 'Strong'), ('medium', 'Medium'), ('weak', 'Weak'), ('missing', 'Missing')], default='medium', max_length=10)),
                ('urgency_score', models.FloatField(default=50.0)),
                ('harm_score', models.FloatField(default=50.0)),
                ('confidence', models.FloatField(default=50.0)),
                ('status', models.CharField(choices=[('nominated', 'Nominated'), ('evidence_collected', 'Evidence Collected'), ('under_review', 'Under Review'), ('resolved', 'Resolved')], default='nominated', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-urgency_score'],
            },
        ),
        migrations.CreateModel(
            name='StewardshipIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('intervention_type', models.CharField(choices=[('clean_heating_upgrade', 'Clean heating upgrade'), ('insulation_support', 'Insulation support'), ('boiler_heat_pump_assessment', 'Boiler / heat pump / electric backup assessment'), ('smart_controls', 'Smart controls'), ('safety_review', 'Safety review'), ('guided_cleanup', 'Guided cleanup'), ('erosion_control_support', 'Erosion control support'), ('habitat_protection', 'Habitat protection'), ('ranger_expert_review', 'Local ranger / expert review'), ('shoreline_cleanup', 'Shoreline cleanup'), ('waste_mapping', 'Waste mapping'), ('water_stewardship', 'Water stewardship'), ('community_awareness', 'Community awareness'), ('monitoring', 'Monitoring'), ('surplus_prediction', 'Surplus prediction'), ('safe_redistribution', 'Safe redistribution where lawful'), ('cold_chain_support', 'Cold-chain support'), ('community_kitchen_support', 'Community kitchen / food-bank support'), ('waste_to_value_routing', 'Waste-to-value routing'), ('greenhouse_materials', 'Greenhouse materials'), ('irrigation_support', 'Irrigation support'), ('local_operator_setup', 'Local operator setup'), ('training', 'Training'), ('production_monitoring', 'Production monitoring'), ('habitat_restoration', 'Habitat restoration'), ('water_access_support', 'Water access support'), ('expert_guided_monitoring', 'Expert-guided monitoring'), ('no_harm_wildlife_protection', 'No-harm wildlife protection')], max_length=35)),
                ('description', models.TextField(blank=True)),
                ('capex_estimate', models.FloatField(default=0.0)),
                ('opex_estimate', models.FloatField(default=0.0)),
                ('estimated_benefit', models.FloatField(blank=True, help_text='Estimated, never labelled a verified outcome.', null=True)),
                ('currency', models.CharField(default='GBP', max_length=10)),
                ('implementation_complexity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('participant_role', models.TextField(blank=True, help_text='Short summary — full detail lives on TourParticipantRole.')),
                ('professional_role', models.TextField(blank=True)),
                ('local_partner_role', models.TextField(blank=True)),
                ('mrv_required', models.BooleanField(default=True)),
                ('governance_required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('modelled', 'Modelled'), ('recommended', 'Recommended'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='modelled', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interventions', to='khalifa_stewardship_tour_operating_system.stewardshipproblem')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='StewardshipTour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('region', models.CharField(blank=True, max_length=150)),
                ('tour_type', models.CharField(choices=[('clean_heat', 'Clean Heat Tour'), ('mountain', 'Mountain Stewardship Tour'), ('lake_water', 'Lake & Water Stewardship Tour'), ('food_surplus', 'Food & Surplus Stewardship Tour'), ('greenhouse', 'Community Greenhouse Tour'), ('wildlife', 'Wildlife & Nature Restoration Tour')], max_length=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('evidence_needed', 'Evidence Needed'), ('under_ai_review', 'Under AI Review'), ('council_review', 'Council Review'), ('approved_with_conditions', 'Approved with Conditions'), ('funding_needed', 'Funding Needed'), ('partner_due_diligence', 'Partner Due Diligence'), ('ready_to_launch', 'Ready to Launch'), ('active', 'Active'), ('completed', 'Completed'), ('mrv_pending', 'MRV Pending'), ('verified_legacy', 'Verified Legacy'), ('blocked', 'Blocked')], default='draft', max_length=25)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('participant_capacity', models.PositiveIntegerField(default=0)),
                ('estimated_price_per_participant', models.FloatField(blank=True, null=True)),
                ('total_budget_required', models.FloatField(default=0.0)),
                ('currency', models.CharField(default='GBP', max_length=10)),
                ('safety_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('local_partner_required', models.BooleanField(default=True)),
                ('human_approval_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='countries.countryprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='stewardshipproblem',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='khalifa_stewardship_tour_operating_system.stewardshiptour'),
        ),
        migrations.CreateModel(
            name='TourFundingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_required', models.FloatField(default=0.0)),
                ('participant_contribution', models.FloatField(default=0.0)),
                ('sponsor_contribution', models.FloatField(default=0.0)),
                ('grant_contribution', models.FloatField(default=0.0)),
                ('recovered_value_contribution', models.FloatField(default=0.0)),
                ('local_partner_contribution', models.FloatField(default=0.0)),
                ('funding_gap', models.FloatField(default=0.0, help_text='Computed — never asserted as secured.')),
                ('currency', models.CharField(default='GBP', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('funded', 'Funded'), ('gap_open', 'Gap Open')], default='draft', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funding_plan', to='khalifa_stewardship_tour_operating_system.stewardshiptour')),
            ],
        ),
        migrations.CreateModel(
            name='TourLegacyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified_outcome_summary', models.TextField(blank=True)),
                ('participants_count', models.PositiveIntegerField(default=0)),
                ('community_benefit', models.TextField(blank=True)),
                ('environmental_benefit', models.TextField(blank=True)),
                ('financial_value_recovered', models.FloatField(blank=True, help_text='Stays null until MRV has actually verified a figure.', null=True)),
                ('evidence_quality', models.CharField(choices=[('strong', 'Strong'), ('medium', 'Medium'), ('weak', 'Weak'), ('missing', 'Missing')], default='medium', max_length=10)),
                ('mrv_status', models.CharField(choices=[('not_started', 'Not Started'), ('baseline_collected', 'Baseline Collected'), ('after_data_pending', 'After-Data Pending'), ('verified', 'Verified')], default='not_started', max_length=20)),
                ('public_private_status', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], default='private', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='legacy_record', to='khalifa_stewardship_tour_operating_system.stewardshiptour')),
            ],
        ),
        migrations.CreateModel(
            name='TourLocalPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner_name', models.CharField(max_length=200)),
                ('partner_type', models.CharField(choices=[('ngo', 'NGO'), ('cooperative', 'Cooperative'), ('municipality', 'Municipality'), ('business', 'Business')], default='ngo', max_length=15)),
                ('role', models.TextField(blank=True)),
                ('due_diligence_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed')], default='not_started', max_length=15)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('contact_status', models.CharField(choices=[('identified', 'Identified'), ('contacted', 'Contacted'), ('confirmed', 'Confirmed')], default='identified', max_length=10)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_partners', to='khalifa_stewardship_tour_operating_system.stewardshiptour')),
            ],
            options={
                'ordering': ['partner_name'],
            },
        ),
        migrations.CreateModel(
            name='TourMRVPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_required', models.BooleanField(default=True)),
                ('after_data_required', models.BooleanField(default=True)),
                ('methodology', models.TextField(blank=True)),
                ('evidence_required', models.JSONField(blank=True, default=list)),
                ('verification_status', models.CharField(choices=[('not_started', 'Not Started'), ('baseline_collected', 'Baseline Collected'), ('after_data_pending', 'After-Data Pending'), ('verified', 'Verified')], default='not_started', max_length=20)),
                ('public_reporting_ready', models.BooleanField(default=False)),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mrv_plan', to='khalifa_stewardship_tour_operating_system.stewardshiptour')),
            ],
        ),
        migrations.CreateModel(
            name='TourParticipantRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('allowed_actions', models.JSONField(blank=True, default=list)),
                ('blocked_actions', models.JSONField(blank=True, default=list)),
                ('safety_requirements', models.TextField(blank=True)),
                ('supervision_required', models.BooleanField(default=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_roles', to='khalifa_stewardship_tour_operating_system.stewardshiptour')),
            ],
            options={
                'ordering': ['role_name'],
            },
        ),
    ]
