# Generated by Django 5.2.14 on 2026-07-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khalifa_stewardship_tour_operating_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stewardshiptour',
            name='human_approved',
            field=models.BooleanField(blank=True, default=None, help_text='Explicit human sign-off, read by services/human_approval_gate.py — never inferred.', null=True),
        ),
    ]
