# Generated by Django 5.2.14 on 2026-07-06 20:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_update_focus_country_data'),
        ('khalifa_stewardship_tour_operating_system', '0002_stewardshiptour_human_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourlocalpartner',
            name='conflict_of_interest_status',
            field=models.CharField(choices=[('not_assessed', 'Not Assessed'), ('clear', 'Clear'), ('flagged', 'Flagged')], default='not_assessed', max_length=15),
        ),
        migrations.AddField(
            model_name='tourlocalpartner',
            name='contact_role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tourlocalpartner',
            name='email_or_phone_reference',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tourlocalpartner',
            name='human_approved',
            field=models.BooleanField(blank=True, default=None, help_text='Explicit human sign-off, read by services/human_approval_gate.py — never inferred.', null=True),
        ),
        migrations.AddField(
            model_name='tourlocalpartner',
            name='insurance_evidence_status',
            field=models.CharField(choices=[('not_provided', 'Not Provided'), ('provided', 'Provided'), ('verified', 'Verified')], default='not_provided', max_length=15),
        ),
        migrations.AddField(
            model_name='tourlocalpartner',
            name='legal_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tourlocalpartner',
            name='local_registration_reference',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='tourlocalpartner',
            name='named_contact',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='tourlocalpartner',
            name='safeguarding_review_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('passed', 'Passed'), ('failed', 'Failed')], default='not_started', max_length=15),
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('participant_injury', 'Participant Injury'), ('community_concern', 'Community Concern'), ('safeguarding_concern', 'Safeguarding Concern'), ('technical_incident', 'Technical Incident'), ('environmental_harm', 'Environmental Harm'), ('food_safety_issue', 'Food Safety Issue'), ('data_privacy_incident', 'Data / Privacy Incident'), ('transport_issue', 'Transport Issue')], max_length=25)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True)),
                ('immediate_action', models.TextField(blank=True)),
                ('escalated_to', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Investigating'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='reported', max_length=15)),
                ('evidence_reference', models.CharField(blank=True, max_length=255)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_reports', to='khalifa_stewardship_tour_operating_system.stewardshiptour')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='SupplierQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=200)),
                ('quote_reference', models.CharField(blank=True, max_length=150)),
                ('amount', models.FloatField(help_text='The quoted amount — never an approved cost.')),
                ('currency', models.CharField(default='GBP', max_length=10)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('inclusions', models.JSONField(blank=True, default=list)),
                ('exclusions', models.JSONField(blank=True, default=list)),
                ('assumptions', models.TextField(blank=True)),
                ('technical_scope', models.TextField(blank=True)),
                ('warranty_information', models.TextField(blank=True)),
                ('evidence_reference', models.CharField(blank=True, max_length=255)),
                ('verification_status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('verified', 'Verified')], default='not_started', max_length=15)),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intervention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_quotes', to='khalifa_stewardship_tour_operating_system.stewardshipintervention')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TourBeneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_reference', models.CharField(help_text='Safe public label, e.g. "Demo Household A — Almaty Region".', max_length=150)),
                ('household_or_beneficiary_type', models.CharField(choices=[('household', 'Household'), ('community', 'Community'), ('school', 'School'), ('other', 'Other')], default='household', max_length=15)),
                ('region', models.CharField(blank=True, max_length=150)),
                ('locality', models.CharField(blank=True, max_length=150)),
                ('private_contact_reference', models.CharField(blank=True, help_text='A pointer to where real contact info lives off-platform (e.g. local partner file) — never raw PII.', max_length=255)),
                ('address_reference', models.CharField(blank=True, help_text='Same reference-only pattern as private_contact_reference.', max_length=255)),
                ('household_size', models.PositiveIntegerField(blank=True, null=True)),
                ('vulnerability_notes_private', models.TextField(blank=True, help_text='Never rendered in any public view.')),
                ('language_preference', models.CharField(blank=True, max_length=100)),
                ('consent_status', models.CharField(choices=[('not_started', 'Not Started'), ('partial', 'Partial'), ('complete', 'Complete'), ('withdrawn', 'Withdrawn')], default='not_started', help_text='Rollup convenience only — the real granular state lives on ConsentRecord rows.', max_length=15)),
                ('eligibility_status', models.CharField(choices=[('pending', 'Pending'), ('eligible', 'Eligible'), ('ineligible', 'Ineligible')], default='pending', max_length=15)),
                ('intake_status', models.CharField(choices=[('identified', 'Identified'), ('contacted', 'Contacted'), ('intake_complete', 'Intake Complete')], default='identified', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='countries.countryprofile')),
                ('stewardship_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='khalifa_stewardship_tour_operating_system.stewardshipproblem')),
            ],
            options={
                'ordering': ['display_reference'],
            },
        ),
        migrations.CreateModel(
            name='LaunchChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist_category', models.CharField(choices=[('beneficiary', 'Beneficiary'), ('technical', 'Technical'), ('partner', 'Partner'), ('finance', 'Finance'), ('participant_safety', 'Participant Safety'), ('mrv', 'MRV'), ('governance', 'Governance')], max_length=20)),
                ('item_key', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('missing', 'Missing'), ('in_review', 'In Review'), ('complete', 'Complete'), ('blocked', 'Blocked')], default='missing', max_length=10)),
                ('evidence_reference', models.CharField(blank=True, max_length=255)),
                ('reviewed_by', models.CharField(blank=True, max_length=150)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('blocking_reason', models.TextField(blank=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='launch_checklist_items', to='khalifa_stewardship_tour_operating_system.stewardshiptour')),
            ],
            options={
                'ordering': ['checklist_category', 'item_key'],
                'unique_together': {('tour', 'item_key')},
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_type', models.CharField(choices=[('intervention', 'Intervention'), ('data_processing', 'Data Processing'), ('photography', 'Photography'), ('video', 'Video'), ('public_story', 'Public Story'), ('follow_up_contact', 'Follow-up Contact'), ('mrv_data_collection', 'MRV Data Collection')], max_length=25)),
                ('status', models.CharField(choices=[('not_requested', 'Not Requested'), ('requested', 'Requested'), ('granted', 'Granted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='not_requested', max_length=15)),
                ('consent_method', models.CharField(blank=True, choices=[('verbal', 'Verbal'), ('written', 'Written'), ('digital', 'Digital')], max_length=10)),
                ('witnessed_by', models.CharField(blank=True, max_length=150)),
                ('evidence_reference', models.CharField(blank=True, max_length=255)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='khalifa_stewardship_tour_operating_system.stewardshiptour')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to='khalifa_stewardship_tour_operating_system.tourbeneficiary')),
            ],
            options={
                'ordering': ['consent_type'],
                'unique_together': {('beneficiary', 'tour', 'consent_type')},
            },
        ),
    ]
