# Generated by Django 5.2.14 on 2026-06-14 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_dataingestionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(default='company', max_length=24)),
                ('subject_ref', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=12)),
                ('engine_version', models.CharField(default='hikma-assess-v1', max_length=24)),
                ('result', models.JSONField(blank=True, null=True)),
                ('error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hikma_assessments', to='companies.companyprofile')),
            ],
            options={
                'db_table': 'hikma_assessment_run',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(default='company', max_length=24)),
                ('subject_ref', models.CharField(blank=True, max_length=120)),
                ('kind', models.CharField(choices=[('say', 'SAY — stated intent / claim'), ('do', 'DO — action / capital allocation'), ('show', 'SHOW — independent evidence / outcome')], max_length=4)),
                ('statement', models.TextField()),
                ('metric_name', models.CharField(blank=True, max_length=120)),
                ('metric_value', models.FloatField(blank=True, null=True)),
                ('metric_unit', models.CharField(blank=True, max_length=32)),
                ('source_type', models.CharField(blank=True, max_length=40)),
                ('source_url', models.URLField(blank=True)),
                ('published_at', models.DateField(blank=True, null=True)),
                ('confidence_tier', models.CharField(choices=[('verified', 'Verified (audit / regulator)'), ('analyst-reviewed', 'Analyst-reviewed'), ('ai-seeded', 'AI-seeded (unreviewed)'), ('model-estimate', 'Model-estimate')], default='ai-seeded', max_length=20)),
                ('scholar_review_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hikma_evidence', to='companies.companyprofile')),
            ],
            options={
                'db_table': 'hikma_evidence',
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['subject_type', 'subject_ref'], name='hikma_evide_subject_217e3c_idx'), models.Index(fields=['kind'], name='hikma_evide_kind_6e5924_idx')],
            },
        ),
    ]
