# Generated by Django 5.2.14 on 2026-06-14 09:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_dataingestionlog'),
        ('hikma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidence',
            name='confidence_score',
            field=models.FloatField(default=0.5),
        ),
        migrations.AddField(
            model_name='evidence',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='IngestRefreshJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_ref', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('error', 'Error')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('sources_seen', models.IntegerField(default=0)),
                ('evidence_created', models.IntegerField(default=0)),
                ('evidence_skipped', models.IntegerField(default=0)),
                ('assessment_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refresh_jobs', to='hikma.assessmentrun')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hikma_refresh_jobs', to='companies.companyprofile')),
            ],
            options={
                'db_table': 'hikma_ingest_refresh_job',
                'ordering': ['-created_at'],
            },
        ),
    ]
