# Generated by Django 5.2.14 on 2026-07-08 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundTaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('company_intelligence_refresh', 'Company Intelligence Refresh'), ('geo_intelligence_refresh', 'Geo Intelligence Refresh'), ('ai_analysis', 'AI Analysis')], db_index=True, max_length=40)),
                ('celery_task_id', models.CharField(blank=True, db_index=True, max_length=155)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('retrying', 'Retrying')], db_index=True, default='queued', max_length=12)),
                ('target_repr', models.CharField(help_text='Human-readable label, e.g. "Acme Ltd" or "Almaty".', max_length=255)),
                ('target_reference', models.CharField(blank=True, help_text='e.g. "companies.CompanyProfile:42" — soft pointer, never a hard cross-app FK.', max_length=200)),
                ('task_kwargs', models.JSONField(blank=True, default=dict)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('error_summary', models.TextField(blank=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-queued_at'],
            },
        ),
    ]
