# Generated by Django 5.2.14 on 2026-07-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_intelligence_engine', '0002_alter_backgroundtaskrun_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundtaskrun',
            name='task_type',
            field=models.CharField(choices=[('company_intelligence_refresh', 'Company Intelligence Refresh'), ('geo_intelligence_refresh', 'Geo Intelligence Refresh'), ('ai_analysis', 'AI Analysis'), ('evidence_memory_refresh', 'Evidence Memory Refresh'), ('intelligence_score_recalculation', 'Intelligence Score Recalculation')], db_index=True, max_length=40),
        ),
    ]
