# Generated by Django 5.2.14 on 2026-07-19 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_companyscoresnapshot_climate_risk_score_and_more'),
        ('evidence_memory', '0004_backfill_access_model'),
        ('league', '0004_add_search_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyControversy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('labour', 'Labour'), ('environmental', 'Environmental'), ('governance', 'Governance'), ('community', 'Community'), ('safety', 'Safety'), ('other', 'Other')], default='other', max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('unresolved', 'Unresolved'), ('disputed', 'Disputed'), ('resolved', 'Resolved')], default='unresolved', max_length=15)),
                ('reported_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controversies', to='companies.companyprofile')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controversies', to='evidence_memory.evidencememory')),
            ],
            options={
                'verbose_name': 'Company Controversy',
                'verbose_name_plural': 'Company Controversies',
                'ordering': ['-reported_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancialFacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField()),
                ('market_cap_usd', models.FloatField(blank=True, null=True)),
                ('total_debt_usd', models.FloatField(blank=True, help_text='Interest-bearing debt.', null=True)),
                ('cash_and_equivalents_usd', models.FloatField(blank=True, null=True)),
                ('interest_bearing_securities_usd', models.FloatField(blank=True, help_text='Interest-bearing cash equivalents/securities held.', null=True)),
                ('non_permissible_income_usd', models.FloatField(blank=True, help_text='Interest income + other non-permissible income, where disclosed.', null=True)),
                ('revenue_usd', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, help_text='Where these figures came from.', max_length=200)),
                ('retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_facts', to='companies.companyprofile')),
            ],
            options={
                'verbose_name': 'Company Financial Facts',
                'verbose_name_plural': 'Company Financial Facts',
                'ordering': ['-as_of_date'],
            },
        ),
        migrations.CreateModel(
            name='CompanyKPIAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kpi_id', models.PositiveSmallIntegerField(help_text='1-114, matches core.esg_principles_data.PRINCIPLES id.')),
                ('status', models.CharField(choices=[('strong_support', 'Strong Support'), ('support', 'Support'), ('mixed', 'Mixed'), ('neutral_or_no_material_link', 'Neutral / No Material Link'), ('conflict', 'Conflict'), ('insufficient_evidence', 'Insufficient Evidence'), ('not_assessed', 'Not Assessed')], default='not_assessed', max_length=30)),
                ('rationale', models.TextField(blank=True, help_text='Why this status was assigned, in terms of the linked evidence — never an unsupported model-generated claim.')),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10)),
                ('last_assessed_at', models.DateTimeField(auto_now=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_assessments_made', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_assessments', to='companies.companyprofile')),
            ],
            options={
                'verbose_name': 'Company KPI Assessment',
                'ordering': ['kpi_id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyKPIEvidenceLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('supports', 'Supports'), ('conflicts', 'Conflicts'), ('context', 'Context Only')], max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_evidence_links_added', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_links', to='company_intelligence.companykpiassessment')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_links', to='evidence_memory.evidencememory')),
            ],
            options={
                'verbose_name': 'Company KPI Evidence Link',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(blank=True, max_length=20)),
                ('exchange', models.CharField(blank=True, help_text='e.g. "NASDAQ", "LSE"', max_length=100)),
                ('isin', models.CharField(blank=True, help_text='ISO 6166 identifier where known.', max_length=12)),
                ('currency', models.CharField(blank=True, help_text='e.g. "USD"', max_length=8)),
                ('is_primary', models.BooleanField(default=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('retrieved_at', models.DateTimeField(blank=True, null=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='league.company')),
            ],
            options={
                'verbose_name': 'Company Listing',
                'ordering': ['-is_primary', 'exchange'],
            },
        ),
        migrations.CreateModel(
            name='ResearchWatchlistEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('researching', 'Researching'), ('high_kpi_alignment', 'High KPI Alignment'), ('needs_review', 'Needs Review'), ('shariah_data_incomplete', 'Shariah Data Incomplete'), ('controversy_review', 'Controversy Review')], default='researching', max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_entries', to='companies.companyprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Research Watchlist Entry',
                'ordering': ['-added_at'],
            },
        ),
        migrations.CreateModel(
            name='ShariahMethodology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "EcoIQ Reference Shariah Screen"', max_length=200)),
                ('version', models.CharField(help_text='e.g. "1.0"', max_length=20)),
                ('description', models.TextField(help_text='What this methodology screens for and how it was derived. Must state it is methodology-based screening, not a religious ruling or individual fatwa.')),
                ('source_reference', models.CharField(blank=True, help_text='Named reference the thresholds/categories are derived from (e.g. an published index methodology). Left blank only if genuinely unavailable — never fabricated.', max_length=300)),
                ('business_activity_rules', models.JSONField(blank=True, default=list)),
                ('financial_ratio_rules', models.JSONField(blank=True, default=dict)),
                ('effective_date', models.DateField()),
                ('is_active', models.BooleanField(default=True, help_text='Available for new screens.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Shariah Methodology',
                'verbose_name_plural': 'Shariah Methodologies',
                'ordering': ['-effective_date'],
                'constraints': [models.UniqueConstraint(fields=('name', 'version'), name='ci_unique_methodology_version')],
            },
        ),
        migrations.CreateModel(
            name='CompanyShariahScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_activity_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('conditional', 'Conditional'), ('insufficient_data', 'Insufficient Data'), ('not_screened', 'Not Screened')], default='not_screened', max_length=20)),
                ('business_activity_reason', models.TextField(blank=True)),
                ('business_activity_evidence_refs', models.JSONField(blank=True, default=list, help_text='List of EvidenceMemory source_reference strings cited.')),
                ('financial_ratio_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('conditional', 'Conditional'), ('insufficient_data', 'Insufficient Data'), ('not_screened', 'Not Screened')], default='not_screened', max_length=20)),
                ('financial_ratio_detail', models.JSONField(blank=True, default=dict, help_text='Computed ratios, thresholds compared against, and which inputs were missing. Never silently substitutes a missing value with zero.')),
                ('overall_result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('conditional', 'Conditional'), ('insufficient_data', 'Insufficient Data'), ('not_screened', 'Not Screened')], default='not_screened', max_length=20)),
                ('data_completeness_pct', models.FloatField(default=0.0)),
                ('review_status', models.CharField(choices=[('automated_preliminary', 'Automated Preliminary Screen'), ('human_reviewed', 'Human Reviewed'), ('methodology_verified', 'Methodology Verified'), ('scholar_reviewed', 'Scholar Reviewed')], default='automated_preliminary', max_length=25)),
                ('screened_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('is_demo', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shariah_screens', to='companies.companyprofile')),
                ('financial_facts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screens', to='company_intelligence.companyfinancialfacts')),
                ('screened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shariah_screens_performed', to=settings.AUTH_USER_MODEL)),
                ('methodology', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screens', to='company_intelligence.shariahmethodology')),
            ],
            options={
                'verbose_name': 'Company Shariah Screen',
                'ordering': ['-screened_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='companykpiassessment',
            constraint=models.UniqueConstraint(fields=('company', 'kpi_id'), name='ci_unique_company_kpi'),
        ),
        migrations.AddConstraint(
            model_name='companykpievidencelink',
            constraint=models.UniqueConstraint(fields=('assessment', 'evidence'), name='ci_unique_assessment_evidence'),
        ),
        migrations.AddConstraint(
            model_name='researchwatchlistentry',
            constraint=models.UniqueConstraint(fields=('user', 'company'), name='ci_unique_user_company_watchlist'),
        ),
    ]
