# Generated by Django 5.2.14 on 2026-07-20 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_intelligence', '0001_initial'),
        ('evidence_memory', '0004_backfill_access_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companycontroversy',
            name='finding_type',
            field=models.CharField(choices=[('allegation', 'Allegation'), ('investigation', 'Investigation (Ongoing)'), ('regulatory_finding', 'Regulatory Finding'), ('court_finding', 'Court Finding'), ('company_admission', 'Company Admission'), ('verified_event', 'Verified Event')], default='allegation', max_length=25),
        ),
        migrations.AddField(
            model_name='companykpievidencelink',
            name='match_basis',
            field=models.CharField(blank=True, help_text='For a proposed (ingestion-matched) link: the deterministic keyword/category match that produced it — never an LLM claim. Blank for manually-created links.', max_length=200),
        ),
        migrations.AddField(
            model_name='companykpievidencelink',
            name='review_state',
            field=models.CharField(choices=[('proposed', 'Proposed — Awaiting Review'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='confirmed', max_length=10),
        ),
        migrations.CreateModel(
            name='EvidenceReviewAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('verify', 'Verify'), ('reject', 'Reject'), ('mark_disputed', 'Mark Disputed'), ('needs_more_evidence', 'Needs More Evidence')], max_length=25)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_actions', to='evidence_memory.evidencememory')),
                ('kpi_evidence_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_actions', to='company_intelligence.companykpievidencelink')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence_review_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidence Review Action',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyFinancialFactSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('market_cap_usd', 'Market Capitalisation'), ('total_debt_usd', 'Total Debt'), ('cash_and_equivalents_usd', 'Cash & Equivalents'), ('interest_bearing_securities_usd', 'Interest-Bearing Securities'), ('non_permissible_income_usd', 'Non-Permissible Income'), ('revenue_usd', 'Revenue')], max_length=40)),
                ('is_derived', models.BooleanField(default=False, help_text='True when this value was derived/interpreted from a reported figure (e.g. interest income used as a proxy for non-permissible income), never for a value copied directly from the filing.')),
                ('interpretation_note', models.TextField(blank=True, help_text='Required explanation when is_derived=True — how the value was derived.')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='financial_fact_sources', to='evidence_memory.evidencememory')),
                ('financial_facts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_sources', to='company_intelligence.companyfinancialfacts')),
            ],
            options={
                'verbose_name': 'Company Financial Fact Source',
                'ordering': ['metric'],
                'constraints': [models.UniqueConstraint(fields=('financial_facts', 'metric'), name='ci_unique_factset_metric')],
            },
        ),
    ]
