# Generated by Django 5.2.14 on 2026-07-20 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_intelligence', '0002_companycontroversy_finding_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencereviewaction',
            name='new_review_state',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='evidencereviewaction',
            name='previous_review_state',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='evidencereviewaction',
            name='relationship_decision',
            field=models.CharField(blank=True, choices=[('supports', 'Supports'), ('conflicts', 'Conflicts'), ('context', 'Context Only'), ('insufficient_to_conclude', 'Insufficient to Conclude')], max_length=30),
        ),
        migrations.AlterField(
            model_name='companykpievidencelink',
            name='relationship',
            field=models.CharField(choices=[('supports', 'Supports'), ('conflicts', 'Conflicts'), ('context', 'Context Only'), ('insufficient_to_conclude', 'Insufficient to Conclude')], max_length=30),
        ),
        migrations.AlterField(
            model_name='companykpievidencelink',
            name='review_state',
            field=models.CharField(choices=[('proposed', 'Proposed — Awaiting Review'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('needs_more_evidence', 'Needs More Evidence'), ('disputed', 'Disputed')], default='confirmed', max_length=25),
        ),
        migrations.AlterField(
            model_name='evidencereviewaction',
            name='action',
            field=models.CharField(choices=[('confirm_supports', 'Confirm — Supports'), ('confirm_conflicts', 'Confirm — Conflicts'), ('confirm_context', 'Confirm — Context Only'), ('confirm_insufficient', 'Confirm — Insufficient to Conclude'), ('reject', 'Reject Match'), ('needs_more_evidence', 'Needs More Evidence'), ('mark_disputed', 'Mark Disputed')], max_length=25),
        ),
    ]
