# Generated by Django 5.2.14 on 2026-07-21 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_observatory', '0007_alter_analysissession_kind'),
        ('companies', '0007_companyprofile_last_refresh_at_and_more'),
        ('company_intelligence', '0003_evidencereviewaction_new_review_state_and_more'),
        ('harvester', '0008_evidence_source_location_sourcedocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRefreshRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_by', models.CharField(choices=[('manual', 'Manual (Staff-Triggered)'), ('scheduled', 'Scheduled'), ('management_command', 'Management Command'), ('other', 'Other')], default='manual', max_length=25)),
                ('status', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('partial', 'Partial'), ('failed', 'Failed')], default='running', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sources_checked', models.PositiveIntegerField(default=0)),
                ('sources_failed', models.PositiveIntegerField(default=0)),
                ('documents_new', models.PositiveIntegerField(default=0)),
                ('documents_updated', models.PositiveIntegerField(default=0)),
                ('documents_unchanged', models.PositiveIntegerField(default=0)),
                ('evidence_created', models.PositiveIntegerField(default=0)),
                ('duplicates_ignored', models.PositiveIntegerField(default=0)),
                ('kpi_candidates_proposed', models.PositiveIntegerField(default=0)),
                ('review_required_count', models.PositiveIntegerField(default=0)),
                ('warnings', models.JSONField(blank=True, default=list)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refresh_runs_triggered', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_runs', to='companies.companyprofile')),
                ('observatory_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refresh_runs', to='ai_observatory.analysissession')),
            ],
            options={
                'verbose_name': 'Company Refresh Run',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DiscoveredSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('domain', models.CharField(blank=True, max_length=200)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('source_type', models.CharField(blank=True, help_text='harvester.constants.SOURCE_TYPES value.', max_length=40)),
                ('tier', models.PositiveSmallIntegerField(default=4)),
                ('discovery_method', models.CharField(choices=[('sec_edgar_identity', 'SEC EDGAR CIK Mapping (Regulatory Filing)'), ('companies_house_identity', 'Companies House Number Mapping (UK Regulatory Filing)'), ('curated_official_domain', 'EcoIQ-Curated Official Domain Registry'), ('staff_registered_field', 'Existing Staff-Entered Company Profile Field'), ('manual', 'Manually Added by Staff')], max_length=30)),
                ('domain_status', models.CharField(choices=[('verified', 'Verified Official Domain'), ('probable', 'Probable — Staff-Entered, Not Independently Verified'), ('unverified', 'Unverified'), ('conflicting', 'Conflicting — Multiple Candidate Domains Found')], default='unverified', max_length=15)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('candidate', 'Candidate — Awaiting Staff Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('registered', 'Registered as an Active Source')], default='candidate', max_length=12)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discovered_sources', to='companies.companyprofile')),
                ('harvester_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_from', to='harvester.source')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_sources_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Discovered Source',
                'ordering': ['-discovered_at'],
                'constraints': [models.UniqueConstraint(fields=('company', 'url'), name='ci_unique_discovered_source_url')],
            },
        ),
    ]
