# Generated by Django 5.2.14 on 2026-07-21 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0007_companyprofile_last_refresh_at_and_more'),
        ('company_intelligence', '0004_companyrefreshrun_discoveredsource'),
        ('evidence_memory', '0004_backfill_access_model'),
        ('harvester', '0008_evidence_source_location_sourcedocument_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='companykpievidencelink',
            name='proposed_via_refresh_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_candidates_proposed_here', to='company_intelligence.companyrefreshrun'),
        ),
        migrations.AddField(
            model_name='companyrefreshrun',
            name='sources_skipped_not_due',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StewardshipChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('new_source', 'New Source'), ('source_changed', 'Source Changed'), ('source_unreachable', 'Source Unreachable'), ('source_recovered', 'Source Recovered'), ('new_document', 'New Document'), ('document_updated', 'Document Updated'), ('document_removed_or_unreachable', 'Document Removed or Unreachable'), ('new_evidence', 'New Evidence'), ('evidence_changed', 'Evidence Changed'), ('new_kpi_candidate', 'New KPI Candidate(s)'), ('potential_conflict', 'Potential Conflict'), ('evidence_stale', 'Evidence Stale'), ('shariah_data_changed', 'Shariah Data Changed'), ('review_required', 'Review Required')], max_length=35)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='info', max_length=10)),
                ('review_required', models.BooleanField(default=False)),
                ('summary', models.CharField(max_length=300)),
                ('previous_state', models.CharField(blank=True, max_length=200)),
                ('new_state', models.CharField(blank=True, max_length=200)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_events', to='companies.companyprofile')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_events', to='harvester.sourcedocument')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_events', to='evidence_memory.evidencememory')),
                ('kpi_evidence_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_events', to='company_intelligence.companykpievidencelink')),
                ('refresh_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_events', to='company_intelligence.companyrefreshrun')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_events', to='harvester.source')),
            ],
            options={
                'verbose_name': 'Stewardship Change Event',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='StewardshipAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('new_source', 'New Source'), ('source_changed', 'Source Changed'), ('source_unreachable', 'Source Unreachable'), ('source_recovered', 'Source Recovered'), ('new_document', 'New Document'), ('document_updated', 'Document Updated'), ('document_removed_or_unreachable', 'Document Removed or Unreachable'), ('new_evidence', 'New Evidence'), ('evidence_changed', 'Evidence Changed'), ('new_kpi_candidate', 'New KPI Candidate(s)'), ('potential_conflict', 'Potential Conflict'), ('evidence_stale', 'Evidence Stale'), ('shariah_data_changed', 'Shariah Data Changed'), ('review_required', 'Review Required')], max_length=35)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='info', max_length=10)),
                ('message', models.CharField(max_length=300)),
                ('priority_score', models.PositiveSmallIntegerField(default=0)),
                ('priority_components', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='new', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_reason', models.TextField(blank=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stewardship_alerts_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stewardship_alerts', to='companies.companyprofile')),
                ('change_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='company_intelligence.stewardshipchangeevent')),
            ],
            options={
                'verbose_name': 'Stewardship Alert',
                'ordering': ['-priority_score', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='stewardshipchangeevent',
            index=models.Index(fields=['company', 'event_type'], name='company_int_company_981369_idx'),
        ),
        migrations.AddIndex(
            model_name='stewardshipchangeevent',
            index=models.Index(fields=['detected_at'], name='company_int_detecte_7ad61b_idx'),
        ),
    ]
