# Generated by Django 5.2.14 on 2026-07-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_intelligence', '0005_companykpievidencelink_proposed_via_refresh_run_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylisting',
            name='companies_house_number',
            field=models.CharField(blank=True, help_text='UK Companies House registration number, where mapped.', max_length=12),
        ),
        migrations.AddField(
            model_name='companylisting',
            name='domain_status',
            field=models.CharField(blank=True, choices=[('verified', 'Verified Official Domain'), ('probable', 'Probable — Staff-Entered, Not Independently Verified'), ('unverified', 'Unverified'), ('conflicting', 'Conflicting — Multiple Candidate Domains Found')], help_text='Reuses the same VERIFIED/PROBABLE/UNVERIFIED/CONFLICTING vocabulary as DiscoveredSource — never a second domain-trust scale.', max_length=15),
        ),
        migrations.AddField(
            model_name='companylisting',
            name='identity_source',
            field=models.CharField(blank=True, help_text='Which real, existing mapping this identity came from (e.g. "SEC EDGAR CIK mapping", "Companies House number mapping", "EcoIQ-curated official domain registry") — never blank when any of the fields above are populated.', max_length=200),
        ),
        migrations.AddField(
            model_name='companylisting',
            name='lei',
            field=models.CharField(blank=True, help_text='ISO 17442 Legal Entity Identifier, where reliably known.', max_length=20),
        ),
        migrations.AddField(
            model_name='companylisting',
            name='official_domain',
            field=models.CharField(blank=True, help_text='e.g. "apple.com" — the company\'s own primary web domain, where known.', max_length=200),
        ),
        migrations.AddField(
            model_name='companylisting',
            name='sec_cik',
            field=models.CharField(blank=True, help_text='10-digit zero-padded SEC EDGAR CIK, where mapped.', max_length=10),
        ),
        migrations.AddField(
            model_name='companylisting',
            name='verified_at',
            field=models.DateTimeField(blank=True, help_text='When identity_sync.py last confirmed these fields against their source mapping.', null=True),
        ),
    ]
