# Generated by Django 5.2.14 on 2026-08-25 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_intelligence', '0006_companylisting_companies_house_number_and_more'),
        ('evidence_memory', '0005_evidencememory_legal_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIRemediationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(help_text='Order within the chain. Not a date: several steps can share a month.')),
                ('kind', models.CharField(choices=[('finding', 'Finding'), ('company_response', 'Company Response'), ('product_or_policy_change', 'Product or Policy Change'), ('regulatory_response', 'Regulatory Response'), ('residual_concern', 'Residual Concern')], max_length=30)),
                ('summary', models.CharField(max_length=300)),
                ('detail', models.TextField(blank=True)),
                ('occurred_on', models.DateField(blank=True, null=True)),
                ('verification', models.CharField(choices=[('claimed', 'Claimed by Organisation'), ('evidenced', 'Evidenced'), ('independently_confirmed', 'Independently Confirmed'), ('contested', 'Contested')], default='claimed', max_length=30)),
                ('is_demo', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remediation_steps', to='company_intelligence.companykpiassessment')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_remediation_steps', to='evidence_memory.evidencememory')),
            ],
            options={
                'verbose_name': 'KPI Remediation Step',
                'ordering': ['assessment', 'position'],
                'constraints': [models.UniqueConstraint(fields=('assessment', 'position'), name='ci_unique_remediation_position')],
            },
        ),
    ]
