# Generated by Django 5.2.14 on 2026-08-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_intelligence', '0007_kpiremediationstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencereviewaction',
            name='evidence_version',
            field=models.CharField(blank=True, help_text='SHA-256 of the evidence text as it stood when reviewed.', max_length=64),
        ),
    ]
