# Generated by Django 5.2.14 on 2026-07-09 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countries', '0003_update_focus_country_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('region', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('exploration', 'Exploration'), ('licensing', 'Licensing'), ('construction', 'Construction'), ('production', 'Production'), ('expansion', 'Expansion')], default='exploration', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ore_grade_g_per_tonne', models.FloatField(blank=True, help_text='Grams of gold per tonne of ore.', null=True)),
                ('resource_tonnes', models.FloatField(blank=True, help_text='Total ore resource, tonnes.', null=True)),
                ('recovery_rate_pct', models.FloatField(blank=True, help_text='% of contained gold recovered by processing.', null=True)),
                ('mine_life_years', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_annual_production_oz', models.FloatField(blank=True, help_text='Expected steady-state annual production, troy oz.', null=True)),
                ('total_capex_usd', models.FloatField(blank=True, help_text='Total initial capital expenditure, USD.', null=True)),
                ('annual_opex_usd', models.FloatField(blank=True, help_text='Total annual operating expenditure, USD.', null=True)),
                ('cash_cost_usd_per_oz', models.FloatField(blank=True, help_text='Direct cash operating cost per oz produced.', null=True)),
                ('aisc_usd_per_oz', models.FloatField(blank=True, help_text='All-in sustaining cost per oz produced (includes sustaining capex).', null=True)),
                ('gold_price_assumption_usd_per_oz', models.FloatField(blank=True, help_text='Gold price assumption used for base-case economics.', null=True)),
                ('discount_rate_pct', models.FloatField(blank=True, help_text='Discount rate used for NPV, %.', null=True)),
                ('data_sources', models.TextField(blank=True, help_text='Citation string, e.g. "NI 43-101 technical report, 2024".')),
                ('data_last_updated', models.DateField(blank=True, null=True)),
                ('is_demo', models.BooleanField(default=True, help_text='Illustrative/demonstration project — never presented as verified real-world market data.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gold_projects', to='countries.countryprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_type', models.CharField(choices=[('crusher', 'Crusher'), ('mill', 'Mill'), ('cil', 'CIL (Carbon-in-Leach)'), ('heap_leach', 'Heap Leach'), ('gravity', 'Gravity Concentration'), ('flotation', 'Flotation'), ('autoclave', 'Autoclave'), ('thickener', 'Thickener'), ('filter_press', 'Filter Press'), ('tailings', 'Tailings Storage Facility'), ('power_plant', 'Power Plant')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('capex_usd', models.FloatField(blank=True, null=True)),
                ('lead_time_months', models.PositiveIntegerField(blank=True, null=True)),
                ('power_usage_kw', models.FloatField(blank=True, null=True)),
                ('water_usage_m3_per_hour', models.FloatField(blank=True, null=True)),
                ('recovery_pct', models.FloatField(blank=True, help_text='Recovery contribution of this equipment stage, %, if known.', null=True)),
                ('notes', models.TextField(blank=True)),
                ('data_source', models.CharField(blank=True, max_length=200)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_specs', to='gold_intelligence.goldproject')),
            ],
            options={
                'ordering': ['equipment_type'],
            },
        ),
        migrations.CreateModel(
            name='CapitalBudgetLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('mining_equipment', 'Mining Equipment'), ('processing_plant', 'Processing Plant'), ('infrastructure', 'Infrastructure'), ('permits_licensing', 'Permits & Licensing'), ('contingency', 'Contingency'), ('other', 'Other')], default='other', max_length=30)),
                ('label', models.CharField(max_length=200)),
                ('planned_usd', models.FloatField(blank=True, null=True)),
                ('committed_usd', models.FloatField(blank=True, null=True)),
                ('spent_usd', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('data_source', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_budget_lines', to='gold_intelligence.goldproject')),
            ],
            options={
                'ordering': ['category', 'label'],
            },
        ),
        migrations.CreateModel(
            name='MineTimelineMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('exploration', 'Exploration'), ('licensing', 'Licensing'), ('construction', 'Construction'), ('processing_plant', 'Processing Plant'), ('production', 'Production'), ('expansion', 'Expansion')], max_length=20)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('delayed', 'Delayed')], default='not_started', max_length=15)),
                ('planned_start', models.DateField(blank=True, null=True)),
                ('planned_end', models.DateField(blank=True, null=True)),
                ('actual_start', models.DateField(blank=True, null=True)),
                ('actual_end', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_milestones', to='gold_intelligence.goldproject')),
            ],
            options={
                'ordering': ['planned_start', 'phase'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('gold_price_usd_per_oz', models.FloatField(blank=True, null=True)),
                ('capex_multiplier', models.FloatField(blank=True, help_text='e.g. 1.15 for a 15% CAPEX overrun. Null = base case CAPEX.', null=True)),
                ('opex_multiplier', models.FloatField(blank=True, help_text='e.g. 1.10 for a 10% OPEX increase. Null = base case OPEX.', null=True)),
                ('recovery_rate_pct_override', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='gold_intelligence.goldproject')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
