# Generated by Django 5.2.14 on 2026-07-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_intelligence', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentspec',
            name='commissioning_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('passed', 'Passed'), ('failed', 'Failed'), ('not_applicable', 'Not Applicable')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='equipmentspec',
            name='delivery_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('passed', 'Passed'), ('failed', 'Failed'), ('not_applicable', 'Not Applicable')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='equipmentspec',
            name='deposit_paid_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentspec',
            name='fat_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('passed', 'Passed'), ('failed', 'Failed'), ('not_applicable', 'Not Applicable')], default='not_started', help_text='Factory Acceptance Test status.', max_length=20),
        ),
        migrations.AddField(
            model_name='equipmentspec',
            name='inspection_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('passed', 'Passed'), ('failed', 'Failed'), ('not_applicable', 'Not Applicable')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='equipmentspec',
            name='installation_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('passed', 'Passed'), ('failed', 'Failed'), ('not_applicable', 'Not Applicable')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='equipmentspec',
            name='insurance_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('passed', 'Passed'), ('failed', 'Failed'), ('not_applicable', 'Not Applicable')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='equipmentspec',
            name='maintenance_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('passed', 'Passed'), ('failed', 'Failed'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='equipmentspec',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='equipmentspec',
            name='manufacturing_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('passed', 'Passed'), ('failed', 'Failed'), ('not_applicable', 'Not Applicable')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='equipmentspec',
            name='performance_guarantee_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('passed', 'Passed'), ('failed', 'Failed'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='equipmentspec',
            name='shipping_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('passed', 'Passed'), ('failed', 'Failed'), ('not_applicable', 'Not Applicable')], default='not_started', max_length=20),
        ),
        migrations.AddField(
            model_name='equipmentspec',
            name='supplier',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='equipmentspec',
            name='warranty_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('passed', 'Passed'), ('failed', 'Failed'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='goldproject',
            name='insurance_coverage_usd',
            field=models.FloatField(blank=True, help_text='Total insurance policy coverage for the project, USD.', null=True),
        ),
        migrations.AddField(
            model_name='goldproject',
            name='insurance_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goldproject',
            name='total_committed_capital_usd',
            field=models.FloatField(blank=True, help_text='Total capital committed by investors, USD.', null=True),
        ),
        migrations.AddField(
            model_name='minetimelinemilestone',
            name='capital_released_usd',
            field=models.FloatField(blank=True, help_text='Capital actually released against this milestone, USD.', null=True),
        ),
        migrations.AddField(
            model_name='minetimelinemilestone',
            name='capital_required_usd',
            field=models.FloatField(blank=True, help_text='Capital required to complete this milestone, USD.', null=True),
        ),
        migrations.AddField(
            model_name='minetimelinemilestone',
            name='completion_pct_override',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='minetimelinemilestone',
            name='delay_risk',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10),
        ),
        migrations.AddField(
            model_name='minetimelinemilestone',
            name='responsible_party',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='minetimelinemilestone',
            name='verification_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='minetimelinemilestone',
            name='verification_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed')], default='not_required', max_length=15),
        ),
        migrations.AlterField(
            model_name='equipmentspec',
            name='equipment_type',
            field=models.CharField(choices=[('crusher', 'Crusher'), ('mill', 'Mill'), ('cil', 'CIL (Carbon-in-Leach)'), ('heap_leach', 'Heap Leach'), ('gravity', 'Gravity Concentration'), ('flotation', 'Flotation'), ('autoclave', 'Autoclave'), ('thickener', 'Thickener'), ('filter_press', 'Filter Press'), ('tailings', 'Tailings Storage Facility'), ('power_plant', 'Power Plant'), ('conveyor', 'Conveyor'), ('electrowinning', 'Electrowinning Cells'), ('smelting_furnace', 'Smelting Furnace'), ('haul_truck', 'Haul Truck'), ('excavator', 'Hydraulic Excavator')], max_length=20),
        ),
    ]
