# Generated by Django 5.2.14 on 2026-07-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_intelligence', '0002_equipmentspec_commissioning_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldproject',
            name='commodity',
            field=models.CharField(choices=[('gold', 'Gold'), ('copper', 'Copper'), ('infrastructure', 'Infrastructure'), ('energy', 'Energy'), ('agriculture', 'Agriculture'), ('other', 'Other')], default='gold', max_length=20),
        ),
    ]
