# Generated by Django 5.2.14 on 2026-07-10 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_intelligence', '0003_goldproject_commodity'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentspec',
            name='commissioned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentspec',
            name='country',
            field=models.CharField(blank=True, help_text='Illustrative label in demo data — not a claim of real involvement.', max_length=100),
        ),
        migrations.AddField(
            model_name='equipmentspec',
            name='expected_lifespan_years',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentspec',
            name='maintenance_contract_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipmentspec',
            name='spare_parts_available',
            field=models.BooleanField(default=False),
        ),
    ]
