# Generated by Django 5.2.14 on 2026-07-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gold_intelligence', '0004_equipmentspec_commissioned_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldproject',
            name='organisation',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
