"""
digital_twin/services/guardrails.py — deterministic decision guardrails.

Combines each ModernisationScenario's StewardshipAssessment rows (see
services/stewardship.py) with a small number of explicit, named rules
straight from the product spec, into one verdict:

    pass | pass_with_warning | requires_evidence | requires_specialist_review | block

Never an LLM judgement — every rule below inspects real, already-stored
fields. Modelled after `capital_guardian.services.red_flag_engine`'s
threshold-comparison style.
"""

VERDICT_ORDER = ['pass', 'pass_with_warning', 'requires_evidence', 'requires_specialist_review', 'block']


def _escalate(current, candidate):
    """Returns whichever verdict is more severe — verdicts never de-escalate
    once raised within a single evaluation."""
    return candidate if VERDICT_ORDER.index(candidate) > VERDICT_ORDER.index(current) else current


def evaluate_guardrails(scenario):
    """Returns {'verdict', 'reasons': [...]} for one ModernisationScenario.
    Reads scenario.stewardship_assessments — call
    services.stewardship.run_stewardship_assessment(scenario) first."""
    verdict = 'pass'
    reasons = []

    assessments = list(scenario.stewardship_assessments.select_related('kpi'))
    intervention = scenario.intervention

    for assessment in assessments:
        if assessment.blocking:
            verdict = _escalate(verdict, 'block')
            reasons.append(f'BLOCK ({assessment.kpi.name}): {assessment.blocking_reason}')

    # Named rule: high financial return + severe worker/community harm ->
    # block. The harm KPI already sets `blocking=True` for keyword-detected
    # harm (handled above); this rule additionally escalates on the
    # combination even when the harm KPI only warned.
    high_return = intervention.estimated_annual_savings and intervention.estimated_annual_savings > 0
    harm_warnings = [a for a in assessments if a.kpi.slug == 'worker-community-harm-screen' and a.warning]
    if high_return and harm_warnings and verdict != 'block':
        verdict = _escalate(verdict, 'block')
        reasons.append('BLOCK: financial return combined with unresolved worker/community harm signal.')

    # Named rule: material community displacement/vulnerability -> requires
    # human and specialist review.
    vulnerability_warnings = [a for a in assessments if a.kpi.slug == 'community-vulnerability-screen' and a.warning and a.warning_reason]
    if vulnerability_warnings and verdict not in ('block',):
        verdict = _escalate(verdict, 'requires_specialist_review')
        for a in vulnerability_warnings:
            reasons.append(f'SPECIALIST REVIEW: {a.warning_reason}')

    # Named rule: incomplete critical evidence -> require additional evidence.
    evidence_gap = [a for a in assessments if a.kpi.slug == 'evidence-backed-confidence' and a.warning]
    if evidence_gap and verdict not in ('block', 'requires_specialist_review'):
        verdict = _escalate(verdict, 'requires_evidence')
        for a in evidence_gap:
            reasons.append(f'EVIDENCE REQUIRED: {a.warning_reason}')

    # Named rule: financial benefit generated by a hidden pollution transfer
    # (savings while emissions/waste demonstrably increase) -> block.
    pollution_transfer = (
        high_return
        and scenario.emissions_impact is not None and scenario.emissions_impact > 0
        and not scenario.evidence_references
    )
    if pollution_transfer:
        verdict = _escalate(verdict, 'block')
        reasons.append(
            'BLOCK: positive financial return combined with an increase in emissions_impact and no supporting '
            'evidence — possible hidden pollution transfer.'
        )

    # Any remaining warning (not already escalated above) -> pass_with_warning.
    other_warnings = [a for a in assessments if a.warning and a not in harm_warnings + vulnerability_warnings + evidence_gap]
    if other_warnings and verdict == 'pass':
        verdict = _escalate(verdict, 'pass_with_warning')
        for a in other_warnings:
            reasons.append(f'WARNING ({a.kpi.name}): {a.warning_reason}')

    if verdict == 'pass' and not reasons:
        reasons.append('No blocking conditions, specialist-review triggers, evidence gaps, or warnings found.')

    return {'verdict': verdict, 'reasons': reasons}
