# Generated by Django 5.2.14 on 2026-07-17 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_to_value_capital_allocation_engine', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='capitalallocationdecision',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('approved_with_conditions', 'Approved with Conditions'), ('rejected', 'Rejected'), ('evidence_requested', 'Evidence Requested'), ('modification_requested', 'Modification Requested')], default='pending', max_length=25),
        ),
        migrations.CreateModel(
            name='DecisionReviewEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approve', 'Approved'), ('reject', 'Rejected'), ('request_evidence', 'Requested More Evidence'), ('request_modification', 'Requested Pathway Modification'), ('resubmit', 'Resubmitted for Review')], max_length=25)),
                ('previous_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('approved_with_conditions', 'Approved with Conditions'), ('rejected', 'Rejected'), ('evidence_requested', 'Evidence Requested'), ('modification_requested', 'Modification Requested')], max_length=25)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('approved_with_conditions', 'Approved with Conditions'), ('rejected', 'Rejected'), ('evidence_requested', 'Evidence Requested'), ('modification_requested', 'Modification Requested')], max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_events', to='waste_to_value_capital_allocation_engine.capitalallocationdecision')),
            ],
            options={
                'verbose_name': 'Decision Review Event',
                'verbose_name_plural': 'Decision Review Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
