# Generated by Django 5.2.14 on 2026-07-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waste_to_value_capital_allocation_engine', '0002_alter_capitalallocationdecision_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationalloss',
            name='loss_type',
            field=models.CharField(choices=[('food_spoilage', 'Food spoilage'), ('meat_spoilage', 'Meat spoilage'), ('cold_chain_failure', 'Cold-chain failure'), ('excess_inventory', 'Excess inventory'), ('overproduction', 'Overproduction'), ('energy_loss', 'Energy loss'), ('heat_loss', 'Heat loss'), ('water_leakage', 'Water leakage'), ('material_waste', 'Material waste'), ('industrial_by_products', 'Industrial by-products'), ('idle_machinery', 'Idle machinery'), ('idle_buildings', 'Idle buildings'), ('unused_warehouse_capacity', 'Unused warehouse capacity'), ('empty_transport_capacity', 'Empty transport capacity'), ('production_downtime', 'Production downtime'), ('defect_rejection_losses', 'Defect and rejection losses'), ('maintenance_inefficiency', 'Maintenance inefficiency'), ('underused_renewable_generation', 'Underused renewable generation'), ('curtailed_energy', 'Curtailed energy'), ('unmatched_surplus', 'Unmatched surplus'), ('avoidable_emissions', 'Avoidable emissions'), ('worker_safety_exposure', 'Worker safety exposure'), ('community_harm', 'Community harm'), ('missing_technology_adoption', 'Missing research or technology adoption')], max_length=40),
        ),
    ]
