/**
 * Tazkiyah 114 — seed content for modules 31-60.
 *
 * Seed-ready structured concepts that future developers can turn into pages.
 * NOTE: all interpretive content is "reflection inspired by Qur'anic themes" and is
 * pending scholar review. Dua lines referenced by these modules are PROMPTS, not
 * narrated/authentic du'as unless explicitly sourced and reviewed.
 *
 * See docs/tazkiyah-114-modules-31-60.md and docs/tazkiyah-114-safety-principles.md.
 *
 * The data array below is intentionally strict-JSON-compatible so it can also be
 * consumed as JSON if preferred.
 */

export type SafetyLevel = "standard" | "sensitive";
export type PremiumPotential = "low" | "medium" | "high";

export interface ModuleSeed {
  id: number;
  slug: string;
  title: string;
  category: string;
  shortDescription: string;
  userNeed: string;
  entryQuestions: string[];
  coreFlow: string[];
  contentBlocks: string[];
  recommendedComponents: string[];
  safetyLevel: SafetyLevel;
  reviewRequired: boolean;
  sensitiveTopics: string[];
  futureRoutes: string[];
  premiumPotential: PremiumPotential;
}

export const moduleSeeds: ModuleSeed[] = [
  {
    "id": 31,
    "slug": "heart-diseases-library",
    "title": "Heart Diseases Library",
    "category": "tazkiyah-diagnosis",
    "shortDescription": "A calm, browsable library of diseases of the heart with reflection and repair.",
    "userNeed": "Something is off in my heart and I cannot name it.",
    "entryQuestions": ["What keeps repeating in your reactions?", "Which feeling do you avoid?", "What would you like your heart to be free of?"],
    "coreFlow": ["Surface a likely heart disease", "Read a gentle reflection", "See the opposite virtue", "Choose one repair action", "Begin a 7-day practice"],
    "contentBlocks": ["How it shows up", "What it quietly destroys", "Qur'anic reminder", "Opposite virtue", "One repair action"],
    "recommendedComponents": ["DiseaseLibraryGrid", "DiseaseCard", "VirtueLink"],
    "safetyLevel": "standard",
    "reviewRequired": true,
    "sensitiveTopics": [],
    "futureRoutes": ["/tazkiyah/heart-diseases", "/tazkiyah/heart-diseases/[slug]"],
    "premiumPotential": "medium"
  },
  {
    "id": 32,
    "slug": "virtue-builder",
    "title": "Virtue Builder",
    "category": "virtues",
    "shortDescription": "Build a target virtue through small daily training and self-checks.",
    "userNeed": "I want to grow in patience, gratitude or sincerity but do not know how.",
    "entryQuestions": ["Which virtue do you most want to build?", "Where do you fall short of it?", "What would living it look like this week?"],
    "coreFlow": ["Choose a virtue", "See its opposite disease", "Do a daily practice", "Answer a self-check", "Complete a 7-day exercise"],
    "contentBlocks": ["Meaning", "Opposite disease", "Qur'anic theme", "Daily practice", "7-day training"],
    "recommendedComponents": ["VirtueTrainer", "SelfCheckList", "SevenDayPlan"],
    "safetyLevel": "standard",
    "reviewRequired": true,
    "sensitiveTopics": [],
    "futureRoutes": ["/tazkiyah/virtues/[slug]"],
    "premiumPotential": "medium"
  },
  {
    "id": 33,
    "slug": "my-current-test",
    "title": "My Current Test",
    "category": "reflection",
    "shortDescription": "Name the test you are in right now and find Qur'anic companionship for it.",
    "userNeed": "I am going through something and do not know how to hold it with faith.",
    "entryQuestions": ["What is heaviest right now?", "How long has it lasted?", "What are you most afraid of in it?"],
    "coreFlow": ["Name the current test", "Reflect on what it may be inviting", "Read an anchor ayah", "Take one step", "Make a dua prompt"],
    "contentBlocks": ["Naming the test", "What it may be inviting", "Ayah reflection", "One action", "Dua prompt"],
    "recommendedComponents": ["GentleStepper", "PathwayResult"],
    "safetyLevel": "standard",
    "reviewRequired": true,
    "sensitiveTopics": ["hardship"],
    "futureRoutes": ["/tazkiyah/my-current-test"],
    "premiumPotential": "low"
  },
  {
    "id": 34,
    "slug": "quranic-stories-as-life-mirrors",
    "title": "Qur'anic Stories as Life Mirrors",
    "category": "stories",
    "shortDescription": "Use Qur'anic narratives as mirrors for present struggles.",
    "userNeed": "I feel alone in this. Has anyone been through something like it?",
    "entryQuestions": ["What experience are you living through?", "What do you most need from a story right now?"],
    "coreFlow": ["Find a story that mirrors your experience", "Read its theme gently", "Reflect", "Take one action"],
    "contentBlocks": ["The human experience mirrored", "Gentle theme", "Ayah anchors", "Reflection", "One action"],
    "recommendedComponents": ["StoryMirrorCard", "MirrorTagFilter"],
    "safetyLevel": "standard",
    "reviewRequired": true,
    "sensitiveTopics": ["betrayal", "hardship"],
    "futureRoutes": ["/tazkiyah/stories", "/tazkiyah/stories/[slug]"],
    "premiumPotential": "medium"
  },
  {
    "id": 35,
    "slug": "prophet-yusuf-pathway",
    "title": "Prophet Yusuf Pathway",
    "category": "stories",
    "shortDescription": "A flagship staged pathway through Surah Yusuf: betrayal, patience, restraint, reunion.",
    "userNeed": "I have been betrayed or wronged and feel stuck in an unfair season.",
    "entryQuestions": ["Who or what hurt you?", "What are you tempted to give up on?", "What would beautiful patience look like here?"],
    "coreFlow": ["The pit", "The test", "The prison", "The rise", "Forgiveness"],
    "contentBlocks": ["Stage theme", "Ayah anchors", "Reflection question", "One action", "Dua prompt"],
    "recommendedComponents": ["StagedPathway", "StageProgress"],
    "safetyLevel": "standard",
    "reviewRequired": true,
    "sensitiveTopics": ["betrayal"],
    "futureRoutes": ["/tazkiyah/pathways/yusuf"],
    "premiumPotential": "high"
  },
  {
    "id": 36,
    "slug": "dua-builder",
    "title": "Du'a Builder",
    "category": "dua",
    "shortDescription": "Help a user shape their own honest du'a in their own words, anchored to a need.",
    "userNeed": "I do not know what to say to Allah, or my du'a feels empty.",
    "entryQuestions": ["What do you most need right now?", "What do you want to thank Allah for first?", "What are you afraid to ask for?"],
    "coreFlow": ["Choose a need", "Praise", "Confess", "Ask", "Trust and close in your own words"],
    "contentBlocks": ["Du'a prompts (not narrated du'as)", "A simple structure to follow", "Encouragement to use your own words"],
    "recommendedComponents": ["DuaBuilderWizard", "DuaPromptCard"],
    "safetyLevel": "standard",
    "reviewRequired": true,
    "sensitiveTopics": ["authenticity-of-dua"],
    "futureRoutes": ["/tazkiyah/dua-builder"],
    "premiumPotential": "medium"
  },
  {
    "id": 37,
    "slug": "istikhara-decision-journal",
    "title": "Istikhara + Decision Journal",
    "category": "decisions",
    "shortDescription": "Support sincere decision-making with istikhara and structured reflection (non-fatwa).",
    "userNeed": "I have a big decision and I am scared or confused.",
    "entryQuestions": ["Is it halal?", "Does it increase taqwa?", "Does it harm anyone?", "What is the real motive: fear, pride, envy, greed, or sincerity?", "Have you made istikhara and sought counsel?"],
    "coreFlow": ["Reflect through the questions", "Make istikhara", "Seek qualified counsel", "Record the decision", "Revisit later"],
    "contentBlocks": ["Reflection scaffold", "Istikhara reminder (not dreams-only)", "Decision journal", "Revisit prompt"],
    "recommendedComponents": ["DecisionCompass", "DecisionJournal"],
    "safetyLevel": "standard",
    "reviewRequired": true,
    "sensitiveTopics": ["decision-pressure"],
    "futureRoutes": ["/tazkiyah/decision-compass"],
    "premiumPotential": "high"
  },
  {
    "id": 38,
    "slug": "repentance-room",
    "title": "Repentance Room",
    "category": "tawbah",
    "shortDescription": "A gentle pathway for people drowning in guilt and wanting to return to Allah.",
    "userNeed": "I sinned, I feel ashamed, and I fear I cannot come back.",
    "entryQuestions": ["What happened?", "What trigger led to it?", "What shame-based lie are you believing?", "What is one boundary you can create now?"],
    "coreFlow": ["Name the sin without despair", "Remember Allah's mercy", "Make tawbah", "Block one trigger", "Replace with one good deed", "Track one day of return"],
    "contentBlocks": ["Do not let shame become distance.", "Return immediately.", "Change one condition.", "Do one good deed after it."],
    "recommendedComponents": ["GentleStepper", "DuaPromptCard", "TriggerBlocker", "TawbahTracker"],
    "safetyLevel": "sensitive",
    "reviewRequired": true,
    "sensitiveTopics": ["sin", "addiction", "despair", "religious guilt"],
    "futureRoutes": ["/tazkiyah/repentance-room"],
    "premiumPotential": "high"
  },
  {
    "id": 39,
    "slug": "salah-repair-pathway",
    "title": "Salah Repair Pathway",
    "category": "salah",
    "shortDescription": "Help users rebuild a consistent, present prayer life without shame.",
    "userNeed": "I keep missing salah, or I pray but my heart is not in it.",
    "entryQuestions": ["Is the gap consistency or presence?", "What gets in the way most?", "What is one tiny change you could keep?"],
    "coreFlow": ["Diagnose the gap", "Choose one small fix", "Practise presence", "Track prayers gently for 7 days"],
    "contentBlocks": ["The barrier", "One tiny next step", "Presence tips", "Ayah reflection", "Tracker"],
    "recommendedComponents": ["SalahTracker", "GentleStepper"],
    "safetyLevel": "standard",
    "reviewRequired": true,
    "sensitiveTopics": ["religious guilt"],
    "futureRoutes": ["/tazkiyah/salah-repair"],
    "premiumPotential": "medium"
  },
  {
    "id": 40,
    "slug": "digital-nafs-repair",
    "title": "Digital Nafs / Social Media Repair",
    "category": "digital",
    "shortDescription": "Repair the relationship with the phone: comparison, validation-seeking, wasted time.",
    "userNeed": "I scroll for hours and feel worse, and I compare myself constantly.",
    "entryQuestions": ["What triggers your scrolling?", "How do you feel afterward?", "What boundary feels doable?"],
    "coreFlow": ["Name the digital trigger", "Set one boundary", "Choose a halal replacement", "Track for 7 days"],
    "contentBlocks": ["The whisper vs the truth", "One boundary", "One replacement", "Reflection", "Tracker"],
    "recommendedComponents": ["TriggerBlocker", "HabitTracker"],
    "safetyLevel": "sensitive",
    "reviewRequired": true,
    "sensitiveTopics": ["addiction", "comparison"],
    "futureRoutes": ["/tazkiyah/digital-nafs"],
    "premiumPotential": "medium"
  },
  {
    "id": 41,
    "slug": "marriage-family-repair",
    "title": "Marriage and Family Repair",
    "category": "relationships",
    "shortDescription": "Reflection pathways for tension, distance and patience in marriage and family.",
    "userNeed": "There is constant conflict or coldness at home and I do not know how to hold it.",
    "entryQuestions": ["What does Allah ask of you in this relationship?", "What boundary is still allowed?", "What character do you need here?"],
    "coreFlow": ["Choose character before reaction", "Hold the allowed boundary", "Take one repair action", "Make a dua prompt"],
    "contentBlocks": ["Character before reaction", "The allowed boundary", "One repair action", "Dua prompt", "Safety note: patience is never acceptance of abuse"],
    "recommendedComponents": ["RelationshipPathway", "BoundaryCard", "SafetyBanner"],
    "safetyLevel": "sensitive",
    "reviewRequired": true,
    "sensitiveTopics": ["abuse", "marital conflict", "family harm"],
    "futureRoutes": ["/tazkiyah/relationships/marriage-family"],
    "premiumPotential": "high"
  },
  {
    "id": 42,
    "slug": "parenting-tazkiyah",
    "title": "Motherhood / Fatherhood Tazkiyah",
    "category": "parenting",
    "shortDescription": "Support parents in raising character while repairing their own hearts.",
    "userNeed": "I lose my temper with my kids and feel guilty as a parent.",
    "entryQuestions": ["What do you struggle with most as a parent?", "What character do you want to model this week?"],
    "coreFlow": ["Parent self-check", "Choose a weekly character theme", "Do one family action", "Make a dua prompt"],
    "contentBlocks": ["Parent self-check", "Child character theme", "One family action", "Dua prompt"],
    "recommendedComponents": ["FamilyThemeCard", "ParentSelfCheck"],
    "safetyLevel": "standard",
    "reviewRequired": true,
    "sensitiveTopics": ["parenting guilt"],
    "futureRoutes": ["/tazkiyah/parenting"],
    "premiumPotential": "high"
  },
  {
    "id": 43,
    "slug": "grief-and-loss-pathway",
    "title": "Grief and Loss Pathway",
    "category": "grief",
    "shortDescription": "Qur'anic companionship in bereavement and loss, without rushing the pain.",
    "userNeed": "I lost someone or something and I cannot carry it.",
    "entryQuestions": ["What did you lose?", "What do you need permission to feel?", "What is one small thing that could steady you today?"],
    "coreFlow": ["Acknowledge the grief", "Hold an anchor verse", "Take one tiny step", "Make a dua prompt", "Allow yourself to grieve"],
    "contentBlocks": ["You are allowed to grieve.", "An anchor verse", "One tiny step", "Dua prompt", "You are not alone; support is available"],
    "recommendedComponents": ["GentlePacing", "SupportBanner"],
    "safetyLevel": "sensitive",
    "reviewRequired": true,
    "sensitiveTopics": ["grief", "bereavement", "trauma"],
    "futureRoutes": ["/tazkiyah/grief"],
    "premiumPotential": "medium"
  },
  {
    "id": 44,
    "slug": "anger-repair-pathway",
    "title": "Anger Repair Pathway",
    "category": "character",
    "shortDescription": "Move from reactive anger to restraint (hilm) and mercy.",
    "userNeed": "I explode and regret it, and my anger hurts people I love.",
    "entryQuestions": ["What triggers your anger most?", "What happens in your body before it?", "Who does it affect?"],
    "coreFlow": ["Map the trigger", "Practise the pause", "Model restraint", "Take one repair action", "Track for 7 days"],
    "contentBlocks": ["Trigger map", "The pause", "Restraint as strength", "One repair", "Dua prompt"],
    "recommendedComponents": ["PausePractice", "HabitTracker"],
    "safetyLevel": "sensitive",
    "reviewRequired": true,
    "sensitiveTopics": ["anger", "harm to others"],
    "futureRoutes": ["/tazkiyah/anger-repair"],
    "premiumPotential": "medium"
  },
  {
    "id": 45,
    "slug": "envy-repair-pathway",
    "title": "Envy Repair Pathway",
    "category": "character",
    "shortDescription": "From envy (hasad) to contentment (qana'ah) and wanting good for others.",
    "userNeed": "I feel diminished by other people's blessings.",
    "entryQuestions": ["Is it lack, or comparison?", "What blessing have you stopped noticing?", "Can you want good for them?"],
    "coreFlow": ["Catch the comparison", "Reframe through provision themes", "Make dua for the person", "Practise gratitude"],
    "contentBlocks": ["Comparison vs trust", "Refuge from envy", "Praise or dua for the other", "Gratitude action"],
    "recommendedComponents": ["ReframeCard", "GratitudeTracker"],
    "safetyLevel": "standard",
    "reviewRequired": true,
    "sensitiveTopics": ["envy", "comparison"],
    "futureRoutes": ["/tazkiyah/envy-repair"],
    "premiumPotential": "medium"
  },
  {
    "id": 46,
    "slug": "money-without-losing-your-soul",
    "title": "Money Without Losing Your Soul",
    "category": "rizq",
    "shortDescription": "Pursue rizq and ambition without riba, corruption, arrogance, or fear-driven shortcuts.",
    "userNeed": "I am scared about money and tempted to compromise my deen.",
    "entryQuestions": ["What decision are you making from fear rather than trust?", "Where are you tempted to cut a corner on your deen?", "What is one halal effort you can make today?"],
    "coreFlow": ["Reframe money without fear", "Reaffirm halal boundaries", "Make one halal effort", "Give a small sadaqah", "Entrust the outcome"],
    "contentBlocks": ["Effort as worship", "Tawakkul is not laziness", "Halal boundary", "One action", "Dua prompt"],
    "recommendedComponents": ["ReframeWall", "DoDontCard"],
    "safetyLevel": "sensitive",
    "reviewRequired": true,
    "sensitiveTopics": ["debt", "riba", "financial fear"],
    "futureRoutes": ["/tazkiyah/money"],
    "premiumPotential": "high"
  },
  {
    "id": 47,
    "slug": "quran-and-emotional-states",
    "title": "Qur'an and Emotional States",
    "category": "emotions",
    "shortDescription": "A fast index from an emotion to Qur'anic companionship.",
    "userNeed": "I just need something for how I feel right now.",
    "entryQuestions": ["What are you feeling right now?", "How strong is it?", "Do you need calm, hope, or courage?"],
    "coreFlow": ["Pick an emotion", "Hold one verse", "Reflect once", "Take one action", "Make a dua prompt"],
    "contentBlocks": ["Emotion", "Anchor verse", "Reflection", "Action", "Dua prompt"],
    "recommendedComponents": ["EmotionPicker", "AnchorVerseCard"],
    "safetyLevel": "standard",
    "reviewRequired": true,
    "sensitiveTopics": ["emotional distress"],
    "futureRoutes": ["/tazkiyah/emotions/[state]"],
    "premiumPotential": "medium"
  },
  {
    "id": 48,
    "slug": "my-allah-assumption",
    "title": "My Allah Assumption",
    "category": "belief",
    "shortDescription": "Examine and repair your assumption about Allah, from fear or distance to good expectation.",
    "userNeed": "I feel like Allah is angry with me or has forgotten me.",
    "entryQuestions": ["What do you assume Allah thinks of you?", "Where did that belief come from?", "What would good expectation feel like?"],
    "coreFlow": ["Name the assumption", "Reflect on mercy and nearness", "Practise good expectation", "Make a dua prompt"],
    "contentBlocks": ["The assumption", "Reminder of mercy and nearness", "Reflection", "One practice", "Dua prompt"],
    "recommendedComponents": ["AssumptionReframe"],
    "safetyLevel": "standard",
    "reviewRequired": true,
    "sensitiveTopics": ["despair", "religious guilt"],
    "futureRoutes": ["/tazkiyah/allah-assumption"],
    "premiumPotential": "medium"
  },
  {
    "id": 49,
    "slug": "from-reaction-to-revelation",
    "title": "From Reaction to Revelation",
    "category": "self-regulation",
    "shortDescription": "Train the pause between impulse and action, responding from values not reactivity.",
    "userNeed": "I react instantly and regret it.",
    "entryQuestions": ["What pulls a reaction out of you?", "What do you wish you did instead?"],
    "coreFlow": ["Catch the impulse", "Pause", "Recall a relevant theme", "Choose the response", "Reflect"],
    "contentBlocks": ["The trigger", "The pause", "The chosen response", "Reflection", "Dua prompt"],
    "recommendedComponents": ["PausePractice"],
    "safetyLevel": "standard",
    "reviewRequired": true,
    "sensitiveTopics": [],
    "futureRoutes": ["/tazkiyah/reaction-to-revelation"],
    "premiumPotential": "low"
  },
  {
    "id": 50,
    "slug": "daily-mizan",
    "title": "Daily Mizan",
    "category": "daily-practice",
    "shortDescription": "The daily morning and evening reflection practice (the balance).",
    "userNeed": "I drift through days without intention or reflection.",
    "entryQuestions": ["What is your intention today?", "Which weakness will you guard?", "Which Name of Allah will you carry?"],
    "coreFlow": ["Morning intention", "Name a weakness to guard", "Carry a Name of Allah", "Commit to one action", "Evening muhasabah"],
    "contentBlocks": ["Morning set", "Evening muhasabah set", "Private journal capture"],
    "recommendedComponents": ["MorningMizan", "EveningMuhasabah"],
    "safetyLevel": "standard",
    "reviewRequired": true,
    "sensitiveTopics": [],
    "futureRoutes": ["/tazkiyah/daily-mizan"],
    "premiumPotential": "high"
  },
  {
    "id": 51,
    "slug": "quranic-boundaries",
    "title": "Qur'anic Boundaries",
    "category": "boundaries",
    "shortDescription": "Reflection on healthy boundaries grounded in justice, dignity and mercy.",
    "userNeed": "People keep crossing my limits and I feel guilty saying no.",
    "entryQuestions": ["What boundary keeps being crossed?", "Why is protecting it just?", "How can you hold it with character?"],
    "coreFlow": ["Clarify the boundary", "See why it is allowed", "Hold it with ihsan", "Take one action"],
    "contentBlocks": ["The allowed boundary", "Justice vs harm", "Holding it with ihsan", "One action", "Safety note: sabr is not silence against injustice"],
    "recommendedComponents": ["BoundaryCard", "SafetyBanner"],
    "safetyLevel": "sensitive",
    "reviewRequired": true,
    "sensitiveTopics": ["abuse", "injustice"],
    "futureRoutes": ["/tazkiyah/boundaries"],
    "premiumPotential": "medium"
  },
  {
    "id": 52,
    "slug": "amanah-of-the-body",
    "title": "Amanah of the Body",
    "category": "amanah",
    "shortDescription": "Treating the body as a trust: rest, health, gratitude, modesty (non-medical).",
    "userNeed": "I neglect or abuse my body, or I feel shame about it.",
    "entryQuestions": ["How have you been treating your body?", "What is one act of care you can offer it today?"],
    "coreFlow": ["See the body as a trust", "Do one act of care", "Practise gratitude for health", "Make a dua prompt"],
    "contentBlocks": ["Body as trust", "One care action", "Gratitude practice", "Dua prompt"],
    "recommendedComponents": ["AmanahCard", "SupportBanner"],
    "safetyLevel": "sensitive",
    "reviewRequired": true,
    "sensitiveTopics": ["eating disorders", "self-harm", "body shame"],
    "futureRoutes": ["/tazkiyah/amanah/body"],
    "premiumPotential": "medium"
  },
  {
    "id": 53,
    "slug": "amanah-of-time",
    "title": "Amanah of Time",
    "category": "amanah",
    "shortDescription": "Time as a trust: barakah, presence and intentional use.",
    "userNeed": "My time leaks away and I have nothing to show Allah.",
    "entryQuestions": ["Where does your time leak most?", "What would you redirect one hour toward?"],
    "coreFlow": ["See time as a trust", "Audit one hour", "Redirect it", "Reflect"],
    "contentBlocks": ["Time as trust", "One redirected hour", "Reflection", "Dua prompt"],
    "recommendedComponents": ["AmanahCard", "HourAudit"],
    "safetyLevel": "standard",
    "reviewRequired": true,
    "sensitiveTopics": [],
    "futureRoutes": ["/tazkiyah/amanah/time"],
    "premiumPotential": "medium"
  },
  {
    "id": 54,
    "slug": "amanah-of-speech",
    "title": "Amanah of Speech",
    "category": "amanah",
    "shortDescription": "The tongue as a trust: truthfulness, gentleness, restraint, no backbiting.",
    "userNeed": "I gossip, lie, speak harshly, or complain constantly.",
    "entryQuestions": ["Which speech habit troubles you most?", "Who does it affect?", "What is one restraint you can practise?"],
    "coreFlow": ["Pick one speech habit", "Choose one restraint", "Make one repair", "Track for 7 days"],
    "contentBlocks": ["Speech as trust", "One restraint", "One repair", "Dua prompt"],
    "recommendedComponents": ["AmanahCard", "HabitTracker"],
    "safetyLevel": "standard",
    "reviewRequired": true,
    "sensitiveTopics": [],
    "futureRoutes": ["/tazkiyah/amanah/speech"],
    "premiumPotential": "low"
  },
  {
    "id": 55,
    "slug": "amanah-of-wealth",
    "title": "Amanah of Wealth",
    "category": "amanah",
    "shortDescription": "Wealth as a trust: halal earning, sadaqah, no riba, generosity without showing off.",
    "userNeed": "How do I hold money without it holding me?",
    "entryQuestions": ["Where does money have a grip on your heart?", "What is one act of ethical generosity you can do?"],
    "coreFlow": ["See wealth as a trust", "Give without riya", "Correct one halal boundary", "Reflect"],
    "contentBlocks": ["Wealth as trust", "Giving without riya", "Halal boundary", "One action", "Dua prompt"],
    "recommendedComponents": ["AmanahCard", "DoDontCard"],
    "safetyLevel": "standard",
    "reviewRequired": true,
    "sensitiveTopics": ["riba"],
    "futureRoutes": ["/tazkiyah/amanah/wealth"],
    "premiumPotential": "medium"
  },
  {
    "id": 56,
    "slug": "amanah-of-power",
    "title": "Amanah of Power",
    "category": "amanah",
    "shortDescription": "Authority and influence as a trust: justice, humility, shura, no corruption.",
    "userNeed": "I have authority and I fear arrogance or corruption.",
    "entryQuestions": ["Where could your authority harm or help?", "Whose voice are you not hearing?", "What is one just, humble action?"],
    "coreFlow": ["Run a leadership self-check", "Choose a just, humble action", "Practise shura", "Reflect"],
    "contentBlocks": ["Power as trust", "Justice and humility", "Shura", "One action", "Dua prompt"],
    "recommendedComponents": ["AmanahCard", "LeaderSelfCheck"],
    "safetyLevel": "standard",
    "reviewRequired": true,
    "sensitiveTopics": ["abuse of power"],
    "futureRoutes": ["/tazkiyah/amanah/power"],
    "premiumPotential": "medium"
  },
  {
    "id": 57,
    "slug": "the-4-return-paths",
    "title": "The 4 Return Paths",
    "category": "tawbah",
    "shortDescription": "Four gentle on-ramps back to Allah after distance, through mercy, fear, love and gratitude.",
    "userNeed": "I want to return but do not know where to start.",
    "entryQuestions": ["Which doorway feels most open today: mercy, love, awe, or gratitude?"],
    "coreFlow": ["Choose a doorway", "Hold an anchor verse", "Take one step home", "Make a dua prompt"],
    "contentBlocks": ["The four doorways", "An anchor verse each", "One step", "Dua prompt"],
    "recommendedComponents": ["ReturnDoorways"],
    "safetyLevel": "standard",
    "reviewRequired": true,
    "sensitiveTopics": ["religious guilt"],
    "futureRoutes": ["/tazkiyah/return-paths"],
    "premiumPotential": "low"
  },
  {
    "id": 58,
    "slug": "repair-by-time-of-day",
    "title": "Repair by Time of Day",
    "category": "daily-practice",
    "shortDescription": "Match a short repair practice to the moment: fajr, midday, asr, maghrib, before sleep.",
    "userNeed": "I want a tiny practice that fits the moment I am in.",
    "entryQuestions": ["What time of day is it for you?", "How much time do you have right now?"],
    "coreFlow": ["Choose the time window", "Read one verse", "Do one micro-action", "Make a dua prompt"],
    "contentBlocks": ["Time-window theme", "Micro-action", "Dua prompt"],
    "recommendedComponents": ["TimeOfDayCard"],
    "safetyLevel": "standard",
    "reviewRequired": true,
    "sensitiveTopics": [],
    "futureRoutes": ["/tazkiyah/by-time"],
    "premiumPotential": "low"
  },
  {
    "id": 59,
    "slug": "seasonal-modes",
    "title": "Ramadan / Dhul Hijjah / Friday Modes",
    "category": "seasonal",
    "shortDescription": "Seasonal modes that reshape the daily companion for blessed times.",
    "userNeed": "I want to make the most of Ramadan, the ten days, or Jumu'ah.",
    "entryQuestions": ["Which season are you in?", "What is your one hope for it?"],
    "coreFlow": ["Enable a seasonal mode", "Follow a daily focus", "Reflect", "Make a dua prompt"],
    "contentBlocks": ["Seasonal theme", "Daily focus", "Reflection", "Dua prompt (sourced du'as labelled separately)"],
    "recommendedComponents": ["SeasonModeBanner", "SeasonDayCard"],
    "safetyLevel": "standard",
    "reviewRequired": true,
    "sensitiveTopics": [],
    "futureRoutes": ["/tazkiyah/modes/[season]"],
    "premiumPotential": "high"
  },
  {
    "id": 60,
    "slug": "community-circles",
    "title": "Community Circles",
    "category": "community",
    "shortDescription": "Small, safe, purpose-led circles (family, sisters, youth, founders, grief), not a feed.",
    "userNeed": "I want support and accountability without social-media toxicity.",
    "entryQuestions": ["What kind of circle would help you?", "What would you like to be accountable for?"],
    "coreFlow": ["Join a small circle", "Start a shared 7-day challenge", "Share an anonymous reflection", "Mark I benefited from this"],
    "contentBlocks": ["Circle purpose", "Shared challenge", "Accountability prompts", "No public metrics"],
    "recommendedComponents": ["CircleRoom", "GroupChallenge", "BenefitedButton"],
    "safetyLevel": "sensitive",
    "reviewRequired": true,
    "sensitiveTopics": ["moderation", "grief", "abuse disclosure"],
    "futureRoutes": ["/tazkiyah/circles", "/tazkiyah/circles/[id]"],
    "premiumPotential": "high"
  }
];

export default moduleSeeds;
