# Generated by Django 5.2.14 on 2026-07-04 05:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=100)),
                ('collaboration_mode', models.CharField(choices=[('solo', 'Solo'), ('parallel', 'Parallel'), ('handoff', 'Handoff'), ('council', 'Council'), ('escalation', 'Escalation')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('input_summary', models.TextField(blank=True)),
                ('output_summary', models.TextField(blank=True)),
                ('position_summary', models.TextField(blank=True, help_text="The agent's stated position/recommendation.")),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('confidence_breakdown', models.JSONField(blank=True, default=dict, help_text='Canonical shape from services.confidence.build_confidence_breakdown().')),
                ('evidence_refs', models.JSONField(blank=True, default=list)),
                ('missing_data', models.JSONField(blank=True, default=list)),
                ('risk_flags', models.JSONField(blank=True, default=list)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Agent Task',
                'verbose_name_plural': 'Agent Tasks',
                'ordering': ['run', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CouncilRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('question', models.TextField(help_text='The user goal this run was opened to answer.')),
                ('task_category', models.CharField(help_text='Routing category used to select agents.', max_length=60)),
                ('is_simulated', models.BooleanField(default=True, help_text='Always True today: no live LLM execution runtime exists in this repository.')),
                ('status', models.CharField(choices=[('open', 'Open'), ('decided', 'Decided'), ('reopened', 'Reopened'), ('closed', 'Closed')], default='open', max_length=20)),
                ('selected_agents', models.JSONField(default=list, help_text='List of {agent_name, selected, reason} — every agent considered, not just the chosen ones.')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Council Run',
                'verbose_name_plural': 'Council Runs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouncilDisagreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(choices=[('factual', 'Factual disagreement'), ('assumption', 'Assumption disagreement'), ('evidence', 'Evidence disagreement'), ('risk_tolerance', 'Risk tolerance disagreement'), ('timing', 'Timing disagreement'), ('domain', 'Domain conflict')], max_length=20)),
                ('evidence_used', models.JSONField(blank=True, default=list)),
                ('resolution_method', models.CharField(choices=[('resolve_automatically', 'Resolve automatically'), ('request_more_evidence', 'Request more evidence'), ('ask_another_agent', 'Ask another agent'), ('require_human_review', 'Require human review'), ('preserve_minority_opinion', 'Preserve minority opinion')], max_length=30)),
                ('final_decision_summary', models.TextField(blank=True)),
                ('minority_opinion_retained', models.BooleanField(default=True)),
                ('position_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disagreements_as_a', to='ai_agent_council.agenttask')),
                ('position_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disagreements_as_b', to='ai_agent_council.agenttask')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disagreements', to='ai_agent_council.councilrun')),
            ],
            options={
                'verbose_name': 'Council Disagreement',
                'verbose_name_plural': 'Council Disagreements',
                'ordering': ['run', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CouncilDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('approved_with_conditions', 'Approved with Conditions'), ('rejected', 'Rejected'), ('suspended', 'Suspended'), ('reopened', 'Reopened'), ('superseded', 'Superseded')], default='draft', max_length=30)),
                ('summary', models.TextField()),
                ('majority_agents', models.JSONField(blank=True, default=list)),
                ('minority_agents', models.JSONField(blank=True, default=list)),
                ('minority_reason', models.TextField(blank=True)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('confidence_breakdown', models.JSONField(blank=True, default=dict)),
                ('human_approval_required', models.BooleanField(default=True)),
                ('human_approved', models.BooleanField(blank=True, null=True)),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='ai_agent_council.councilrun')),
            ],
            options={
                'verbose_name': 'Council Decision',
                'verbose_name_plural': 'Council Decisions',
            },
        ),
        migrations.AddField(
            model_name='agenttask',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='ai_agent_council.councilrun'),
        ),
        migrations.CreateModel(
            name='AgentHandoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_agent', models.CharField(max_length=100)),
                ('receiver_agent', models.CharField(max_length=100)),
                ('reason', models.TextField()),
                ('evidence_attached', models.JSONField(blank=True, default=list)),
                ('unresolved_questions', models.JSONField(blank=True, default=list)),
                ('confidence_at_handoff', models.FloatField(blank=True, null=True)),
                ('required_output', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handoffs', to='ai_agent_council.councilrun')),
            ],
            options={
                'verbose_name': 'Agent Handoff',
                'verbose_name_plural': 'Agent Handoffs',
                'ordering': ['run', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CrossExaminationExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questioner_agent', models.CharField(max_length=100)),
                ('target_agent', models.CharField(max_length=100)),
                ('challenge_type', models.CharField(max_length=60)),
                ('reason', models.TextField()),
                ('requested_evidence', models.JSONField(blank=True, default=list)),
                ('response_answer', models.TextField(blank=True)),
                ('response_evidence', models.JSONField(blank=True, default=list)),
                ('response_confidence', models.FloatField(blank=True, null=True)),
                ('unresolved_uncertainty', models.TextField(blank=True)),
                ('sequence', models.PositiveIntegerField(default=0)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cross_examinations', to='ai_agent_council.councilrun')),
            ],
            options={
                'verbose_name': 'Cross-Examination Exchange',
                'verbose_name_plural': 'Cross-Examination Exchanges',
                'ordering': ['run', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='DecisionMemoryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_decision_summary', models.TextField()),
                ('reason', models.TextField()),
                ('open_questions', models.JSONField(blank=True, default=list)),
                ('unresolved_risks', models.JSONField(blank=True, default=list)),
                ('review_trigger', models.TextField(blank=True, help_text='What new evidence/event would justify reopening this decision.')),
                ('reopened', models.BooleanField(default=False)),
                ('reopened_reason', models.TextField(blank=True)),
                ('new_evidence_summary', models.TextField(blank=True)),
                ('updated_decision_summary', models.TextField(blank=True)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('decision', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memory_entry', to='ai_agent_council.councildecision')),
            ],
            options={
                'verbose_name': 'Decision Memory Entry',
                'verbose_name_plural': 'Decision Memory Entries',
            },
        ),
    ]
