# Generated by Django 5.2.14 on 2026-06-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, help_text='Short summary of the submission')),
                ('source_type', models.CharField(choices=[('heating_household', 'Heating — Household Application'), ('heating_akimat', 'Heating — Akimat / Partnership'), ('heating_company', 'Heating — Company Sponsorship'), ('home_assessment', 'Heating — Home Assessment'), ('access_request', 'Investor Readiness / Access Request'), ('review_request', 'EcoIQ Review Request'), ('profile_claim', 'Company Profile Claim'), ('newsletter', 'Newsletter Signup'), ('contact', 'Contact Form'), ('other', 'Other')], db_index=True, default='other', max_length=40)),
                ('source_model', models.CharField(blank=True, help_text='app_label.model of the related object', max_length=120)),
                ('source_object_id', models.CharField(blank=True, max_length=64)),
                ('admin_url', models.CharField(blank=True, help_text='Admin change URL of the related object', max_length=300)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('archived', 'Archived')], db_index=True, default='unread', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=10)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='notificatio_status_6198c6_idx')],
            },
        ),
    ]
