# Generated by Django 5.2.14 on 2026-07-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_adminnotification_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnotification',
            name='source_type',
            field=models.CharField(choices=[('heating_household', 'Heating — Household Application'), ('heating_akimat', 'Heating — Akimat / Partnership'), ('heating_company', 'Heating — Company Sponsorship'), ('home_assessment', 'Heating — Home Assessment'), ('access_request', 'Investor Readiness / Access Request'), ('review_request', 'EcoIQ Review Request'), ('profile_claim', 'Company Profile Claim'), ('newsletter', 'Newsletter Signup'), ('contact', 'Contact Form'), ('background_task', 'Background Intelligence Task'), ('good_agents_opportunity', '114 Good Agents — Opportunity / Discovery Event'), ('other', 'Other')], db_index=True, default='other', max_length=40),
        ),
    ]
