# Generated by Django 5.2.14 on 2026-08-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_adminnotification_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='classified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='classified_by',
            field=models.CharField(blank=True, help_text='Who or what set spam_status — a username, or a command name.', max_length=60),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='duplicate_count',
            field=models.PositiveIntegerField(default=0, help_text='Further identical submissions suppressed after the first.'),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, help_text='Keyed digest of the normalised submission. Never the message itself.', max_length=64),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='previous_status',
            field=models.CharField(blank=True, help_text='Status before the last bulk classification, so it can be rolled back.', max_length=16),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='risk_reasons',
            field=models.JSONField(blank=True, default=list, help_text='Deterministic reason codes; never free text.'),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='source_endpoint',
            field=models.CharField(blank=True, db_index=True, help_text='Which public form produced this (e.g. contact).', max_length=120),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='spam_status',
            field=models.CharField(choices=[('unclassified', 'Unclassified'), ('accepted', 'Accepted'), ('review', 'Needs review'), ('rejected', 'Rejected (spam)'), ('legitimate', 'Confirmed legitimate'), ('archived', 'Archived')], db_index=True, default='unclassified', help_text='Screening outcome. "unclassified" means it predates screening.', max_length=16),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['spam_status', '-created_at'], name='notificatio_spam_st_b0d9a0_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['fingerprint'], name='notificatio_fingerp_578307_idx'),
        ),
    ]
